Repository airqo-platform/AirQo-api, pull requests merged in 2020-10, with the labels that each got.

#155 Topic: inserting device measurements into platform
  src/device-registry/app.js
  src/device-registry/controllers/component.js
  src/device-registry/controllers/device.js
  src/device-registry/models/ComponentType.js
  src/device-registry/models/Device.js
  src/device-registry/routes/api.js
  src/device-registry/utils/insertion.js
Labels: Ready, enhancement

#153 Inaccurate GPS sensor reading and no device feeds
  src/data-mgt/controllers/manager.js
Labels: Ready

#163 [bug] Unexpected new rows in Events collection
  src/device-registry/controllers/component.js
Labels: Ready, bug

#176 [Auth Service] Remove case sensitivity from tenant ID
  src/auth-service/controllers/candidate.js
  src/auth-service/controllers/join.js
  src/auth-service/services/auth.js
Labels: Ready, bug

#191 refactor data mgt
  src/data-mgt/app.js
  src/data-mgt/app.yaml
  src/data-mgt/config/app.middleware.js
  src/data-mgt/config/constants.js
  src/data-mgt/config/database.js
  src/data-mgt/config/redis.js
  src/data-mgt/controllers/manager.js
  src/data-mgt/go/.gitkeep
  src/data-mgt/java/.gitkeep
  src/data-mgt/node/.gcloudignore
  src/data-mgt/node/.gitignore
  src/data-mgt/node/README.md
  src/data-mgt/node/app.js
  src/data-mgt/node/app.yaml
  src/data-mgt/node/bin/www
  src/data-mgt/node/config/app.middleware.js
  src/data-mgt/node/config/constants.js
  src/data-mgt/node/config/database.js
  src/data-mgt/node/config/redis.js
  src/data-mgt/node/config/router.middleware.js
  src/data-mgt/node/controllers/load.js
  src/data-mgt/node/controllers/transform.js
  src/data-mgt/node/models/Channel.js
  src/data-mgt/node/models/Feed.js
  src/data-mgt/node/models/Issue.js
  src/data-mgt/node/models/MaintenanceLogs.js
  src/data-mgt/node/models/Monitor.js
  src/data-mgt/node/models/weather.js
  src/data-mgt/node/package-lock.json
  src/data-mgt/node/package.json
  src/data-mgt/node/public/stylesheets/style.css
  src/data-mgt/node/routes/api.js
  src/data-mgt/node/service/monitor.js
  src/data-mgt/node/utils/date.js
  src/data-mgt/node/utils/errors.js
  src/data-mgt/node/utils/gps-check.js
  src/data-mgt/node/utils/log.js
  src/data-mgt/node/utils/mappings.js
  src/data-mgt/python/README.md
  src/data-mgt/python/bin/start.sh
  src/data-mgt/python/config/constants.py
  src/data-mgt/python/config/dao.py
  src/data-mgt/python/config/db_connection.py
  src/data-mgt/python/controllers/__init__.py
  src/data-mgt/python/controllers/load.py
  src/data-mgt/python/controllers/transform.py
  src/data-mgt/python/helpers/.gitkeep
  src/data-mgt/python/jobs/.gitkeep
  src/data-mgt/python/models/.gitkeep
  src/data-mgt/python/requirements/common.txt
  src/data-mgt/python/requirements/dev.txt
  src/data-mgt/python/requirements/prod.txt
  src/data-mgt/python/routes/api.py
  src/data-mgt/routes/api.js
Labels: Ready, chore

#187 ENVs injection - Device Monitoring
  k8s/prod-device-monitor-api.yaml
  k8s/stage-device-monitor-api.yaml
  src/device-monitoring/.dockerignore
  src/device-monitoring/Dockerfile
  src/device-monitoring/Dockerfile.stage.txt
  src/device-monitoring/config.py
  src/device-monitoring/controllers/helpers.py
  src/device-monitoring/helpers/db_helpers.py
Labels: Ready

#178 [Chore] Platform Notifications (Alerts) microservice
  src/notifications/.gitignore
  src/notifications/Dockerfile
  src/notifications/Dockerfile.deploy
  src/notifications/bin/start.sh
  src/notifications/config/app.conf
  src/notifications/config/constants.go
  src/notifications/config/dao.go
  src/notifications/config/db_connection.go
  src/notifications/controllers/.gitkeep
  src/notifications/controllers/notify.go
  src/notifications/docs/IMG-2435.JPG
  src/notifications/docs/IMG-2437.JPG
  src/notifications/docs/IMG-2438.JPG
  src/notifications/helpers/.gitkeep
  src/notifications/jobs/.gitkeep
  src/notifications/main.go
  src/notifications/models/.gitkeep
  src/notifications/models/AccountType.go
  src/notifications/models/Login.go
  src/notifications/models/Notification.go
  src/notifications/models/NotificationSettings.go
  src/notifications/models/NotificationType.go
  src/notifications/routes/api.go
Labels: Ready, chore

#193 Fx refactor device monitoring
  src/device-monitoring/.gitignore
  src/device-monitoring/controllers/device_status.py
  src/device-monitoring/jobs/calculate_devices_uptime.py
  src/device-monitoring/models/device_status.py
  src/device-monitoring/routes/api.py
Labels: Ready

#139 Alternative prediction approach
  src/predict/app.py
  src/predict/controllers/prediction.py
  src/predict/helpers/utils.py
  src/predict/jobs/prediction_job.py
  src/predict/jobs/training.py
  src/predict/models/datamanagement.py
  src/predict/models/predict.py
  src/predict/requirements.txt
  src/predict/routes/api.py
Labels: Ready
