Repository airqo-platform/AirQo-api, pull requests merged in 2020-11, with the labels that each got.

#195 chore: deploy data-mgt and redis on k8s
  k8s/prod-data-mgt-api.yaml
  k8s/prod-redis-server.yaml
  k8s/stage-data-mgt-api.yaml
  k8s/stage-device-monitor-api.yaml
  k8s/stage-redis-server.yaml
  src/data-mgt/node/.dockerignore
  src/data-mgt/node/Dockerfile
  src/data-mgt/node/Dockerfile.stage.txt
  src/data-mgt/node/config/constants.js
  src/data-mgt/node/config/redis.js
  src/data-mgt/node/docker-compose.yaml
  src/data-mgt/node/package-lock.json
Labels: Ready, chore

#207 Ft gp model
  src/predict/.gitignore
  src/predict/app.py
  src/predict/controllers/prediction.py
  src/predict/gcp_helpers/cloud_function.py
  src/predict/helpers/utils.py
  src/predict/requirements.txt
  src/predict/routes/api.py
  src/predict/saved_model/saved_model.pb
  src/predict/saved_model/variables/variables.data-00000-of-00001
  src/predict/saved_model/variables/variables.index
Labels: Ready

#210 send email after user has been updated
  src/auth-service/config/constants.js
  src/auth-service/controllers/join.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/sendEmail.js
Labels: Ready, feature

#196 set up files for ansible project
  ansible/README.md
  ansible/development.ini
  ansible/extension/setup/.gitkeep
  ansible/extension/setup/hosts
  ansible/extension/setup/initial.yml
  ansible/extension/setup/kube-dependencies.yml
  ansible/extension/setup/master.yml
  ansible/extension/setup/workers.yml
  ansible/group-vars/all/apt.yml
  ansible/group-vars/mysql/.gitkeep
  ansible/group-vars/postgresql/postgresql-password.yml 
  ansible/group-vars/postgresql/postgresql.yml
  ansible/group-vars/webservers/apt.yml
  ansible/group-vars/webservers/nginx.yml
  ansible/plays/ansible.cfg
  ansible/plays/postgresql.yml
  ansible/plays/webservers.yml
  ansible/production.ini
  ansible/roles/external/.gitkeep
  ansible/roles/internal/.gitkeep
  ansible/roles/roles_requirements.yml
  ansible/test.ini 
  ansible/vpass 
Labels: Ready, chore

#212 Kubernetes Secrets for the Auth Service
  k8s/prod-auth-api.yaml
  k8s/stage-auth-api.yaml
  src/auth-service/.gitignore
  src/auth-service/package-lock.json
  src/auth-service/package.json
Labels: Ready

#216 photo uploads
  src/auth-service/models/User.js
  src/device-registry/config/cloudinary.js
  src/device-registry/controllers/device.js
  src/device-registry/controllers/process-image.js
  src/device-registry/models/Device.js
  src/device-registry/models/Image.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api.js
  src/device-registry/utils/errors.js
  src/device-registry/utils/multer.js
Labels: Ready, feature

#213 Kubernetes Secrets for the Device Registry microservice
  k8s/prod-device-registry-api.yaml
  k8s/stage-device-registry-api.yaml
  src/device-registry/.gitignore
Labels: Ready

#211 add k8s deployment scripts for cronjobs
  k8s/prod-network-uptime-cronjob.yaml
  k8s/prod-predict-cronjob.yaml
  k8s/stage-network-uptime-cronjob.yaml
Labels: Ready

#204 Issue-fix-201
  src/data-mgt/node/.gitignore
  src/data-mgt/node/Docker.redis.txt
Labels: Ready

#214 Kubernetes Secrets for the Data Management microservice
  k8s/prod-data-mgt-api.yaml
  k8s/stage-data-mgt-api.yaml
  src/data-mgt/.gitignore
Labels: Ready

#202 Bg stream kcca device data
  pipeline/cloud-functions/python/cloud_function_process_kcca_device_measurements.py
  pipeline/cloud-functions/python/device_registry.py
  pipeline/cloud-functions/python/helpers.py
  pipeline/cloud-functions/python/main.py
Labels: Ready, bug

#219 changing file perms the entry bash script and CLI logs for node micros
  src/auth-service/auth-secret.yaml
  src/auth-service/bin/www
  src/auth-service/config/dbConnection.js
  src/data-mgt/data-mgt-secret.yaml
  src/data-mgt/node/bin/www
  src/data-mgt/node/config/database.js
  src/data-mgt/node/package-lock.json
  src/data-mgt/node/package.json
  src/device-registry/bin/www
  src/device-registry/config/database.js
  src/device-registry/device-reg-secret.yaml
  src/device-registry/uploads/2020-11-05T11:19:27.456Z-Screenshot 2020-11-05 at 08.33.42.png
  src/incentives/bin/www
Labels: Ready, hotfix

#119 [hotfix] issue 117
  src/auth-service/app.js
  src/auth-service/controllers/candidate.js
  src/auth-service/controllers/join.js
  src/auth-service/utils/register.js
Labels: Ready, hotfix

#227 [chore] update base url of device monitoring microservice
  src/device-monitoring/config.py
  src/device-monitoring/routes/api.py
Labels: Ready, chore

#226 [bug] k8s deployment scripts
  k8s/prod-data-mgt-api.yaml
  k8s/prod-redis-server.yaml
  k8s/stage-data-mgt-api.yaml
  k8s/stage-prediction-api.yaml
  k8s/stage-redis-server.yaml
Labels: Ready, bug

#229 api gateway using nginx and haproxy
  k8s/prod-device-monitor-api.yaml
  k8s/prod-platform-ingress-resource.yaml
  k8s/stage-device-monitor-api.yaml
  k8s/stage-device-registry-api.yaml
  k8s/stage-platform-ingress-resource.yaml
Labels: Ready, feature
