Repository airqo-platform/AirQo-api, pull requests merged in 2021-05, with the labels that each got.

#344 in case devices are not available, return appropriate response
  src/device-registry/controllers/create-device.js
Labels: enhancement, ready for review

#342 Resolving Issue 340
  src/device-registry/models/Event.js
  src/device-registry/utils/get-measurements.js
Labels: ready for review

#360 return device details alongside the device measurements
  src/device-registry/models/Event.js
Labels: device-registry, enhancement, ready for review

#377 Returning dictionary for device details
  src/device-registry/models/Event.js
Labels: ready for review

#380 [Device-Registry] Split activity endpoint
  src/device-registry/controllers/manage-site.js
  src/device-registry/models/Device.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api.js
  src/device-registry/utils/site-activities.js
  src/device-registry/utils/validators/auth.js
  src/device-registry/utils/validators/requestBody.js
  src/device-registry/utils/validators/requestQuery.js
Labels: ready for review

#384 Filter active or primary Devices
  src/device-registry/controllers/create-device.js
  src/device-registry/services/.gitkeep
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/get-device-details.js
Labels: ready for review

#387 fix a bug for device already exists
  src/device-registry/controllers/create-device.js
  src/device-registry/models/Device.js
  src/device-registry/utils/does-device-exist.js
Labels: device-registry, hotfix, ready for review

#363 filter events by frequency
  src/device-registry/controllers/create-event.js
  src/device-registry/utils/date.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/get-device-details.js
  src/device-registry/utils/get-measurements.js
Labels: device-registry, enhancement, ready for review

#365 Airqo PM 2.5 calibrated values
  src/data-mgt/python/jobs/airqo_device_measurements.py
  src/data-mgt/python/jobs/events.py
Labels: ready for review

#347 Nearest devices
  src/device-registry/controllers/create-device.js
  src/device-registry/routes/api.js
  src/device-registry/utils/nearest-device.js
Labels: ready for review

#385 [hotfix] create gpmodel microservice
  k8s/prod-gp-model-cronjob.yaml
  k8s/stage-gp-model-cronjob.yaml
  src/gp-model/.gitignore
  src/gp-model/Dockerfile
  src/gp-model/Dockerfile.stage
  src/gp-model/Jenkinsfile
  src/gp-model/bin/start.sh
  src/gp-model/cloud_function.py
  src/gp-model/config/__init__.py
  src/gp-model/controllers/__init__.py
  src/gp-model/helpers/__init__.py
  src/gp-model/models/__init__.py
  src/gp-model/requirements.txt
  src/gp-model/routes/__init__.py
Labels: gp-model-microservice, hotfix, ready for review

#396 [device-uptime] Eliminate BQ from device uptime
  src/device-uptime/Dockerfile
  src/device-uptime/Dockerfile.stage.txt
  src/device-uptime/README.md
  src/device-uptime/app.py
  src/device-uptime/config.py
  src/device-uptime/config/__init__.py
  src/device-uptime/config/constants.py
  src/device-uptime/config/db_connection.py
  src/device-uptime/controllers/__init__.py
  src/device-uptime/controllers/correlation.py
  src/device-uptime/controllers/health.py
  src/device-uptime/controllers/uptime.py
  src/device-uptime/device_uptime.py
  src/device-uptime/helpers/__init__.py
  src/device-uptime/helpers/calculate_uptime.py
  src/device-uptime/helpers/convert_dates.py
  src/device-uptime/helpers/get_device_hourly_records_count.py
  src/device-uptime/helpers/get_expected_records_count.py
  src/device-uptime/main.py
  src/device-uptime/models.py
  src/device-uptime/models/__init__.py
  src/device-uptime/models/device.py
  src/device-uptime/models/device_uptime.py
  src/device-uptime/models/network_uptime.py
  src/device-uptime/models/network_uptime_analysis_results.py
  src/device-uptime/models/raw_feeds_pms.py
  src/device-uptime/requirements.txt
  src/device-uptime/requirements/common.txt
  src/device-uptime/requirements/dev.txt
  src/device-uptime/requirements/prod.txt
  src/device-uptime/routes/__init__.py
  src/device-uptime/routes/api.py
  src/device-uptime/utils/__init__.py
  src/device-uptime/utils/device_hourly_records.py
Labels: ready for review

#393 add an additional sensor (field) in gen 5 devices
  src/data-mgt/node/utils/mappings.js
Labels: bug, data-engineering, data-mgt, ready for review
