Repository airqo-platform/AirQo-api, pull requests merged in 2021-04, with the labels that each got.

#276 renaming location registry to site registry
  src/site-registry/.gitignore
  src/site-registry/Dockerfile
  src/site-registry/Dockerfile.stage.txt
  src/site-registry/README.md
  src/site-registry/app.py
  src/site-registry/app.yaml
  src/site-registry/bin/start.sh
  src/site-registry/config.py
  src/site-registry/config/constants.py
  src/site-registry/config/db_connection.py
  src/site-registry/controllers/__init__.py
  src/site-registry/controllers/controller.py
  src/site-registry/helpers/.gitkeep
  src/site-registry/helpers/__init__.py
  src/site-registry/helpers/helper.py
  src/site-registry/jobs/.gitkeep
  src/site-registry/models/.gitkeep
  src/site-registry/models/__init__.py
  src/site-registry/models/location.py
  src/site-registry/requirements.txt
  src/site-registry/requirements/common.txt
  src/site-registry/requirements/dev.txt
  src/site-registry/requirements/prod.txt
  src/site-registry/routes/api.py
Labels: chore, ready for review

#299 [enhancement] k8s deployment config
  k8s/prod-analytics-api.yaml
  k8s/prod-auth-api.yaml
  k8s/prod-calibrate-api.yaml
  k8s/prod-data-mgt-api.yaml
  k8s/prod-device-monitor-api.yaml
  k8s/prod-device-registry-api.yaml
  k8s/prod-device-status-cronjob.yaml
  k8s/prod-device-uptime-cronjob.yaml
  k8s/prod-locate-api.yaml
  k8s/prod-location-registry-api.yaml
  k8s/prod-network-uptime-cronjob.yaml
  k8s/prod-predict-cronjob.yaml
  k8s/prod-prediction-api.yaml
  k8s/prod-redis-server.yaml
  k8s/stage-analytics-api.yaml
  k8s/stage-auth-api.yaml
  k8s/stage-calibrate-api.yaml
  k8s/stage-data-mgt-api.yaml
  k8s/stage-device-monitor-api.yaml
  k8s/stage-device-registry-api.yaml
  k8s/stage-device-status-cronjob.yaml
  k8s/stage-device-uptime-cronjob.yaml
  k8s/stage-locate-api.yaml
  k8s/stage-location-registry-api.yaml
  k8s/stage-network-uptime-cronjob.yaml
  k8s/stage-prediction-api.yaml
  k8s/stage-redis-server.yaml
Labels: enhancement, ready for review

#315 reduce caching time for the data transformation endpoints
  src/data-mgt/node/config/constants.js
  src/data-mgt/node/controllers/transform.js
Labels: hotfix, ready for review

#303 [PLAT-430] Infrastructure as Code
  infra/.gitignore
  infra/ansible/README.md
  infra/ansible/development/Vagrantfile
  infra/ansible/development/extension/.gitkeep
  infra/ansible/development/group-vars/.gitkeep
  infra/ansible/development/plays/master.yml
  infra/ansible/development/plays/worker.yml
  infra/ansible/development/roles/.gitkeep
  infra/ansible/production/extension/setup/.gitkeep
  infra/ansible/production/extension/setup/hosts
  infra/ansible/production/extension/setup/initial.yml
  infra/ansible/production/extension/setup/kube-dependencies.yml
  infra/ansible/production/extension/setup/master.yml
  infra/ansible/production/extension/setup/workers.yml
  infra/ansible/production/group-vars/mysql/.gitkeep
  infra/ansible/production/plays/ansible.cfg
  infra/ansible/production/roles/external/.gitkeep
  infra/ansible/production/roles/internal/.gitkeep
  infra/ansible/staging/group-vars/mysql/.gitkeep
  infra/ansible/staging/plays/ansible.cfg
  infra/ansible/staging/roles/external/.gitkeep
  infra/ansible/staging/roles/internal/.gitkeep
  infra/ansible/staging/setup/.gitkeep
  infra/ansible/staging/setup/hosts
  infra/ansible/staging/setup/initial.yml
  infra/ansible/staging/setup/kube-dependencies.yml
  infra/ansible/staging/setup/master.yml
  infra/ansible/staging/setup/workers.yml
  infra/setup/.gitignore
  infra/terraform/README.md
  infra/terraform/aws/assets/.gitkeep
  infra/terraform/aws/production/.gitkeep
  infra/terraform/aws/staging/.gitkeep
  infra/terraform/gcp/assets/.gitkeep
  infra/terraform/gcp/production/firewall.tf
  infra/terraform/gcp/production/main.tf
  infra/terraform/gcp/production/network.tf
  infra/terraform/gcp/production/provider.tf
  infra/terraform/gcp/production/variables.tf
  infra/terraform/gcp/staging/firewall.tf
  infra/terraform/gcp/staging/main.tf
  infra/terraform/gcp/staging/network.tf
  infra/terraform/gcp/staging/provider.tf
  infra/terraform/gcp/staging/variables.tf
Labels: ready for review

#287 Ft historical device measurements
  src/data-mgt/.gitignore
  src/data-mgt/python/batch-jobs/.gitignore
  src/data-mgt/python/batch-jobs/Dockerfile
  src/data-mgt/python/batch-jobs/Readme.md
  src/data-mgt/python/batch-jobs/airqo/Dockerfile
  src/data-mgt/python/batch-jobs/airqo/Readme.md
  src/data-mgt/python/batch-jobs/airqo/batch_fetch_airqo_data.py
  src/data-mgt/python/batch-jobs/airqo/requirements.txt
  src/data-mgt/python/batch-jobs/kcca/Dockerfile
  src/data-mgt/python/batch-jobs/kcca/Readme.md
  src/data-mgt/python/batch-jobs/kcca/batch_fetch_kcca_data.py
  src/data-mgt/python/batch-jobs/kcca/requirements.txt
Labels: data-engineering, enhancement, ready for review

#307 Ft device measurements calibrated values
  src/data-mgt/python/jobs/.gcloudignore
  src/data-mgt/python/jobs/.gitignore
  src/data-mgt/python/jobs/README.md
  src/data-mgt/python/jobs/airqo_device_measurements.py
  src/data-mgt/python/jobs/date.py
  src/data-mgt/python/jobs/events.py
  src/data-mgt/python/jobs/kcca_device_measurements.py
  src/data-mgt/python/jobs/main.py
  src/data-mgt/python/jobs/requirements.txt
Labels: duplicate, enhancement, ready for review

#318 SOFT delete, update and create Device
  src/device-registry/controllers/create-device.js
  src/device-registry/models/Device.js
  src/device-registry/routes/api.js
  src/device-registry/utils/does-device-exist.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/get-device-details.js
  src/device-registry/utils/soft-update-device.js
  src/device-registry/utils/transform-device-name.js
Labels: hotfix, ready for review

#321 disable DB disconnection whenever the system experiences challenges
  src/auth-service/config/dbConnection.js
  src/data-mgt/node/config/database.js
  src/device-registry/config/database.js
Labels: hotfix, ready for review

#324 Refactor and hotfix device deployment
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/manage-site.js
  src/device-registry/models/Event.js
  src/device-registry/routes/api.js
  src/device-registry/services/.gitkeep
  src/device-registry/services/auth.js
  src/device-registry/services/insertHistorical.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/delete-channel.js
  src/device-registry/utils/delete-device.js
  src/device-registry/utils/does-device-exist.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/get-device-details.js
  src/device-registry/utils/get-measurements.js
  src/device-registry/utils/insert-measurements.js
  src/device-registry/utils/integrations.js
  src/device-registry/utils/jsonify.js
  src/device-registry/utils/site-activities.js
Labels: chore, device-registry, hotfix, ready for review

#336 Hotfix for getting most recent events when query is made shortly after mid-night
  src/device-registry/models/Event.js
  src/device-registry/utils/date.js
  src/device-registry/utils/generate-filter.js
Labels: hotfix, ready for review

#325 [Analytics] refactor analytics url
  src/analytics/controllers/dashboard.py
  src/analytics/controllers/graph.py
  src/analytics/controllers/helpers.py
  src/analytics/controllers/monitoring_site.py
  src/analytics/controllers/report.py
Labels: ready for review

#267 Add Jenkinsfile for each microservice
  k8s/prod-auth-api.yaml
  k8s/prod-calibrate-api.yaml
  k8s/prod-data-mgt-api.yaml
  k8s/prod-device-monitor-api.yaml
  k8s/prod-device-registry-api.yaml
  k8s/prod-locate-api.yaml
  k8s/stage-auth-api.yaml
  k8s/stage-calibrate-api.yaml
  k8s/stage-data-mgt-api.yaml
  k8s/stage-device-monitor-api.yaml
  k8s/stage-device-registry-api.yaml
  k8s/stage-locate-api.yaml
  src/analytics/Jenkinsfile
  src/auth-service/Jenkinsfile
  src/calibrate/Jenkinsfile
  src/data-mgt/node/Jenkinsfile
  src/device-monitoring/jenkinsfile
  src/device-registry/Jenkinsfile
  src/device-status/Jenkinsfile
  src/device-uptime/Jenkinsfile
  src/incentives/Jenkinsfile
  src/locate/Jenkinsfile
  src/location-registry/Jenkinsfile
  src/predict/Jenkinsfile
  src/site-registry/Jenkinsfile
Labels: ready for review

#343 Reduce requirements for calibrate microservice
  src/calibrate/Dockerfile
  src/calibrate/Dockerfile.stage.txt
  src/calibrate/config/constants.py
  src/calibrate/config/dao.py
  src/calibrate/config/db_connection.py
  src/calibrate/readme.md
  src/calibrate/requirements.txt
Labels: ready for review

#329 Enhancement streaming functions
  src/data-mgt/python/jobs/airqo_device_measurements.py
  src/data-mgt/python/jobs/date.py
  src/data-mgt/python/jobs/events.py
  src/data-mgt/python/jobs/kcca_device_measurements.py
  src/data-mgt/python/jobs/requirements.txt
Labels: enhancement, ready for review
