Repository airqo-platform/AirQo-api, pull requests merged in 2021-06, with the labels that each got.

#392 query Events by timestamps
  src/device-registry/controllers/create-event.js
  src/device-registry/utils/date.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/get-measurements.js
Labels: device-registry, enhancement, ready for review

#386 Uncertainty in heatmaps
  src/predict/controllers/prediction.py
  src/predict/gcp_helpers/cloud_function.py
  src/predict/helpers/utils.py
Labels: ready for review

#408 [device-uptime] fix devices with no daily events
  src/device-uptime/utils/device_hourly_records.py
Labels: ready for review

#430 Retrieve measurements for private devices
  src/data-mgt/node/config/constants.js
  src/data-mgt/node/controllers/transform.js
  src/data-mgt/node/utils/errors.js
  src/data-mgt/node/utils/jsonify.js
Labels: data-mgt, events, ready for review

#421 add default values for Event attributes
  src/device-registry/models/Event.js
Labels: events, ready for review

#424 get measurements for specific devices in one go
  src/device-registry/utils/generate-filter.js
Labels: device-registry, events, ready for review

#407 Confirm(register) candidates from Candidates list
  src/auth-service/app.js
  src/auth-service/config/constants.js
  src/auth-service/config/dbConnection.js
  src/auth-service/config/mailer.js
  src/auth-service/config/middleware.js
  src/auth-service/controllers/candidate.js
  src/auth-service/controllers/defaults.js
  src/auth-service/controllers/join.js
  src/auth-service/controllers/request.js
  src/auth-service/controllers/test/ut_join.js
  src/auth-service/controllers/test/ut_request.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/Defaults.js
  src/auth-service/models/User.js
  src/auth-service/models/test/ut_candidate.js
  src/auth-service/models/test/ut_defaults.js
  src/auth-service/models/test/ut_user.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/api.js
  src/auth-service/routes/test/ut_api.js
  src/auth-service/services/mailer.js
  src/auth-service/services/test/ut_auth.js
  src/auth-service/services/test/ut_mailer.js
  src/auth-service/utils/defaults.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/errors.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/generate-password.js
  src/auth-service/utils/join.js
  src/auth-service/utils/jsonify.js
  src/auth-service/utils/multitenancy.js
  src/auth-service/utils/register.js
  src/auth-service/utils/request.js
  src/auth-service/utils/test/ut_generate-filter.js
  src/auth-service/utils/test/ut_join.js
  src/auth-service/utils/test/ut_request.js
  src/auth-service/utils/validations.candidate.js
  src/auth-service/utils/validations.forgot.js
  src/auth-service/utils/validations.js
  src/auth-service/utils/validations.login.js
  src/auth-service/utils/validations.register.js
  src/auth-service/utils/validations.update.pwd.in.js
  src/auth-service/utils/validations.update.pwd.js
Labels: authentication-service, ready for review, refactoring

#435 ensure Events are returned when device query params are not provided
  src/device-registry/controllers/create-event.js
  src/device-registry/utils/errors.js
  src/device-registry/utils/generate-filter.js
Labels: events, ready for review

#439 set default limit when fetching for device measurements to 1000
  src/device-registry/config/constants.js
  src/device-registry/utils/date.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/get-measurements.js
Labels: events, ready for review

#444 Optimise query performance for the GET events endpoint
  src/device-registry/config/constants.js
  src/device-registry/utils/date.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/get-measurements.js
Labels: events, ready for review

#394 Reimplement Site Registry
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-site.js
  src/device-registry/controllers/manage-site.js
  src/device-registry/controllers/test/ut_create-activity.js
  src/device-registry/controllers/test/ut_create-site.js
  src/device-registry/models/Activity.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Location.js
  src/device-registry/models/Setting.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/test/site.js
  src/device-registry/models/test/ut_site.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/date.js
  src/device-registry/utils/errors.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/get-device-details.js
  src/device-registry/utils/get-measurements.js
  src/device-registry/utils/site-activities.js
  src/device-registry/utils/test/ut_create-activity.js
  src/device-registry/utils/test/ut_create-site.js
Labels: device-registry, ready for review, site-registry

#441 Streams multi tenancy
  kafka/clusters/prod-kafka-cluster.yaml
  kafka/clusters/stage-kafka-cluster.yaml
  kafka/connectors/stage-kcca-device-measurements-connect.yaml
  kafka/connectors/stage-kcca-device-measurements-connector.yaml
  kafka/connectors/stage-kcca-device-measurements-mongo-source-connect.yaml
  kafka/connectors/stage-kcca-device-measurements-mongo-source-connector.yaml
  kafka/stage-airqo-raw-measurements-stream.yaml
  kafka/stage-kcca-raw-measurements-stream.yaml
  kafka/topics/stage-topic-kcca-device-measurements.yaml
  kafka/topics/stage-topic-kcca-raw-device-measurements.yaml
  kafka/topics/stage-topic-transformed-device-measurements.yaml
  src/data-mgt/java/streams/device-measurements/.gitignore
  src/data-mgt/java/streams/device-measurements/Dockerfile
  src/data-mgt/java/streams/device-measurements/Readme.md
  src/data-mgt/java/streams/device-measurements/device-measurements.iml
  src/data-mgt/java/streams/device-measurements/pom.xml
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/Calibrate.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/DeviceMeasurements.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/Utils.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/Device.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/DevicesResponse.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/KccaLocation.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/KccaXticValue.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/KccaXtics.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/Measurement.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/RawAirQoMeasurement.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/RawKccaMeasurement.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/SiteDetails.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/TransformedDeviceMeasurements.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/TransformedLocation.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/TransformedMeasurement.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/TransformedValue.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/altitude.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/battery.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/externalHumidity.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/externalPressure.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/externalTemperature.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/hdop.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/internalHumidity.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/internalTemperature.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/location.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/no2.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/pm1.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/pm10.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/pm2_5.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/s2_pm10.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/s2_pm2_5.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/satellites.java
  src/data-mgt/java/streams/device-measurements/src/main/java/net/airqo/models/speed.java
  src/data-mgt/java/streams/device-measurements/src/main/resources/application.properties
  src/data-mgt/java/streams/device-measurements/src/main/resources/log4j.properties
  src/data-mgt/java/streams/device-measurements/src/main/resources/test.application.properties
  src/data-mgt/java/streams/device-measurements/src/main/resources/test.empty.properties
  src/data-mgt/java/streams/device-measurements/src/main/resources/transformed-device-measurements.avsc
  src/data-mgt/java/streams/device-measurements/src/test/java/net/airqo/CalibrateTest.java
  src/data-mgt/java/streams/device-measurements/src/test/java/net/airqo/DeviceMeasurementsTest.java
  src/data-mgt/java/streams/device-measurements/src/test/java/net/airqo/UtilsTest.java
Labels: ready for review

#440 Kcca frequency measurements
  kafka/connectors/stage-kcca-device-measurements-connect.yaml
  kafka/connectors/stage-kcca-device-measurements-connector-daily.yaml
  kafka/connectors/stage-kcca-device-measurements-connector-raw.yaml
  src/data-mgt/java/connectors/kcca-source-connector/Dockerfile
  src/data-mgt/java/connectors/kcca-source-connector/Readme.md
  src/data-mgt/java/connectors/kcca-source-connector/kcca-source-connector.iml
  src/data-mgt/java/connectors/kcca-source-connector/pom.xml
  src/data-mgt/java/connectors/kcca-source-connector/src/main/java/net/airqo/connectors/KccaSourceConnector.java
  src/data-mgt/java/connectors/kcca-source-connector/src/main/java/net/airqo/connectors/Utils.java
  src/data-mgt/java/connectors/kcca-source-connector/src/main/java/net/airqo/connectors/VersionUtil.java
  src/data-mgt/java/connectors/kcca-source-connector/src/main/java/net/airqo/connectors/config/KccaSourceConnectorConfig.java
  src/data-mgt/java/connectors/kcca-source-connector/src/main/java/net/airqo/connectors/models/RawMeasurements.java
  src/data-mgt/java/connectors/kcca-source-connector/src/main/java/net/airqo/connectors/tasks/KccaSourceTask.java
  src/data-mgt/java/connectors/kcca-source-connector/src/test/java/net/airqo/connectors/TestUtils.java
  src/data-mgt/java/connectors/kcca-source-connector/src/test/resources/.gitignore
  src/data-mgt/java/connectors/kcca-source-connector/src/test/resources/test.application.properties
Labels: ready for review

#438 [device-uptime] Uptime hourly calculation
  src/device-uptime/config.py
  src/device-uptime/device_uptime.py
  src/device-uptime/requirements.txt
  src/device-uptime/utils/device_hourly_records.py
Labels: ready for review

#446 [device-registry] temporary deployment
  k8s/stage-temp-device-registry-api.yaml
Labels: device-registry, devops, ready for review

#447 update the events schema accordingly
  src/device-registry/models/Event.js
  src/device-registry/utils/generate-filter.js
Labels: device-registry, work in progress

#448 make site name not required
  src/device-registry/models/Event.js
Labels: ready for review

#449 enable insertion of device measurements for various frequencies
  src/device-registry/models/Event.js
  src/device-registry/utils/insert-measurements.js
Labels: events, ready for review
