Repository airqo-platform/AirQo-api, pull requests merged in 2021-11, with the labels that each got.

#639 automatically generate road metadata during site creation
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-site.js
  src/device-registry/utils/create-site.js
Labels: ready for review, device-registry

#657 handling the many to many relationship between Sites and AirQlouds
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Site.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-site.js
Labels: ready for review, device-registry, site-registry, airqloud

#662 [Analytics] add GPS coordinates to downloaded data
  src/analytics/api/models/events.py
  src/analytics/api/models/exceedance.py
  src/analytics/api/models/site.py
  src/analytics/api/utils/request_validators.py
  src/analytics/api/views/dashboard.py
Labels: ready for review

#661 for external users, use the average field for daily measurements
  src/device-registry/models/Event.js
Labels: ready for review, device-registry, events

#658 temporarily disable deletion of Sites
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Site.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-site.js
Labels: ready for review, device-registry, site-registry

#655 Mobile App Signup/signin with email link
  src/auth-service/.gitignore
  src/auth-service/app.js
  src/auth-service/config/constants.js
  src/auth-service/config/firebase-admin.js
  src/auth-service/config/firebase-settings.js
  src/auth-service/controllers/join.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/api-v1.js
  src/auth-service/services/mailer.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/generate-password.js
  src/auth-service/utils/join.js
  src/auth-service/utils/request.js
Labels: ready for review, authentication-service

#665 Auth microservice CI/CD
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/auth-service/prod-auth-api.yaml
  k8s/auth-service/stage-auth-api.yaml
  src/auth-service/Dockerfile
  src/auth-service/Dockerfile.stage
Labels: ready for review

#654 AirQo Daily averages
  k8s/calibrate-job/prod-airqo-daily-average-job.yaml
  k8s/calibrate-job/stage-airqo-daily-average-job.yaml
  src/data-mgt/python/cron-jobs/airqoApi.py
  src/data-mgt/python/cron-jobs/averages.py
  src/data-mgt/python/cron-jobs/calibrate.py
  src/data-mgt/python/cron-jobs/config.py
  src/data-mgt/python/cron-jobs/main.py
  src/data-mgt/python/cron-jobs/utils.py
Labels: Ready for merge, ready for review

#653 Device Registry Topics
  k8s/topics/prod-dr-topics.yaml
  k8s/topics/stage-dr-topics.yaml
Labels: Ready for merge, ready for review

#666 adding terms and conditions link and modification of the referral codes in the welcome emails
  src/auth-service/controllers/join.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/join.js
Labels: ready for review, authentication-service

#671 Minor correction on the number of digits in the code sent in user emails
  src/auth-service/utils/join.js
Labels: ready for review

#669 [Analytics] Approximate data export coordinates
  src/analytics/api/utils/coordinates.py
  src/analytics/api/views/dashboard.py
Labels: ready for review

#663 Enhancing the request access email message
  src/auth-service/utils/email.msgs.js
Labels: ready for review, authentication-service

#656 verify email address during request access
  src/auth-service/config/constants.js
  src/auth-service/controllers/request.js
  src/auth-service/models/Candidate.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/api-v1.js
  src/auth-service/services/mailer.js
  src/auth-service/utils/log.js
  src/auth-service/utils/request.js
  src/auth-service/utils/validations.js
Labels: ready for review, authentication-service

#664 A few enhancements to Site registry
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Site.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-site.js
Labels: ready for review, device-registry, site-registry

#667 return the sensor 1 pm2.5 value in cases where external=no
  src/device-registry/models/Event.js
Labels: ready for review, device-registry

#670 adjust the startTime for getting greenness to one month ago
  src/device-registry/config/constants.js
Labels: ready for review

#672 resolve runtime issues for validation errors in the User entity logic
  src/auth-service/models/User.js
  src/auth-service/package-lock.json
  src/auth-service/utils/join.js
Labels: ready for review, authentication-service

#659 reduce projected Site/Device details when getting devices/AirQlouds/Sites
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
Labels: hotfix, ready for review, device-registry, NOT ready for merge

#648 Calibrate microservice deployment
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/calibrate/prod-calibrate-api.yaml
  k8s/calibrate/stage-calibrate-api.yaml
  src/calibrate/Dockerfile
  src/calibrate/Dockerfile.stage
  src/calibrate/jobs/regression.py
  src/calibrate/models/regression.py
  src/calibrate/readme.md
Labels: ready for review

#676 reverting a change on the external=no query parameter
  src/device-registry/models/Event.js
Labels: ready for review

#675 Calibration fixes
  .github/workflows/deploy-apis-to-production.yml
  k8s/calibrate/prod-calibrate-api.yaml
  k8s/calibrate/stage-calibrate-api.yaml
  src/data-mgt/python/cron-jobs/airqoApi.py
  src/data-mgt/python/cron-jobs/calibrate.py
  src/data-mgt/python/cron-jobs/config.py
Labels: Ready for merge, ready for review

#673 Mobile App Welcome Message
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
  k8s/notification-service/prod-notification-api.yaml
  k8s/notification-service/stage-notification-api.yaml
  k8s/topics/stage-notification-topics.yaml
  src/config
  src/notifications/.dockerignore
  src/notifications/.gitignore
  src/notifications/Dockerfile
  src/notifications/Readme.md
  src/notifications/config/config.go
  src/notifications/config/constants.go
  src/notifications/config/dao.go
  src/notifications/config/db_connection.go
  src/notifications/controllers/notify.go
  src/notifications/go.mod
  src/notifications/go.sum
  src/notifications/main.go
  src/notifications/models/AccountType.go
  src/notifications/models/AppNotificationModel.go
  src/notifications/models/ConfigModel.go
  src/notifications/models/Login.go
  src/notifications/models/MessageModel.go
  src/notifications/models/Notification.go
  src/notifications/models/NotificationSettings.go
  src/notifications/models/NotificationType.go
  src/notifications/models/ResponseModel.go
  src/notifications/models/TopicModel.go
  src/notifications/routes/api.go
  src/notifications/templates/mobile-welcome-email-template.html
  src/notifications/templates/netmanager-welcome-email-template.html
  src/notifications/templates/welcome-email-template.html
  src/notifications/utils/emailClient.go
  src/notifications/utils/firebaseClient.go
  src/notifications/utils/kafkaClient.go
Labels: ready for review

#679 Triggering Github actions
  src/analytics/Jenkinsfile
  src/auth-service/cloudbuild.yaml
  src/calibrate/Jenkinsfile
  src/device-registry/app.yaml
  src/notifications/Dockerfile
Labels: Ready for merge

#680 Trigger production Github workflows
  src/analytics/Jenkinsfile
  src/auth-service/cloudbuild.yaml
  src/calibrate/Jenkinsfile
  src/device-registry/app.yaml
  src/notifications/Dockerfile
Labels: Ready for merge

#681 GitHub workflow enhancements
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/notifications/Readme.md
  src/notifications/controllers/notify.go
  src/notifications/main.go
  src/workflow-versions
Labels: Ready for merge, ready for review

#682 sort out the sensor one readings for the internal use case of GET Events
  src/device-registry/models/Event.js
Labels: ready for review, device-registry, events

#686 fix the raw frequency concern
  src/device-registry/models/Event.js
Labels: ready for review, device-registry

#688 reversing an unnecessary hotfix for getting raw events
  src/device-registry/models/Event.js
Labels: ready for review

#683 deploy gpmodel
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/gp-model/prod-airqo-gp-model-job.yaml
Labels: ready for review, gp-model-microservice

#547 General gp model
  src/gp-model/.gitignore
  src/gp-model/Dockerfile
  src/gp-model/Dockerfile.dev
  src/gp-model/Dockerfile.stage
  src/gp-model/config.py
  src/gp-model/helpers/get_data.py
  src/gp-model/main.py
  src/gp-model/requirements.txt
Labels: ready for review

#693 hotfix: deploy gpmodel
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
Labels: Ready for merge
