Repository airqo-platform/AirQo-api, pull requests merged in 2021-10, with the labels that each got.

#618 Kubernetes Image versioning
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/device-registry/Dockerfile
  src/device-registry/Dockerfile.stage
  src/device-registry/README.md
Labels: Ready for merge, ready for review

#621 Git actions Image tagging
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
Labels: Ready for merge, ready for review

#620 Datawarehouse Deployment
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/data-warehouse/prod-data-warehouse-api.yaml
  k8s/data-warehouse/stage-data-warehouse-api.yaml
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
  src/data-mgt/python/extract-external-data/.gitignore
  src/data-mgt/python/extract-external-data/models/extract.py
  src/data-mgt/python/extract-external-data/routes/api.py
Labels: Ready for merge, ready for review

#622 Update Dockerfile
  src/data-mgt/python/extract-external-data/Dockerfile
Labels: Ready for merge, ready for review

#624 Datawarehouse message broker
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/data-warehouse/prod-data-warehouse-api.yaml
  k8s/data-warehouse/stage-data-warehouse-api.yaml
  k8s/topics/prod-airqo-streams-topics.yaml
  k8s/topics/stage-airqo-streams-topics.yaml
  src/data-mgt/python/extract-external-data/Dockerfile
  src/data-mgt/python/extract-external-data/message_broker.py
  src/data-mgt/python/extract-external-data/requirements.txt
Labels: Ready for merge, ready for review

#619 [DeviceUptime] retain last battery voltage when device is offline
  src/device-uptime/utils/device_hourly_records.py
Labels: ready for review

#613 Getting devices without forecast
  src/data-mgt/python/devices-tranformation/Readme.md
  src/data-mgt/python/devices-tranformation/airqoApi.py
  src/data-mgt/python/devices-tranformation/main.py
  src/data-mgt/python/devices-tranformation/transformation.py
  src/data-mgt/python/devices-tranformation/utils.py
Labels: Ready for merge, ready for review

#623 add more validations for login endpoint
  src/auth-service/routes/api-v1.js
  src/auth-service/routes/api-v2.js
Labels: bug, ready for review, authentication-service

#631 check for tenant using email address
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-organization.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/Defaults.js
  src/auth-service/models/Organization.js
  src/auth-service/models/Settings.js
  src/auth-service/models/User.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/api-v1.js
  src/auth-service/services/auth.js
  src/auth-service/utils/create-organization.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#652 add mobility to the returned fields of the GET devices endpoint
  src/device-registry/models/Device.js
Labels: ready for review
