Repository airqo-platform/AirQo-api, pull requests merged in 2021-12, with the labels that each got.

#687 introducing new endpoint for authenticating emails
  src/auth-service/controllers/join.js
  src/auth-service/routes/api-v1.js
  src/auth-service/services/mailer.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/join.js
Labels: ready for review, device-registry

#692 Updating site search names
  src/data-mgt/python/devices-tranformation/Readme.md
  src/data-mgt/python/devices-tranformation/airqoApi.py
  src/data-mgt/python/devices-tranformation/main.py
  src/data-mgt/python/devices-tranformation/transformation.py
Labels: Ready for merge, ready for review

#694 Hotfix - calibration job
  src/data-mgt/python/cron-jobs/airqoApi.py
  src/data-mgt/python/cron-jobs/calibrate.py
  src/data-mgt/python/cron-jobs/utils.py
Labels: Ready for merge, ready for review

#684 [deviceStatus] Fix alternator powerType visibility
  src/device-status/device_status.py
Labels: ready for review

#695 Kcca historical measurements
  src/data-mgt/python/batch-jobs/kcca_batch_fetch.py
Labels: ready for review

#699 Gp model remove tenant
  src/gp-model/config.py
  src/gp-model/helpers/get_data.py
Labels: ready for review, gp-model-microservice, priority-high

#674 set up the pagination support for the GET Events endpoint
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Event.js
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/insert-measurements.js
Labels: ready for review, device-registry, events

#698 AirQo Historical measurements calibration
  src/data-mgt/python/cron-jobs/airqoApi.py
  src/data-mgt/python/cron-jobs/calibrate.py
  src/data-mgt/python/cron-jobs/config.py
  src/data-mgt/python/cron-jobs/main.py
Labels: Ready for merge, ready for review

#701 [Metadata] Functionality to export sites and devices as csv
  src/data-mgt/python/devices-tranformation/Readme.md
  src/data-mgt/python/devices-tranformation/airqoApi.py
  src/data-mgt/python/devices-tranformation/main.py
  src/data-mgt/python/devices-tranformation/transformation.py
Labels: Ready for merge, ready for review

#704 Fix averages job
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/calibrate-job/prod-airqo-daily-average-job.yaml
  k8s/calibrate-job/prod-calibrate-job.yaml
  k8s/calibrate-job/stage-airqo-daily-average-job.yaml
  k8s/calibrate-job/stage-calibrate-job.yaml
  src/data-mgt/python/cron-jobs/Dockerfile
  src/data-mgt/python/cron-jobs/calibrate.py
Labels: ready for review
