Repository airqo-platform/AirQo-api, pull requests merged in 2021-07, with the labels that each got.

#451 Get events when query "timestamps" are zero or not provided
  src/device-registry/utils/date.js
Labels: device-registry, events, ready for review

#454 Enhancements on device schema
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Device.js
  src/device-registry/routes/api.js
  src/device-registry/utils/errors.js
Labels: device-registry, ready for review

#461 readME file for device registry microservice
  src/device-registry/README.md
Labels: ready for review

#456 [Exceedance] calculate exceedances
  src/exceedances/README.md
  src/exceedances/config.py
  src/exceedances/exceedance.py
  src/exceedances/models.py
  src/exceedances/requirements.txt
  src/exceedances/utils/exceedances.py
Labels: ready for review

#467 [Analytics] final refactoring
  src/analytics/Dockerfile
  src/analytics/README.md
  src/analytics/api/docs/dashboard/exceedances_post.yml
  src/analytics/api/models/__init__.py
  src/analytics/api/models/base/base_model.py
  src/analytics/api/models/base/model_operations.py
  src/analytics/api/models/constants.py
  src/analytics/api/models/device_exceedances.py
  src/analytics/api/models/device_measurements.py
  src/analytics/api/models/events.py
  src/analytics/api/models/exceedance.py
  src/analytics/api/models/monitoring_site.py
  src/analytics/api/models/pm25_models.py
  src/analytics/api/models/report_template.py
  src/analytics/api/models/site.py
  src/analytics/api/utils/pollutants/charts.py
  src/analytics/api/utils/pollutants/pm_25.py
  src/analytics/api/views/__init__.py
  src/analytics/api/views/dashboard.py
  src/analytics/app.py
  src/analytics/app.yaml
  src/analytics/bin/start.sh
  src/analytics/config.py
  src/analytics/controllers/__init__.py
  src/analytics/controllers/analyze.py
  src/analytics/controllers/dashboard.py
  src/analytics/controllers/graph.py
  src/analytics/controllers/helpers.py
  src/analytics/controllers/monitoring_site.py
  src/analytics/controllers/report.py
  src/analytics/helpers/.gitkeep
  src/analytics/helpers/__init__.py
  src/analytics/helpers/clarity_api.py
  src/analytics/helpers/cloud_function_calculate_average_daily_measurements_for_the_last_28_days.py
  src/analytics/helpers/cloud_function_calculate_exceedences_for_the_last_28_days.py
  src/analytics/helpers/cloud_function_generate_pm25_locations_category_count.py
  src/analytics/helpers/cloud_function_update_daily_measurements.py
  src/analytics/helpers/cloud_function_update_hourly_measurements.py
  src/analytics/helpers/helpers.py
  src/analytics/helpers/mongo_helpers.py
  src/analytics/jobs/.gitkeep
  src/analytics/main.py
  src/analytics/manage.py
  src/analytics/models/__init__.py
  src/analytics/models/dashboard.py
  src/analytics/models/division.py
  src/analytics/models/graph.py
  src/analytics/models/monitoring_site.py
  src/analytics/models/report.py
  src/analytics/requirements-old.txt
  src/analytics/requirements.txt
  src/analytics/requirements/common.txt
  src/analytics/requirements/dev.txt
  src/analytics/requirements/prod.txt
  src/analytics/routes/api.py
  src/exceedances/utils/exceedances.py
Labels: ready for review

#474 changing the daily limit to 500 records
  src/device-registry/app.js
  src/device-registry/bin/www
  src/device-registry/config/cloudinary.js
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/utils/insert-measurements.js
  src/device-registry/utils/transform-measurements.js
Labels: device-registry, events, hotfix, ready for review

#475 add more site attributes in response
  src/device-registry/models/Site.js
Labels: ready for review

#485 Site Tahmo Attribute
  src/device-registry/models/Site.js
Labels: Ready for merge

#466 Events monitor
  k8s/events-monitor/.helmignore
  k8s/events-monitor/Chart.yaml
  k8s/events-monitor/templates/NOTES.txt
  k8s/events-monitor/templates/_helpers.tpl
  k8s/events-monitor/templates/cronjob.yaml
  k8s/events-monitor/templates/tests/test-connection.yaml
  k8s/events-monitor/values-dev.yaml
  src/data-mgt/python/events-monitor/.dockerignore
  src/data-mgt/python/events-monitor/.gitignore
  src/data-mgt/python/events-monitor/Dockerfile
  src/data-mgt/python/events-monitor/main.py
  src/data-mgt/python/events-monitor/requirements.txt
Labels: ready for review

#481 Sites Tahmo mapping
  src/data-mgt/python/devices-tranformation/.gitignore
  src/data-mgt/python/devices-tranformation/Readme.md
  src/data-mgt/python/devices-tranformation/airqoApi.py
  src/data-mgt/python/devices-tranformation/main.py
  src/data-mgt/python/devices-tranformation/requirements.txt
  src/data-mgt/python/devices-tranformation/tahmo.py
  src/data-mgt/python/devices-tranformation/transformation.py
  src/data-mgt/python/devices-tranformation/utils.py
Labels: data-mgt, device-registry, ready for review

#486 [DeviceStatus] Update status job
  src/device-status/README.md
  src/device-status/config.py
  src/device-status/device_status.py
  src/device-status/models.py
Labels: ready for review

#484 [DeviceUptime] Update uptime job
  src/device-uptime/README.md
  src/device-uptime/config.py
  src/device-uptime/device_uptime.py
  src/device-uptime/models.py
Labels: ready for review

#489 [Analytics] remove outliers from chart data
  src/analytics/api/models/events.py
Labels: ready for review

#457 Encrypt device keys, add input validations and refactor
  src/device-registry/.gitignore
  src/device-registry/app.js
  src/device-registry/bin/www
  src/device-registry/config/cloudinary.js
  src/device-registry/config/constants.js
  src/device-registry/config/database.js
  src/device-registry/config/log4js.json
  src/device-registry/config/redis.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/controllers/process-image.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Site.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/routes/api.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/errors.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/jsonify.js
  src/device-registry/utils/multitenancy.js
  src/device-registry/utils/test/ut_create-event.js
Labels: device-registry, ready for review, requires-frontend-update

#487 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: chore, ready for review

#476 remove the counter document in the list of returned sites
  src/device-registry/controllers/create-site.js
  src/device-registry/utils/create-site.js
Labels: device-registry, ready for review, site-registry

#482 [Analytics] Update download data format
  src/analytics/api/models/events.py
  src/analytics/api/views/dashboard.py
Labels: ready for review

#490 Kafka calibrate
  k8s/calibrate/prod-calibrate-kafka.yaml
  k8s/calibrate/stage-calibrate-kafka.yaml
  src/calibrate/.dockerignore
  src/calibrate/.gitignore
  src/calibrate/kafka.Dockerfile
  src/calibrate/kafka_consumer.py
  src/calibrate/models/__init__.py
  src/calibrate/readme.md
  src/calibrate/requirements.txt
  src/calibrate/schema.py
Labels: ready for review

#496 correct dependency name
  src/device-registry/utils/create-event.js
Labels: device-registry, hotfix, priority-high, ready for review

#497 Hotfixes for auth-service and device-monitoring security
  src/auth-service/utils/join.js
  src/auth-service/utils/log.js
  src/device-monitoring/jobs/calculate_devices_uptime.py
Labels: authentication-service, ready for review

#494 [DeviceMonitoring] Refactoring device monitoring
  src/device-monitoring/README.md
  src/device-monitoring/app.py
  src/device-monitoring/config/constants.py
  src/device-monitoring/controllers/check_health.py
  src/device-monitoring/controllers/check_status.py
  src/device-monitoring/helpers/convert_dates.py
  src/device-monitoring/helpers/pre_request.py
  src/device-monitoring/models.py
  src/device-monitoring/models/__init__.py
  src/device-monitoring/models/device_status.py
  src/device-monitoring/models/device_uptime.py
  src/device-monitoring/requirements.txt
  src/device-monitoring/routes.py
  src/device-monitoring/routes/__init__.py
  src/device-monitoring/routes/api.py
  src/device-uptime/device_uptime.py
  src/device-uptime/models.py
  src/device-uptime/utils/device_hourly_records.py
Labels: ready for review

#495 Enhancements and hotfixes for device registry
  src/device-registry/config/constants.js
  src/device-registry/config/log4js.json
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Site.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/get-measurements.js
  src/device-registry/utils/sanitize.js
Labels: device-registry, enhancement, hotfix, ready for review

#483 Refactor gp model microservice
  src/gp-model/.dockerignore
  src/gp-model/.gitignore
  src/gp-model/Dockerfile
  src/gp-model/Dockerfile.stage
  src/gp-model/bin/start.sh
  src/gp-model/cloud_function.py
  src/gp-model/config.py
  src/gp-model/config/__init__.py
  src/gp-model/controllers/__init__.py
  src/gp-model/helpers/__init__.py
  src/gp-model/main.py
  src/gp-model/models/__init__.py
  src/gp-model/requirements.txt
  src/gp-model/routes/__init__.py
Labels: ready for review
