Repository airqo-platform/AirQo-api, pull requests merged in 2021-09, with the labels that each got.

#563 Returning nearest sites based on latitude and longitude
  src/device-registry/controllers/create-site.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/distance.js
Labels: ready for review

#409 [CI-CD] GitHub Actions
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/device-monitoring/.dockerignore
  src/device-registry/.dockerignore
  src/exceedances/Dockerfile
  src/exceedances/Dockerfile.prod.airqo
  src/exceedances/Dockerfile.prod.kcca
  src/exceedances/Dockerfile.stage
  src/exceedances/Dockerfile.stage.airqo
  src/exceedances/Dockerfile.stage.kcca
Labels: ready for review, devops, k8s

#565 disable editing of unique name for AirQlouds
  src/device-registry/models/Airqloud.js
Labels: ready for review, device-registry, airqloud

#567 k8s config maps
  k8s/analytics/prod-analytics-api.yaml
  k8s/analytics/stage-analytics-api.yaml
  k8s/analytics/templates/deployment.yaml
  k8s/analytics/values-dev.yaml
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/prod-auth-api.yaml
  k8s/auth-service/stage-auth-api.yaml
  k8s/auth-service/templates/deployment.yaml
  k8s/auth-service/values-dev.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/prod-device-registry-api.yaml
  k8s/device-registry/stage-device-registry-api.yaml
  k8s/device-registry/templates/deployment.yaml
  k8s/device-registry/values-dev.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/prod-airqo-device-status-job.yaml
  k8s/device-status/stage-airqo-device-status-job.yaml
  k8s/device-uptime/prod-airqo-device-uptime-job.yaml
  k8s/device-uptime/stage-airqo-device-uptime-job.yaml
  k8s/exceedance/prod-airqo-exceedance-job.yaml
  k8s/exceedance/prod-kcca-exceedance-job.yaml
  k8s/exceedance/stage-airqo-exceedance-job.yaml
  k8s/exceedance/stage-kcca-exceedance-job.yaml
  k8s/gp-model/prod-airqo-gp-model-job.yaml
  k8s/gp-model/stage-airqo-gp-model-job.yaml
  k8s/locate/prod-locate-api.yaml
  k8s/locate/stage-locate-api.yaml
  k8s/locate/templates/deployment.yaml
  k8s/locate/values-dev.yaml
  k8s/locate/values-prod.yaml
  k8s/locate/values-stage.yaml
  k8s/predict-job/prod-airqo-predict-job.yaml
  k8s/predict-job/stage-airqo-predict-job.yaml
  k8s/predict/prod-prediction-api.yaml
  k8s/predict/stage-prediction-api.yaml
  k8s/predict/templates/deployment.yaml
  k8s/predict/values-dev.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
Labels: ready for review, devops, k8s

#574 remove unused attributes from device entity
  src/device-registry/models/Device.js
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/site-activities.js
Labels: ready for review

#571 increase the valid height of devices during deployment
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review, device-registry

#566 refactor error handling and entity fields for Sites use case
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Site.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-site.js
Labels: ready for review, device-registry, site-registry, requires-frontend-update

#568 refactor error handling for device creation use case
  src/device-registry/controllers/create-device.js
  src/device-registry/models/Device.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry

#569 introducing the long_organization field for candidates and users
  src/auth-service/controllers/join.js
  src/auth-service/controllers/request.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/User.js
  src/auth-service/utils/join.js
  src/auth-service/utils/request.js
  src/auth-service/utils/validations.js
Labels: ready for review, authentication-service, request-access

#576 hotfix-cicd
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
Labels: ready for review

#572 Migrate Channel Data Update Job
  k8s/channel-data/prod-airqo-update-channel-data-job.yaml
  k8s/channel-data/stage-airqo-update-channel-data-job.yaml
  src/channel-data/.dockerignore
  src/channel-data/.gitignore
  src/channel-data/Dockerfile.prod
  src/channel-data/Dockerfile.stage
  src/channel-data/config.py
  src/channel-data/main.py
  src/channel-data/requirements.txt
Labels: work in progress

#579 fix the duplicate records problem
  src/device-registry/controllers/create-event.js
  src/device-registry/utils/insert-measurements.js
Labels: bug, Ready for merge, ready for review, device-registry, events

#575 new use case: create organization
  src/auth-service/controllers/create-organization.js
  src/auth-service/models/Location.js
  src/auth-service/models/Organization.js
  src/auth-service/models/Settings.js
  src/auth-service/routes/api-v1.js
  src/auth-service/routes/api-v2.js
  src/auth-service/utils/create-organization.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review, authentication-service

#584 [device-monitoring] Leaderboard plat 742
  k8s/device-monitor/prod-device-monitor-api.yaml
  k8s/device-monitor/stage-device-monitor-api.yaml
  k8s/device-monitor/templates/deployment.yaml
  k8s/device-monitor/values-dev.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  src/device-monitoring/controllers/check_status.py
  src/device-monitoring/helpers/utils.py
  src/device-monitoring/models.py
  src/device-monitoring/routes.py
Labels: ready for review

#580 Do not drop old photos when updating device pictures
  src/device-registry/models/Device.js
  src/device-registry/utils/create-device.js
Labels: bug, ready for review, device-registry

#586 add description to user details when confirming Candidate
  src/auth-service/models/User.js
  src/auth-service/utils/request.js
Labels: Ready for merge, ready for review, authentication-service

#587 migrate staging to production
  .github/workflows/deploy-apis-to-production.yml
  src/auth-service/models/User.js
  src/auth-service/utils/request.js
Labels: Ready for merge, ready for review

#589 Pm10 calibration
  src/calibrate/.gitignore
  src/calibrate/controllers/calibrate.py
  src/calibrate/jobs/regression.py
  src/calibrate/models/regression.py
  src/calibrate/requirements.txt
  src/calibrate/routes/api.py
Labels: ready for review

#603 schema changes to the AirQloud entity
  src/device-registry/models/Airqloud.js
Labels: ready for review, device-registry, airqloud

#602 [Analytics] enable sorting of downloaded data by time field
  src/analytics/api/models/base/model_operations.py
  src/analytics/api/models/events.py
Labels: ready for review

#588 Extract external data Microservice
  k8s/data-warehouse/prod-data-warehouse-api.yaml
  k8s/data-warehouse/stage-data-warehouse-api.yaml
  src/data-mgt/python/extract-external-data/.dockerignore
  src/data-mgt/python/extract-external-data/.gitignore
  src/data-mgt/python/extract-external-data/Dockerfile
  src/data-mgt/python/extract-external-data/app.py
  src/data-mgt/python/extract-external-data/controllers/__init__.py
  src/data-mgt/python/extract-external-data/controllers/extract.py
  src/data-mgt/python/extract-external-data/helpers/validation.py
  src/data-mgt/python/extract-external-data/models/TAHMO/__init__.py
  src/data-mgt/python/extract-external-data/models/__init__.py
  src/data-mgt/python/extract-external-data/models/extract.py
  src/data-mgt/python/extract-external-data/readme.md
  src/data-mgt/python/extract-external-data/requirements.txt
  src/data-mgt/python/extract-external-data/routes/api.py
Labels: ready for review

#534 Update Kafka-Calibrate
  k8s/calibrate-job/prod-calibrate-job.yaml
  k8s/calibrate-job/stage-calibrate-job.yaml
  k8s/calibrate/prod-calibrate-kafka.yaml
  k8s/calibrate/stage-calibrate-kafka.yaml
  src/calibrate/.dockerignore
  src/calibrate/.gitignore
  src/calibrate/jobs/regression.py
  src/calibrate/kafka.Dockerfile
  src/calibrate/kafka_consumer.py
  src/calibrate/readme.md
  src/calibrate/requirements.txt
  src/calibrate/schema.py
  src/data-mgt/python/cron-jobs/airqoApi.py
  src/data-mgt/python/cron-jobs/airqo_api.py
  src/data-mgt/python/cron-jobs/calibrate.py
  src/data-mgt/python/cron-jobs/config.py
  src/data-mgt/python/cron-jobs/date.py
  src/data-mgt/python/cron-jobs/main.py
  src/data-mgt/python/cron-jobs/measurements.py
  src/data-mgt/python/cron-jobs/readme.md
  src/data-mgt/python/cron-jobs/utils.py
Labels: Ready for merge, ready for review

#610 resolves the runtime during user creation
  src/auth-service/models/User.js
Labels: ready for review

#606 remove regular expressions
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry

#616 Small change to trigger analytics CI/CD 😁
  src/analytics/Dockerfile
  src/analytics/Dockerfile.stage
Labels: Ready for merge, ready for review

#617 Analytics Production workflow
  .github/workflows/deploy-apis-to-production.yml
  src/analytics/Dockerfile
  src/analytics/Dockerfile.stage
Labels: Ready for merge, ready for review
