Repository airqo-platform/AirQo-api, pull requests merged in 2021-03, with the labels that each got.

#269 [fix] adding redis env to k8s
  k8s/prod-analytics-api.yaml
  k8s/prod-auth-api.yaml
  k8s/prod-calibrate-api.yaml
  k8s/prod-device-monitor-api.yaml
  k8s/prod-device-registry-api.yaml
  k8s/prod-locate-api.yaml
  k8s/prod-location-registry-api.yaml
  k8s/prod-prediction-api.yaml
  k8s/stage-analytics-api.yaml
  k8s/stage-auth-api.yaml
  k8s/stage-calibrate-api.yaml
  k8s/stage-device-monitor-api.yaml
  k8s/stage-device-registry-api.yaml
  k8s/stage-locate-api.yaml
  k8s/stage-location-registry-api.yaml
Labels: Ready, hotfix

#248 Jenkins on k8s
  k8s/jenkins/jenkins-deployment.yaml
  k8s/jenkins/jenkins-ns.yaml
  k8s/jenkins/jenkins-service.yaml
Labels: Ready

#271 [hotfix]location registry DB URL error
  src/location-registry/app.py
  src/location-registry/models/location.py
Labels: Ready

#282 return the ID every after carrying out a SITE activity
  src/device-registry/models/location_activity.js
  src/device-registry/utils/doActivityHelpers.js
Labels: Ready, hotfix

#284 hotfix for deleting devices
  src/device-registry/controllers/device.js
  src/device-registry/utils/delete-device.js
  src/device-registry/utils/deviceControllerHelpers.js
Labels: Ready, hotfix

#288 Sort the site activity logs
  src/device-registry/controllers/device.js
  src/device-registry/models/location_activity.js
  src/device-registry/utils/doActivityHelpers.js
Labels: Ready, hotfix

#278 eliminate duplicate entries for days
  src/device-registry/controllers/create-component.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/manage-site.js
  src/device-registry/controllers/test/create-component.js
  src/device-registry/controllers/test/create-device.js
  src/device-registry/controllers/test/create-event.js
  src/device-registry/controllers/test/process-image.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/test/component-type.js
  src/device-registry/models/test/component.js
  src/device-registry/models/test/device.js
  src/device-registry/models/test/event.js
  src/device-registry/models/test/site-activity.js
  src/device-registry/models/test/site.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api.js
  src/device-registry/utils/create-request-body.js
  src/device-registry/utils/date.js
  src/device-registry/utils/does-component-exist.js
  src/device-registry/utils/does-device-exist.js
  src/device-registry/utils/errors.js
  src/device-registry/utils/generate-fields-values.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/get-device-details.js
  src/device-registry/utils/get-measurements.js
  src/device-registry/utils/insert-measurements.js
  src/device-registry/utils/site-activities.js
  src/device-registry/utils/test/create-device.js
  src/device-registry/utils/test/date.js
  src/device-registry/utils/test/does-component-exist.js
  src/device-registry/utils/test/does-device-exist.js
  src/device-registry/utils/test/errors.js
  src/device-registry/utils/test/generate-fields-values.js
  src/device-registry/utils/test/generate-filter.js
  src/device-registry/utils/test/get-device-details.js
  src/device-registry/utils/test/get-measurements.js
  src/device-registry/utils/test/mappings.js
  src/device-registry/utils/test/multitenancy.js
  src/device-registry/utils/test/site-activities.js
  src/device-registry/utils/test/transform-measurements.js
  src/device-registry/utils/test/validations.js
  src/device-registry/utils/transform-measurements.js
  src/device-registry/utils/transformMeasurements.js
  src/device-registry/utils/transmit-values.js
Labels: Ready, bug, hotfix

#272 Airqo analytics data docs
  src/analytics/README.md
Labels: Ready, documentation

#283 delete a specific photo
  src/device-registry/config/cloudinary.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/process-image.js
  src/device-registry/models/Device.js
  src/device-registry/routes/api.js
  src/device-registry/utils/delete-cloudinary-image.js
  src/device-registry/utils/does-device-exist.js
  src/device-registry/utils/get-last-path.js
  src/device-registry/utils/update-device.js
  src/device-registry/utils/upload-images.js
Labels: Ready, enhancement
