Repository airqo-platform/AirQo-api, pull requests merged in 2022-03, with the labels that each got.

#737 Airflow image build fix
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/airflow/Dockerfile
  src/airflow/dags/app_insights.py
Labels: Ready for merge, ready for review

#735 Events cronjob schedule
  k8s/events-monitor/prod-cronjob.yaml
  k8s/events-monitor/prod-events-notifs-cronjob.yaml
  k8s/events-monitor/stage-cronjob.yaml
  k8s/events-monitor/stage-events-notifs-cronjob.yaml
Labels: ready for review

#736 extract-external-data app deployment fix
  src/data-mgt/python/extract-external-data/requirements.txt
Labels: Ready for merge, ready for review

#734 Github workflow cleanup
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/data-mgt/prod-data-mgt-api.yaml
  k8s/data-mgt/stage-data-mgt-api.yaml
  workflow-versions
Labels: Ready for merge, ready for review

#740 introducing new Sites field --location_name---
  src/device-registry/models/Site.js
Labels: ready for review, device-registry

#741 move to production
  src/device-registry/models/Site.js
Labels: ready for review

#746 Update acceptable device deployment statuses
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: Ready for merge, ready for review

#742 Metadata grooming
  src/data-mgt/python/devices-tranformation/Readme.md
  src/data-mgt/python/devices-tranformation/airqoApi.py
  src/data-mgt/python/devices-tranformation/transformation.py
Labels: Ready for merge, ready for review

#747 Workflow typo fix
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
Labels: Ready for merge, ready for review

#744 calculate and show centre of AirQloud
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/models/Airqloud.js
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/create-airqloud.js
Labels: ready for review, device-registry, airqloud

#713 review validations for creating defaults and also fix saving periods
  src/auth-service/models/Defaults.js
  src/auth-service/routes/api-v1.js
Labels: ready for review, authentication-service

#749 Candidate to User transition
  src/auth-service/models/Candidate.js
  src/auth-service/models/User.js
Labels: ready for review, priority-medium

#750 [DP-171] Predict Job Maintenance
  src/predict-job/.dockerignore
  src/predict-job/.gitignore
  src/predict-job/Dockerfile
  src/predict-job/Dockerfile.dev
  src/predict-job/Dockerfile.stage
  src/predict-job/config.py
  src/predict-job/main.py
  src/predict-job/requirements.txt
Labels: Ready for merge, ready for review, predict

#751 k8s folder cleanup
  k8s/calibrate-job/.helmignore
  k8s/calibrate-job/Chart.yaml
  k8s/calibrate-job/prod-airqo-daily-average-job.yaml
  k8s/calibrate-job/prod-calibrate-job.yaml
  k8s/calibrate-job/stage-airqo-daily-average-job.yaml
  k8s/calibrate-job/stage-calibrate-job.yaml
  k8s/calibrate-job/stage-values.yaml
  k8s/calibrate-job/templates/NOTES.txt
  k8s/calibrate-job/templates/_helpers.tpl
  k8s/calibrate-job/templates/cronjob.yaml
  k8s/calibrate-job/templates/tests/test-connection.yaml
  k8s/calibrate/prod-calibrate-kafka.yaml
  k8s/calibrate/stage-calibrate-kafka.yaml
Labels: Ready for merge

#752 Predict job CICD
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/predict-job/prod-airqo-predict-job.yaml
  k8s/predict-job/stage-airqo-predict-job.yaml
  k8s/predict/prod-airqo-predict-job.yaml
  k8s/predict/stage-airqo-predict-job.yaml
Labels: Ready for merge, ready for review

#745 precomit file for git guardian usage
  .gitignore
  .pre-commit-config.yaml
Labels: ready for review, device-registry

#753 ETL utility functions
  src/airflow/README.md
  src/airflow/dags/main.py
  src/airflow/dev-requirements.txt
  src/airflow/main.py
Labels: Ready for merge

#756 Calibrate deployment [pipeline cluster]
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  workflow-trigger
Labels: Ready for merge

#757 View microservice build fix
  src/view/Dockerfile
  src/view/pom.xml
Labels: Ready for merge

#755 Pipeline maintenance
  src/airflow/Dockerfile
  src/airflow/README.md
  src/airflow/airflow_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/__init__.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/message_broker.py
  src/airflow/airqo_etl_utils/schema/.gitignore
  src/airflow/airqo_etl_utils/schema/__init__.py
  src/airflow/airqo_etl_utils/schema/data_warehouse.json
  src/airflow/airqo_etl_utils/schema/measurements.json
  src/airflow/airqo_etl_utils/schema/weather_data.json
  src/airflow/airqo_etl_utils/setup.py
  src/airflow/airqo_etl_utils/tahmo.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/weather_measurements.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
  src/data-mgt/python/devices-tranformation/transformation.py
Labels: ready for review

#758 resolve issues with getting sites for an AirQloud
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/utils/create-airqloud.js
Labels: ready for review

#761 disabling weather station look up during site refresh
  src/device-registry/controllers/create-site.js
  src/device-registry/utils/create-site.js
Labels: ready for review

#762 Pipeline maintenance [Part 2]
  src/airflow/README.md
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/schema/measurements.json
  src/airflow/airqo_etl_utils/schema/weather_data.json
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/weather_measurements.py
  src/airflow/main.py
Labels: Ready for merge

#764 View API enhancements
  src/view/src/main/java/airqo/ViewApplication.java
  src/view/src/main/java/airqo/controllers/MeasurementController.java
  src/view/src/main/java/airqo/models/Insight.java
  src/view/src/main/java/airqo/predicate/InsightPredicate.java
  src/view/src/main/java/airqo/tasks/InsightsTasks.java
  src/view/src/main/resources/application-api.properties
  src/view/src/test/java/airqo/MeasurementControllerTests.java
Labels: Ready for merge, ready for review

#772 missing mountType and powerType after device deployment
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/generate-filter.js
Labels: Ready for merge, ready for review

#763 Calibrate micro requirements
  src/calibrate/requirements.txt
Labels: Ready for merge, ready for review

#774 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/channel-data/prod-airqo-update-channel-data-job.yaml
  k8s/channel-data/stage-airqo-update-channel-data-job.yaml
  src/calibrate/requirements.txt
  src/channel-data/.gitignore
  src/channel-data/Dockerfile
  src/channel-data/Dockerfile.prod
  src/channel-data/Dockerfile.stage
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review
