Repository airqo-platform/AirQo-api, pull requests merged in 2022-09, with the labels that each got.

#1018 Hotfix - AirQo BAM data streaming
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#958 disable the Youtube video link from the Platform welcome
  src/auth-service/utils/email.msgs.js
Labels: ready for review, authentication-service

#1021 disable Kickbox by commenting out code section
  src/auth-service/utils/inquire.js
  src/auth-service/utils/join.js
  src/auth-service/utils/request.js
Labels: ready for review

#1023 [API authorization] handling cors at the route level
  src/device-registry/app.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review, device-registry

#1026 just removing comments from code
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1020 move to production
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/main.py
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/inquire.js
  src/auth-service/utils/join.js
  src/auth-service/utils/request.js
  src/device-registry/app.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1028 re-enable automatic download of csv file on browser API calls
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1029 move to production
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1030 disable logic for validation using Kickbox
  src/auth-service/utils/validations.js
Labels: ready for review

#1031 move to production
  src/auth-service/utils/validations.js
Labels: ready for review

#985 Just general refactoring for device-registry
  src/device-registry/app.js
  src/device-registry/bin/www
  src/device-registry/config/constants.js
  src/device-registry/config/log4js.js
  src/device-registry/config/log4js.json
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-site.js
  src/device-registry/utils/create-event.js
Labels: ready for review, device-registry

#1036 error logging hotfixes to device registry
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/date.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1037 move to production
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/date.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1038 removing the CORS restrictions on the events endpoint
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1040 completely removing the cors middleware
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1041 move to production
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1042 removing cors restrictions
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1044 remove cors package completely and utilise the domain whitelist
  src/device-registry/app.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1046 add ENV in device-registry error logs
  src/device-registry/config/constants.js
  src/device-registry/config/kafka-node.js
  src/device-registry/config/log4js.json
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Measurement.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/date.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/multitenancy.js
Labels: ready for review

#1022 allow duplicate data access requests but do not store them in the DB
  src/auth-service/controllers/request.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/api-v1.js
  src/auth-service/routes/api-v2.js
  src/auth-service/utils/request.js
Labels: ready for review

#1043 move to production
  src/auth-service/controllers/request.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/api-v1.js
  src/auth-service/routes/api-v2.js
  src/auth-service/utils/request.js
  src/device-registry/app.js
  src/device-registry/config/constants.js
  src/device-registry/config/kafka-node.js
  src/device-registry/config/log4js.json
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Measurement.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/date.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/multitenancy.js
Labels: ready for review

#1019 Maintenance - Data pipelines
  src/airflow/README.md
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/schema/data_warehouse.json
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/nasa_measurements.py
  src/airflow/main.py
  src/airflow/schedule-dag.py
Labels: Ready for merge, ready for review

#1047 dealing with missing header information from SSL encrypted website
  src/device-registry/config/constants.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1049 temporarily allowing all domains
  src/device-registry/config/constants.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1048 move to production
  src/airflow/README.md
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/schema/data_warehouse.json
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/nasa_measurements.py
  src/airflow/main.py
  src/airflow/schedule-dag.py
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1052 addressing a runtime TypeError on the sites use-case
  src/device-registry/utils/date.js
Labels: ready for review, device-registry

#1032 Chore - Data pipelines
  src/airflow/Dockerfile
  src/airflow/airflow_xcom/gcs_xcom_backend.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/plume_labs_api.py
  src/airflow/airqo_etl_utils/plume_labs_utils.py
  src/airflow/airqo_etl_utils/schema/sensor_positions.json
  src/airflow/airqo_etl_utils/setup.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/app_notifications.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/meta_data.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/main.py
  src/airflow/schedule-dag.py
Labels: Ready for merge, ready for review

#1053 move to production
  src/airflow/Dockerfile
  src/airflow/airflow_xcom/gcs_xcom_backend.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/plume_labs_api.py
  src/airflow/airqo_etl_utils/plume_labs_utils.py
  src/airflow/airqo_etl_utils/schema/sensor_positions.json
  src/airflow/airqo_etl_utils/setup.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/app_notifications.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/meta_data.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/main.py
  src/airflow/schedule-dag.py
  src/device-registry/utils/date.js
Labels: ready for review

#1055 adding nasa as one of the valid tenants
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1057 Add check for null values
  src/airflow/airqo_etl_utils/airqo_utils.py
Labels: Ready for merge, ready for review

#1059 just refactor the input validation error object response
  src/device-registry/utils/errors.js
Labels: ready for review

#1060 move to production
  src/device-registry/utils/errors.js
Labels: ready for review

#1061 Data pipeline maintenance
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/dags/kcca_measurements.py
Labels: ready for review

#1064 Move to production
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/dags/kcca_measurements.py
Labels: ready for review

#1062 Fix failing workflows
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/view-api/prod-view-api.yaml
  k8s/view-api/stage-view-api.yaml
Labels: enhancement, Ready for merge, ready for review, devops

#1054 correct secret name for predict deploy preview
  .github/workflows/deploy-previews.yml
Labels: Ready for merge, ready for review

#1068 Fix - Device registry
  src/device-registry/config/constants.js
Labels: ready for review, device-registry

#1063 Ft auto code formating
  .pre-commit-config.yaml
Labels: enhancement, Ready for merge, ready for review

#1069 Device measurements schema
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/schema/measurements.json
  src/airflow/airqo_etl_utils/tahmo_api.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#1070 ft - latest measurements
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/schema/latest_measurements.json
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
Labels: Ready for merge, ready for review

#1072 Chore message broker
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/connectors/prod-airqo-measurements-connector.yaml
  k8s/connectors/prod-kcca-measurements-connector.yaml
  k8s/connectors/prod-measurements-connect.yaml
  k8s/connectors/stage-airqo-measurements-connector.yaml
  k8s/connectors/stage-kcca-measurements-connector.yaml
  k8s/connectors/stage-measurements-connect.yaml
  k8s/database-source-connectors/.helmignore
  k8s/database-source-connectors/Chart.yaml
  k8s/database-source-connectors/stage-database-source-connect.yaml
  k8s/database-source-connectors/stage-events-database-source-connector.yaml
  k8s/database-source-connectors/templates/NOTES.txt
  k8s/database-source-connectors/templates/_helpers.tpl
  k8s/database-source-connectors/templates/database-source-connect.yaml
  k8s/database-source-connectors/templates/database-source-connector.yaml
  k8s/database-source-connectors/templates/tests/test-connection.yaml
  k8s/database-source-connectors/values.yaml
  k8s/kafka-clusters/kafka-cluster.yaml
  k8s/kafka-connect/.helmignore
  k8s/kafka-connect/Chart.yaml
  k8s/kafka-connect/dev-values.yaml
  k8s/kafka-connect/prod-values.yaml
  k8s/kafka-connect/stage-values.yaml
  k8s/kafka-connect/templates/NOTES.txt
  k8s/kafka-connect/templates/_helpers.tpl
  k8s/kafka-connect/templates/connect.yaml
  k8s/kafka-connectors/clarity-connector.yaml
  k8s/kafka-connectors/database-connector.yaml
  k8s/kafka-connectors/measurements-connect.yaml
  k8s/kafka-connectors/thingspeak-connector.yaml
  k8s/kafka-operator/deployment-script.sh
  src/kafka-connectors/measurements-source-connector/Dockerfile
Labels: Ready for merge, ready for review

#1067 Fix k8s deployments
  k8s/view-api/prod-view-api.yaml
  k8s/view-api/stage-view-api.yaml
  src/meta-data/api/controllers/extract.py
  src/meta-data/api/models/extract.py
Labels: ready for review

#1074 Hotfixes for device registry
  src/device-registry/app.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-location.js
  src/device-registry/models/Location.js
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/generate-filter.js
Labels: enhancement, ready for review, device-registry

#1073 Ft docs subdomain
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
Labels: enhancement, Ready for merge, ready for review

#1080 refactor input validations for tenant and deployment statuses
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1079 few minor refactors to create location use-case
  src/device-registry/controllers/create-location.js
Labels: ready for review

#1077 Data consolidation
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/schema/data_warehouse.json
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/weather_measurements.py
  src/airflow/main.py
  src/airflow/schedule-dag.py
Labels: Ready for merge, ready for review

#1083 hotfixes around the new Device Status field
  src/device-registry/models/Device.js
  src/device-registry/utils/create-site.js
Labels: ready for review

#1082 deal with metric conversions for external pressure from hectopascal to kilopascal
  src/data-mgt/node/config/constants.js
  src/data-mgt/node/controllers/transform.js
  src/data-mgt/node/utils/transform.js
Labels: ready for review

#1086 Chore KCCA pipeline
  src/airflow/airqo_etl_utils/air_quality_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/plume_labs_utils.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#1078 Fix metadata worflow
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/(to-de-deleted)data-warehouse/prod-data-warehouse-api.yaml
  k8s/(to-de-deleted)data-warehouse/stage-data-warehouse-api.yaml
  k8s/meta-data/stage-meta-data-api.yaml
  src/data-mgt/python/(to-be-deleted)extract-external-data/.dockerignore
  src/data-mgt/python/(to-be-deleted)extract-external-data/.gitignore
  src/data-mgt/python/(to-be-deleted)extract-external-data/Dockerfile
  src/data-mgt/python/(to-be-deleted)extract-external-data/app.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/controllers/__init__.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/controllers/extract.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/helpers/validation.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/message_broker.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/models/TAHMO/__init__.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/models/__init__.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/models/extract.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/readme.md
  src/data-mgt/python/(to-be-deleted)extract-external-data/requirements.txt
  src/data-mgt/python/(to-be-deleted)extract-external-data/routes/api.py
  src/data-mgt/python/extract-external-data/controllers/extract.py
  src/data-mgt/python/extract-external-data/models/TAHMO/__init__.py
  src/data-mgt/python/extract-external-data/models/extract.py
  src/data-mgt/python/extract-external-data/routes/api.py
Labels: Ready for merge, ready for review

#1088 Adding device name to exported data
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
Labels: Ready for merge, ready for review

#1089 Move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/(to-de-deleted)data-warehouse/prod-data-warehouse-api.yaml
  k8s/(to-de-deleted)data-warehouse/stage-data-warehouse-api.yaml
  k8s/meta-data/stage-meta-data-api.yaml
  src/airflow/airqo_etl_utils/air_quality_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/plume_labs_utils.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/main.py
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/.dockerignore
  src/data-mgt/python/(to-be-deleted)extract-external-data/.gitignore
  src/data-mgt/python/(to-be-deleted)extract-external-data/Dockerfile
  src/data-mgt/python/(to-be-deleted)extract-external-data/app.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/controllers/__init__.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/controllers/extract.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/helpers/validation.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/message_broker.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/models/TAHMO/__init__.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/models/__init__.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/models/extract.py
  src/data-mgt/python/(to-be-deleted)extract-external-data/readme.md
  src/data-mgt/python/(to-be-deleted)extract-external-data/requirements.txt
  src/data-mgt/python/(to-be-deleted)extract-external-data/routes/api.py
  src/data-mgt/python/extract-external-data/controllers/extract.py
  src/data-mgt/python/extract-external-data/models/TAHMO/__init__.py
  src/data-mgt/python/extract-external-data/models/extract.py
  src/data-mgt/python/extract-external-data/routes/api.py
Labels: ready for review

#1090 hotfix - pipeline conversion error
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/data_validator.py
Labels: Ready for merge, ready for review

#1091 Move to production
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/data_validator.py
Labels: Ready for merge, ready for review

#1094 removing device from SQL queries
  src/device-registry/utils/create-event.js
Labels: ready for review

#1095 move to production
  src/device-registry/utils/create-event.js
Labels: ready for review

#1096 Hotfix device measurements
  src/device-registry/utils/create-event.js
Labels: ready for review

#1097 more (x3) hotfixes to the SQL query of getting measurements from DW
  src/device-registry/utils/create-event.js
Labels: ready for review

#1098 move to production
  src/device-registry/utils/create-event.js
Labels: ready for review

#1099 more hotfixes (x4) to the SQL query
  src/device-registry/utils/create-event.js
Labels: ready for review

#1100 move to production
  src/device-registry/utils/create-event.js
Labels: ready for review

#1092 Updating the data pipeline to use bulk decrypt endpoint
  src/airflow/airqo_etl_utils/airqo_api.py
Labels: Ready for merge, ready for review
