Repository airqo-platform/AirQo-api, pull requests merged in 2022-11, with the labels that each got.

#1153 Fix Transform-Measurements `Data not iterable` Error
  src/device-registry/utils/create-event.js
Labels: bug

#1157 move to production
  src/device-registry/utils/create-event.js
Labels: ready for review

#1159 correct spelling errors in cloud run names
  .github/workflows/remove-deploy-previews.yml
Labels: bug, Ready for merge, ready for review, refactoring

#1151 argo cd k8s manifests
  k8s/argo-cd/README.md
  k8s/argo-cd/argocd-cm.yaml
  k8s/argo-cd/argocd-cmd-params-cm.yaml
  k8s/argo-cd/argocd-rbac-cm.yaml
  k8s/argo-cd/argocd-server-deployment.yaml
  k8s/argo-cd/cluster-role-bindings.yaml
  k8s/nginx/production/virtual-server.yaml
Labels: Ready for merge, ready for review, devops

#1142 Adding data unit tests
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/airqo_measurements.py
  src/cloud_functions/data_validation/.gitignore
  src/cloud_functions/data_validation/main.py
  src/cloud_functions/data_validation/requirements.txt
  src/cloud_functions/data_validation/src/__init__.py
  src/cloud_functions/data_validation/src/gcs.py
  src/data-unit-tests/.gitignore
  src/data-unit-tests/deploy.sh
  src/data-unit-tests/great_expectations/.gitignore
  src/data-unit-tests/great_expectations/expectations/airqo_data_tests.json
  src/data-unit-tests/great_expectations/great_expectations.yml
  src/data-unit-tests/great_expectations/loading_args/airqo_data_tests.yml
Labels: Ready for merge, ready for review

#1161 setting the content header during requests
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1160 move to production
  .github/workflows/remove-deploy-previews.yml
  k8s/argo-cd/README.md
  k8s/argo-cd/argocd-cm.yaml
  k8s/argo-cd/argocd-cmd-params-cm.yaml
  k8s/argo-cd/argocd-rbac-cm.yaml
  k8s/argo-cd/argocd-server-deployment.yaml
  k8s/argo-cd/cluster-role-bindings.yaml
  k8s/nginx/production/virtual-server.yaml
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/airqo_measurements.py
  src/cloud_functions/data_validation/.gitignore
  src/cloud_functions/data_validation/main.py
  src/cloud_functions/data_validation/requirements.txt
  src/cloud_functions/data_validation/src/__init__.py
  src/cloud_functions/data_validation/src/gcs.py
  src/data-unit-tests/.gitignore
  src/data-unit-tests/deploy.sh
  src/data-unit-tests/great_expectations/.gitignore
  src/data-unit-tests/great_expectations/expectations/airqo_data_tests.json
  src/data-unit-tests/great_expectations/great_expectations.yml
  src/data-unit-tests/great_expectations/loading_args/airqo_data_tests.yml
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1163 slight change to the set headers
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1164 move to production
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1165 Hotfix create events for csv download
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1166 move to production
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1167 reverting changes
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1168 move to production
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1170 Storing latest measurements on a kafka topic
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/message_broker_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/kcca_measurements.py
Labels: Ready for merge, ready for review

#1171 ensure automatic download to CSV
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1172 move to production
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/message_broker_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/kcca_measurements.py
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1173 increasing the valid size of the input body when creating things
  src/device-registry/app.js
Labels: ready for review

#1174 move to production
  src/device-registry/app.js
Labels: ready for review

#1175 use correct service names as expected by ArgoCD
  k8s/nginx/production/ingress.yaml
  k8s/nginx/production/virtual-server.yaml
  k8s/nginx/staging/virtual-server.yaml
Labels: Ready for merge, ready for review, devops

#1143 Query measurements by AirQloud ID or GPS coordinates
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Airqloud.js
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry

#1181 temporarily disabled the call to the metadata API for road metadata
  src/device-registry/utils/create-site.js
Labels: ready for review, device-registry

#1178 edge cases when getting measurements using AirQloud IDs or GPS coordinates
  src/device-registry/config/constants.js
  src/device-registry/models/Event.js
  src/device-registry/utils/create-event.js
Labels: ready for review, device-registry

#1182 move to production
  k8s/nginx/production/ingress.yaml
  k8s/nginx/production/virtual-server.yaml
  k8s/nginx/staging/virtual-server.yaml
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Event.js
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1184 ensure that ALL new data access requests are received by the system
  src/auth-service/utils/request.js
Labels: bug, ready for review, authentication-service

#1177 [VIEW API] App insights graph data
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/view-api/prod-view-api.yaml
  k8s/view-api/stage-view-api.yaml
  src/view/README.md
  src/view/pom.xml
  src/view/src/main/java/airqo/ViewApplication.java
  src/view/src/main/java/airqo/config/CacheConfig.java
  src/view/src/main/java/airqo/config/GlobalExceptionHandler.java
  src/view/src/main/java/airqo/controllers/MeasurementController.java
  src/view/src/main/java/airqo/controllers/MessageBroker.java
  src/view/src/main/java/airqo/models/Frequency.java
  src/view/src/main/java/airqo/models/GraphInsight.java
  src/view/src/main/java/airqo/models/InsightData.java
  src/view/src/main/java/airqo/services/BigQueryApi.java
  src/view/src/main/java/airqo/services/BigQueryApiImpl.java
  src/view/src/main/java/airqo/services/InsightsService.java
  src/view/src/main/java/airqo/services/InsightsServiceImpl.java
  src/view/src/main/resources/application.properties
Labels: ready for review

#1186 Hotfix - failing workflow
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/view/clean.sh
Labels: Ready for merge, ready for review

#1180 [Data pipeline] Daily and forecast data storage
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/daily_data_utils.py
  src/airflow/airqo_etl_utils/forecast_data_utils.py
  src/airflow/airqo_etl_utils/schema/forecast_measurements.json
  src/airflow/dags/daily_measurements.py
  src/airflow/dags/forecast_measurements.py
Labels: Ready for merge, ready for review

#1179 Administrative levels Endpoint
  src/meta-data/api/controllers/extract.py
  src/meta-data/api/models/extract.py
  src/meta-data/api/routes/api.py
Labels: ready for review

#1189 View api hotfixes
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/view/src/main/java/airqo/config/CacheConfig.java
  src/view/src/main/java/airqo/controllers/MeasurementController.java
  src/view/src/main/java/airqo/models/GraphInsight.java
  src/view/src/main/java/airqo/models/InsightData.java
  src/view/src/main/java/airqo/services/InsightsServiceImpl.java
Labels: ready for review

#1191 Move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/daily_data_utils.py
  src/airflow/airqo_etl_utils/forecast_data_utils.py
  src/airflow/airqo_etl_utils/schema/forecast_measurements.json
  src/airflow/dags/daily_measurements.py
  src/airflow/dags/forecast_measurements.py
  src/meta-data/api/controllers/extract.py
  src/meta-data/api/models/extract.py
  src/meta-data/api/routes/api.py
  src/view/src/main/java/airqo/config/CacheConfig.java
  src/view/src/main/java/airqo/controllers/MeasurementController.java
  src/view/src/main/java/airqo/models/GraphInsight.java
  src/view/src/main/java/airqo/models/InsightData.java
  src/view/src/main/java/airqo/services/InsightsServiceImpl.java
Labels: ready for review

#1192 [View API] maintenance
  src/view/Dockerfile
  src/view/pom.xml
  src/view/src/main/java/airqo/ViewApplication.java
  src/view/src/main/java/airqo/controllers/MeasurementController.java
  src/view/src/main/java/airqo/models/GraphInsight.java
  src/view/src/main/java/airqo/models/InsightData.java
  src/view/src/main/java/airqo/services/InsightsServiceImpl.java
  src/view/src/test/java/airqo/ViewApplicationTests.java
Labels: Ready for merge, ready for review

#1196 [Insights API] Querying historical data from BigQuery
  src/view/src/main/java/airqo/Utils.java
  src/view/src/main/java/airqo/config/CacheConfig.java
  src/view/src/main/java/airqo/controllers/MeasurementController.java
  src/view/src/main/java/airqo/services/BigQueryApi.java
  src/view/src/main/java/airqo/services/BigQueryApiImpl.java
  src/view/src/main/java/airqo/services/MeasurementService.java
  src/view/src/main/java/airqo/services/MeasurementServiceImpl.java
Labels: Ready for merge, ready for review

#1193 Add docs redirect for mobile app privacy policy
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: Ready for merge, ready for review

#1190 Schema updates and hotfixes for device registry
  src/device-registry/app.js
  src/device-registry/config/constants.js
  src/device-registry/config/kafkajs.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-monitor.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1197 [View api] Setting up tests in GitHub actions CI/CD
  .github/workflows/run-tests.yml
  src/view/src/test/java/airqo/MeasurementControllerTests.java
Labels: Ready for merge, ready for review

#1188 Fix Circular dependencies in device registry.
  src/device-registry/config/constants.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#1198 [Data pipelines] Maintenance
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/daily_measurements.py
Labels: Ready for merge, ready for review

#1200 add api and 'terms and conditions' redirects
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: enhancement, Ready for merge, ready for review

#1204 [View API] Hotfix
  src/view/src/main/java/airqo/services/InsightsServiceImpl.java
Labels: Ready for merge, ready for review

#1202 analytics report job CI/CD
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  infra/terraform/gcp/modules/SecretManagerSecret/prod-env-analytics-report-job.tf
  infra/terraform/gcp/modules/SecretManagerSecret/prod-key-analytics-report-job-service-account.tf
  infra/terraform/gcp/modules/SecretManagerSecret/sta-env-analytics-report-job.tf
  infra/terraform/gcp/modules/SecretManagerSecret/sta-key-analytics-report-job-service-account.tf
  k8s/analytics/api/.helmignore
  k8s/analytics/api/Chart.yaml
  k8s/analytics/api/charts/.gitkeep
  k8s/analytics/api/templates/NOTES.txt
  k8s/analytics/api/templates/_helpers.tpl
  k8s/analytics/api/templates/deployment.yaml
  k8s/analytics/api/templates/hpa.yaml
  k8s/analytics/api/templates/service.yaml
  k8s/analytics/api/templates/tests/test-connection.yaml
  k8s/analytics/api/values-prod.yaml
  k8s/analytics/api/values-stage.yaml
  k8s/analytics/job/.helmignore
  k8s/analytics/job/Chart.yaml
  k8s/analytics/job/charts/.gitkeep
  k8s/analytics/job/templates/_helpers.tpl
  k8s/analytics/job/templates/cronjob.yaml
  k8s/analytics/job/values-prod.yaml
  k8s/analytics/job/values-stage.yaml
  k8s/analytics/values-dev.yaml
Labels: enhancement, Ready for merge, ready for review, devops
