Repository airqo-platform/AirQo-api, pull requests merged in 2022-07, with the labels that each got.

#903 enabling cors on the Get AirQlouds summary route for the website
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
Labels: ready for review

#905 enable cors from app instance
  src/device-registry/app.js
  src/device-registry/routes/api-v1.js
Labels: ready for review

#906 undo all attempts for resolving cors
  src/device-registry/app.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
Labels: ready for review

#907 hotfixing the cors issue in this microservice
  src/device-registry/config/router.middleware.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#909 add more allowed hosts form cors
  src/device-registry/routes/api-v2.js
Labels: ready for review

#912 utilising cors package to resolve issue.
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#901 Added device registry credentials volumn mounts
  .github/workflows/deploy-previews.yml
  k8s/device-registry/prod-device-registry-api.yaml
  k8s/device-registry/stage-device-registry-api.yaml
Labels: Ready for merge, ready for review, device-registry

#895 Approximating coordinates for export feature
  src/analytics/api/models/events.py
Labels: ready for review

#916 making the device type check case insensitive
  src/data-mgt/node/utils/transform.js
Labels: ready for review

#918 enabling cors at the express app creation point
  src/device-registry/app.js
Labels: ready for review

#902 Hotfix get measurements endpoint (version two)
  src/device-registry/config/constants.js
  src/device-registry/utils/create-event.js
Labels: work in progress

#919 Query for sites without particular fields
  src/data-mgt/python/devices-tranformation/Readme.md
  src/data-mgt/python/devices-tranformation/airqoApi.py
  src/data-mgt/python/devices-tranformation/main.py
  src/data-mgt/python/devices-tranformation/tahmo.py
  src/data-mgt/python/devices-tranformation/transformation.py
  src/data-mgt/python/devices-tranformation/utils.py
Labels: Ready for merge, ready for review

#921 separating ENVS for the datawarehouse queries
  src/device-registry/config/constants.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#920 Streaming urban better data
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/plume_labs_api.py
  src/airflow/airqo_etl_utils/schema/mobile_measurements.json
  src/airflow/airqo_etl_utils/tests/urban_better_utils_tests.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
Labels: ready for review

#923 Enhancements to create device use case
  src/device-registry/models/Device.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#924 adding state as one of the valid admin level for airqlouds
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#922 Chore data pipelines
  src/airflow/airflow_xcom/gcs_xcom_backend.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_data_calibration_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/schema/bam_measurements.json
  src/airflow/airqo_etl_utils/schema/measurements.json
  src/airflow/airqo_etl_utils/schema/mobile_measurements.json
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/docker-compose.yaml
Labels: ready for review

#927 Chore data pipeline
  src/airflow/airqo_etl_utils/schema/mobile_measurements.json
  src/airflow/airqo_etl_utils/tests/urban_better_utils_tests.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/main.py
  src/airflow/schedule-dag.py
Labels: Ready for merge, ready for review

#928 PLAT-1193 urban better data api
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/views/dashboard.py
  src/analytics/config.py
Labels: Ready for merge, ready for review

#929 Hotfix - data pipeline
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_data_calibration_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
Labels: Ready for merge, ready for review

#931 Data warehouse QA [Weather Data]
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_data_calibration_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/schema/weather_data.json
  src/airflow/airqo_etl_utils/tahmo.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/weather_measurements.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#934 Custom data calibration pipeline
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/schema/airqo_mobile_measurements.json
  src/airflow/airqo_etl_utils/tahmo_api.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/airqo_mobile_measurements.py
  src/airflow/dags/weather_measurements.py
  src/airflow/main.py
  src/airflow/requirements.txt
Labels: Ready for merge, ready for review

#939 Renaming Message Broker Namespace
  .github/workflows/deploy-apis-to-staging.yml
Labels: Ready for merge

#936 Streamimg urban better data from air beam
  src/airflow/airqo_etl_utils/air_beam_api.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/schema/devices_meta_data.json
  src/airflow/airqo_etl_utils/schema/mobile_measurements.json
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/main.py
  src/airflow/schedule-dag.py
Labels: Ready for merge, ready for review

#807 deploy jenkins to cicd
  k8s/jenkins/jenkins-ns.yaml
  k8s/jenkins/jenkins-server.yaml
  k8s/jenkins/jenkins-service.yaml
Labels: devops

#940 Deploying data pipelines on staging cluster
  .github/workflows/deploy-apis-to-staging.yml
  k8s/airflow/stage-airflow-app.yaml
Labels: Ready for merge, ready for review

#949 adding province as a valid admin level
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review, device-registry

#933 Enhancements to the API product (V2)
  src/device-registry/app.js
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-event.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/date.js
Labels: ready for review, device-registry, events-registry

#935 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/airflow/stage-airflow-app.yaml
  k8s/jenkins/jenkins-server.yaml
  k8s/jenkins/jenkins-service.yaml
  k8s/kafka-clusters/kafka-cluster.yaml
  k8s/kafka-operator/deployment-script.sh
  k8s/kafka-operator/namespace.yaml
  k8s/kafka-topics/kafka-topics.yaml
  src/airflow/airqo_etl_utils/air_beam_api.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_data_calibration_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/schema/airqo_mobile_measurements.json
  src/airflow/airqo_etl_utils/schema/devices_meta_data.json
  src/airflow/airqo_etl_utils/schema/mobile_measurements.json
  src/airflow/airqo_etl_utils/schema/weather_data.json
  src/airflow/airqo_etl_utils/tahmo.py
  src/airflow/airqo_etl_utils/tahmo_api.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/airqo_mobile_measurements.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/dags/weather_measurements.py
  src/airflow/main.py
  src/airflow/requirements.txt
  src/airflow/schedule-dag.py
  src/analytics/requirements.txt
  src/device-registry/app.js
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-event.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/date.js
Labels: ready for review

#950 Updating validation rules for get measurements v2
  src/device-registry/routes/api-v2.js
Labels: ready for review, device-registry, events-registry

#943 Cleanup - Migrate staging data pipelines to main staging cluster
  .github/workflows/deploy-apis-to-production.yml
  k8s/airflow/airflow-app.yaml
  k8s/airflow/stage-airflow-app.yaml
  k8s/kafka-clusters/kafka-cluster.yaml
  k8s/kafka-topics/kafka-topics.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
Labels: ready for review

#951 Chore data pipeline utility files
  k8s/airflow/stage-airflow-app.yaml
  src/airflow/airqo_etl_utils/air_beam_api.py
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/app_notification_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/message_broker.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/plume_labs_api.py
  src/airflow/airqo_etl_utils/setup.py
  src/airflow/airqo_etl_utils/tahmo_api.py
  src/airflow/airqo_etl_utils/tests/urban_better_utils_tests.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#898 Purple Air Kafka Connector
  .github/workflows/deploy-apis-to-staging.yml
  k8s/airflow/stage-airflow-app.yaml
  k8s/kafka-connectors/measurements-connect.yaml
  k8s/kafka-connectors/purple-air-connector.yaml
  k8s/kafka-topics/kafka-topics.yaml
  src/kafka-connectors/measurements-source-connector/.gitignore
  src/kafka-connectors/measurements-source-connector/Dockerfile
  src/kafka-connectors/measurements-source-connector/Readme.md
  src/kafka-connectors/measurements-source-connector/measurements-source-connector.iml
  src/kafka-connectors/measurements-source-connector/pom.xml
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/PurpleAirConnector.java
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/PurpleAirConnectorConfig.java
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/PurpleAirData.java
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/PurpleAirSourceTask.java
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/Utils.java
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/VersionUtil.java
  src/kafka-connectors/measurements-source-connector/src/main/resources/application.properties
  src/kafka-connectors/measurements-source-connector/src/main/resources/log4j.properties
Labels: ready for review

#953 Enhancements create event
  src/device-registry/utils/create-event.js
Labels: ready for review, events-registry

#954 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/airflow/airflow-app.yaml
  k8s/airflow/stage-airflow-app.yaml
  k8s/kafka-clusters/kafka-cluster.yaml
  k8s/kafka-connectors/measurements-connect.yaml
  k8s/kafka-connectors/purple-air-connector.yaml
  k8s/kafka-topics/kafka-topics.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
  src/airflow/airqo_etl_utils/air_beam_api.py
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/app_notification_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/message_broker.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/plume_labs_api.py
  src/airflow/airqo_etl_utils/setup.py
  src/airflow/airqo_etl_utils/tahmo_api.py
  src/airflow/airqo_etl_utils/tests/urban_better_utils_tests.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/main.py
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-event.js
  src/kafka-connectors/measurements-source-connector/.gitignore
  src/kafka-connectors/measurements-source-connector/Dockerfile
  src/kafka-connectors/measurements-source-connector/Readme.md
  src/kafka-connectors/measurements-source-connector/measurements-source-connector.iml
  src/kafka-connectors/measurements-source-connector/pom.xml
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/PurpleAirConnector.java
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/PurpleAirConnectorConfig.java
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/PurpleAirData.java
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/PurpleAirSourceTask.java
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/Utils.java
  src/kafka-connectors/measurements-source-connector/src/main/java/purpleAir/VersionUtil.java
  src/kafka-connectors/measurements-source-connector/src/main/resources/application.properties
  src/kafka-connectors/measurements-source-connector/src/main/resources/log4j.properties
Labels: ready for review

#955 Streaming BAM data [US Embassies and AirQo]
  src/airflow/airqo_etl_utils/air_beam_api.py
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/app_notification_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/message_broker.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/plume_labs_api.py
  src/airflow/airqo_etl_utils/schema/bam_measurements.json
  src/airflow/airqo_etl_utils/tahmo_api.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
  src/airflow/schedule-dag.py
Labels: Ready for merge, ready for review

#956 Enhancements create event
  src/device-registry/app.js
  src/device-registry/controllers/create-event.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-event.js
Labels: ready for review, device-registry, events-registry

#959 move to production
  src/airflow/airqo_etl_utils/air_beam_api.py
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/app_notification_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/message_broker.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/plume_labs_api.py
  src/airflow/airqo_etl_utils/schema/bam_measurements.json
  src/airflow/airqo_etl_utils/tahmo_api.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
  src/airflow/schedule-dag.py
  src/device-registry/app.js
  src/device-registry/controllers/create-event.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#957 Streaming NASA data sourced from Purple Air
  src/airflow/.gitignore
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/purple_air_api.py
  src/airflow/airqo_etl_utils/purple_air_utils.py
  src/airflow/airqo_etl_utils/schema/devices_meta_data.json
  src/airflow/airqo_etl_utils/schema/raw_measurements.json
  src/airflow/dags/nasa_measurements.py
  src/airflow/main.py
  src/airflow/schedule-dag.py
Labels: Ready for merge, ready for review

#925 enhancements/refactoring of the data management microservice
  src/data-mgt/node/config/constants.js
  src/data-mgt/node/controllers/transform.js
  src/data-mgt/node/utils/date.js
  src/data-mgt/node/utils/transform.js
Labels: work in progress, ready for review, data-mgt

#962 Code cleanup - data pipelines
  .github/workflows/deploy-apis-to-staging.yml
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/purple_air_utils.py
  src/airflow/airqo_etl_utils/schema/calibrated_measurements.json
  src/airflow/airqo_etl_utils/schema/raw_measurements.json
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/meta_data.py
  src/airflow/dags/nasa_measurements.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/main.py
Labels: Ready for merge
