Repository airqo-platform/AirQo-api, pull requests merged in 2022-08, with the labels that each got.

#964 Hotfix - Nasa data query params
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/purple_air_utils.py
  src/airflow/airqo_etl_utils/schema/raw_measurements.json
  src/airflow/main.py
  src/airflow/schedule-dag.py
Labels: Ready for merge

#961 move to production
  .github/workflows/deploy-apis-to-staging.yml
  src/airflow/.gitignore
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/purple_air_api.py
  src/airflow/airqo_etl_utils/purple_air_utils.py
  src/airflow/airqo_etl_utils/schema/calibrated_measurements.json
  src/airflow/airqo_etl_utils/schema/devices_meta_data.json
  src/airflow/airqo_etl_utils/schema/raw_measurements.json
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/meta_data.py
  src/airflow/dags/nasa_measurements.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/main.py
  src/airflow/schedule-dag.py
  src/data-mgt/node/config/constants.js
  src/data-mgt/node/controllers/transform.js
  src/data-mgt/node/utils/date.js
  src/data-mgt/node/utils/transform.js
Labels: ready for review

#966 Fix data pipelines
  src/airflow/Dockerfile
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/plume_labs_api.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/dags/app_insights.py
  src/airflow/requirements.txt
Labels: Ready for merge, ready for review

#968 Migrate production pipeline to main cluster
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/airflow/airflow-app.yaml
  k8s/message-broker-topics/prod-kafka-topics.yaml
  k8s/message-broker-topics/stage-kafka-topics.yaml
Labels: Ready for merge, ready for review

#967 Move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/airflow/airflow-app.yaml
  k8s/message-broker-topics/prod-kafka-topics.yaml
  k8s/message-broker-topics/stage-kafka-topics.yaml
  src/airflow/Dockerfile
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/plume_labs_api.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/dags/app_insights.py
  src/airflow/requirements.txt
Labels: Ready for merge

#969 Hotfix run Device Test in Platform
  src/data-mgt/node/controllers/transform.js
  src/data-mgt/node/utils/date.js
Labels: ready for review

#970 move to production
  src/data-mgt/node/controllers/transform.js
  src/data-mgt/node/utils/date.js
Labels: ready for review

#971 adding new query parameters for v2 endpoint
  src/device-registry/utils/create-event.js
Labels: ready for review

#972 move to production
  src/device-registry/utils/create-event.js
Labels: ready for review

#948 Mob 91 backing up the user data
  src/firebase/backup/.firebaserc
  src/firebase/backup/.gitignore
  src/firebase/backup/README.md
  src/firebase/backup/firebase.json
  src/firebase/backup/functions/.eslintrc.js
  src/firebase/backup/functions/.gitignore
  src/firebase/backup/functions/index.js
  src/firebase/backup/functions/package-lock.json
  src/firebase/backup/functions/package.json
Labels: Ready for merge, ready for review

#974 Fix - data pipelines
  k8s/kafka-clusters/kafka-cluster.yaml
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/schema/airqo_mobile_measurements.json
  src/airflow/airqo_etl_utils/schema/measurements.json
  src/airflow/airqo_etl_utils/tests/airqo_utils_tests.py
  src/airflow/airqo_etl_utils/tests/urban_better_utils_tests.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/airqo_mobile_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/main.py
  src/airflow/schedule-dag.py
Labels: Ready for merge, ready for review

#976 handle difference between hourly and raw schemas
  src/device-registry/utils/create-event.js
Labels: ready for review

#977 move to production
  src/device-registry/utils/create-event.js
Labels: ready for review

#979 Hotfix for the events v2 to cater for mobile data
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#980 move to production
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#981 add support for new query parameters
  src/device-registry/utils/create-event.js
Labels: ready for review

#983 addressing the issues of nested time for gps_device_timestamp
  src/device-registry/utils/create-event.js
Labels: ready for review

#984 move to production
  src/device-registry/utils/create-event.js
Labels: ready for review

#941 Ft cleanup deploy previews & and namespace manifests
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  .pre-commit-config.yaml
  k8s/namespaces/cicd.yaml
  k8s/namespaces/development.yaml
  k8s/namespaces/message-broker.yaml
  k8s/namespaces/pipeline.yaml
  k8s/namespaces/production.yaml
  k8s/namespaces/staging.yaml
Labels: enhancement, Ready for merge, ready for review

#932 Add site name to exported data [AQCSV]
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/views/dashboard.py
Labels: ready for review

#986 Fix data pipelines
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/schema/mobile_measurements.json
  src/airflow/airqo_etl_utils/tests/airqo_utils_tests.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#991 Add weather stations to site details
  src/device-registry/models/Site.js
Labels: ready for review

#989 Hotfix - Typos
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/dags/urban_better_measurements.py
Labels: Ready for merge, ready for review

#987 Process historical BAM data
  src/airflow/main.py
Labels: Ready for merge, ready for review

#990 Enhancing the datawarehouse microservice to return nearest weather stations
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/meta-data-service/prod-meta-data-api.yaml
  k8s/meta-data-service/stage-meta-data-api.yaml
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
  src/meta-data/.dockerignore
  src/meta-data/.gitignore
  src/meta-data/Dockerfile
  src/meta-data/README.md
  src/meta-data/api/__init__.py
  src/meta-data/api/controllers/__init__.py
  src/meta-data/api/controllers/extract.py
  src/meta-data/api/docs/get-nearest-stations.yml
  src/meta-data/api/helpers/__init__.py
  src/meta-data/api/helpers/validation.py
  src/meta-data/api/models/TAHMO/__init__.py
  src/meta-data/api/models/__init__.py
  src/meta-data/api/models/extract.py
  src/meta-data/api/routes/__init__.py
  src/meta-data/api/routes/api.py
  src/meta-data/app.py
  src/meta-data/config.py
  src/meta-data/docker-compose.yml
  src/meta-data/requirements.txt
  src/meta-data/run-docker-compose.sh
Labels: ready for review

#993 Hotfix - metadata api build failure
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/meta-data/prod-meta-data-api.yaml
  k8s/meta-data/stage-meta-data-api.yaml
Labels: Ready for merge, ready for review

#960 cleans up datawarehouse deployment
  k8s/data-warehouse/prod-data-warehouse-api.yaml
  k8s/data-warehouse/stage-data-warehouse-api.yaml
Labels: enhancement, ready for review

#994 Add distance to weather station
  src/device-registry/models/Site.js
Labels: Ready for merge

#997 enhancements to the public API
  src/device-registry/controllers/create-device.js
  src/device-registry/models/Device.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#995 Using multiple Tahmo stations for a site's weather data
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
Labels: ready for review

#998 Fix - typo
  .github/workflows/deploy-apis-to-production.yml
  workflow-trigger
Labels: Ready for merge, ready for review

#999 Calibrating mobile devices' data
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/schema/airqo_mobile_measurements.json
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/airqo_mobile_measurements.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#1001 Move to production
  .github/workflows/deploy-apis-to-production.yml
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/calibration_utils.py
  src/airflow/airqo_etl_utils/schema/airqo_mobile_measurements.json
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/airqo_mobile_measurements.py
  src/airflow/main.py
  workflow-trigger
Labels: ready for review

#1002 making site ID optional
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review

#1000 disabling kafka connectors on staging
  .github/workflows/deploy-apis-to-staging.yml
Labels: Ready for merge, ready for review

#988 Ft secrets injection
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
Labels: enhancement, Ready for merge, ready for review, devops

#880 Update stage-platform-ingress-resource.yaml
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
Labels: Ready for merge, ready for review

#1003 Hotfix data pipelines
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_mobile_measurements.py
Labels: Ready for merge, ready for review

#1005 Hotfix issues around access to BAM measurements
  src/device-registry/utils/create-event.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1006 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/clusters/production/prod-kafka-cluster.yaml
  k8s/clusters/staging/access-control/dev-restricted-user.yaml
  k8s/clusters/staging/access-control/dev-user.yaml
  k8s/clusters/staging/dev-kafka-cluster.yaml
  k8s/clusters/staging/dev-values.yaml
  k8s/clusters/staging/stage-kafka-cluster.yaml
  k8s/clusters/staging/stage-values.yaml
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_mobile_measurements.py
  src/device-registry/config/constants.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1007 fix - date time querying
  src/airflow/.dockerignore
  src/airflow/.gitignore
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/purple_air_utils.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#978 changing the run script from nodemon to node
  src/data-mgt/node/package.json
Labels: ready for review

#1012 just making the field8 BAM value field definitions more descriptive
  src/data-mgt/node/config/constants.js
Labels: ready for review

#1008 Refactor - streaming AirQo BAM data
  src/airflow/airflow_xcom/gcs_xcom_backend.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/schema/bam_raw_measurements.json
  src/airflow/airqo_etl_utils/thingspeak_api.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/airqo_mobile_measurements.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#1010 move to production
  src/airflow/.dockerignore
  src/airflow/.gitignore
  src/airflow/airflow_xcom/gcs_xcom_backend.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/purple_air_utils.py
  src/airflow/airqo_etl_utils/schema/bam_raw_measurements.json
  src/airflow/airqo_etl_utils/thingspeak_api.py
  src/airflow/airqo_etl_utils/urban_better_utils.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/airqo_mobile_measurements.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/main.py
  src/data-mgt/node/config/constants.js
  src/data-mgt/node/package.json
  src/device-registry/utils/create-event.js
Labels: ready for review

#992 Maintenance - Data pipelines
  src/airflow/airflow_xcom/gcs_xcom_backend.py
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/tahmo_api.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/meta_data.py
  src/airflow/main.py
  src/data-mgt/python/devices-tranformation/airqoApi.py
  src/data-mgt/python/devices-tranformation/main.py
  src/data-mgt/python/devices-tranformation/tahmo.py
  src/data-mgt/python/devices-tranformation/transformation.py
  src/meta-data/api/models/extract.py
Labels: Ready for merge, ready for review

#1014 fixing the retrieval of BAM measurements
  src/device-registry/utils/create-event.js
Labels: ready for review

#1016 Output html instead of CSV data
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1017 move to production
  src/device-registry/controllers/create-event.js
Labels: ready for review
