Repository airqo-platform/AirQo-api, pull requests merged in 2022-04, with the labels that each got.

#775 Update configurations to reduce the uptime calculations to 30 mins
  k8s/device-status/prod-airqo-device-status-job.yaml
  k8s/device-status/stage-airqo-device-status-job.yaml
  k8s/device-uptime/prod-airqo-device-uptime-job.yaml
  k8s/device-uptime/stage-airqo-device-uptime-job.yaml
Labels: ready for review, device-status, device-uptime, devops

#777 Hotfix transmit events
  src/device-registry/utils/create-event.js
Labels: Ready for merge, ready for review

#769 App Forecast Insights
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/dags/app_insights.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
  src/airflow/message-broker-setup.sh
  src/view/src/main/java/airqo/controllers/MessageBroker.java
  src/view/src/main/java/airqo/models/Insight.java
  src/view/src/main/java/airqo/repository/InsightRepository.java
  src/view/src/main/java/airqo/services/MeasurementService.java
  src/view/src/main/java/airqo/services/MeasurementServiceImpl.java
  src/view/src/main/java/airqo/tasks/InsightsTasks.java
Labels: Ready for merge, ready for review

#776 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/device-status/prod-airqo-device-status-job.yaml
  k8s/device-status/stage-airqo-device-status-job.yaml
  k8s/device-uptime/prod-airqo-device-uptime-job.yaml
  k8s/device-uptime/stage-airqo-device-uptime-job.yaml
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/dags/app_insights.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
  src/airflow/message-broker-setup.sh
  src/device-registry/utils/create-event.js
  src/device-status/config.py
  src/device-uptime/config.py
  src/view/src/main/java/airqo/controllers/MessageBroker.java
  src/view/src/main/java/airqo/models/Insight.java
  src/view/src/main/java/airqo/repository/InsightRepository.java
  src/view/src/main/java/airqo/services/MeasurementService.java
  src/view/src/main/java/airqo/services/MeasurementServiceImpl.java
  src/view/src/main/java/airqo/tasks/InsightsTasks.java
Labels: Ready for merge, ready for review

#780 Hotfix[pipeline] - added checks for null values
  src/airflow/airqo_etl_utils/airqo_utils.py
Labels: Ready for merge, ready for review

#782 Hotfix - Events Pipeline ETL
  src/airflow/airqo_etl_utils/airqo_utils.py
Labels: Ready for merge, ready for review

#783 Triggering entire workflow
  workflow-trigger
Labels: Ready for merge

#784 move to production
  src/airflow/airqo_etl_utils/airqo_utils.py
  workflow-trigger
Labels: Ready for merge, ready for review

#785 change field name when getting activities
  src/device-registry/controllers/create-activity.js
Labels: Ready for merge, ready for review

#786 move to production
  src/device-registry/controllers/create-activity.js
Labels: Ready for merge, ready for review

#789 View consumer adjustments
  src/airflow/dags/app_insights.py
  src/view/src/main/java/airqo/controllers/MessageBroker.java
Labels: Ready for merge, ready for review

#790 Streaming weather data
  src/airflow/dags/airqo_measurements.py
Labels: Ready for merge, ready for review

#791 re-enabled the weather api access--was recently fixed
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Site.js
  src/device-registry/utils/create-site.js
Labels: ready for review

#770 Ft network uptime
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/calibrate/stage-calibrate-api.yaml
  k8s/network-uptime/prod-airqo-network-uptime-job.yaml
  k8s/network-uptime/stage-airqo-network-uptime-job.yaml
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
  src/network-uptime/.dockerignore
  src/network-uptime/Dockerfile
  src/network-uptime/README.md
  src/network-uptime/network-dashboard.py
  src/network-uptime/requirements.txt
Labels: ready for review

#792 Enabling caching on view API
  src/view/pom.xml
  src/view/src/main/java/airqo/ViewApplication.java
Labels: Ready for merge, ready for review

#689 read events using Date Ranges
  src/data-mgt/node/app.js
  src/data-mgt/node/config/constants.js
  src/data-mgt/node/config/redis.js
  src/data-mgt/node/controllers/transform.js
  src/data-mgt/node/package-lock.json
  src/data-mgt/node/package.json
  src/data-mgt/node/routes/api.js
  src/data-mgt/node/utils/clean-measurements.js
  src/data-mgt/node/utils/date.js
  src/data-mgt/node/utils/errors.js
  src/data-mgt/node/utils/gps-check.js
  src/data-mgt/node/utils/jsonify.js
  src/data-mgt/node/utils/mappings.js
  src/data-mgt/node/utils/transform.js
Labels: ready for review, data-mgt

#795 Fix deploy to k8s stage failure on staging deploy GitHub action
  .pre-commit-config.yaml
  k8s/network-uptime/prod-airqo-network-uptime-job.yaml
  k8s/network-uptime/stage-airqo-network-uptime-job.yaml
Labels: hotfix, ready for review

#798 trigger deploy workflow
  workflow-trigger
Labels: Ready for merge

#797 Functionality for refreshing all sites for a particular tenant
  src/data-mgt/python/devices-tranformation/Readme.md
  src/data-mgt/python/devices-tranformation/airqoApi.py
  src/data-mgt/python/devices-tranformation/main.py
  src/data-mgt/python/devices-tranformation/transformation.py
Labels: ready for review

#800 Change the type for the Aspect field of each Site from String to Number.
  src/device-registry/models/Site.js
  src/device-registry/routes/api-v1.js
Labels: hotfix, ready for review, device-registry, site-registry

#799 Fix network uptime workflow runtime error
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/network-uptime/prod-airqo-network-uptime-api.yaml
  k8s/network-uptime/stage-airqo-network-uptime-api.yaml
  src/network-uptime/network-dashboard.py
Labels: Ready for merge, ready for review

#803 fixed dashbord error&refactored date hardcoding
  src/network-uptime/.dockerignore
  src/network-uptime/network-dashboard.py
Labels: Ready for merge, ready for review

#802 Data pipeline - Scheduling Jobs
  src/airflow/README.md
  src/airflow/airqo_etl_utils/arg_parse_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/dags/app_insights.py
  src/airflow/db-setup.sh
  src/airflow/docker-compose.yaml
  src/airflow/schedule-dag.py
Labels: ready for review

#805 Streaming raw measurements, sites and devices into BigQuery
  src/airflow/README.md
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/schema/devices.json
  src/airflow/airqo_etl_utils/schema/sites.json
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/meta_data.py
  src/airflow/dags/weather_measurements.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
  src/airflow/schedule-dag.py
Labels: ready for review

#808 hotfix on refresh AirQlouds
  src/device-registry/models/Airqloud.js
  src/device-registry/utils/create-airqloud.js
Labels: Ready for merge, ready for review

#809 Just logging Site details in the Alternative Flows during AirQloud refresh
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/utils/create-airqloud.js
Labels: Ready for merge, ready for review

#815 Fix - Calibrate tool endpoint
  src/calibrate/controllers/calibrate.py
  src/calibrate/readme.md
Labels: ready for review
