Repository airqo-platform/AirQo-api, pull requests merged in 2022-02, with the labels that each got.

#709 Predict api cicd
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/predict/prod-prediction-api.yaml
  k8s/predict/stage-prediction-api.yaml
  src/auth-service/package-lock.json
  src/device-registry/package-lock.json
  src/incentives/package-lock.json
  src/predict/Dockerfile
Labels: ready for review, devops, predict

#716 Packaging utility functions and fixing typos in workflow files
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/airflow/.dockerignore
  src/airflow/.gitignore
  src/airflow/Dockerfile
  src/airflow/README.md
  src/airflow/airflow_utils/__init__.py
  src/airflow/airflow_utils/airqo_api.py
  src/airflow/airflow_utils/airqo_utils.py
  src/airflow/airflow_utils/app_insights_utils.py
  src/airflow/airflow_utils/commons.py
  src/airflow/airflow_utils/config.py
  src/airflow/airflow_utils/date.py
  src/airflow/airflow_utils/kcca_utils.py
  src/airflow/airflow_utils/message_broker.py
  src/airflow/airflow_utils/setup.py
  src/airflow/airflow_utils/tahmo.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/main.py
  src/airflow/dags/weather_measurements.py
  src/airflow/docker-compose.yaml
Labels: ready for review

#712 Refactor CI/CD files
  pipeline/cloud-functions/node/.gitkeep
  pipeline/cloud-functions/python/.gcloudignore
  pipeline/cloud-functions/python/.gitkeep
  pipeline/cloud-functions/python/README.md
  pipeline/cloud-functions/python/cloud_function_process_kcca_device_measurements.py
  pipeline/cloud-functions/python/device_registry.py
  pipeline/cloud-functions/python/helpers.py
  pipeline/cloud-functions/python/main.py
  pipeline/cloud-functions/python/requirements.txt
  pipeline/deploy-changed.sh
  src/analytics/app.yaml
  src/auth-service/app.yaml
  src/averages/app.yaml
  src/categories/app.yaml
  src/data-mgt/node/app.yaml
  src/device-monitoring/app.yaml
  src/device-registry/app.yaml
  src/device-status/app.yaml
  src/device-uptime/app.yaml
  src/incentives/app.yaml
  src/locate/app.yaml
Labels: enhancement, Ready for merge, ready for review, refactoring

#717 Pipeline and message broker cleanup
  k8s/average/prod-airqo-average-job.yaml
  k8s/average/prod-kcca-average-job.yaml
  k8s/average/stage-airqo-average-job.yaml
  k8s/average/stage-kcca-average-job.yaml
  k8s/batch-streams/jobs/.gitignore
  k8s/batch-streams/jobs/prod-airqo-batch-measurements-cronjob.yaml
  k8s/batch-streams/jobs/prod-kcca-batch-measurements-cronjob.yaml
  k8s/batch-streams/jobs/stage-airqo-batch-measurements-cronjob.yaml
  k8s/batch-streams/jobs/stage-kcca-batch-measurements-cronjob.yaml
  k8s/batch-streams/streams/prod-airqo-batch-measurements-stream.yaml
  k8s/batch-streams/streams/prod-airqo-batch-tahmo-values-stream.yaml
  k8s/batch-streams/streams/prod-kcca-batch-measurements-stream.yaml
  k8s/batch-streams/streams/stage-airqo-batch-measurements-stream.yaml
  k8s/batch-streams/streams/stage-airqo-batch-tahmo-values-stream.yaml
  k8s/batch-streams/streams/stage-kcca-batch-measurements-stream.yaml
  k8s/clusters/prod-kafka-cluster.yaml
  k8s/clusters/stage-kafka-cluster.yaml
  k8s/connectors/prod-measurements-connect.yaml
  k8s/connectors/stage-measurements-connect.yaml
  k8s/kafka-connectors/.helmignore
  k8s/kafka-connectors/Chart.yaml
  k8s/kafka-connectors/dev-values.yaml
  k8s/kafka-connectors/prod-values.yaml
  k8s/kafka-connectors/stage-values.yaml
  k8s/kafka-connectors/templates/NOTES.txt
  k8s/kafka-connectors/templates/_helpers.tpl
  k8s/kafka-connectors/templates/connector.yaml
  k8s/kafka-topics/.gitignore
  k8s/kafka-topics/.helmignore
  k8s/kafka-topics/Chart.yaml
  k8s/kafka-topics/stage-values.yaml
  k8s/kafka-topics/templates/NOTES.txt
  k8s/kafka-topics/templates/_helpers.tpl
  k8s/kafka-topics/templates/kafka-topics.yaml
  k8s/measurements-consumer/.helmignore
  k8s/measurements-consumer/Chart.yaml
  k8s/measurements-consumer/prod-airqo-measurements-consumer.yaml
  k8s/measurements-consumer/prod-kcca-measurements-consumer.yaml
  k8s/measurements-consumer/stage-airqo-measurements-consumer.yaml
  k8s/measurements-consumer/stage-kcca-measurements-consumer.yaml
  k8s/measurements-consumer/templates/NOTES.txt
  k8s/measurements-consumer/templates/_helpers.tpl
  k8s/measurements-consumer/templates/deployment.yaml
  k8s/measurements-consumer/values.yaml
  k8s/message-broker-topics/prod-measurements-topics.yaml
  k8s/message-broker-topics/stage-measurements-topics.yaml
  k8s/message-broker-topics/stage-notification-topics.yaml
  k8s/topics/dev-topics.yaml
  k8s/topics/prod-airqo-streams-topics.yaml
  k8s/topics/prod-averaged-measurements-topic.yaml
  k8s/topics/prod-kcca-streams-topics.yaml
  k8s/topics/stage-airqo-batch-topics.yaml
  k8s/topics/stage-airqo-streams-topics.yaml
  k8s/topics/stage-averaged-mesurements.yaml
  k8s/topics/stage-kcca-batch-topics.yaml
  k8s/topics/stage-kcca-streams-topics.yaml
Labels: Ready for merge, ready for review

#718 BigQuery hourly measurements table refactoring
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/airflow/README.md
  src/airflow/airflow_utils/airqo_utils.py
  src/airflow/airflow_utils/app_insights_utils.py
  src/airflow/airflow_utils/bigquery_api.py
  src/airflow/airflow_utils/commons.py
  src/airflow/airflow_utils/kcca_utils.py
  src/airflow/airflow_utils/message_broker.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/main.py
  src/airflow/db-setup.sh
  src/airflow/docker-compose.yaml
Labels: ready for review

#707 Airqualibrate pdt1 similar devices
  src/calibrate/.gitignore
  src/calibrate/controllers/calibrate.py
  src/calibrate/jobs/regression.py
  src/calibrate/jobs/train_calibrate_tool.py
  src/calibrate/models/calibrate_tool.py
  src/calibrate/models/regression.py
  src/calibrate/models/train_calibrate_tool.py
  src/calibrate/requirements.txt
  src/calibrate/routes/api.py
Labels: ready for review

#721 [Analytics] BigQuery Data Export
  src/analytics/.gitignore
  src/analytics/api/models/events.py
  src/analytics/api/views/dashboard.py
  src/analytics/config.py
  src/analytics/main.py
  src/analytics/requirements.txt
Labels: ready for review

#728 Analytics volume mounts
  k8s/analytics/prod-analytics-api.yaml
  k8s/analytics/stage-analytics-api.yaml
Labels: Ready for merge, ready for review

#723 use open source util for email verification
  src/auth-service/utils/request.js
Labels: hotfix, ready for review, authentication-service

#724 Update pull_request_template.md
  .github/pull_request_template.md
Labels: ready for review

#711 set token to 100000 for test email address
  src/auth-service/utils/join.js
Labels: ready for review, authentication-service

#725 Fix 'Refactor CI/CD files' action failure
  .github/workflows/deploy-apis-to-staging.yml
Labels: hotfix, ready for review

#733 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/workflow-versions
  workflow-versions
Labels: ready for review
