Repository airqo-platform/AirQo-api, pull requests merged in 2022-12, with the labels that each got.

#1205 Ft auto image update
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/test-changes.yml
  k8s/analytics/api/.helmignore
  k8s/analytics/api/Chart.yaml
  k8s/analytics/api/charts/.gitkeep
  k8s/analytics/api/templates/NOTES.txt
  k8s/analytics/api/templates/_helpers.tpl
  k8s/analytics/api/templates/deployment.yaml
  k8s/analytics/api/templates/hpa.yaml
  k8s/analytics/api/templates/service.yaml
  k8s/analytics/api/templates/tests/test-connection.yaml
  k8s/analytics/api/values-prod.yaml
  k8s/analytics/api/values-stage.yaml
  k8s/events-monitor/templates/cronjob.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/network-uptime/values-stage.yaml
  k8s/redis/.helmignore
  k8s/redis/Chart.yaml
  k8s/redis/charts/.gitkeep
  k8s/redis/templates/deployment.yaml
  k8s/redis/templates/hpa.yaml
  k8s/redis/templates/service.yaml
  k8s/redis/values-prod.yaml
  k8s/redis/values-stage.yaml
  k8s/view/api/.helmignore
  k8s/view/api/Chart.yaml
  k8s/view/api/charts/.gitkeep
  k8s/view/api/templates/NOTES.txt
  k8s/view/api/templates/_helpers.tpl
  k8s/view/api/templates/deployment.yaml
  k8s/view/api/templates/hpa.yaml
  k8s/view/api/templates/service.yaml
  k8s/view/api/templates/tests/test-connection.yaml
  k8s/view/api/values-prod.yaml
  k8s/view/api/values-stage.yaml
  k8s/view/message-broker/.helmignore
  k8s/view/message-broker/Chart.yaml
  k8s/view/message-broker/charts/.gitkeep
  k8s/view/message-broker/templates/NOTES.txt
  k8s/view/message-broker/templates/_helpers.tpl
  k8s/view/message-broker/templates/deployment.yaml
  k8s/view/message-broker/templates/hpa.yaml
  k8s/view/message-broker/values-prod.yaml
  k8s/view/message-broker/values-stage.yaml
  k8s/view/prod-view-api.yaml
  k8s/view/prod-view-message-broker.yaml
  k8s/view/stage-view-api.yaml
  k8s/view/stage-view-message-broker.yaml
  workflow-trigger
Labels: enhancement, ready for review, devops

#1183 Send welcome message to mobile application new users
  src/auth-service/config/constants.js
  src/auth-service/config/firebase-admin.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/services/mailer.js
Labels: ready for review

#1210 bcc to different emails of inquiries
  src/auth-service/config/constants.js
  src/auth-service/controllers/request.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/User.js
  src/auth-service/services/mailer.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/inquire.js
  src/auth-service/utils/request.js
Labels: ready for review

#1206 linking meta data microservice to message broker
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/meta-data/templates/deployment.yaml
  k8s/meta-data/values-prod.yaml
  k8s/meta-data/values-stage.yaml
  src/meta-data/Dockerfile
  src/meta-data/airqo_api.py
  src/meta-data/api/controllers/extract.py
  src/meta-data/config.py
  src/meta-data/message-broker.py
  src/meta-data/requirements.txt
Labels: ready for review

#1208 [Data pipeline] - fix hourly measurements message format
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/message_broker_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/kcca_measurements.py
Labels: work in progress, ready for review

#1213 Fix push to gcr
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  .github/workflows/test-changes.yml
  workflow-trigger
Labels: bug, hotfix, ready for review

#1217 [Data pipeline] - hotfix
  src/airflow/airqo_etl_utils/date.py
Labels: ready for review

#1218 Move to production
  src/airflow/airqo_etl_utils/date.py
Labels: ready for review

#1216 Fix failing deployments
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  workflow-trigger
Labels: hotfix, ready for review, devops

#1219 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  workflow-trigger
Labels: ready for review

#1221 fix remaining production failing deployments
  .github/workflows/deploy-apis-to-production.yml
  workflow-trigger
Labels: hotfix

#1223 set specific argocd version to install
  k8s/argo-cd/README.md
  k8s/argo-cd/argocd-server-deployment.yaml
Labels: enhancement, hotfix, ready for review

#1209 [Device Registry] Hotfixes AND metadata(DB) updates + migrations
  src/device-registry/.gitignore
  src/device-registry/app.js
  src/device-registry/config/kafka-node.js
  src/device-registry/config/kafkajs.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Activity.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Location.js
  src/device-registry/models/Measurement.js
  src/device-registry/models/Photo.js
  src/device-registry/models/Sensor.js
  src/device-registry/models/Setting.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/routes/api-v1.js
  src/device-registry/scripts/bulk-create.js
  src/device-registry/scripts/bulk-delete.js
  src/device-registry/scripts/bulk-update.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1225 move to production
  k8s/argo-cd/README.md
  k8s/argo-cd/argocd-server-deployment.yaml
  src/device-registry/.gitignore
  src/device-registry/app.js
  src/device-registry/config/kafka-node.js
  src/device-registry/config/kafkajs.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Activity.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Location.js
  src/device-registry/models/Measurement.js
  src/device-registry/models/Photo.js
  src/device-registry/models/Sensor.js
  src/device-registry/models/Setting.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/routes/api-v1.js
  src/device-registry/scripts/bulk-create.js
  src/device-registry/scripts/bulk-delete.js
  src/device-registry/scripts/bulk-update.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1226 temporarily disable bulk action activities
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-site.js
Labels: ready for review

#1228 Hotfix device registry
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-site.js
Labels: ready for review

#1229 only calculate uptime for AirQo devices
  src/device-uptime/device_uptime.py
Labels: ready for review

#1231 resolving status issues
  src/device-status/device_status.py
Labels: ready for review

#1233 Cont'd: Hotfix device status
  src/device-status/device_status.py
  src/device-status/models.py
Labels: ready for review

#1232 move to production...
  src/device-status/device_status.py
  src/device-status/models.py
Labels: ready for review

#1220 [Analytics] - Dealing with Duplicate values via data export.
  src/analytics/api/models/events.py
Labels: ready for review

#1234 edge cases for device name during device creation process
  src/device-registry/models/Device.js
Labels: ready for review, device-registry

#1236 move to production
  src/analytics/api/models/events.py
  src/device-registry/models/Device.js
Labels: ready for review

#1235 Refactor firebase lookup endpoint
  src/auth-service/controllers/join.js
Labels: ready for review
