Repository airqo-platform/AirQo-api, pull requests merged in 2022-10, with the labels that each got.

#1076 Pipeline integration with firebase
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/schema/latest_measurements.json
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#1104 Hotfixes - Data pipelines
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/kcca_utils.py
Labels: Ready for merge, ready for review

#1093 Fix meta data workflow
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/meta-data/prod-meta-data-api.yaml
  k8s/meta-data/stage-meta-data-api.yaml
Labels: enhancement, Ready for merge, hotfix, ready for review

#1105 Chore - data pipelines
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/dags/airflow_app.py
Labels: Ready for merge, ready for review

#1106 hotfix data pipelines
  src/airflow/README.md
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/analytics/api/utils/data_formatters.py
Labels: Ready for merge, ready for review

#1110 [Data Pipeline] fix consolidated latest data
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/app_insights.py
  src/airflow/dev-requirements.txt
Labels: Ready for merge, ready for review

#1109 Move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/meta-data/prod-meta-data-api.yaml
  k8s/meta-data/stage-meta-data-api.yaml
  src/airflow/README.md
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/schema/latest_measurements.json
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/airflow_app.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dev-requirements.txt
  src/airflow/main.py
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/views/__init__.py
  src/analytics/api/views/map.py
  src/analytics/config.py
  src/analytics/manage.py
  src/gp-model/helpers/get_data.py
  src/gp-model/main.py
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
Labels: ready for review

#1113 [Meta Data API] Extracting geo coordinates from an IP address
  src/meta-data/api/controllers/extract.py
  src/meta-data/api/models/extract.py
  src/meta-data/api/routes/api.py
Labels: ready for review

#1112 [Data Pipelines] Fix - data consolidation
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/dags/airflow_app.py
  src/airflow/dags/data_warehouse.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#1111 add analytics hosts to ingress
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
Labels: Ready for merge, ready for review

#1117 APIs to get mobile carrier and geo coordinates
  src/meta-data/api/controllers/extract.py
  src/meta-data/api/models/extract.py
  src/meta-data/api/routes/api.py
  src/meta-data/config.py
Labels: Ready for merge, ready for review

#1118 [Meta Data API] Fixes a query params typo while getting greeness
  src/meta-data/api/controllers/extract.py
Labels: Ready for merge, ready for review

#1115 [Data pipeline] Fixed url suffixes
  src/airflow/Dockerfile
  src/airflow/airqo_etl_utils/air_beam_api.py
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/setup.py
  src/airflow/airqo_etl_utils/tahmo_api.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/airflow_app.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/airqo_mobile_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/app_notifications.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/meta_data.py
  src/airflow/dags/nasa_measurements.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/dags/weather_measurements.py
Labels: ready for review

#1101 Fix deviceregistry monthsinfront
  src/device-registry/config/constants.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/date.js
Labels: ready for review

#1120 Fix hardcoded urls
  src/device-status/config.py
  src/device-uptime/config.py
Labels: Ready for merge, ready for review

#1114 [BigQuery] Reforming devices and sites schemas
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/schema/devices.json
  src/airflow/airqo_etl_utils/schema/sites.json
  src/airflow/airqo_etl_utils/schema/sites_meta_data.json
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airflow_app.py
  src/airflow/dags/meta_data.py
  src/airflow/main.py
Labels: Ready for merge, ready for review

#1122 refactor the deviceDeploy endpoint to handle updating of the device s…
  src/device-registry/utils/create-activity.js
Labels: hotfix, ready for review, device-registry

#1124 [Data pipeline] Multiple fixes
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/message_broker.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/schema/devices_meta_data.json
  src/airflow/airqo_etl_utils/schema/latest_measurements.json
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/meta_data.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
Labels: Ready for merge, ready for review

#1126 Hotfix - airnow latest data
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
Labels: Ready for merge, ready for review

#1085 addresses issue #1075
  src/auth-service/config/constants.js
  src/auth-service/services/mailer.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/multitenancy.js
  src/auth-service/utils/request.js
Labels: hotfix, ready for review, authentication-service

#1130 [Data pipeline] Fix - data duplication error
  src/airflow/Dockerfile
  src/airflow/airflow-requirements.txt
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/schema/README.md
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/dag_docs.py
  src/airflow/dags/task_docs.py
Labels: Ready for merge, ready for review

#1129 move to production
  src/airflow/Dockerfile
  src/airflow/airflow-requirements.txt
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/schema/README.md
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/dag_docs.py
  src/airflow/dags/task_docs.py
  src/auth-service/config/constants.js
  src/auth-service/services/mailer.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/multitenancy.js
  src/auth-service/utils/request.js
Labels: ready for review

#1128 airflow env secrets injection
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
Labels: enhancement, Ready for merge, ready for review

#1131 Virtual server for (staging-)platform.airqo.net
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .prettierignore
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/production/ingress.yaml
  k8s/nginx/production/virtual-server.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/nginx/staging/ingress.yaml
  k8s/nginx/staging/virtual-server.yaml
  workflow-trigger
Labels: enhancement, Ready for merge, ready for review

#1132 support query measurements by network name
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Event.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry

#1119 Enhancements to the Auth Service
  src/auth-service/config/mailchimp.js
  src/auth-service/controllers/join.js
  src/auth-service/routes/api-v1.js
  src/auth-service/services/auth.js
  src/auth-service/services/mailer.js
  src/auth-service/utils/join.js
Labels: ready for review, authentication-service

#1135 [Data pipelines] 2.4.1 post upgrade fixes
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/airqo_mobile_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/meta_data.py
  src/airflow/dags/nasa_measurements.py
  src/airflow/dags/weather_measurements.py
Labels: Ready for merge, ready for review

#1136 Fix data pipelines
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/dags/app_insights.py
Labels: Ready for merge, ready for review

#1011 Mobile app api authentication exemptions
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .prettierignore
  k8s/nginx/production/global-config.yaml
  k8s/nginx/production/ingress.yaml
  k8s/nginx/production/virtual-server.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/nginx/staging/ingress.yaml
  k8s/nginx/staging/virtual-server.yaml
  workflow-trigger
Labels: enhancement, Ready for merge, ready for review, authentication-service

#1087 Adding consumer to run at app start
  src/device-registry/config/kafkajs.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#1139 introducing new script for running staging in auth
  src/auth-service/Dockerfile
  src/auth-service/package.json
  src/auth-service/routes/api-v1.js
  src/auth-service/utils/join.js
Labels: ready for review, authentication-service

#1138 introducing a new script for running staging in data-mgt/node
  src/data-mgt/node/Dockerfile.stage
  src/data-mgt/node/package.json
Labels: ready for review, data-mgt

#1141 move to production
  src/auth-service/Dockerfile
  src/auth-service/package.json
  src/auth-service/routes/api-v1.js
  src/auth-service/utils/join.js
  src/data-mgt/node/Dockerfile.stage
  src/data-mgt/node/package.json
  src/device-registry/Dockerfile
  src/device-registry/config/kafkajs.js
  src/device-registry/package.json
  src/device-registry/utils/create-event.js
Labels: ready for review

#1144 resolving the runtime error in run device test
  src/data-mgt/node/controllers/transform.js
  src/data-mgt/node/utils/transform.js
Labels: ready for review

#1146 just handling a runtime error for fetching candidates by category
  src/auth-service/controllers/request.js
  src/auth-service/models/Candidate.js
  src/auth-service/utils/request.js
Labels: ready for review, authentication-service

#1149 [View API] Chore
  src/view/README.md
  src/view/docker-compose.yaml
  src/view/message-broker-setup.sh
  src/view/pom.xml
  src/view/src/main/asciidoc/index.adoc
  src/view/src/main/java/airqo/config/WebConfig.java
  src/view/src/main/java/airqo/controllers/DeviceController.java
  src/view/src/main/java/airqo/controllers/MeasurementController.java
  src/view/src/main/java/airqo/controllers/MessageBroker.java
  src/view/src/main/java/airqo/controllers/SiteController.java
  src/view/src/main/java/airqo/models/Device.java
  src/view/src/main/java/airqo/models/Measurement.java
  src/view/src/main/java/airqo/models/Site.java
  src/view/src/main/java/airqo/models/Tahmo.java
  src/view/src/main/java/airqo/models/Tenant.java
  src/view/src/main/java/airqo/predicate/DevicePredicate.java
  src/view/src/main/java/airqo/predicate/MeasurementPredicate.java
  src/view/src/main/java/airqo/predicate/SitePredicate.java
  src/view/src/main/java/airqo/repository/DeviceRepository.java
  src/view/src/main/java/airqo/repository/MeasurementRepository.java
  src/view/src/main/java/airqo/repository/SiteRepository.java
  src/view/src/main/java/airqo/serializers/DeviceSerializer.java
  src/view/src/main/java/airqo/serializers/MeasurementSerializer.java
  src/view/src/main/java/airqo/serializers/SiteSerializer.java
  src/view/src/main/java/airqo/services/DeviceService.java
  src/view/src/main/java/airqo/services/DeviceServiceImpl.java
  src/view/src/main/java/airqo/services/MeasurementService.java
  src/view/src/main/java/airqo/services/MeasurementServiceImpl.java
  src/view/src/main/java/airqo/services/SiteService.java
  src/view/src/main/java/airqo/services/SiteServiceImpl.java
  src/view/src/test/java/airqo/DeviceControllerTests.java
  src/view/src/test/java/airqo/MeasurementControllerTests.java
  src/view/src/test/java/airqo/SiteControllerTests.java
Labels: Ready for merge, ready for review

#1147 [Data pipeline] - adding checks for BAM devices without site ids
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
Labels: Ready for merge, ready for review

#1150 addressing recent create-event use case challenges
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-monitor.js
Labels: ready for review

#1152 resolving a runtime error due to changes in the warehouse schema
  src/device-registry/utils/create-event.js
Labels: ready for review

#1154 move to production
  src/device-registry/utils/create-event.js
Labels: ready for review

#1155 adding the NETWORK field to all device registry resources
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Location.js
  src/device-registry/models/Photo.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry
