Repository airqo-platform/AirQo-api, pull requests merged in 2022-06, with the labels that each got.

#864 Ft resource limits
  k8s/airflow/airflow-app.yaml
  k8s/airflow/stage-airflow-app.yaml
  k8s/analytics/prod-analytics-api.yaml
  k8s/analytics/stage-analytics-api.yaml
  k8s/auth-service/prod-auth-api.yaml
  k8s/auth-service/stage-auth-api.yaml
  k8s/calibrate/prod-calibrate-api.yaml
  k8s/calibrate/stage-calibrate-api.yaml
  k8s/channel-data/prod-airqo-update-channel-data-job.yaml
  k8s/channel-data/stage-airqo-update-channel-data-job.yaml
  k8s/data-mgt/prod-data-mgt-api.yaml
  k8s/data-mgt/stage-data-mgt-api.yaml
  k8s/data-mgt/values-dev.yaml
  k8s/data-warehouse/prod-data-warehouse-api.yaml
  k8s/data-warehouse/stage-data-warehouse-api.yaml
  k8s/device-monitor/prod-device-monitor-api.yaml
  k8s/device-monitor/stage-device-monitor-api.yaml
  k8s/device-registry/prod-device-registry-api.yaml
  k8s/device-registry/stage-device-registry-api.yaml
  k8s/device-status/prod-airqo-device-status-job.yaml
  k8s/device-status/stage-airqo-device-status-job.yaml
  k8s/device-uptime/prod-airqo-device-uptime-job.yaml
  k8s/device-uptime/stage-airqo-device-uptime-job.yaml
  k8s/exceedance/prod-airqo-exceedance-job.yaml
  k8s/exceedance/prod-kcca-exceedance-job.yaml
  k8s/exceedance/stage-airqo-exceedance-job.yaml
  k8s/exceedance/stage-kcca-exceedance-job.yaml
  k8s/gp-model/prod-airqo-gp-model-job.yaml
  k8s/gp-model/stage-airqo-gp-model-job.yaml
  k8s/grafana/agent/daemonSet.yaml
  k8s/grafana/agent/statefulSet.yaml
  k8s/jenkins/jenkins-deployment.yaml
  k8s/kafka-connect/templates/connect.yaml
  k8s/locate/prod-locate-api.yaml
  k8s/locate/stage-locate-api.yaml
  k8s/locate/templates/deployment.yaml
  k8s/network-uptime/prod-airqo-network-uptime-api.yaml
  k8s/network-uptime/stage-airqo-network-uptime-api.yaml
  k8s/notification-service/prod-notification-api.yaml
  k8s/notification-service/stage-notification-api.yaml
  k8s/predict/prod-airqo-predict-job.yaml
  k8s/predict/prod-airqo-train-job.yaml
  k8s/predict/prod-prediction-api.yaml
  k8s/predict/stage-airqo-predict-job.yaml
  k8s/predict/stage-airqo-train-job.yaml
  k8s/predict/stage-prediction-api.yaml
  k8s/predict/templates/deployment.yaml
  k8s/streams/prod-airqo-raw-measurements-stream.yaml
  k8s/streams/prod-airqo-tahmo-values-stream.yaml
  k8s/streams/prod-kcca-raw-measurements-stream.yaml
  k8s/streams/stage-airqo-raw-measurements-stream.yaml
  k8s/streams/stage-airqo-tahmo-values-stream.yaml
  k8s/streams/stage-kcca-raw-measurements-stream.yaml
  k8s/test-deploy/stage-temp-device-registry-api.yaml
  k8s/view-api/prod-view-api.yaml
  k8s/view-api/prod-view-message-broker.yaml
  k8s/view-api/stage-view-api.yaml
  k8s/view-api/stage-view-message-broker.yaml
  workflow-trigger
Labels: Ready for merge, ready for review, devops

#870 Endpoint for creating approximate GPS coordinates
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/date.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry

#875 Add airqalibrate subdomain
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
Labels: Ready for merge

#873 [Website - Contact Us] receive inquiries from users through email
  src/auth-service/config/constants.js
  src/auth-service/controllers/inquire.js
  src/auth-service/models/Inquiry.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/prisma/schema.prisma
  src/auth-service/routes/api-v1.js
  src/auth-service/services/mailer.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/inquire.js
  src/auth-service/utils/validations.js
Labels: ready for review, authentication-service

#878 Backend support for AQCSV data format
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/utils/dates.py
  src/analytics/api/utils/pollutants/pm_25.py
  src/analytics/api/views/dashboard.py
Labels: ready for review

#881 Hotfix email error
  src/auth-service/config/constants.js
  src/auth-service/services/mailer.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
Labels: ready for review, authentication-service

#885 more legit solution to the emailing service error
  src/auth-service/config/constants.js
  src/auth-service/controllers/inquire.js
  src/auth-service/routes/api-v1.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/inquire.js
  src/auth-service/utils/join.js
  src/auth-service/utils/request.js
Labels: ready for review, authentication-service

#886 move to production
  src/auth-service/config/constants.js
  src/auth-service/controllers/inquire.js
  src/auth-service/routes/api-v1.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/inquire.js
  src/auth-service/utils/join.js
  src/auth-service/utils/request.js
Labels: ready for review

#862 Message broker topics CI/CD
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/message-broker-topics/prod-kafka-topics.yaml
  k8s/message-broker-topics/stage-kafka-topics.yaml
Labels: Ready for merge, ready for review

#866 App notifications [Backend]
  src/airflow/README.md
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/airqo_etl_utils/app_notification_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/message_broker.py
  src/airflow/airqo_etl_utils/setup.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/app_notifications.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/meta_data.py
  src/airflow/dev-requirements.txt
  src/airflow/main.py
Labels: ready for review

#888 reduced input validation to 2 decimal places for GPS approximation
  src/device-registry/routes/api-v1.js
Labels: ready for review, device-registry

#879 adding category to the device filter query options
  src/device-registry/controllers/create-device.js
  src/device-registry/models/Device.js
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/generate-filter.js
Labels: enhancement, ready for review, device-registry

#876 PLAT-1161 Streaming BAM data
  k8s/message-broker-topics/prod-kafka-topics.yaml
  k8s/message-broker-topics/stage-kafka-topics.yaml
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/message_broker.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
  src/airflow/message-broker-setup.sh
Labels: ready for review

#891 Hot fix - airflow import error
  src/airflow/dags/airnow_bam_data.py
Labels: Ready for merge, ready for review

#889 Approximating site coordinates [BigQuery]
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/schema/sites.json
  src/data-mgt/python/devices-tranformation/Readme.md
  src/data-mgt/python/devices-tranformation/airqoApi.py
  src/data-mgt/python/devices-tranformation/main.py
  src/data-mgt/python/devices-tranformation/transformation.py
Labels: Ready for merge, ready for review

#890 Move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  k8s/calibrate/prod-calibrate-api.yaml
  k8s/calibrate/stage-calibrate-api.yaml
  k8s/fault-detection/prod-fault-detection-api.yaml
  k8s/fault-detection/stage-fault-detection-api.yaml
  k8s/message-broker-topics/prod-kafka-topics.yaml
  k8s/message-broker-topics/stage-kafka-topics.yaml
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  src/airflow/README.md
  src/airflow/airqo_etl_utils/airflow_custom_utils.py
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/app_notification_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/message_broker.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/schema/sites.json
  src/airflow/airqo_etl_utils/setup.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/app_notifications.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/meta_data.py
  src/airflow/dev-requirements.txt
  src/airflow/docker-compose.yaml
  src/airflow/main.py
  src/airflow/message-broker-setup.sh
  src/analytics/Dockerfile
  src/data-mgt/python/devices-tranformation/Readme.md
  src/data-mgt/python/devices-tranformation/airqoApi.py
  src/data-mgt/python/devices-tranformation/main.py
  src/data-mgt/python/devices-tranformation/transformation.py
  src/device-monitoring/Dockerfile
  src/device-registry/controllers/create-device.js
  src/device-registry/models/Device.js
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/generate-filter.js
  src/gp-model/Dockerfile
  src/locate/Dockerfile
  src/predict/api/Dockerfile
Labels: ready for review

#893 Hot fix Bam data datetime
  src/airflow/airqo_etl_utils/airnow_utils.py
Labels: Ready for merge, ready for review

#894 Data pipeline hot fixes
  src/airflow/airqo_etl_utils/bigquery_api.py
Labels: Ready for merge, ready for review

#871 fetching measurements from BQ
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-event.js
  src/device-registry/routes/api-v2.js
  src/device-registry/utils/create-event.js
  src/events-registry/.gitkeep
  src/events-registry/config/.gitkeep
  src/events-registry/controllers/.gitkeep
  src/events-registry/routes/.gitkeep
  src/events-registry/utils/.gitkeep
Labels: ready for review, device-registry, events
