Repository airqo-platform/AirQo-api, pull requests merged in 2022-05, with the labels that each got.

#814 Calibrate tool ingress configurations
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
Labels: Ready for merge, ready for review

#821 description and tags missing during maintenance logs creation
  src/device-registry/controllers/create-activity.js
Labels: ready for review

#818 Move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/airflow/airflow-app.yaml
  k8s/airflow/stage-airflow-app.yaml
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
  src/airflow/Dockerfile
  src/airflow/README.md
  src/airflow/airflow_xcom/__init__.py
  src/airflow/airflow_xcom/gcs_xcom_backend.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/commons.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/constants.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/airqo_etl_utils/message_broker.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/airqo_etl_utils/schema/data_warehouse.json
  src/airflow/airqo_etl_utils/schema/devices.json
  src/airflow/airqo_etl_utils/schema/measurements.json
  src/airflow/airqo_etl_utils/schema/sites.json
  src/airflow/airqo_etl_utils/schema/weather_data.json
  src/airflow/airqo_etl_utils/setup.py
  src/airflow/airqo_etl_utils/weather_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/app_insights.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/meta_data.py
  src/airflow/dags/weather_measurements.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
  src/airflow/run-airflow-only.sh
  src/airflow/xcom-setup.sh
  src/calibrate/cicd-build-trigger
  src/calibrate/controllers/calibrate.py
  src/calibrate/readme.md
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/utils/create-airqloud.js
Labels: ready for review

#817 Calibrating historical data
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/schema/calibrated_measurements.json
  src/airflow/dags/airqo_measurements.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
  src/airflow/run-airflow-only.sh
Labels: Ready for merge, ready for review

#697 App authentication functions
  .gitignore
  src/data-mgt/.gitignore
  src/firebase/auth/.firebaserc
  src/firebase/auth/.gitignore
  src/firebase/auth/firebase.json
  src/firebase/auth/functions/.eslintrc.js
  src/firebase/auth/functions/.gitignore
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
  src/firebase/auth/functions/package.json
  src/firebase/auth/package-lock.json
  src/firebase/auth/package.json
Labels: work in progress

#824 [Hotfix] Adding versioning to airflow docker file
  src/airflow/Dockerfile
Labels: Ready for merge, ready for review

#826 Subscribe to our Newsletter
  src/auth-service/app.js
  src/auth-service/config/constants.js
  src/auth-service/config/mailchimp.js
  src/auth-service/controllers/join.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/api-v1.js
  src/auth-service/utils/join.js
Labels: ready for review, authentication-service

#765 [nginx ingress] Update Locate Path
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
Labels: Ready for merge, devops

#828 just a hotfix on error handling for the newsletter subscription
  src/auth-service/utils/join.js
Labels: hotfix, ready for review, authentication-service

#829 move to production
  src/auth-service/utils/join.js
Labels: Ready for merge, ready for review

#836 hotfix: update ingress resource configuration
  k8s/nginx-ingress/stage-platform-ingress-resource.yaml
Labels: Ready for merge, ready for review, devops, k8s

#837 Fetching D3 chart data from BigQuery
  src/analytics/api/models/events.py
  src/analytics/api/views/dashboard.py
Labels: ready for review

#839 update production ingresses
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
Labels: Ready for merge, hotfix, ready for review, devops

#845 Fix - Dashboard exccedances chart job
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/exceedances/Dockerfile
  src/exceedances/Dockerfile.prod.airqo
  src/exceedances/Dockerfile.prod.kcca
  src/exceedances/Dockerfile.stage.airqo
  src/exceedances/Dockerfile.stage.kcca
  src/exceedances/models.py
Labels: Ready for merge, ready for review

#846 Fix typo - exceedances CI/CD
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/exceedances/Dockerfile
Labels: Ready for merge, ready for review

#849 forecast model: update dockerfile
  src/predict/jobs/train/Dockerfile
Labels: Ready for merge, ready for review, devops, forecast

#842 Update PR template
  .github/pull_request_template.md
Labels: enhancement, ready for review

#812 Grafana agent
  k8s/grafana/agent/daemonSet.yaml
  k8s/grafana/agent/statefulSet.yaml
  k8s/grafana/deploy-kube-state-metrics.sh
Labels: devops

#848 correct typos
  k8s/predict/stage-airqo-predict-job.yaml
  k8s/predict/stage-airqo-train-job.yaml
  k8s/predict/stage-prediction-api.yaml
Labels: Ready for merge, ready for review, devops

#847 Move to production
  .github/pull_request_template.md
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/grafana/agent/daemonSet.yaml
  k8s/grafana/agent/statefulSet.yaml
  k8s/grafana/deploy-kube-state-metrics.sh
  k8s/nginx-ingress/prod-api-ingress-resource.yaml
  k8s/nginx-ingress/prod-platform-ingress-resource.yaml
  k8s/predict/stage-airqo-predict-job.yaml
  k8s/predict/stage-airqo-train-job.yaml
  k8s/predict/stage-prediction-api.yaml
  src/analytics/api/models/events.py
  src/analytics/api/views/dashboard.py
  src/exceedances/Dockerfile
  src/exceedances/Dockerfile.prod.airqo
  src/exceedances/Dockerfile.prod.kcca
  src/exceedances/Dockerfile.stage.airqo
  src/exceedances/Dockerfile.stage.kcca
  src/exceedances/models.py
  src/network-uptime/Dockerfile
  src/network-uptime/requirements.txt
  src/predict/jobs/train/Dockerfile
Labels: ready for review

#838 Updating historical calibrated data
  src/airflow/airflow_xcom/gcs_xcom_backend.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/meta_data.py
  src/airflow/dags/weather_measurements.py
  src/airflow/main.py
Labels: Ready for merge

#850 Adding formatting to exported data
  src/analytics/api/models/events.py
Labels: ready for review

#859 Increasing request timeout for the Kafka producers
  src/airflow/airqo_etl_utils/message_broker.py
Labels: Ready for merge, ready for review

#861 Move to production
  src/airflow/airqo_etl_utils/message_broker.py
Labels: Ready for merge, ready for review

#860 Getting historical daily averages from bigquery
  src/analytics/api/models/events.py
  src/analytics/api/views/dashboard.py
Labels: ready for review

#865 Move to production
  src/analytics/api/models/events.py
  src/analytics/api/views/dashboard.py
Labels: Ready for merge, ready for review
