Repository airqo-platform/AirQo-api, pull requests merged in 2023-09, with the labels that each got.

#2152 fix readme
  README.md
Labels: ready for review

#2155 Update AirQo logos on the emails sent out
  src/auth-service/config/images/airqoLogo.png
  src/firebase/auth/functions/config/images/airqoLogo.png
Labels: ready for review

#2160 hotfixes for creating networks
  src/auth-service/config/constants.js
  src/auth-service/models/User.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#2157 Fixing errors when running Auth-Service tests
  src/auth-service/models/SearchHistory.js
  src/auth-service/utils/create-search-history.js
  src/auth-service/utils/test/ut_create-location-history.js
  src/auth-service/utils/test/ut_create-search-history.js
Labels: ready for review

#2158 Enable streaming historical consolidated Data
  src/airflow/airqo_etl_utils/date.py
  src/airflow/dags/data_warehouse.py
Labels: ready for review

#2161 fix name transformation during cration of roles
  src/auth-service/utils/control-access.js
Labels: ready for review

#2162 remove network_role on role or network deletion
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-network.js
  src/auth-service/utils/test/ut_control-access.js
  src/auth-service/utils/test/ut_create-network.js
Labels: ready for review

#2163 more hotfixes for access control
  src/auth-service/config/constants.js
  src/auth-service/models/User.js
  src/auth-service/models/test/ut_user.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#2165 fixing the user information projections
  src/auth-service/config/constants.js
  src/auth-service/models/User.js
Labels: ready for review

#2166 more hotfixes for networks and roles
  src/auth-service/config/constants.js
  src/auth-service/models/User.js
  src/auth-service/utils/create-user.js
Labels: ready for review

#2167 more hotfixes for access control
  src/auth-service/config/constants.js
  src/auth-service/middleware/check-scope.js
  src/auth-service/middleware/rate-limit.js
  src/auth-service/routes/v1/groups.js
Labels: ready for review

#2168 handling cases where networkz net_name is undefined
  src/auth-service/config/constants.js
  src/auth-service/middleware/test/ut_check-scope.js
  src/auth-service/models/test/ut_user.js
Labels: ready for review

#2170 small fixes for listing users
  src/auth-service/config/constants.js
  src/auth-service/models/User.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2171 putting back the addToSet
  src/auth-service/models/User.js
Labels: ready for review

#2172 removing commented out code and introducing script folder
  src/auth-service/config/constants.js
  src/auth-service/models/User.js
  src/auth-service/utils/scripts/bulk-script.js
  src/auth-service/utils/scripts/update-network-roles.js
Labels: ready for review

#2175 allow update of network roles for users without network_ids
  src/auth-service/models/User.js
Labels: ready for review

#2177 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/config/constants.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
  src/firebase/auth/functions/config/emailTemplates.js
Labels: ready for review

#2178 re-enable user update emails
  src/auth-service/utils/create-user.js
Labels: ready for review

#2179 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/utils/create-user.js
Labels: ready for review

#2180 Adding missing mongoose Import to models
  src/device-registry/models/Event.js
  src/device-registry/models/KnowYourAirAnswer.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirQuestion.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/KnowYourAirUserQuizProgress.js
  src/device-registry/models/Location.js
  src/device-registry/models/Measurement.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/UniqueIdentifierCounter.js
Labels: ready for review

#2159 Translations to French for health tips from the API
  src/device-registry/package.json
  src/device-registry/routes/v2/events.js
  src/device-registry/routes/v2/tips.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/test/ut_create-health-tips.js
  src/device-registry/utils/test/ut_translate.js
  src/device-registry/utils/translate.js
Labels: ready for review

#2182 Fix Translate on Staging
  src/device-registry/Dockerfile
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/translate.js
Labels: ready for review

#2184 Followup Pr for translate functionality
  src/device-registry/utils/create-event.js
Labels: ready for review

#2183 Fix Failing task in AirQo Bam DAG
  src/airflow/airqo_etl_utils/data_validator.py
Labels: ready for review

#2181 move to production
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/airflow/airqo_etl_utils/data_validator.py
  src/device-registry/Dockerfile
  src/device-registry/models/Event.js
  src/device-registry/models/KnowYourAirAnswer.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirQuestion.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/KnowYourAirUserQuizProgress.js
  src/device-registry/models/Location.js
  src/device-registry/models/Measurement.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/UniqueIdentifierCounter.js
  src/device-registry/package.json
  src/device-registry/routes/v2/events.js
  src/device-registry/routes/v2/tips.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/test/ut_create-health-tips.js
  src/device-registry/utils/test/ut_translate.js
  src/device-registry/utils/translate.js
Labels: ready for review

#2187 Update package.lock File
  src/device-registry/package-lock.json
Labels: ready for review

#2185 Fixing mongo insertion errors
  src/auth-service/utils/create-favorite.js
  src/auth-service/utils/create-location-history.js
  src/auth-service/utils/create-search-history.js
Labels: ready for review

#2188 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/utils/create-favorite.js
  src/auth-service/utils/create-location-history.js
  src/auth-service/utils/create-search-history.js
  src/device-registry/package-lock.json
Labels: ready for review

#2076 Forecast enchancements
  src/airflow/airflow-requirements.txt
  src/airflow/airqo_etl_utils/air_beam_api.py
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/ml_utils.py
  src/airflow/airqo_etl_utils/plume_labs_api.py
  src/airflow/airqo_etl_utils/purple_air_api.py
  src/airflow/airqo_etl_utils/tahmo_api.py
  src/airflow/airqo_etl_utils/tests/airqo_utils_tests.py
  src/airflow/airqo_etl_utils/tests/big_query_api_tests.py
  src/airflow/airqo_etl_utils/tests/conftest.py
  src/airflow/airqo_etl_utils/tests/ml_utils_tests.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/ml_prediction_jobs.py
  src/airflow/dags/ml_training_jobs.py
  src/airflow/dev-requirements.txt
  src/airflow/requirements.txt
  src/predict/api/helpers.py
  src/predict/api/prediction.py
Labels: data-engineering, ready for review, predict, forecast

#2190 Add Translation for KYA Lessons and Quizzes
  src/device-registry/routes/v2/kya.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/test/ut_create-know-your-air.js
  src/device-registry/utils/test/ut_translate.js
  src/device-registry/utils/translate.js
Labels: ready for review

#2192 Forecast job hotfix
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/ml_utils.py
  src/airflow/airqo_etl_utils/tests/conftest.py
  src/airflow/airqo_etl_utils/tests/ml_utils_tests.py
  src/airflow/dags/ml_prediction_jobs.py
Labels: data-engineering, ready for review, forecast

#2193 Fixing Run time errors for tests in Incentives and Data-Mgt microservices
  src/data-mgt/node/utils/log.js
  src/data-mgt/node/utils/test/ut_date.js
  src/data-mgt/node/utils/test/ut_errors.js
  src/data-mgt/node/utils/test/ut_log.js
  src/incentives/utils/test/ut_create-transaction.js
  src/incentives/utils/test/ut_generate-filter.js
Labels: ready for review

#2198 Remove `margin of error` from forecast endpoint results
  src/predict/api/helpers.py
Labels: ready for review, predict

#2173 request access to either a Group or a Network
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-candidate.js
  src/auth-service/controllers/create-group.js
  src/auth-service/controllers/create-inquiry.js
  src/auth-service/controllers/create-request.js
  src/auth-service/controllers/test/ut_create-candidate.js
  src/auth-service/controllers/test/ut_create-group.js
  src/auth-service/controllers/test/ut_create-inquiry.js
  src/auth-service/controllers/test/ut_create-request.js
  src/auth-service/controllers/test/ut_create-user.js
  src/auth-service/models/AccessRequest.js
  src/auth-service/models/Group.js
  src/auth-service/models/Network.js
  src/auth-service/models/User.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/v1/groups.js
  src/auth-service/routes/v1/requests.js
  src/auth-service/routes/v1/test/ut_groups.js
  src/auth-service/routes/v1/test/ut_requests.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/routes/v2/networks.js
  src/auth-service/routes/v2/requests.js
  src/auth-service/routes/v2/test/ut_groups.js
  src/auth-service/routes/v2/test/ut_requests.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-candidate.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/create-inquiry.js
  src/auth-service/utils/create-network.js
  src/auth-service/utils/create-request.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_create-candidate.js
  src/auth-service/utils/test/ut_create-group.js
  src/auth-service/utils/test/ut_create-network.js
  src/auth-service/utils/test/ut_create-request.js
Labels: enhancement, ready for review, auth-service

#2200 fixing available users for Networks
  src/auth-service/utils/create-network.js
Labels: ready for review

#2201 on user creation, add default network and role if not provided
  src/auth-service/models/User.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#2202 fixing list available and assigned users to network in deployed ENV
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-network.js
  src/auth-service/models/AccessRequest.js
  src/auth-service/models/AccessToken.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/Favorite.js
  src/auth-service/models/Group.js
  src/auth-service/models/LocationHistory.js
  src/auth-service/models/Network.js
  src/auth-service/models/Role.js
  src/auth-service/models/SearchHistory.js
  src/auth-service/models/User.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#2197 greeness scale,
  src/meta-data/api/models/extract.py
  src/meta-data/message-broker.py
Labels: ready for review, metadata-microservice

#2191 removing distance from Kampala from the metadata calculations
  src/meta-data/message-broker.py
Labels: ready for review, metadata-microservice

#2199 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/incentives/values-prod.yaml
  k8s/meta-data/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-candidate.js
  src/auth-service/controllers/create-group.js
  src/auth-service/controllers/create-inquiry.js
  src/auth-service/controllers/create-network.js
  src/auth-service/controllers/create-request.js
  src/auth-service/controllers/test/ut_create-candidate.js
  src/auth-service/controllers/test/ut_create-group.js
  src/auth-service/controllers/test/ut_create-inquiry.js
  src/auth-service/controllers/test/ut_create-request.js
  src/auth-service/controllers/test/ut_create-user.js
  src/auth-service/models/AccessRequest.js
  src/auth-service/models/AccessToken.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/Favorite.js
  src/auth-service/models/Group.js
  src/auth-service/models/LocationHistory.js
  src/auth-service/models/Network.js
  src/auth-service/models/Role.js
  src/auth-service/models/SearchHistory.js
  src/auth-service/models/User.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/v1/groups.js
  src/auth-service/routes/v1/requests.js
  src/auth-service/routes/v1/test/ut_groups.js
  src/auth-service/routes/v1/test/ut_requests.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/routes/v2/networks.js
  src/auth-service/routes/v2/requests.js
  src/auth-service/routes/v2/test/ut_groups.js
  src/auth-service/routes/v2/test/ut_requests.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-candidate.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/create-inquiry.js
  src/auth-service/utils/create-network.js
  src/auth-service/utils/create-request.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_create-candidate.js
  src/auth-service/utils/test/ut_create-group.js
  src/auth-service/utils/test/ut_create-network.js
  src/auth-service/utils/test/ut_create-request.js
  src/meta-data/api/models/extract.py
  src/meta-data/message-broker.py
  src/predict/api/helpers.py
Labels: ready for review

#2174 enhancing the device measurements endpoints
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/AdminLevel.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Grid.js
  src/device-registry/models/KnowYourAirAnswer.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirQuestion.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/KnowYourAirUserQuizProgress.js
  src/device-registry/models/Measurement.js
  src/device-registry/models/Network.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/test/ut_measurement.js
  src/device-registry/routes/v2/index.js
  src/device-registry/routes/v2/measurements.js
  src/device-registry/routes/v2/metadata.js
  src/device-registry/routes/v2/test/ut_measurements.js
  src/device-registry/routes/v2/test/ut_metadata.js
  src/device-registry/routes/v2/test/ut_transmit.js
  src/device-registry/routes/v2/transmit.js
  src/device-registry/utils/common.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-cohort.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-grid.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/test/ut_common.js
  src/device-registry/utils/test/ut_create-device.js
  src/device-registry/utils/test/ut_create-event.js
  src/device-registry/utils/test/ut_create-grid.js
Labels: ready for review

#2206 Outgoing Emails Enhancement: Logo size
  src/auth-service/config/constants.js
  src/firebase/auth/functions/config/emailTemplates.js
Labels: ready for review

#2207 Fixing Mongo Insertion errors for Location History and SearchHistory
  src/auth-service/utils/create-location-history.js
  src/auth-service/utils/create-search-history.js
Labels: ready for review

#2194 Rename "Distance to Kampala" to "Distance to Capital City"
  src/device-registry/config/constants.js
  src/device-registry/models/Site.js
  src/device-registry/routes/v1/sites.js
  src/device-registry/routes/v2/sites.js
Labels: ready for review

#2209 sorting the runtime errors relating to Redis
  src/device-registry/controllers/create-event.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2212 Authservice codecoverage
  .github/workflows/coverage.yaml
  src/auth-service/.gitignore
  src/auth-service/package-lock.json
  src/auth-service/package.json
Labels: ready for review

#2210 Enable Translation of health tips in Production
  src/device-registry/utils/create-event.js
Labels: ready for review

#2211 Fix MongoDB Error from cluster sharding setup - forecast job
  src/airflow/airqo_etl_utils/ml_utils.py
  src/predict/api/prediction.py
Labels: ready for review, predict, forecast

#2196 [META-DATA] JWT to token authentication
  src/meta-data/airqo_api.py
  src/meta-data/config.py
Labels: ready for review

#2195 Added coverage for data-mgt
  .github/workflows/data-mgt-test.yml
  .gitignore
  src/data-mgt/node/.gitignore
  src/data-mgt/node/package-lock.json
  src/data-mgt/node/package.json
Labels: ready for review

#2215 re-enable cache again
  src/device-registry/utils/create-event.js
Labels: ready for review

#2216 resolving runtimes for skip and limit query parameters
  src/device-registry/controllers/create-site.js
  src/device-registry/routes/v2/sites.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
Labels: ready for review
