Repository airqo-platform/AirQo-api, pull requests merged in 2023-08, with the labels that each got.

#1949 HotFix: KYA Creating UserProgress
  src/device-registry/utils/create-know-your-air.js
Labels: ready for review, mobile-app

#1950 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/utils/create-know-your-air.js
Labels: ready for review

#1955 [device-registry] hotfixes after recent refactoring
  src/device-registry/config/constants.js
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
  src/device-registry/routes/v1/index.js
  src/device-registry/routes/v2/index.js
Labels: ready for review, device-registry

#1956 removing the unique constraint on the networks field of Users
  src/auth-service/models/User.js
Labels: ready for review, auth-service

#1957 adding more details to the README
  src/data-mgt/node/README.md
Labels: ready for review, data-mgt

#1958 enhancing the input validations for admin_levels and networks
  src/device-registry/routes/v1/activities.js
  src/device-registry/routes/v1/airqlouds.js
  src/device-registry/routes/v1/devices.js
  src/device-registry/routes/v1/events.js
  src/device-registry/routes/v1/grids.js
  src/device-registry/routes/v1/kya.js
  src/device-registry/routes/v1/locations.js
  src/device-registry/routes/v1/photos.js
  src/device-registry/routes/v1/sensors.js
  src/device-registry/routes/v1/sites.js
  src/device-registry/routes/v1/tips.js
  src/device-registry/routes/v2/activities.js
  src/device-registry/routes/v2/airqlouds.js
  src/device-registry/routes/v2/devices.js
  src/device-registry/routes/v2/events.js
  src/device-registry/routes/v2/grids.js
  src/device-registry/routes/v2/kya.js
  src/device-registry/routes/v2/locations.js
  src/device-registry/routes/v2/measurements.js
  src/device-registry/routes/v2/photos.js
  src/device-registry/routes/v2/sensors.js
  src/device-registry/routes/v2/sites.js
  src/device-registry/routes/v2/tips.js
Labels: enhancement, ready for review, device-registry

#1959 more refactoring done in data-mgt and more unit test files
  src/data-mgt/node/.gitignore
  src/data-mgt/node/bin/www
  src/data-mgt/node/config/constants.js
  src/data-mgt/node/controllers/transform.js
  src/data-mgt/node/routes/v1/channels.js
  src/data-mgt/node/routes/v1/feeds.js
  src/data-mgt/node/routes/v1/hourly.js
  src/data-mgt/node/routes/v1/index.js
  src/data-mgt/node/routes/v1/test/ut_channels.js
  src/data-mgt/node/routes/v1/test/ut_hourly.js
  src/data-mgt/node/routes/v2/channels.js
  src/data-mgt/node/routes/v2/feeds.js
  src/data-mgt/node/routes/v2/hourly.js
  src/data-mgt/node/routes/v2/index.js
  src/data-mgt/node/routes/v2/test/ut_channels.js
  src/data-mgt/node/routes/v2/test/ut_hourly.js
Labels: work in progress, data-mgt

#1962 adding role_name and role_id to the list of assigned users
  src/auth-service/utils/create-network.js
Labels: ready for review, auth-service

#1963 discontinuing v1 of events
  src/device-registry/routes/v1/index.js
Labels: ready for review, device-registry

#1293 readME guide for GP Model
  src/gp-model/README.md
Labels: documentation, priority-low, ml-ops

#1961 Designs for Request access email
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_email.msgs.js
  src/auth-service/utils/test/ut_mailer.js
Labels: ready for review

#1966 [data-mgt/node] fix runtime error
  src/data-mgt/node/bin/server.js
Labels: hotfix, ready for review

#1968 making corrections to the server file
  src/data-mgt/node/bin/server.js
  src/data-mgt/node/package.json
Labels: ready for review

#1972 Using v2 in airflow utils
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/config.py
Labels: ready for review

#1973 Move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/config.py
Labels: ready for review

#1975 Fix decrypt bulk
  src/device-registry/routes/v2/devices.js
Labels: ready for review

#1976 move to production
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/routes/v2/devices.js
Labels: ready for review

#1943 Enable users to log into Mobile and Analytics using the same account details
  src/auth-service/config/constants.js
  src/auth-service/config/redis.js
  src/auth-service/config/test/ut_constants.js
  src/auth-service/config/test/ut_redis.js
  src/auth-service/controllers/create-user.js
  src/auth-service/controllers/test/ut_create-user.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/v1/test/ut_users.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/test/ut_users.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-favorite.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_create-user.js
  src/auth-service/utils/test/ut_mailer.js
Labels: enhancement, ready for review, auth-service

#1977 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/bin/server.js
  src/auth-service/config/constants.js
  src/auth-service/config/redis.js
  src/auth-service/config/test/ut_constants.js
  src/auth-service/config/test/ut_redis.js
  src/auth-service/controllers/create-user.js
  src/auth-service/controllers/test/ut_create-user.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/v1/test/ut_users.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/test/ut_users.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-favorite.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_create-user.js
  src/auth-service/utils/test/ut_mailer.js
Labels: ready for review

#1983 Disable v1 in analytics
  src/analytics/api/middlewares/base_validator.py
  src/analytics/api/models/__init__.py
  src/analytics/api/models/base/model_operations.py
  src/analytics/api/models/exceedance.py
  src/analytics/api/models/site.py
  src/analytics/api/utils/case_converters.py
  src/analytics/api/utils/dates.py
  src/analytics/api/utils/http.py
  src/analytics/api/utils/messages.py
  src/analytics/api/utils/pollutants/__init__.py
  src/analytics/api/utils/pollutants/charts.py
  src/analytics/api/utils/pollutants/date.py
  src/analytics/api/utils/pollutants/pm_25.py
  src/analytics/api/utils/pollutants/units.py
  src/analytics/api/utils/pre_request.py
  src/analytics/api/utils/request_validators.py
  src/analytics/api/views/dashboard.py
  src/analytics/api/views/data.py
  src/analytics/api/views/report.py
  src/analytics/config.py
  src/analytics/jobs/reports/main.py
  src/analytics/jobs/reports/utils.py
  src/analytics/main.py
Labels: ready for review

#1987 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/config/constants.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/Client.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#1939 Implement fault detection - V0
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/fault-detection/.helmignore
  k8s/fault-detection/Chart.yaml
  k8s/fault-detection/charts/.gitkeep
  k8s/fault-detection/templates/NOTES.txt
  k8s/fault-detection/templates/_helpers.tpl
  k8s/fault-detection/templates/deployment.yaml
  k8s/fault-detection/templates/hpa.yaml
  k8s/fault-detection/templates/service.yaml
  k8s/fault-detection/templates/tests/test-connection.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/fault-detection/values-stage.yaml
  src/airflow/.dockerignore
  src/airflow/.gitignore
  src/airflow/Dockerfile
  src/airflow/airflow-requirements.txt
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/tests/airqo_utils_tests.py
  src/airflow/airqo_etl_utils/tests/bigquery_api_tests.py
  src/airflow/airqo_etl_utils/tests/conftest.py
  src/airflow/dags/fault_detection_job.py
  src/airflow/dev-requirements.txt
  src/airflow/requirements.txt
  src/predict/api/Dockerfile
  src/predict/api/Jenkinsfile
  src/predict/api/README.md
  src/predict/api/app.py
  src/predict/api/bin/start.sh
  src/predict/api/config.py
  src/predict/api/controllers/__init__.py
  src/predict/api/helpers.py
  src/predict/api/helpers/__init__.py
  src/predict/api/prediction.py
  src/predict/api/requirements.txt
  src/predict/api/routes.py
  src/predict/api/routes/api.py
  src/predict/api/tests.py
  src/predict/jobs/forecast/Dockerfile
Labels: data-engineering, ready for review, predict, fault-detection

#1989 adding more logging options for accessing data downloads
  src/auth-service/middleware/passport.js
  src/auth-service/utils/control-access.js
Labels: ready for review, auth-service

#1992 Setup Airflow Database upgrade
  src/airflow/Dockerfile
Labels: data-engineering, ready for review

#1974 Computing data completeness using hourly data.
  src/device-monitoring/README.md
  src/device-monitoring/app.py
  src/device-monitoring/controllers/check_status.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/models/__init__.py
  src/device-monitoring/models/base.py
  src/device-monitoring/models/collocation.py
  src/device-monitoring/models/uptime.py
  src/device-monitoring/requirements.txt
  src/device-monitoring/tests/__init__.py
  src/device-monitoring/tests/test_collocation_utils.py
Labels: ready for review

#1993 Airflow hotfix
  src/airflow/Dockerfile
  src/airflow/dags/data_summary.py
Labels: data-engineering, ready for review

#1994 resolving the Kafka topic bug
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review

#1995 add more logs for JWT and use new object param for logic
  src/auth-service/middleware/passport.js
Labels: ready for review

#1996 Adding the request method as a custom header to the proxy
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#1999 fixing auth-access
  src/auth-service/middleware/passport.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#1997 Analytics hotfix - restore import statement
  src/analytics/.gitignore
  src/analytics/main.py
Labels: hotfix, ready for review

#2000 Add docker build targets for data mgt
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/data-mgt/node/README.md
Labels: ready for review

#2001 fixing a runtime in auth-service
  src/auth-service/middleware/passport.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2002 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-mgt/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/middleware/passport.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2003 fixing a runtime seen in Slack
  src/auth-service/utils/control-access.js
Labels: ready for review, auth-service

#2004 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review, auth-service

#1964 Designs for Inquiry emails
  src/auth-service/config/constants.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_email.msgs.js
  src/auth-service/utils/test/ut_mailer.js
Labels: ready for review

#1951 Fixes for the failing Unit tests - Create site.
  src/device-registry/utils/create-site.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/test/ut_create-site.js
Labels: ready for review

#2008 restoring staging logging
  src/auth-service/utils/log.js
Labels: ready for review, auth-service

#2006 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/config/constants.js
  src/auth-service/middleware/passport.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_email.msgs.js
  src/auth-service/utils/test/ut_mailer.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/test/ut_create-site.js
Labels: ready for review

#2010 Add token to airflow
  src/airflow/airqo_etl_utils/airqo_api.py
Labels: ready for review

#2015 temporarily disable access token creation
  src/auth-service/utils/control-access.js
Labels: ready for review

#2016 move to production
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#2014 Remove param validation for faulty devices endpoint
  src/predict/api/helpers.py
  src/predict/api/prediction.py
  src/predict/api/tests.py
Labels: ready for review, predict

#2017 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  src/gp-model/main.py
  src/predict/api/helpers.py
  src/predict/api/prediction.py
  src/predict/api/requirements.txt
  src/predict/api/tests.py
Labels: ready for review

#2024 logging logs QA
  src/auth-service/middleware/passport.js
  src/auth-service/middleware/test/ut_passport.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/test/ut_control-access.js
Labels: ready for review

#2025 Fix kafka-staging.
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review

#2009 add more details for Cohorts and Grids summary
  src/device-registry/routes/v2/devices.js
  src/device-registry/routes/v2/test/ut_devices.js
  src/device-registry/utils/common.js
  src/device-registry/utils/test/ut_common.js
Labels: ready for review

#2026 hotfix for quuerying cohorts and grids
  src/device-registry/utils/common.js
Labels: ready for review

#2027 fixing runtime and adding unit tests for passport middleware
  src/auth-service/middleware/passport.js
  src/auth-service/middleware/test/ut_passport.js
Labels: ready for review

#2029 just passing the entire req object
  src/auth-service/controllers/create-token.js
Labels: ready for review

#2028 HOTFIX - disable flask caching for faulty devices endpoint
  src/predict/api/app.py
  src/predict/api/prediction.py
Labels: hotfix, ready for review, predict

#2031 adding new action for viewing data
  src/auth-service/utils/control-access.js
Labels: ready for review

#2035 adding more exclusion items + refactoring the unit tests
  src/device-registry/config/constants.js
  src/device-registry/utils/common.js
  src/device-registry/utils/test/ut_common.js
  src/device-registry/utils/test/ut_create-event.js
Labels: ready for review

#2020 Designs for Welcome emails
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_email.msgs.js
  src/auth-service/utils/test/ut_mailer.js
Labels: ready for review

#2019 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  src/auth-service/bin/kafka-consumer.js
  src/auth-service/controllers/create-token.js
  src/auth-service/controllers/create-user.js
  src/auth-service/middleware/passport.js
  src/auth-service/middleware/test/ut_passport.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_control-access.js
  src/auth-service/utils/test/ut_email.msgs.js
  src/auth-service/utils/test/ut_mailer.js
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/config/constants.js
  src/device-registry/routes/v2/devices.js
  src/device-registry/routes/v2/test/ut_devices.js
  src/device-registry/utils/common.js
  src/device-registry/utils/test/ut_common.js
  src/device-registry/utils/test/ut_create-event.js
  src/predict/api/app.py
  src/predict/api/prediction.py
Labels: ready for review

#2038 small modifications to the projections of cohorts and grids
  src/device-registry/config/constants.js
  src/device-registry/utils/common.js
  src/device-registry/utils/test/ut_common.js
Labels: ready for review

#2040 small changes to send anauthorized access for deprecated events endpoint
  src/auth-service/utils/control-access.js
Labels: ready for review

#2039 move to production [work in progress]
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/utils/control-access.js
  src/device-registry/config/constants.js
  src/device-registry/utils/common.js
  src/device-registry/utils/test/ut_common.js
Labels: ready for review

#2041 small modifications to block requests to v1 of events
  src/auth-service/utils/control-access.js
  src/auth-service/utils/test/ut_control-access.js
Labels: ready for review

#2037 Added stop and start kubelet to ansible script
  infra/ansible/roles/k8s/templates/disk_cleanup.sh.j2
Labels: ready for review

#2047 awaiting the Kafka consumer
  src/device-registry/bin/index.js
Labels: ready for review

#2048 small enhancements to the start scripts
  src/device-registry/bin/index.js
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/bin/server.js
Labels: ready for review

#2051 add new Kafka topics
  k8s/kafka/topics/kafka-topics.yaml
  src/auth-service/bin/server.js
  src/data-mgt/node/bin/server.js
  src/device-registry/bin/server.js
Labels: ready for review

#2046 move to production
  infra/ansible/roles/k8s/templates/disk_cleanup.sh.j2
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-mgt/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/kafka/topics/kafka-topics.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/bin/server.js
  src/data-mgt/node/bin/server.js
  src/device-registry/bin/index.js
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/bin/server.js
Labels: ready for review

#2053 Changed node afinity from required to preferred
  k8s/device-status/templates/cronjob.yaml
  k8s/device-uptime/templates/cronjob-v2.yaml
  k8s/device-uptime/templates/cronjob.yaml
Labels: ready for review

#2055 Replacing v1 with v2 for device monitoring.
  src/device-monitoring/routes.py
Labels: ready for review

#2050 Enhance Device Deployment Process with Device HOST Details
  src/device-registry/config/constants.js
  src/device-registry/models/Device.js
  src/device-registry/models/Host.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/test/ut_host.js
  src/device-registry/routes/v2/activities.js
  src/device-registry/utils/create-activity.js
Labels: ready for review, device-registry

#2054 Move to Production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/templates/cronjob.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/templates/cronjob-v2.yaml
  k8s/device-uptime/templates/cronjob.yaml
  k8s/device-uptime/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-monitoring/routes.py
  src/device-registry/config/constants.js
  src/device-registry/models/Device.js
  src/device-registry/models/Host.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/test/ut_host.js
  src/device-registry/routes/v2/activities.js
  src/device-registry/utils/create-activity.js
Labels: ready for review

#2061 fixing the airqlouds admin_level validation
  src/device-registry/routes/v2/airqlouds.js
Labels: ready for review

#2063 fixing the admin_levels issue
  src/device-registry/routes/v2/airqlouds.js
Labels: ready for review

#2062 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-monitoring/controllers/check_status.py
  src/device-monitoring/models/uptime.py
  src/device-registry/routes/v2/airqlouds.js
Labels: ready for review

#2064 Adding more validations to collocation inputs
  src/device-monitoring/config/constants.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/models/collocation.py
  src/device-monitoring/tests/test_collocation_utils.py
Labels: ready for review

#1944 Implement Forecasting job (training & prediction) in airflow
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/predict/templates/predict-job.yaml
  k8s/predict/templates/train-job.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  src/airflow/.gitignore
  src/airflow/Dockerfile
  src/airflow/airflow-requirements.txt
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/ml_utils.py
  src/airflow/airqo_etl_utils/tests/big_query_api_tests.py
  src/airflow/airqo_etl_utils/tests/conftest.py
  src/airflow/airqo_etl_utils/tests/ml_utils_tests.py
  src/airflow/dags/forecast_measurements.py
  src/airflow/dags/ml_prediction_jobs.py
  src/airflow/dags/ml_training_jobs.py
  src/airflow/dev-requirements.txt
  src/airflow/requirements.txt
  src/predict/api/dump.rdb
  src/predict/api/helpers.py
  src/predict/api/requirements.txt
  src/predict/jobs/forecast/daily_forecasts.py
  src/predict/jobs/forecast_training/daily_forecast_training.py
  src/predict/jobs/forecast_training/hourly_forecast_training.py
  src/predict/jobs/forecast_training/requirements.txt
Labels: data-engineering, ready for review, forecast

#2065 Faulty devices hotfix
  src/predict/api/prediction.py
Labels: ready for review, predict

#2060 Putting retries on api requests in Airflow
  src/airflow/airqo_etl_utils/air_beam_api.py
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/plume_labs_api.py
  src/airflow/airqo_etl_utils/purple_air_api.py
  src/airflow/airqo_etl_utils/tahmo_api.py
  src/airflow/airqo_etl_utils/utils.py
Labels: ready for review

#2049 Adds Client ID rate limits when accessing AirQo API
  src/auth-service/bin/index.js
  src/auth-service/bin/kafka-consumer.js
  src/auth-service/bin/server.js
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-client.js
  src/auth-service/controllers/create-token.js
  src/auth-service/middleware/rate-limit.js
  src/auth-service/middleware/test/ut_rate-limit.js
  src/auth-service/models/AccessToken.js
  src/auth-service/models/Client.js
  src/auth-service/models/User.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/v1/clients.js
  src/auth-service/routes/v1/tokens.js
  src/auth-service/routes/v2/clients.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/test/ut_mailer.js
  src/device-registry/config/constants.js
Labels: ready for review, auth-service

#2068 fix an issue with update token information
  src/auth-service/utils/control-access.js
Labels: ready for review

#2069 more unit tests and general cleanup of access control utils
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/test/ut_control-access.js
  src/auth-service/utils/test/ut_create-user.js
Labels: ready for review

#2070 fixing the list permissions issue in v2
  src/auth-service/routes/v1/test/ut_permissions.js
  src/auth-service/routes/v2/permissions.js
  src/auth-service/routes/v2/test/ut_permissions.js
  src/auth-service/utils/test/ut_create-user.js
Labels: ready for review

#2074 removing client_id as a unique requirement
  src/auth-service/models/Client.js
Labels: ready for review

#2073 small enhancements to the bulk script
  src/auth-service/utils/bulk-script.js
Labels: enhancement, ready for review, auth-service

#2075 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/models/Client.js
  src/auth-service/utils/bulk-script.js
Labels: ready for review

#2077 Adding Stack trace temporarily to the server file
  src/auth-service/bin/server.js
Labels: ready for review

#2078 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/bin/server.js
Labels: ready for review

#2043 KYA Quiz endpoints
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/models/KnowYourAirAnswer.js
  src/device-registry/models/KnowYourAirQuestion.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/KnowYourAirUserQuizProgress.js
  src/device-registry/models/test/ut_know-your-air-answer.js
  src/device-registry/models/test/ut_know-your-air-question.js
  src/device-registry/models/test/ut_know-your-air-quiz-progress.js
  src/device-registry/routes/v1/kya.js
  src/device-registry/routes/v2/kya.js
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/test/ut_create-know-your-air.js
Labels: ready for review

#2082 adding email and userName to the new logic for access token logs
  src/auth-service/config/constants.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/test/ut_control-access.js
Labels: ready for review

#2081 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/config/constants.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/test/ut_control-access.js
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/models/KnowYourAirAnswer.js
  src/device-registry/models/KnowYourAirQuestion.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/KnowYourAirUserQuizProgress.js
  src/device-registry/models/test/ut_know-your-air-answer.js
  src/device-registry/models/test/ut_know-your-air-question.js
  src/device-registry/models/test/ut_know-your-air-quiz-progress.js
  src/device-registry/routes/v1/kya.js
  src/device-registry/routes/v2/kya.js
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/test/ut_create-know-your-air.js
Labels: ready for review

#2083 Changing number of kafka partitions on the topics
  k8s/kafka/topics/kafka-topics.yaml
Labels: ready for review

#2085 temporarily disable token refresh
  src/auth-service/models/AccessToken.js
  src/auth-service/models/Client.js
  src/auth-service/routes/v1/clients.js
  src/auth-service/routes/v1/tokens.js
  src/auth-service/routes/v2/clients.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2084 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/kafka/topics/kafka-topics.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/models/AccessToken.js
  src/auth-service/models/Client.js
  src/auth-service/routes/v1/clients.js
  src/auth-service/routes/v1/tokens.js
  src/auth-service/routes/v2/clients.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2086 re-enable rate limiting
  src/auth-service/routes/v1/tokens.js
  src/auth-service/routes/v2/tokens.js
Labels: ready for review

#2089 adding more logs for kafka-consumer
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review

#2091 small changes to the KAFKA error logs
  src/device-registry/bin/index.js
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review, device-registry

#2092 hotfix - collocation data completeness
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/models/collocation.py
  src/device-monitoring/tests/test_collocation_utils.py
Labels: ready for review

#2087 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/routes/v1/tokens.js
  src/auth-service/routes/v2/tokens.js
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/models/collocation.py
  src/device-monitoring/tests/test_collocation_utils.py
  src/device-registry/bin/index.js
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review

#2072 Adding data provider to Sites Meta data
  src/device-registry/config/constants.js
  src/device-registry/models/Site.js
  src/device-registry/routes/v2/sites.js
  src/device-registry/utils/create-site.js
Labels: ready for review

#2094 undo the rate limiting
  src/auth-service/routes/v2/tokens.js
Labels: ready for review

#2093 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/routes/v2/tokens.js
  src/device-registry/config/constants.js
  src/device-registry/models/Site.js
  src/device-registry/routes/v2/sites.js
  src/device-registry/utils/create-site.js
Labels: ready for review

#2095 new endpoint for accessing Host transactions
  src/incentives/controllers/create-transaction.js
  src/incentives/routes/v1/transactions.js
  src/incentives/routes/v2/transactions.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/generate-filter.js
Labels: ready for review

#2097 resolve runtime error
  src/incentives/controllers/test/ut_create-transaction.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/test/ut_create-transaction.js
  src/incentives/utils/test/ut_generate-filter.js
Labels: ready for review

#2057 Storing historical parish data
  src/predict/api/app.py
  src/predict/api/helpers.py
  src/predict/api/prediction.py
  src/predict/jobs/predict_places_air_quality/configure.py
  src/predict/jobs/predict_places_air_quality/main.py
  src/predict/jobs/predict_places_air_quality/utils.py
Labels: ready for review

#2098 KYA - Adds sorting to returned tasks and questions
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirQuiz.js
Labels: ready for review

#2096 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/incentives/values-stage.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_email.msgs.js
  src/auth-service/utils/test/ut_email.templates.js
  src/auth-service/utils/test/ut_mailer.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/incentives/controllers/create-transaction.js
  src/incentives/controllers/test/ut_create-transaction.js
  src/incentives/routes/v1/transactions.js
  src/incentives/routes/v2/transactions.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/generate-filter.js
  src/incentives/utils/test/ut_create-transaction.js
  src/incentives/utils/test/ut_generate-filter.js
  src/predict/api/app.py
  src/predict/api/helpers.py
  src/predict/api/prediction.py
  src/predict/jobs/predict_places_air_quality/configure.py
  src/predict/jobs/predict_places_air_quality/main.py
  src/predict/jobs/predict_places_air_quality/utils.py
Labels: ready for review

#2099 Hot Fix Kya
  src/device-registry/models/KnowYourAirLesson.js
Labels: ready for review

#2100 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/incentives/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/models/KnowYourAirLesson.js
Labels: ready for review

#2101 Fix KYA: Adding missing fields
  src/device-registry/models/KnowYourAirLesson.js
Labels: ready for review

#2104 refactoring the models to export models instead of schemas
  src/auth-service/bin/index.js
  src/auth-service/bin/kafka-consumer.js
  src/auth-service/controllers/create-user.js
  src/auth-service/middleware/passport.js
  src/auth-service/middleware/rate-limit.js
  src/auth-service/models/AccessToken.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/Client.js
  src/auth-service/models/Defaults.js
  src/auth-service/models/Department.js
  src/auth-service/models/Favorite.js
  src/auth-service/models/Group.js
  src/auth-service/models/Inquiry.js
  src/auth-service/models/LocationHistory.js
  src/auth-service/models/Network.js
  src/auth-service/models/Permission.js
  src/auth-service/models/Role.js
  src/auth-service/models/Scope.js
  src/auth-service/models/User.js
  src/auth-service/models/log.js
  src/auth-service/models/searchHistory.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-default.js
  src/auth-service/utils/create-favorite.js
  src/auth-service/utils/create-inquiry.js
  src/auth-service/utils/create-location-history.js
  src/auth-service/utils/create-network.js
  src/auth-service/utils/create-search-history.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/log-winston.js
  src/auth-service/utils/request-access.js
Labels: ready for review

#2107 add site details and device deployment status to cohort information
  src/device-registry/bin/test/unit-test-structure.js
  src/device-registry/config/constants.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/test/ut_cohort.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/test/ut_create-health-tips.js
  src/device-registry/utils/test/ut_create-know-your-air.js
Labels: ready for review

#2110 adding more missing Cohort information
  src/device-registry/models/Cohort.js
Labels: ready for review

#2118 correct the logger querying
  src/auth-service/utils/create-user.js
Labels: ready for review

#2117 Minor Fixes for the quiz(New version)
  src/device-registry/config/constants.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/test/ut_cohort.js
  src/device-registry/models/test/ut_device.js
  src/device-registry/models/test/ut_know-your-air-quiz.js
  src/device-registry/routes/v2/kya.js
Labels: ready for review

#2108 Airflow tests hotfix
  src/airflow/airqo_etl_utils/tests/__init__.py
  src/airflow/airqo_etl_utils/tests/airqo_utils_tests.py
  src/airflow/airqo_etl_utils/tests/big_query_api_tests.py
  src/airflow/airqo_etl_utils/tests/bigquery_api_tests.py
  src/airflow/airqo_etl_utils/tests/conftest.py
  src/airflow/airqo_etl_utils/tests/ml_utils_tests.py
Labels: data-engineering, ready for review

#2123 Update codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
Labels: ready for review, devops

#2126 just enhancing the client detail information
  src/auth-service/config/constants.js
  src/auth-service/models/Client.js
  src/auth-service/models/User.js
Labels: ready for review

#2130 fix the host creation issue via v2
  src/incentives/routes/v2/hosts.js
Labels: ready for review

#2131 Hotfix forecasts endpoint
  src/predict/api/.gitignore
  src/predict/api/dump.rdb
  src/predict/api/helpers.py
  src/predict/api/prediction.py
  src/predict/api/requirements.txt
  src/predict/api/tests/__init__.py
  src/predict/api/tests/conftest.py
  src/predict/api/tests/tests.py
Labels: ready for review, predict, forecast

#2132 add more filter options for querying candidates
  src/auth-service/routes/v1/requests.js
  src/auth-service/routes/v2/requests.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/request-access.js
Labels: ready for review

#2134 get devices summary and return updated cohort details
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-device.js
  src/device-registry/routes/v1/devices.js
  src/device-registry/routes/v2/devices.js
  src/device-registry/utils/create-cohort.js
  src/device-registry/utils/create-device.js
Labels: ready for review

#2128 enhance create-events and also hotfix create-cohort
  src/device-registry/controllers/create-event.js
  src/device-registry/models/AdminLevel.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Grid.js
  src/device-registry/models/HealthTips.js
  src/device-registry/models/Host.js
  src/device-registry/models/KnowYourAirAnswer.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirQuestion.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/KnowYourAirUserQuizProgress.js
  src/device-registry/models/Location.js
  src/device-registry/models/Measurement.js
  src/device-registry/models/Network.js
  src/device-registry/models/Photo.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/UniqueIdentifierCounter.js
  src/device-registry/routes/v1/activities.js
  src/device-registry/routes/v1/airqlouds.js
  src/device-registry/routes/v1/cohorts.js
  src/device-registry/routes/v1/devices.js
  src/device-registry/routes/v1/events.js
  src/device-registry/routes/v1/kya.js
  src/device-registry/routes/v1/locations.js
  src/device-registry/routes/v1/photos.js
  src/device-registry/routes/v1/sensors.js
  src/device-registry/routes/v1/sites.js
  src/device-registry/routes/v1/tips.js
  src/device-registry/routes/v2/activities.js
  src/device-registry/routes/v2/airqlouds.js
  src/device-registry/routes/v2/cohorts.js
  src/device-registry/routes/v2/devices.js
  src/device-registry/routes/v2/events.js
  src/device-registry/routes/v2/grids.js
  src/device-registry/routes/v2/kya.js
  src/device-registry/routes/v2/locations.js
  src/device-registry/routes/v2/measurements.js
  src/device-registry/routes/v2/photos.js
  src/device-registry/routes/v2/sensors.js
  src/device-registry/routes/v2/sites.js
  src/device-registry/routes/v2/tips.js
  src/device-registry/utils/common.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-cohort.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-grid.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/errors.js
Labels: ready for review

#2138 fix a runtime on KYA
  src/device-registry/models/Host.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/Measurement.js
Labels: ready for review

#2140 correct the unit tests for create-site use case
  src/device-registry/utils/create-site.js
  src/device-registry/utils/test/ut_create-site.js
Labels: ready for review

#2142 also include measurements to endpoints which should not use JWTs
  src/auth-service/middleware/passport.js
Labels: ready for review

#2141 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/middleware/passport.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/test/ut_create-site.js
Labels: ready for review

#2144 have different default expiry dates for tokens dependent on use-case
  src/auth-service/models/AccessToken.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2145 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/models/AccessToken.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2146 remove spammy Slack error logs for Kafka in device-registry
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review

#2147 move to production
  README.md
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/models/Grid.js
  src/device-registry/utils/common.js
Labels: ready for review
