Repository airqo-platform/AirQo-api, pull requests merged in 2023-07, with the labels that each got.

#1781 send user update emails in production environment ONLY
  src/auth-service/models/User.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
Labels: ready for review, auth-service

#1784 Using airqo tenant when updating site meta data
  src/airflow/airqo_etl_utils/airqo_api.py
Labels: ready for review

#1785 Move to production
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/airflow/airqo_etl_utils/airqo_api.py
Labels: ready for review

#1786 enhancements to User Update Emails
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review, auth-service

#1787 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review, auth-service

#1788 making the KAFKA input validation messages better
  src/device-registry/bin/www
Labels: ready for review

#1795 make kafka logs better
  src/device-registry/bin/www
Labels: ready for review

#1794 Meta data validation checks
  src/airflow/airqo_etl_utils/airqo_api.py
  src/meta-data/api/helpers/validation.py
  src/meta-data/message-broker.py
Labels: ready for review

#1796 Adding failure reasons to collocation results
  src/device-monitoring/helpers/collocation_utils.py
Labels: ready for review

#1776 Exporting collocation data
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
Labels: ready for review

#1790 Setup CI/CD for PR Predicting and storing air quality of parishes.
  .github/workflows/deploy-apis-to-staging.yml
  k8s/predict/predict-places-air-quality/.helmignore
  k8s/predict/predict-places-air-quality/Chart.yaml
  k8s/predict/predict-places-air-quality/charts/.gitkeep
  k8s/predict/predict-places-air-quality/templates/_helpers.tpl
  k8s/predict/predict-places-air-quality/values-prod.yaml
  k8s/predict/predict-places-air-quality/values-stage.yaml
  k8s/predict/templates/places-airquality.yaml
  k8s/predict/values-stage.yaml
Labels: ready for review

#1797 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/kafka/BigQuery-connectors/.helmignore
  k8s/kafka/BigQuery-connectors/Chart.yaml
  k8s/kafka/BigQuery-connectors/templates/NOTES.txt
  k8s/kafka/BigQuery-connectors/templates/_helpers.tpl
  k8s/kafka/BigQuery-connectors/templates/deployment.yaml
  k8s/kafka/BigQuery-connectors/templates/hpa.yaml
  k8s/kafka/BigQuery-connectors/templates/tests/test-connection.yaml
  k8s/kafka/BigQuery-connectors/values-prod.yaml
  k8s/kafka/BigQuery-connectors/values-stage.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
Labels: ready for review

#1806 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
Labels: ready for review

#1808 Adding device summary
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/models.py
Labels: ready for review

#1802 Adding more metadata fields, data source and Api key, to networks
  src/auth-service/config/constants.js
  src/auth-service/models/Network.js
  src/auth-service/routes/v1/networks.js
  src/auth-service/routes/v2/networks.js
Labels: ready for review

#1800 Adjusting Reauthentication endpoint to cater for mobile In-app Account deletion
  src/auth-service/controllers/create-user.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#1798 Replacing nan with null while returning device voltage.
  src/device-monitoring/models.py
Labels: ready for review

#1811 KAFKA errors: only timestamp and device-number as the only logged
  src/device-registry/bin/www
Labels: ready for review

#1809 Move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-user.js
  src/auth-service/models/Network.js
  src/auth-service/routes/v1/networks.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/networks.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/models.py
  src/device-registry/bin/www
Labels: ready for review

#1804 Adding networks api to airflow.
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
Labels: ready for review

#1812 move to production
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
Labels: ready for review

#1810 Adding added by details to collocation data
  src/device-monitoring/config/constants.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/utils.py
  src/device-monitoring/models.py
Labels: ready for review

#1803 Removed test-connectio.yaml,NOTES.tx and changed name and label to lo…
  k8s/kafka/BigQuery-connectors/Chart.yaml
  k8s/kafka/BigQuery-connectors/templates/NOTES.txt
  k8s/kafka/BigQuery-connectors/templates/_helpers.tpl
  k8s/kafka/BigQuery-connectors/templates/deployment.yaml
  k8s/kafka/BigQuery-connectors/templates/hpa.yaml
  k8s/kafka/BigQuery-connectors/templates/tests/test-connection.yaml
  k8s/kafka/BigQuery-connectors/values-prod.yaml
  k8s/kafka/BigQuery-connectors/values-stage.yaml
Labels: ready for review

#1801 Update Schedule for the consolidated-data DAG to daily
  src/airflow/dags/data_warehouse.py
Labels: ready for review

#1774 Add forecast API public documentation for docs website
  src/predict/README.md
  src/predict/api/README.md
Labels: documentation, ready for review, predict

#1782 Add cilium cni
  istio/pipeline-gateway.yaml
  istio/prod-pipeline-vs.yaml
  istio/stage-pipeline-vs.yaml
  k8s/cilium/config.yaml
Labels: ready for review, devops

#1814 Edit file path from src/kafka/connectors to src/kafka-connectors
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
Labels: ready for review

#1815 upgrade redis resources
  k8s/redis/templates/deployment.yaml
Labels: ready for review

#1817 Updating python version --airflow
  src/airflow/Dockerfile
Labels: ready for review

#1818 AIRFLOW:Update-Fix for Get tenants
  src/airflow/airqo_etl_utils/airqo_api.py
Labels: ready for review

#1670 Enhance AirQloud Creation to Support Multiple Criteria for Grouping
  src/device-registry/app.js
  src/device-registry/config/constants.js
  src/device-registry/config/redis.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/test/ut_create-site.js
  src/device-registry/models/AdminLevel.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/Device.js
  src/device-registry/models/Grid.js
  src/device-registry/models/Network.js
  src/device-registry/models/Site.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/v1/airqlouds.js
  src/device-registry/routes/v1/cohorts.js
  src/device-registry/routes/v1/grids.js
  src/device-registry/routes/v1/index.js
  src/device-registry/routes/v2/airqlouds.js
  src/device-registry/routes/v2/cohorts.js
  src/device-registry/routes/v2/grids.js
  src/device-registry/routes/v2/index.js
  src/device-registry/utils/common.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-cohort.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-grid.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/test/ut_create-activity.js
  src/device-registry/utils/test/ut_create-airqloud.js
  src/device-registry/utils/test/ut_create-cohort.js
  src/device-registry/utils/test/ut_create-device.js
  src/device-registry/utils/test/ut_create-event.js
  src/device-registry/utils/test/ut_create-grid.js
Labels: ready for review, device-registry

#1592 Predicting and storing air quality of parishes
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/predict/templates/places-airquality.yaml
  k8s/predict/values-stage.yaml
  src/predict/api/app.py
  src/predict/api/config/constants.py
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
  src/predict/api/requirements.txt
  src/predict/api/routes/api.py
  src/predict/jobs/predict_places_air_quality/.dockerignore
  src/predict/jobs/predict_places_air_quality/.gitignore
  src/predict/jobs/predict_places_air_quality/Dockerfile
  src/predict/jobs/predict_places_air_quality/README.md
  src/predict/jobs/predict_places_air_quality/__init__.py
  src/predict/jobs/predict_places_air_quality/configure.py
  src/predict/jobs/predict_places_air_quality/main.py
  src/predict/jobs/predict_places_air_quality/requirements.txt
  src/predict/jobs/predict_places_air_quality/utils.py
Labels: work in progress

#1822 Adding more error handling to data export
  src/analytics/api/models/data_export.py
  src/analytics/api/utils/exceptions.py
  src/analytics/api/views/data.py
  src/analytics/celery_app.py
Labels: ready for review

#1824 fixing a runtime error for mongoose projection
  src/device-registry/models/AdminLevel.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/Device.js
  src/device-registry/models/Grid.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/Network.js
  src/device-registry/models/Site.js
Labels: ready for review

#1827 Generate search name and location name when creating Site
  src/device-registry/utils/create-site.js
Labels: ready for review

#1826 Fixing a runtime error for mongoose projection -- AUTHSERVICE
  src/auth-service/models/Favorite.js
Labels: ready for review

#1828 Fixing typo on predict API
  src/predict/api/helpers/utils.py
Labels: ready for review

#1741 Implementation of hourly forecasts
  src/predict/api/config/constants.py
  src/predict/jobs/forecast/Dockerfile
  src/predict/jobs/forecast/config.py
  src/predict/jobs/forecast/daily_forecasts.py
  src/predict/jobs/forecast/hourly_forecasts.py
  src/predict/jobs/forecast/models.py
  src/predict/jobs/forecast/requirements.txt
  src/predict/jobs/forecast/utils.py
  src/predict/jobs/forecast_training/Dockerfile
  src/predict/jobs/forecast_training/config.py
  src/predict/jobs/forecast_training/daily_forecast_training.py
  src/predict/jobs/forecast_training/hourly_forecast_training.py
  src/predict/jobs/forecast_training/models.py
  src/predict/jobs/forecast_training/requirements.txt
  src/predict/jobs/forecast_training/transform.py
  src/predict/jobs/forecast_training/utils.py
Labels: ready for review, predict

#1830 undoing previous Model projection changes when listing
  src/device-registry/config/constants.js
  src/device-registry/models/AdminLevel.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/Device.js
  src/device-registry/models/Grid.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/Network.js
  src/device-registry/models/Site.js
Labels: ready for review, device-registry

#1831 undoing previous Model projection changes when listing
  src/auth-service/config/constants.js
  src/auth-service/models/Favorite.js
Labels: ready for review, auth-service

#1820 Comparing mobile app versions
  src/view/pom.xml
  src/view/src/main/java/airqo/config/GlobalExceptionHandler.java
  src/view/src/main/java/airqo/controllers/AppController.java
  src/view/src/main/java/airqo/models/StoreVersion.java
  src/view/src/main/java/airqo/services/AppService.java
  src/view/src/main/resources/application.properties
Labels: ready for review

#1823 Making data summary interval an environment variable
  src/analytics/config.py
  src/analytics/devices_summary.py
Labels: ready for review

#1834 Adding v2 to view api
  src/view/src/main/java/airqo/controllers/AppController.java
  src/view/src/main/java/airqo/controllers/MeasurementController.java
  src/view/src/main/resources/application-api.properties
  src/view/src/test/java/airqo/MeasurementControllerTests.java
Labels: ready for review

#1835 Hotfix Pipeline: Convert tenant to string.
  src/airflow/airqo_etl_utils/airqo_api.py
Labels: ready for review

#1833 Update dockerfiles for forecast jobs
  src/predict/jobs/forecast/Dockerfile
  src/predict/jobs/forecast/run_scripts.sh
  src/predict/jobs/forecast_training/Dockerfile
  src/predict/jobs/forecast_training/run_scripts.sh
Labels: ready for review, predict

#1837 use same paths as in auth microservice
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#1836 Move to production
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/view/values-stage.yaml
  src/airflow/airqo_etl_utils/airqo_api.py
  src/predict/jobs/forecast/Dockerfile
  src/predict/jobs/forecast/run_scripts.sh
  src/predict/jobs/forecast_training/Dockerfile
  src/predict/jobs/forecast_training/run_scripts.sh
  src/view/src/main/java/airqo/controllers/AppController.java
  src/view/src/main/java/airqo/controllers/MeasurementController.java
  src/view/src/main/resources/application-api.properties
  src/view/src/test/java/airqo/MeasurementControllerTests.java
Labels: ready for review

#1840 Triggering predict microservice build
  src/predict/api/README.md
Labels: ready for review

#1841 Updating predict requirements
  src/predict/jobs/predict_places_air_quality/requirements.txt
Labels: ready for review

#1773 Set up CI/CD for Search-api-data production
  .github/workflows/deploy-apis-to-production.yml
  k8s/predict/values-prod.yaml
Labels: ready for review

#1842 Device summary computations DAG
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/data_summary_utils.py
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/airnow.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/daily_measurements.py
  src/airflow/dags/data_summary.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/nasa_measurements.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/dags/weather_measurements.py
Labels: ready for review

#1838 MLFlow hot fix - predict
  src/predict/jobs/forecast_training/Dockerfile
Labels: ready for review, predict

#1845 Fix Projections in AirQloud summary
  src/device-registry/config/constants.js
Labels: ready for review

#1847 add more v2 endpoints auth
  k8s/nginx/production/platform-vs.yaml
Labels: ready for review

#1844 Ft unsuspend place predict
  k8s/nginx/development/global-config.yaml
  k8s/predict/templates/places-airquality.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
Labels: ready for review

#1850 fix a runtime error for creating cohorts
  src/device-registry/controllers/create-cohort.js
Labels: ready for review

#1851 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/platform-vs.yaml
  k8s/predict/templates/places-airquality.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  k8s/view/values-prod.yaml
  src/device-registry/controllers/create-cohort.js
Labels: ready for review

#1854 Increases predict microservice resources
  k8s/predict/values-prod.yaml
Labels: ready for review

#1855 Fix uptime graphs
  k8s/data-mgt/templates/deployment.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/templates/cronjob.yaml
  k8s/device-uptime/templates/cronjob-v2.yaml
  k8s/device-uptime/templates/cronjob.yaml
Labels: hotfix, ready for review, devops

#1858 Adding admin level to AirQlouds summary endpoint
  src/device-registry/config/constants.js
Labels: ready for review

#1859 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-mgt/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/device-uptime/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-registry/config/constants.js
Labels: ready for review

#1862 Enabling predict places air quality job
  k8s/predict/templates/places-airquality.yaml
Labels: ready for review

#1864 Resolving collocation errors
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/models.py
Labels: ready for review

#1865 Move to production
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/models.py
Labels: ready for review

#1867 Fixing api.airqo.net failing to work for auth service
  k8s/nginx/production/api-vs.yaml
Labels: ready for review, auth-service

#1868 move to production
  k8s/nginx/production/api-vs.yaml
Labels: ready for review

#1869 adding function bodies to the create-transaction util
  src/incentives/app.js
  src/incentives/config/constants.js
  src/incentives/models/Host.js
  src/incentives/models/transaction.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/test/ut_create-transaction.js
Labels: ready for review, incentives

#1870 move to production
  src/incentives/app.js
  src/incentives/config/constants.js
  src/incentives/models/Host.js
  src/incentives/models/transaction.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/test/ut_create-transaction.js
Labels: ready for review

#1872 Move to production
  src/predict/api/helpers/utils.py
Labels: ready for review

#1873 INCENTIVES: enable the Slack logs
  src/incentives/.gitignore
  src/incentives/app.js
  src/incentives/bin/www
  src/incentives/config/constants.js
  src/incentives/config/log4js.js
  src/incentives/controllers/create-host.js
  src/incentives/controllers/create-transaction.js
  src/incentives/models/Host.js
  src/incentives/models/transaction.js
  src/incentives/package-lock.json
  src/incentives/package.json
  src/incentives/utils/create-transaction.js
Labels: ready for review, incentives

#1866 Incentives API ci/cd
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/incentives/.helmignore
  k8s/incentives/Chart.yaml
  k8s/incentives/templates/NOTES.txt
  k8s/incentives/templates/_helpers.tpl
  k8s/incentives/templates/deployment.yaml
  k8s/incentives/templates/hpa.yaml
  k8s/incentives/templates/service.yaml
  k8s/incentives/templates/tests/test-connection.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
Labels: work in progress, ready for review

#1875 Fix incentives cicd
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  k8s/incentives/templates/deployment.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  src/incentives/package.json
Labels: hotfix, ready for review

#1877 Increased client-max-body-size in Nginx config files
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#1876 INCENTIVES: more refactoring for unit tests, utils , controllers and config files
  src/incentives/config/constants.js
  src/incentives/config/test/ut_constants.js
  src/incentives/controllers/create-transaction.js
  src/incentives/controllers/test/ut_create-transaction.js
  src/incentives/models/test/ut_transaction.js
  src/incentives/models/transaction.js
  src/incentives/routes/v1/test/ut_transactions.js
  src/incentives/routes/v1/transactions.js
  src/incentives/routes/v2/test/ut_transactions.js
  src/incentives/routes/v2/transactions.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/test/ut_create-transaction.js
Labels: ready for review, incentives

#1878 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/incentives/.helmignore
  k8s/incentives/Chart.yaml
  k8s/incentives/templates/NOTES.txt
  k8s/incentives/templates/_helpers.tpl
  k8s/incentives/templates/deployment.yaml
  k8s/incentives/templates/hpa.yaml
  k8s/incentives/templates/service.yaml
  k8s/incentives/templates/tests/test-connection.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  src/incentives/config/constants.js
  src/incentives/config/test/ut_constants.js
  src/incentives/controllers/create-transaction.js
  src/incentives/controllers/test/ut_create-transaction.js
  src/incentives/models/test/ut_transaction.js
  src/incentives/models/transaction.js
  src/incentives/package.json
  src/incentives/routes/v1/test/ut_transactions.js
  src/incentives/routes/v1/transactions.js
  src/incentives/routes/v2/test/ut_transactions.js
  src/incentives/routes/v2/transactions.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/test/ut_create-transaction.js
Labels: ready for review

#1879 Hot Fix Site Creation
  src/device-registry/models/Site.js
Labels: ready for review

#1880 move to production
  src/device-registry/models/Site.js
Labels: ready for review

#1882 move to production
  .github/workflows/deploy-apis-to-production.yml
Labels: ready for review

#1883 Testing out Device registry deployment Fix
  src/device-registry/README.md
Labels: ready for review

#1884 move to production
  src/device-registry/README.md
Labels: ready for review

#1885 Triggering the deployment workflow
  workflow-trigger
Labels: ready for review

#1890 fix the gateway timeout
  src/device-registry/utils/create-event.js
Labels: ready for review

#1888 move to production
  README.md
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-stage.yaml
  k8s/channel-data/values-stage.yaml
  k8s/data-mgt/values-stage.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/values-stage.yaml
  k8s/exceedance/values-stage-airqo.yaml
  k8s/exceedance/values-stage-kcca.yaml
  k8s/fault-detection/values-stage.yaml
  k8s/gp-model/values-stage.yaml
  k8s/incentives/values-stage.yaml
  k8s/kafka/BigQuery-connectors/values-stage.yaml
  k8s/locate/values-stage.yaml
  k8s/meta-data/values-stage.yaml
  k8s/predict/values-stage.yaml
  k8s/view/values-stage.yaml
  src/device-registry/utils/create-event.js
  workflow-trigger
Labels: ready for review

#1886 Enhancements for kya (Excluding Package.lock)
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/routes/v1/kya.js
  src/device-registry/routes/v2/kya.js
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1892 MOVE TO PRODUCTION
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/kafka/BigQuery-connectors/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/routes/v1/kya.js
  src/device-registry/routes/v2/kya.js
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1819 introducing recall_type to support different types of device recalls
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/routes/v1/activities.js
  src/device-registry/routes/v2/activities.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry

#1891 INCENTIVES hotfixes
  src/incentives/controllers/create-host.js
  src/incentives/controllers/create-transaction.js
  src/incentives/models/Host.js
  src/incentives/models/transaction.js
  src/incentives/routes/v1/transactions.js
  src/incentives/routes/v2/transactions.js
  src/incentives/utils/create-host.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/generate-filter.js
Labels: hotfix, ready for review, incentives

#1896 remove unsued microservice folders from our src/
  src/app-enable/sample.txt
  src/events-registry/.gitkeep
  src/events-registry/config/.gitkeep
  src/events-registry/controllers/.gitkeep
  src/events-registry/routes/.gitkeep
  src/events-registry/utils/.gitkeep
  src/service-monitoring/.dockerignore
  src/service-monitoring/Dockerfile
  src/service-monitoring/index.js
  src/service-monitoring/models/EventBridge.js
  src/service-monitoring/package.json
  src/service-monitoring/sample.txt
Labels: ready for review

#1900 increasing the accepted payload size
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  src/device-registry/app.js
Labels: ready for review

#1897 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/app-enable/sample.txt
  src/device-registry/app.js
  src/events-registry/.gitkeep
  src/events-registry/config/.gitkeep
  src/events-registry/controllers/.gitkeep
  src/events-registry/routes/.gitkeep
  src/events-registry/utils/.gitkeep
  src/service-monitoring/.dockerignore
  src/service-monitoring/Dockerfile
  src/service-monitoring/index.js
  src/service-monitoring/models/EventBridge.js
  src/service-monitoring/package.json
  src/service-monitoring/sample.txt
Labels: ready for review

#1901 increasing the limit again
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  src/device-registry/app.js
Labels: ready for review

#1902 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/events-monitor/.gitignore
  k8s/events-monitor/.helmignore
  k8s/events-monitor/Chart.yaml
  k8s/events-monitor/prod-values.yaml
  k8s/events-monitor/stage-values.yaml
  k8s/events-monitor/templates/NOTES.txt
  k8s/events-monitor/templates/_helpers.tpl
  k8s/events-monitor/templates/cronjob.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/templates/deployment.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/incentives/values-prod.yaml
  k8s/kafka/BigQuery-connectors/values-prod.yaml
  k8s/kafka/BigQuery-connectors/values-stage.yaml
  k8s/kafka/connectors/measurements-connect.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/notification-service/prod-notification-api.yaml
  k8s/notification-service/stage-notification-api.yaml
  k8s/predict/values-prod.yaml
  k8s/view/templates/message-broker-hpa.yaml
  k8s/view/templates/message-broker.yaml
  k8s/view/values-prod.yaml
  k8s/view/values-stage.yaml
  src/device-registry/app.js
Labels: ready for review

#1904 resolving app config issues
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  src/auth-service/app.js
  src/device-registry/app.js
Labels: ready for review

#1905 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/app.js
  src/device-registry/app.js
Labels: ready for review

#1907 adjusting config details at Nginx file size
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#1906 move to productioin
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
Labels: ready for review

#1908 fix potential denial of service
  src/device-registry/app.js
Labels: ready for review

#1909 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-registry/app.js
Labels: ready for review

#1911 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
Labels: ready for review

#1914 add new logs for create host use case
  src/incentives/controllers/create-host.js
Labels: hotfix, ready for review, incentives

#1915 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-stage.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/incentives/controllers/create-host.js
Labels: ready for review

#1916 resolving a runtime in staging
  src/incentives/utils/create-transaction.js
  src/incentives/utils/log.js
Labels: ready for review

#1918 handling a new edge case
  src/incentives/utils/create-transaction.js
Labels: ready for review

#1917 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/incentives/utils/create-transaction.js
  src/incentives/utils/log.js
Labels: ready for review

#1919 Adding support for resetting a batch
  src/device-monitoring/controllers/collocation.py
Labels: ready for review

#1903 Hotfix cicd
  k8s/notification-service/prod-notification-api.yaml
  k8s/notification-service/stage-notification-api.yaml
Labels: ready for review

#1923 Adding collocation check type
  src/device-monitoring/models.py
Labels: ready for review

#1924 HotFix - Maintainence Logs
  src/device-registry/controllers/create-activity.js
Labels: ready for review

#1921 Move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/notification-service/prod-notification-api.yaml
  k8s/notification-service/stage-notification-api.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/models.py
  src/device-registry/controllers/create-activity.js
Labels: ready for review

#1926 Follow Up -fix maintenance Logs
  src/device-registry/controllers/create-activity.js
  src/device-registry/utils/create-activity.js
Labels: ready for review

#1927 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-registry/controllers/create-activity.js
  src/device-registry/utils/create-activity.js
Labels: ready for review

#1928 Adding more collocation validation checks
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/models.py
Labels: ready for review

#1932 Registering the data summary DAG
  src/airflow/dags/data_summary.py
Labels: ready for review

#1935 Adding more collocation input validation
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/models.py
Labels: ready for review

#1936 Collocation typos
  src/device-monitoring/models.py
Labels: ready for review

#1938 Refactoring Auth Service and adding more unit tests
  src/auth-service/Dockerfile
  src/auth-service/app.js
  src/auth-service/bin/index.js
  src/auth-service/bin/kafka-consumer.js
  src/auth-service/bin/server.js
  src/auth-service/bin/test/ut_index.js
  src/auth-service/bin/test/ut_kafka-consumer.js
  src/auth-service/bin/test/ut_server.js
  src/auth-service/bin/test/ut_www.js
  src/auth-service/bin/www
  src/auth-service/config/constants.js
  src/auth-service/config/database.js
  src/auth-service/config/test/unit-test-structure.js
  src/auth-service/controllers/create-network.js
  src/auth-service/controllers/test/ut_create-client.js
  src/auth-service/controllers/test/ut_create-default.js
  src/auth-service/controllers/test/ut_create-department.js
  src/auth-service/controllers/test/ut_create-favorite.js
  src/auth-service/controllers/test/ut_create-group.js
  src/auth-service/controllers/test/ut_create-inquiry.js
  src/auth-service/controllers/test/ut_create-location-history.js
  src/auth-service/controllers/test/ut_create-network.js
  src/auth-service/controllers/test/ut_create-permission.js
  src/auth-service/controllers/test/ut_create-role.js
  src/auth-service/controllers/test/ut_create-scope.js
  src/auth-service/controllers/test/ut_create-token.js
  src/auth-service/middleware/test/ut_passport.js
  src/auth-service/package.json
  src/auth-service/routes/index.js
  src/auth-service/routes/test/ut_index.js
  src/auth-service/routes/v1/index.js
  src/auth-service/routes/v2/clients.js
  src/auth-service/routes/v2/index.js
  src/auth-service/routes/v2/scopes.js
  src/auth-service/test/ut_app.js
Labels: ready for review

#1940 Search history Endpoints(Corrected)
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-search-history.js
  src/auth-service/models/searchHistory.js
  src/auth-service/routes/v1/index.js
  src/auth-service/routes/v1/searchHistory.js
  src/auth-service/routes/v2/index.js
  src/auth-service/routes/v2/searchHistory.js
  src/auth-service/utils/create-search-history.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#1942 More Unit Tests for the create search history use case
  src/auth-service/controllers/test/ut_create-search-history.js
  src/auth-service/models/test/ut_search-history.js
  src/auth-service/routes/v1/test/ut_search-histories.js
  src/auth-service/routes/v2/test/ut_search-histories.js
  src/auth-service/utils/create-search-history.js
  src/auth-service/utils/test/ut_create-search-history.js
  src/auth-service/utils/test/ut_generate-filter.js
Labels: ready for review

#1848 Add User details to site activities (deploy, recall and maintain)
  src/device-registry/config/constants.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/v1/activities.js
  src/device-registry/routes/v2/activities.js
Labels: ready for review

#1945 hotfix jwt thing
  src/auth-service/models/User.js
Labels: ready for review
