Repository airqo-platform/AirQo-api, pull requests merged in 2023-10, with the labels that each got.

#2218 refactoring list events mongoose static function
  src/device-registry/bin/www
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Grid.js
  src/device-registry/models/Site.js
  src/device-registry/models/test/ut_event.js
  src/device-registry/routes/v2/activities.js
  src/device-registry/routes/v2/airqlouds.js
  src/device-registry/routes/v2/cohorts.js
  src/device-registry/routes/v2/devices.js
  src/device-registry/routes/v2/events.js
  src/device-registry/routes/v2/grids.js
  src/device-registry/routes/v2/kya.js
  src/device-registry/routes/v2/locations.js
  src/device-registry/routes/v2/measurements.js
  src/device-registry/routes/v2/metadata.js
  src/device-registry/routes/v2/photos.js
  src/device-registry/routes/v2/sites.js
  src/device-registry/routes/v2/tips.js
  src/device-registry/routes/v2/transmit.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/test/ut_create-airqloud.js
Labels: ready for review

#2220 remove more unwanted fields when getting running devices
  src/device-registry/models/Event.js
Labels: ready for review

#2222 enhancements to the Host creation
  src/incentives/models/Host.js
  src/incentives/routes/v2/hosts.js
Labels: ready for review

#2224 Capture the domain name and IP address of any system making a request
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  src/auth-service/controllers/create-token.js
Labels: ready for review

#2225 [auth-service] logging the domain name and ip address of caller
  src/auth-service/middleware/passport.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2228 comment out log statements for HEADER information
  src/auth-service/middleware/passport.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2213 incentives test coverage
  .github/workflows/incentives-test.yml
  src/incentives/package-lock.json
  src/incentives/package.json
Labels: ready for review

#2232 adding NETWORKS to User JWT
  src/auth-service/controllers/create-user.js
  src/auth-service/controllers/test/ut_create-user.js
  src/auth-service/models/User.js
  src/auth-service/models/test/ut_user.js
Labels: ready for review

#2234 fixing runtime error for user login
  src/auth-service/config/constants.js
  src/auth-service/models/User.js
Labels: ready for review

#2233 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-user.js
  src/auth-service/controllers/test/ut_create-user.js
  src/auth-service/models/User.js
  src/auth-service/models/test/ut_user.js
Labels: ready for review

#2235 reduce number of fields returned for summary of AirQlouds
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-airqloud.js
Labels: ready for review

#2236 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-airqloud.js
Labels: ready for review

#2237 hotfixes to accomodate the introduction of Groups
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-group.js
  src/auth-service/controllers/create-request.js
  src/auth-service/models/Group.js
  src/auth-service/models/Role.js
  src/auth-service/models/User.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/create-request.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/test/ut_control-access.js
  src/auth-service/utils/test/ut_create-group.js
  src/auth-service/utils/test/ut_create-request.js
  src/auth-service/utils/test/ut_generate-filter.js
Labels: ready for review

#2239 correcting the field name for each group
  src/auth-service/models/User.js
Labels: hotfix, ready for review

#2240 adding number of Group users to the endpoint for Groups
  src/auth-service/config/constants.js
Labels: ready for review

#2241 add Site details to AirQloud summary endopint
  src/device-registry/config/constants.js
Labels: ready for review

#2242 fix email notification after assigning user to Organisation
  src/auth-service/utils/create-request.js
Labels: ready for review

#2244 ensuring that assigned users are returned for the group
  src/auth-service/models/Group.js
Labels: ready for review

#2245 fixed Group update
  src/auth-service/routes/v2/groups.js
  src/auth-service/utils/create-group.js
Labels: ready for review

#2246 correcting the error message
  src/auth-service/routes/v2/groups.js
Labels: ready for review

#2247 ensure that one who creates the group is assigned the group
  src/auth-service/utils/create-group.js
  src/auth-service/utils/test/ut_create-group.js
Labels: ready for review

#2249 ensuring that duplicate groups are eliminated
  src/auth-service/models/User.js
Labels: ready for review

#2251 adding group status and creation date to the groups of each user
  src/auth-service/config/constants.js
  src/auth-service/models/User.js
Labels: ready for review

#2243 hotfixes or SIM card management
  src/incentives/models/Sim.js
  src/incentives/routes/v2/sims.js
  src/incentives/utils/create-sim.js
  src/incentives/utils/generate-filter.js
Labels: ready for review

#2252 remove networks and groups from JWT
  src/auth-service/models/User.js
Labels: ready for review

#2253 support devices in storing user defaults
  src/auth-service/controllers/create-default.js
  src/auth-service/models/Defaults.js
  src/auth-service/routes/v2/defaults.js
Labels: ready for review

#2254 specifying the group manager
  src/auth-service/config/constants.js
  src/auth-service/models/Group.js
  src/auth-service/models/User.js
  src/auth-service/utils/create-group.js
Labels: ready for review

#2255 input validations for sim card creation
  src/incentives/routes/v2/sims.js
  src/incentives/utils/create-sim.js
Labels: ready for review

#2258 Fix for Deploy devices
  src/device-registry/utils/create-activity.js
Labels: ready for review

#2238 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-default.js
  src/auth-service/controllers/create-group.js
  src/auth-service/controllers/create-request.js
  src/auth-service/models/Defaults.js
  src/auth-service/models/Group.js
  src/auth-service/models/Role.js
  src/auth-service/models/User.js
  src/auth-service/routes/v2/defaults.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/create-request.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/test/ut_control-access.js
  src/auth-service/utils/test/ut_create-group.js
  src/auth-service/utils/test/ut_create-request.js
  src/auth-service/utils/test/ut_generate-filter.js
  src/device-registry/config/constants.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Photo.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/generate-filter.js
  src/incentives/models/Sim.js
  src/incentives/routes/v2/sims.js
  src/incentives/utils/create-sim.js
  src/incentives/utils/generate-filter.js
Labels: ready for review

#2259 Hotfix deploy
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#2260 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#2261 enhance filter util
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#2262 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#2263 small change to trigger new secrets
  src/incentives/README.md
Labels: ready for review

#2265 hotfix for incentives
  src/incentives/README.md
Labels: ready for review

#2266 Grid summary endpoint
  src/device-registry/controllers/create-grid.js
  src/device-registry/routes/v2/grids.js
Labels: ready for review

#2264 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/controllers/create-grid.js
  src/device-registry/routes/v2/grids.js
  src/incentives/README.md
  src/incentives/models/Sim.js
Labels: ready for review

#2269 utilising new schema name
  src/incentives/models/Sim.js
Labels: ready for review

#2270 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  k8s/predict/values-prod.yaml
  src/incentives/models/Sim.js
Labels: ready for review

#2271 Disable Tests for Translate for Kya and health tips temporarily
  src/device-registry/utils/test/ut_translate.js
Labels: ready for review

#2219 Update Champions Inquiry Email
  src/auth-service/config/constants.js
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#2272 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/config/constants.js
  src/auth-service/utils/email.msgs.js
  src/device-registry/utils/test/ut_translate.js
Labels: ready for review

#2273 Correct Inquiry emails
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#2274 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#2151 Faulty devices endpoint update
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/bigquery_api.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/tests/airqo_utils_tests.py
  src/airflow/requirements.txt
  src/predict/api/helpers.py
  src/predict/api/prediction.py
Labels: data-engineering, ready for review, fault-detection

#2256 Run-airflow read me for window
  src/airflow/README.md
  src/airflow/run-airflow-only.sh
  src/airflow/run.sh
Labels: data-engineering

#2257 setup codecov for airlfow microservice
  .github/workflows/codecov.yml
  src/airflow/airqo_etl_utils/ml_utils.py
  src/airflow/airqo_etl_utils/tests/conftest.py
  src/airflow/airqo_etl_utils/tests/test_airqo_utils.py
  src/airflow/airqo_etl_utils/tests/test_big_query_api.py
  src/airflow/airqo_etl_utils/tests/test_ml_utils.py
  src/airflow/airqo_etl_utils/tests/urban_better_utils_tests.py
  src/airflow/requirements.txt
Labels: data-engineering, ready for review, devops

#2276 adding new fields to the Network Schema
  src/auth-service/models/Network.js
  src/auth-service/routes/v2/networks.js
Labels: ready for review

#2277 New mandatory fields when creating new NETWORKS
  src/auth-service/models/Network.js
  src/auth-service/routes/v2/networks.js
Labels: ready for review

#2281 restore the create user functionality
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/test/ut_create-user.js
Labels: ready for review

#2282 resolve issues around email verification
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-user.js
Labels: ready for review

#2284 updating the URL in the verify email
  src/auth-service/config/constants.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.templates.js
Labels: ready for review

#2285 allow special characters in password validation
  src/auth-service/models/User.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/users.js
Labels: ready for review

#2283 Update data export functionality for AQCSV
  src/analytics/Dockerfile
  src/analytics/api/tests/conftest.py
  src/analytics/api/tests/test_data_formatters.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/requirements.txt
Labels: python, ready for review

#2286 enhancing the create use endpoing to also consider categories
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-request.js
  src/auth-service/models/AccessRequest.js
  src/auth-service/models/Group.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/routes/v2/requests.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-request.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_email.templates.js
  src/auth-service/utils/test/ut_mailer.js
Labels: ready for review

#2287 new email template for the invited user
  src/auth-service/config/constants.js
  src/auth-service/utils/create-request.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#2288 send invites to multiple emails
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-request.js
  src/auth-service/models/User.js
  src/auth-service/routes/v2/requests.js
  src/auth-service/utils/create-request.js
Labels: ready for review

#2289 add default role
  src/auth-service/models/User.js
Labels: ready for review

#2290 update the URL of the email invite for Group
  src/auth-service/utils/email.templates.js
Labels: ready for review

#2291 update the error response for access requests
  src/auth-service/utils/create-request.js
Labels: ready for review

#2292 fixing runtime errors for assigning roles to users
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/test/ut_control-access.js
Labels: ready for review

#2293 final routes for the verification emails
  src/auth-service/utils/email.templates.js
Labels: ready for review

#2295 accept invitation email
  src/auth-service/controllers/create-request.js
  src/auth-service/routes/v2/requests.js
  src/auth-service/utils/create-request.js
  src/auth-service/utils/email.templates.js
Labels: ready for review

#2296 updating the url in the email
  src/auth-service/utils/email.templates.js
Labels: ready for review

#2297 Added contributing guide
  README.md
  contributing.md
Labels: ready for review

#2299 create organisation by explicityl providing user id in request body
  src/auth-service/routes/v2/groups.js
  src/auth-service/utils/create-group.js
Labels: ready for review

#2302 change in accept invite URL
  src/auth-service/utils/email.templates.js
Labels: ready for review

#2294 Weekly Email Notifications for Favorites
  src/firebase/auth/firebase.json
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/config/images/favoriteIcon.png
  src/firebase/auth/functions/config/notificationEmailTemplate.html
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
  src/firebase/auth/functions/package.json
Labels: ready for review

#2300 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/routes/v2/groups.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/email.templates.js
  src/firebase/auth/firebase.json
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/config/images/favoriteIcon.png
  src/firebase/auth/functions/config/notificationEmailTemplate.html
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
  src/firebase/auth/functions/package.json
Labels: ready for review

#2303 Hotfixes for Group Creation and Role Assignment
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-group.js
  src/auth-service/models/User.js
  src/auth-service/routes/v2/users-04-05-2023.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/test/ut_create-group.js
Labels: ready for review

#2305 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-group.js
  src/auth-service/models/User.js
  src/auth-service/routes/v2/users-04-05-2023.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/test/ut_create-group.js
Labels: ready for review

#2306 fix runtime for assigning many users
  src/auth-service/controllers/create-group.js
  src/auth-service/controllers/test/ut_create-group.js
  src/auth-service/models/Group.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/test/ut_create-group.js
Labels: ready for review

#2307 move to production
  k8s/airflow/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/controllers/create-group.js
  src/auth-service/controllers/test/ut_create-group.js
  src/auth-service/models/Group.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/test/ut_create-group.js
Labels: ready for review

#2308 fixing the endpoint for removing indices in the database
  src/auth-service/controllers/create-group.js
  src/auth-service/utils/create-group.js
Labels: ready for review

#2309 move to production
  k8s/airflow/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/controllers/create-group.js
  src/auth-service/utils/create-group.js
Labels: ready for review

#2310 small hotfix around grp_website issue
  src/auth-service/utils/create-group.js
Labels: ready for review

#2311 move to production
  k8s/airflow/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/utils/create-group.js
Labels: ready for review

#2304 Whitelist endpoints
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#2317 Reverse WhiteListing
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#2318 whitelist updatePassword via email and create users endpoint
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#2319 more whitelisting changes for updatePasswordViaEmail
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#2321 restore previous state
  k8s/nginx/staging/global-config.yaml
  src/auth-service/README.md
Labels: ready for review

#2322 just whitelisting the updatePasswordViaEmail for now
  k8s/nginx/staging/global-config.yaml
  src/auth-service/README.md
Labels: ready for review

#2323 adding the same configs for both production and development
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
Labels: ready for review

#2324 whitelistimg the POST for /api/v2/users
  k8s/nginx/staging/global-config.yaml
  src/auth-service/README.md
Labels: ready for review

#2326 just allow all auth service endpoints
  k8s/nginx/staging/global-config.yaml
  src/auth-service/README.md
Labels: ready for review

#2327 just allow all auth service endpoints through
  k8s/nginx/staging/global-config.yaml
  src/auth-service/README.md
Labels: ready for review

#2328 apply the same configuration to both development and production envs
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
Labels: ready for review

#2313 Add portuguese and swahilli translations for KYA and Tips
  src/device-registry/utils/test/ut_translate.js
  src/device-registry/utils/translate.js
Labels: ready for review

#2315 Analytics AQCSV Data Export Hotfix
  src/analytics/api/tests/test_data_formatters.py
  src/analytics/api/utils/data_formatters.py
Labels: ready for review

#2316 Minor Cleanup and Fixes for the Firebase Functions
  src/auth-service/config/constants.js
  src/firebase/auth/README.md
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
Labels: ready for review

#2329 getting the IP and Host details
  k8s/nginx/staging/global-config.yaml
  src/auth-service/middleware/passport.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2330 resolving a few issues around candidate creation and what not
  src/auth-service/models/Candidate.js
  src/auth-service/models/User.js
Labels: ready for review

#2331 store the ip address and hostname of the requester
  src/auth-service/middleware/passport.js
  src/auth-service/models/log.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2314 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/values-prod.yaml
  src/analytics/api/tests/test_data_formatters.py
  src/analytics/api/utils/data_formatters.py
  src/auth-service/README.md
  src/auth-service/config/constants.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/User.js
  src/auth-service/models/log.js
  src/auth-service/utils/control-access.js
  src/device-registry/utils/test/ut_translate.js
  src/device-registry/utils/translate.js
  src/firebase/auth/README.md
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
Labels: ready for review

#2332 adding the client and host details to prod and dev environments too
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  src/auth-service/README.md
Labels: ready for review

#2333 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/README.md
Labels: ready for review

#2334 limit to just 2 sites when getting or GPS coordinate
  src/device-registry/controllers/create-event.js
Labels: ready for review

#2336 fixing runtime errors
  src/auth-service/middleware/passport.js
Labels: ready for review

#2335 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/middleware/passport.js
  src/device-registry/controllers/create-event.js
Labels: ready for review

#2337 undo some schema configs
  src/auth-service/models/log.js
Labels: ready for review

#2339 removing more configs
  src/auth-service/middleware/passport.js
  src/auth-service/models/log.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2340 commented out all client and domain code from auth
  src/auth-service/middleware/passport.js
  src/auth-service/models/log.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2341 just checking out a different microservice
  src/device-registry/routes/v2/devices.js
Labels: ready for review

#2342 troubleshooting deployment issues
  k8s/nginx/staging/global-config.yaml
  src/auth-service/README.md
  src/device-registry/routes/v2/sites.js
Labels: ready for review

#2343 auth service feedback from workshop
  k8s/nginx/staging/global-config.yaml
  src/auth-service/routes/v2/groups.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#2344 allow formatted name for Site
  src/device-registry/config/constants.js
Labels: ready for review

#2346 just commenting out some configs in the Nginx configuration
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#2338 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/middleware/passport.js
  src/auth-service/models/log.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/generate-filter.js
  src/device-registry/config/constants.js
  src/device-registry/routes/v2/devices.js
  src/device-registry/routes/v2/sites.js
Labels: ready for review

#2347 restore production nginx config
  k8s/nginx/production/global-config.yaml
Labels: ready for review

#2349 auth and device registry changes
  src/auth-service/README.md
  src/device-registry/README.md
Labels: ready for review

#2351 restore some parts in both dev and stage nginx config
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#2352 trigger auth and device registry
  src/auth-service/README.md
  src/device-registry/README.md
Labels: ready for review

#2354 staging config back to status earlier in the week
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#2355 just general refactoring of nginx
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#2356 fixing logic for CRUD around Groups
  src/auth-service/models/Group.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#2353 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/README.md
  src/auth-service/models/Group.js
  src/auth-service/utils/create-group.js
  src/auth-service/utils/generate-filter.js
  src/device-registry/README.md
Labels: ready for review

#2358 temporarily disable deletion of Groups and Networks
  src/auth-service/utils/create-group.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#2359 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/utils/create-group.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#2360 prevent accidental removal of groups from Users
  src/auth-service/models/User.js
Labels: ready for review

#2361 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/models/User.js
Labels: ready for review

#2362 unprotect user update endpoints
  src/auth-service/routes/v2/users.js
Labels: ready for review

#2357 Fix for predict caching mechanism
  src/predict/api/helpers.py
Labels: ready for review, predict

#2367 create sim cards in bulk
  src/incentives/controllers/create-sim.js
  src/incentives/routes/v2/sims.js
  src/incentives/utils/create-sim.js
Labels: ready for review

#2366 adding default tenant for the create-defaults usecase
  src/auth-service/controllers/create-default.js
  src/auth-service/routes/v2/defaults.js
Labels: ready for review

#2364 Remove madagascar 4m gp-model
  src/gp-model/main.py
Labels: ready for review

#2368 adding unit test for the createBulk function for sim cards usecase
  src/incentives/.gitignore
  src/incentives/utils/create-sim.js
  src/incentives/utils/test/ut_create-sim.js
Labels: ready for review

#2363 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  src/auth-service/controllers/create-default.js
  src/auth-service/routes/v2/defaults.js
  src/auth-service/routes/v2/users.js
  src/gp-model/main.py
  src/incentives/.gitignore
  src/incentives/controllers/create-sim.js
  src/incentives/routes/v2/sims.js
  src/incentives/utils/create-sim.js
  src/incentives/utils/test/ut_create-sim.js
  src/predict/api/helpers.py
Labels: ready for review

#2369 just controller cleanup for fetchimng using GPS coordinates
  src/device-registry/controllers/create-event.js
Labels: ready for review

#2370 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/controllers/create-event.js
Labels: ready for review

#2371 Store Client IP address and hostName details
  src/auth-service/middleware/passport.js
  src/auth-service/models/log.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2372 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/middleware/passport.js
  src/auth-service/models/log.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2373 capture the client original IP address
  k8s/nginx/staging/global-config.yaml
  src/auth-service/middleware/passport.js
  src/auth-service/models/log.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2375 small correction to the nginx configuration
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#2374 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/middleware/passport.js
  src/auth-service/models/log.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2377 update the nginx configs for dev and prod
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
Labels: ready for review

#2378 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/nginx/development/global-config.yaml
  k8s/nginx/production/global-config.yaml
  k8s/predict/values-prod.yaml
Labels: ready for review

#2376 introducing last login field on User collection
  src/auth-service/bin/cronJob.js
  src/auth-service/bin/server.js
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-user.js
  src/auth-service/models/User.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/utils/control-access.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#2380 also update the isActive for user who has authenticated through JWT
  src/auth-service/middleware/passport.js
Labels: ready for review

#2379 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/bin/cronJob.js
  src/auth-service/bin/server.js
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-user.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/User.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/utils/control-access.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#2382 enhance the logic for the jon which updates the lastLogin of users
  src/auth-service/bin/cronJob.js
Labels: ready for review

#2383 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/bin/cronJob.js
Labels: ready for review

#2384 Modifying Logo for email notifications
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/config/images/airqoLogoAlternate.png
  src/firebase/auth/functions/index.js
Labels: ready for review

#2381 list combination of users and access requests v1
  src/auth-service/controllers/create-user.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
Labels: ready for review

#2386 fixing routing issues
  src/auth-service/routes/v2/users.js
Labels: ready for review

#2365 Spatial join update
  src/predict/jobs/predict_places_air_quality/README.md
  src/predict/jobs/predict_places_air_quality/main.py
Labels: ready for review

#2387 adding isActive and temporarily disabling the cronjob
  src/auth-service/bin/server.js
  src/auth-service/config/constants.js
  src/auth-service/models/User.js
Labels: ready for review

#2385 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  src/auth-service/bin/server.js
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-user.js
  src/auth-service/models/User.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/config/images/airqoLogoAlternate.png
  src/firebase/auth/functions/index.js
  src/predict/jobs/predict_places_air_quality/README.md
  src/predict/jobs/predict_places_air_quality/main.py
Labels: ready for review

#2388 small enhancement around the create group use case
  src/auth-service/utils/create-group.js
Labels: ready for review
