Repository airqo-platform/AirQo-api, pull requests merged in 2023-04, with the labels that each got.

#1441 disable Slack logging for duplicate data entries
  src/device-registry/bin/www
Labels: ready for review

#1443 Ft daily forecasts deployment updates
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/predict/job/values-prod.yaml
  k8s/predict/job/values-stage.yaml
  src/predict/README.md
Labels: enhancement, ready for review

#1444 [Data Export] Adding a limit to exported records
  src/analytics/api/models/events.py
  src/analytics/config.py
Labels: ready for review

#1442 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/predict/job/values-prod.yaml
  k8s/predict/job/values-stage.yaml
  src/analytics/api/models/events.py
  src/analytics/config.py
  src/device-registry/bin/www
  src/predict/README.md
  src/predict/api/Dockerfile
  src/predict/api/app.py
  src/predict/api/config/constants.py
  src/predict/api/config/db_connection.py
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
  src/predict/api/helpers/validation.py
  src/predict/api/models/datamanagement.py
  src/predict/api/models/predict.py
  src/predict/api/models/processing.py
  src/predict/api/requirements.txt
  src/predict/api/requirements/dev.txt
  src/predict/api/requirements/prod.txt
  src/predict/api/routes/api.py
  src/predict/jobs/forecast/.dockerignore
  src/predict/jobs/forecast/.gitignore
  src/predict/jobs/forecast/Dockerfile
  src/predict/jobs/forecast/config.py
  src/predict/jobs/forecast/daily_forecasts.py
  src/predict/jobs/forecast/hourly_forecasts.py
  src/predict/jobs/forecast/models.py
  src/predict/jobs/forecast/requirements.txt
  src/predict/jobs/forecast/transform.py
  src/predict/jobs/forecast/utils.py
  src/predict/jobs/forecast_training/.dockerignore
  src/predict/jobs/forecast_training/.gitignore
  src/predict/jobs/forecast_training/Dockerfile
  src/predict/jobs/forecast_training/config.py
  src/predict/jobs/forecast_training/daily_forecast_training.py
  src/predict/jobs/forecast_training/hourly_forecast_training.py
  src/predict/jobs/forecast_training/models.py
  src/predict/jobs/forecast_training/requirements.txt
  src/predict/jobs/forecast_training/transform.py
  src/predict/jobs/forecast_training/utils.py
  src/predict/jobs/met-forecast.py
  src/predict/jobs/predict/main.py
  src/predict/jobs/predict/requirements.txt
  src/predict/jobs/prediction_job.py
  src/predict/jobs/train/main.py
  src/predict/jobs/train/requirements.txt
  src/predict/jobs/train/transform.py
  src/predict/jobs/training.py
Labels: ready for review

#1445 Running the the microservice using docker & changing server to gunicorn for deployments
  src/predict/api/Dockerfile
  src/predict/api/README.md
  src/predict/api/requirements.txt
Labels: ready for review

#1448 align v2 with v1 of events
  src/device-registry/routes/v2/events-old.js
  src/device-registry/routes/v2/events.js
Labels: ready for review, device-registry

#1447 Modify forecasts to use site_id
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
  src/predict/api/models/predict.py
  src/predict/api/requirements/dev.txt
  src/predict/api/requirements/prod.txt
  src/predict/api/routes/api.py
  src/predict/jobs/forecast/config.py
  src/predict/jobs/forecast/daily_forecasts.py
  src/predict/jobs/forecast/hourly_forecasts.py
  src/predict/jobs/forecast/models.py
  src/predict/jobs/forecast/requirements.txt
  src/predict/jobs/forecast/transform.py
  src/predict/jobs/forecast/utils.py
Labels: work in progress, predict

#1449 move to production
  src/device-registry/routes/v2/events-old.js
  src/device-registry/routes/v2/events.js
  src/predict/api/Dockerfile
  src/predict/api/README.md
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
  src/predict/api/models/predict.py
  src/predict/api/requirements.txt
  src/predict/api/requirements/dev.txt
  src/predict/api/requirements/prod.txt
  src/predict/api/routes/api.py
  src/predict/jobs/forecast/config.py
  src/predict/jobs/forecast/daily_forecasts.py
  src/predict/jobs/forecast/hourly_forecasts.py
  src/predict/jobs/forecast/models.py
  src/predict/jobs/forecast/requirements.txt
  src/predict/jobs/forecast/transform.py
  src/predict/jobs/forecast/utils.py
Labels: ready for review

#1451 move to production
  src/device-registry/controllers/create-event.js
  src/device-registry/routes/v2/events.js
Labels: ready for review

#1452 fixing the pagination caching aspects
  src/device-registry/utils/create-event.js
Labels: ready for review

#1454 Forecast hotfix for accessing BigQuery data
  src/predict/api/helpers/utils.py
  src/predict/jobs/forecast/config.py
  src/predict/jobs/forecast/models.py
  src/predict/jobs/forecast_training/config.py
  src/predict/jobs/forecast_training/daily_forecast_training.py
  src/predict/jobs/forecast_training/models.py
  src/predict/jobs/forecast_training/requirements.txt
  src/predict/jobs/forecast_training/transform.py
Labels: hotfix, ready for review, predict

#1458 adding createdAt and updatedAt to the tool
  src/auth-service/models/User.js
Labels: ready for review

#1459 move to production
  src/auth-service/models/User.js
  src/predict/api/helpers/utils.py
  src/predict/jobs/forecast/config.py
  src/predict/jobs/forecast/models.py
  src/predict/jobs/forecast_training/config.py
  src/predict/jobs/forecast_training/daily_forecast_training.py
  src/predict/jobs/forecast_training/models.py
  src/predict/jobs/forecast_training/requirements.txt
  src/predict/jobs/forecast_training/transform.py
Labels: ready for review

#1425 enhancements, hotfixes and new endpoints for device (events) registry
  src/device-registry/app.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Event.js
  src/device-registry/models/Measurement.js
  src/device-registry/routes/v2/index.js
  src/device-registry/routes/v2/measurements.js
  src/device-registry/utils/common.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-monitor.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/date.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/test/ut_common.js
  src/device-registry/utils/test/ut_create-event.js
  src/device-registry/utils/test/ut_create-site.js
Labels: ready for review, device-registry

#1462 hotfix for returning all running devices
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1463 move to production
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1457 refactor code to address API version issue
  src/gp-model/data/data.py
  src/gp-model/main.py
Labels: hotfix, refactoring

#1464 [Data Export] Resolving internal server issues
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/views/__init__.py
  src/analytics/api/views/dashboard.py
  src/analytics/api/views/data.py
Labels: ready for review

#1470 remove site from recalled device
  src/device-registry/utils/create-activity.js
Labels: ready for review

#1472 add deployment date to details during device deployment
  src/device-registry/utils/create-activity.js
Labels: ready for review

#1473 add the maintenance date to device details during maintenance
  src/device-registry/utils/create-activity.js
Labels: ready for review

#1467 move to production
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/views/__init__.py
  src/analytics/api/views/dashboard.py
  src/analytics/api/views/data.py
  src/device-registry/controllers/create-device.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/generate-filter.js
  src/gp-model/data/data.py
  src/gp-model/main.py
Labels: ready for review

#1468 slight change to the welcome email, adding the user guide
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#1465 [Data Export] Adding AQCSV parameters for raw data
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/utils/pollutants/pm_25.py
Labels: ready for review

#1479 add access tokens on v2
  src/auth-service/app.js
  src/auth-service/routes/v2/tokens.js
Labels: ready for review, auth-service

#1478 move to production
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/utils/pollutants/pm_25.py
  src/auth-service/app.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/utils/email.msgs.js
  src/gp-model/data/data.py
Labels: ready for review

#1481 ability to query KCCA devices individually
  src/device-registry/models/Device.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1475 Excluding BAM devices from uptime
  src/device-uptime/device_uptime.py
Labels: ready for review

#1482 move to production
  src/device-registry/models/Device.js
  src/device-registry/utils/generate-filter.js
  src/device-uptime/device_uptime.py
Labels: ready for review

#1480 Fix forecast endpoint routes to match ingress.yml
  src/predict/api/routes/api.py
Labels: ready for review, predict

#1483 store previous sites after recall activity
  src/device-registry/models/Device.js
  src/device-registry/utils/create-activity.js
Labels: enhancement, ready for review, device-registry

#1484 move to production
  src/device-registry/models/Device.js
  src/device-registry/utils/create-activity.js
  src/predict/api/routes/api.py
Labels: ready for review

#1485 ensure any device's long name is also unique
  src/device-registry/models/Device.js
Labels: ready for review

#1486 move to production
  src/device-registry/models/Device.js
Labels: ready for review

#1493 fixing issues around the access control use case
  src/auth-service/controllers/create-role.js
  src/auth-service/models/Role.js
  src/auth-service/routes/v1/roles.js
  src/auth-service/routes/v2/roles.js
Labels: ready for review, auth-service

#1496 more hotfixes for access control use case
  src/auth-service/routes/v2/users.js
Labels: ready for review

#1491 move to production
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-role.js
  src/auth-service/controllers/create-user.js
  src/auth-service/models/AccessToken.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/Client.js
  src/auth-service/models/Department.js
  src/auth-service/models/Group.js
  src/auth-service/models/Inquiry.js
  src/auth-service/models/Network.js
  src/auth-service/models/Permission.js
  src/auth-service/models/Role.js
  src/auth-service/models/Scope.js
  src/auth-service/models/User.js
  src/auth-service/routes/v1/roles.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/routes/v2/users.js
Labels: ready for review

#1499 more hotfixes in auth-service
  src/auth-service/controllers/create-user.js
  src/auth-service/models/Permission.js
  src/auth-service/models/Role.js
  src/auth-service/routes/v1/permissions.js
  src/auth-service/routes/v1/roles.js
  src/auth-service/routes/v2/permissions.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#1500 move to production
  src/auth-service/controllers/create-user.js
  src/auth-service/models/Permission.js
  src/auth-service/models/Role.js
  src/auth-service/routes/v1/permissions.js
  src/auth-service/routes/v1/roles.js
  src/auth-service/routes/v2/permissions.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#1501 align response message with entity logic
  src/auth-service/models/Role.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#1502 move to production
  src/auth-service/models/Role.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#1503 updating the bulk script
  src/device-registry/utils/bulk-script.js
Labels: ready for review, device-registry

#1505 [AirQlouds] Automating refresh functionality
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/dags/meta_data.py
Labels: ready for review

#1507 Delete update_latest_data_table task
  src/airflow/dags/airqo_measurements.py
Labels: ready for review

#1510 remove role_users users list and also return most recent roles
  src/auth-service/models/Role.js
  src/auth-service/models/User.js
Labels: ready for review

#1512 More Hotfixes for auth-service
  src/auth-service/models/Role.js
  src/auth-service/routes/v1/roles.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/mailer.js
Labels: ready for review, auth-service

#1511 move to production
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/meta_data_utils.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/meta_data.py
  src/analytics/api/models/events.py
  src/auth-service/models/Role.js
  src/auth-service/models/User.js
  src/auth-service/routes/v1/roles.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#1513 More Hotfixes for the auth service
  src/auth-service/models/Role.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#1514 move to production
  src/auth-service/models/Role.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#1515 fix forgot password
  src/auth-service/controllers/create-user.js
  src/auth-service/utils/create-user.js
Labels: ready for review

#1516 move to production
  src/auth-service/controllers/create-user.js
  src/auth-service/utils/create-user.js
Labels: ready for review

#1517 hotfix for logging user activity
  src/auth-service/models/log.js
Labels: ready for review

#1518 move to production
  src/auth-service/models/log.js
Labels: ready for review
