Repository airqo-platform/AirQo-api, pull requests merged in 2023-01, with the labels that each got.

#1240 Disabling usage of the API to store measurements.
  src/airflow/airqo_etl_utils/airqo_api.py
Labels: ready for review

#1241 fix runtime error on feedback endpoint
  src/auth-service/services/mailer.js
Labels: ready for review

#1244 [Data Pipelines] - Deleted old DAGs
  src/airflow/airqo_etl_utils/app_insights_utils.py
  src/airflow/dags/app_insights.py
  src/airflow/main.py
  src/airflow/schedule-dag.py
Labels: ready for review

#1246 Address issues around missing metadata
  src/meta-data/README.md
  src/meta-data/airqo_api.py
  src/meta-data/message-broker.py
Labels: ready for review

#1185 Add a more robust logging mechanism to the auth service.
  src/auth-service/.gitignore
  src/auth-service/app.js
  src/auth-service/bin/www
  src/auth-service/config/constants.js
  src/auth-service/config/firebase-admin.js
  src/auth-service/config/log4js.js
  src/auth-service/controllers/create-organization.js
  src/auth-service/controllers/defaults.js
  src/auth-service/controllers/inquire.js
  src/auth-service/controllers/join.js
  src/auth-service/controllers/request.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/services/auth.js
  src/auth-service/services/mailer.js
  src/auth-service/utils/addList.js
  src/auth-service/utils/create-organization.js
  src/auth-service/utils/defaults.js
  src/auth-service/utils/errors.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/generate-password.js
  src/auth-service/utils/inquire.js
  src/auth-service/utils/join.js
  src/auth-service/utils/multitenancy.js
  src/auth-service/utils/request.js
  src/auth-service/utils/sendEmail.js
  src/auth-service/utils/settings.js
  src/auth-service/utils/validations.js
Labels: enhancement, ready for review, auth-service

#1201 Ft update ansible IaC
  infra/ansible/README.md
  infra/ansible/development/Vagrantfile
  infra/ansible/development/extension/.gitkeep
  infra/ansible/development/group-vars/.gitkeep
  infra/ansible/development/plays/master.yml
  infra/ansible/development/plays/worker.yml
  infra/ansible/development/roles/.gitkeep
  infra/ansible/playbooks/initial.yml
  infra/ansible/playbooks/kube-dependencies.yml
  infra/ansible/playbooks/master.yml
  infra/ansible/playbooks/workers.yml
  infra/ansible/production/extension/setup/.gitkeep
  infra/ansible/production/extension/setup/hosts
  infra/ansible/production/extension/setup/initial.yml
  infra/ansible/production/extension/setup/kube-dependencies.yml
  infra/ansible/production/extension/setup/master.yml
  infra/ansible/production/extension/setup/workers.yml
  infra/ansible/production/group-vars/mysql/.gitkeep
  infra/ansible/production/plays/ansible.cfg
  infra/ansible/production/roles/external/.gitkeep
  infra/ansible/production/roles/internal/.gitkeep
  infra/ansible/setup/etc/ansible.cfg
  infra/ansible/setup/etc/hosts
  infra/ansible/setup/etc/roles/.gitkeep
  infra/ansible/setup/gcp.yaml
  infra/ansible/staging/group-vars/mysql/.gitkeep
  infra/ansible/staging/plays/ansible.cfg
  infra/ansible/staging/roles/external/.gitkeep
  infra/ansible/staging/roles/internal/.gitkeep
  infra/ansible/staging/setup/.gitkeep
  infra/ansible/staging/setup/hosts
  infra/ansible/staging/setup/initial.yml
  infra/terraform/gcp/modules/ComputeDisk/ansible-controller.tf
  infra/terraform/gcp/modules/ComputeInstance/ansible-controller.tf
Labels: enhancement, ready for review, devops

#1245 Re-streaming US Embassies data
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/message_broker_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/docker-compose.yaml
  src/airflow/main.py
Labels: ready for review

#1253 hotfixes for auth-service
  src/auth-service/controllers/join.js
  src/auth-service/services/mailer.js
Labels: work in progress, auth-service

#1238 different content for different inquiry emails
  src/auth-service/services/mailer.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/inquire.js
Labels: ready for review, auth-service

#1256 Triggering airflow ,analytics and meta data
  src/airflow/README.md
  src/analytics/README.md
  src/meta-data/README.md
Labels: ready for review

#1249 [VIEW API] maintenance works
  src/view/README.md
  src/view/pom.xml
  src/view/src/main/java/airqo/models/Frequency.java
Labels: work in progress, ready for review

#1243 add new fields for Site --- "short_link" and "images"
  src/device-registry/models/Site.js
Labels: ready for review, device-registry

#1259 [View api] cleanup
  src/view/pom.xml
  src/view/src/main/java/airqo/models/Insight.java
  src/view/src/main/java/airqo/repository/BaseRepository.java
Labels: ready for review

#1252 Fixes the analytics automated report job deploy error
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
Labels: bug, hotfix, ready for review

#1260 fixing a runtime error
  src/auth-service/controllers/join.js
Labels: ready for review, auth-service

#1248 hotfixes for device registry
  src/device-registry/.gitignore
  src/device-registry/app.js
  src/device-registry/config/constants.js
  src/device-registry/models/Device.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
Labels: ready for review, device-registry

#1261 make the auth service logger messages more descriptive
  src/auth-service/app.js
Labels: ready for review, auth-service

#1258 move to production
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/airflow/README.md
  src/analytics/README.md
  src/auth-service/app.js
  src/auth-service/controllers/join.js
  src/device-registry/.gitignore
  src/device-registry/app.js
  src/device-registry/config/constants.js
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/meta-data/README.md
  src/view/README.md
  src/view/pom.xml
  src/view/src/main/java/airqo/models/Frequency.java
  src/view/src/main/java/airqo/models/Insight.java
  src/view/src/main/java/airqo/repository/BaseRepository.java
Labels: work in progress, ready for review

#1262 make the log message for non existent endpoint more descriptive
  src/device-registry/app.js
Labels: ready for review

#1264 make the log message for non existent endpoint more descriptive
  src/auth-service/app.js
Labels: ready for review, auth-service

#1263 move to production
  src/auth-service/app.js
  src/device-registry/app.js
Labels: ready for review

#1265 change the email response for general email inquiries accordingly
  src/auth-service/services/mailer.js
Labels: ready for review

#1266 move to production
  src/auth-service/services/mailer.js
Labels: ready for review

#1267 remove trailing comma
  src/auth-service/utils/email.templates.js
Labels: ready for review

#1268 move to production
  src/auth-service/utils/email.templates.js
Labels: ready for review

#1272 Saving US Embassy data via API
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/airqo_utils.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/main.py
Labels: ready for review

#1273 use the correct images as with cicd
  k8s/airflow/airflow-app.yaml
  k8s/airflow/stage-airflow-app.yaml
Labels: hotfix, ready for review, devops

#1278 few hotfixes to the authentication service
  src/auth-service/app.js
  src/auth-service/config/admin.js
  src/auth-service/config/multiTenant.js
  src/auth-service/config/storage.js
  src/auth-service/controllers/create-default.js
  src/auth-service/controllers/create-group.js
  src/auth-service/controllers/create-inquiry.js
  src/auth-service/controllers/create-network.js
  src/auth-service/controllers/create-scope.js
  src/auth-service/controllers/create-token.js
  src/auth-service/controllers/create-user.js
  src/auth-service/controllers/request-access.js
  src/auth-service/middleware/can-access.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/Defaults.js
  src/auth-service/models/Department.js
  src/auth-service/models/Group.js
  src/auth-service/models/Network.js
  src/auth-service/models/Role.js
  src/auth-service/models/Settings.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/prisma/schema.prisma
  src/auth-service/public/stylesheets/style.css
  src/auth-service/routes/v1/departments.js
  src/auth-service/routes/v1/groups.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-default.js
  src/auth-service/utils/create-network.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/errors.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review, auth-service

#1281 hotfixing issue around candidates endpoints
  src/auth-service/app.js
Labels: ready for review, auth-service

#1282 move to production
  src/auth-service/app.js
Labels: ready for review

#1283 resolving a runtime for candidate creation
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-user.js
  src/auth-service/models/Candidate.js
  src/auth-service/routes/v1/requests.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#1285 just another small validation hotfix
  src/auth-service/routes/v1/requests.js
Labels: ready for review

#1286 move to production
  src/auth-service/routes/v1/requests.js
Labels: ready for review

#1288 move to production
  src/auth-service/models/User.js
Labels: ready for review
