Repository airqo-platform/AirQo-api, pull requests merged in 2023-05, with the labels that each got.

#1524 [Analytics] v2 endpoints
  src/analytics/api/utils/pre_request.py
  src/analytics/api/views/dashboard.py
  src/analytics/api/views/data.py
  src/analytics/api/views/report.py
  src/analytics/config.py
  src/analytics/main.py
Labels: ready for review

#1506 Add healthtips to forecasts
  src/predict/api/Dockerfile
  src/predict/api/models/predict.py
  src/predict/jobs/forecast/Dockerfile
  src/predict/jobs/forecast/config.py
  src/predict/jobs/forecast/daily_forecasts.py
  src/predict/jobs/forecast/models.py
Labels: ready for review, predict

#1492 Add Design to welcome Email messages
  src/firebase/auth/config/emailTemplates.js
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/config/images/airqoLogo.png
  src/firebase/auth/functions/config/images/welcomeImage.png
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
Labels: ready for review

#1488 hotfixes for querying events
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Photo.js
  src/device-registry/routes/v1/devices.js
  src/device-registry/routes/v2/devices.js
  src/device-registry/routes/v2/photos.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: hotfix, ready for review, device-registry

#1521 Auto k8s worker disk cleanup
  infra/ansible/cleanup_k8s_workers_disks.yml
  infra/ansible/roles/k8s/templates/disk_cleanup.sh.j2
Labels: ready for review, devops

#1528 the site summary endpoint
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Site.js
  src/device-registry/routes/v1/sites.js
  src/device-registry/routes/v2/sites.js
Labels: ready for review

#1529 move to production
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Site.js
  src/device-registry/routes/v1/sites.js
  src/device-registry/routes/v2/sites.js
Labels: ready for review

#1532 bringing back the longitude and latitude
  src/device-registry/models/Airqloud.js
Labels: ready for review

#1033 🚫 DO NOT REVIEW OR LOOK AT THIS 🚫
  src/device-registry/models/Airqloud.js
Labels: invalid

#1530 Hotfixes for the auth service
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-network.js
  src/auth-service/controllers/create-role.js
  src/auth-service/middleware/can-access.js
  src/auth-service/models/Network.js
  src/auth-service/models/Permission.js
  src/auth-service/models/Role.js
  src/auth-service/models/User.js
  src/auth-service/routes/v1/networks.js
  src/auth-service/routes/v1/roles.js
  src/auth-service/routes/v2/networks.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-network.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review, auth-service

#1540 Device Registry Hotfixes
  src/device-registry/config/constants.js
Labels: ready for review, device-registry

#1541 auth service hotfixes
  src/auth-service/controllers/create-role.js
  src/auth-service/controllers/create-user.js
  src/auth-service/controllers/request-access.js
  src/auth-service/routes/v1/roles.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/request-access.js
Labels: ready for review, auth-service

#1525 Implementing Platform Email designs.
  src/auth-service/config/images/Twitter.png
  src/auth-service/config/images/airqoLogo.png
  src/auth-service/config/images/facebookLogo.png
  src/auth-service/config/images/linkedInLogo.png
  src/auth-service/config/images/youtubeLogo.png
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/config/images/Twitter.png
  src/firebase/auth/functions/config/images/facebookLogo.png
  src/firebase/auth/functions/config/images/linkedInLogo.png
  src/firebase/auth/functions/config/images/youtubeLogo.png
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
  src/firebase/auth/functions/package.json
Labels: ready for review

#1542 handle all duplicate request values when updating role permissions
  src/auth-service/utils/control-access.js
Labels: ready for review, auth-service

#1544 Add status, permissions(id and name) to role summary
  src/auth-service/config/constants.js
Labels: ready for review, auth-service

#1497 Collocation logic and V2 APIs
  src/device-monitoring/Dockerfile
  src/device-monitoring/app.py
  src/device-monitoring/config/constants.py
  src/device-monitoring/config/db_connection.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/helpers/convert_dates.py
  src/device-monitoring/helpers/exceptions.py
  src/device-monitoring/helpers/pre_request.py
  src/device-monitoring/helpers/utils.py
  src/device-monitoring/models.py
  src/device-monitoring/routes.py
Labels: ready for review

#1550 Collocation hotfixes
  src/device-monitoring/app.py
  src/device-monitoring/config/db_connection.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/models.py
Labels: ready for review

#1551 fix running device list
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Event.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#1552 move to production
  src/device-monitoring/Dockerfile
  src/device-monitoring/app.py
  src/device-monitoring/config/constants.py
  src/device-monitoring/config/db_connection.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/helpers/convert_dates.py
  src/device-monitoring/helpers/exceptions.py
  src/device-monitoring/helpers/pre_request.py
  src/device-monitoring/helpers/utils.py
  src/device-monitoring/models.py
  src/device-monitoring/routes.py
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Event.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#1553 move to production
  src/auth-service/controllers/create-network.js
  src/auth-service/models/User.js
  src/auth-service/routes/v1/networks.js
  src/auth-service/routes/v2/networks.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#1522 New DAG for airnow
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/message_broker_utils.py
  src/airflow/dags/airnow.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/main.py
Labels: ready for review

#1556 Collocation hotfixes
  src/device-monitoring/app.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/routes.py
Labels: ready for review

#1554 auth service hotfixes
  src/auth-service/app.js
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-role.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/Network.js
  src/auth-service/routes/v1/roles.js
  src/auth-service/routes/v1/tokens.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/log.js
Labels: ready for review, auth-service

#1558 Collocation hotfixes
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
Labels: ready for review

#1557 move to production
  src/airflow/airqo_etl_utils/airnow_api.py
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/airqo_api.py
  src/airflow/airqo_etl_utils/config.py
  src/airflow/airqo_etl_utils/data_validator.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/message_broker_utils.py
  src/airflow/dags/airnow.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/main.py
  src/auth-service/app.js
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-role.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/Network.js
  src/auth-service/routes/v1/roles.js
  src/auth-service/routes/v1/tokens.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/log.js
  src/device-monitoring/app.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/routes.py
  src/predict/jobs/forecast/daily_forecasts.py
Labels: ready for review

#1559 Changing collocation data output format
  src/device-monitoring/helpers/collocation.py
Labels: ready for review

#1560 logging the Google profile
  src/auth-service/middleware/passport.js
Labels: ready for review

#1561 move to production
  src/auth-service/middleware/passport.js
  src/device-monitoring/helpers/collocation.py
Labels: ready for review

#1563 move to production
  src/airflow/airqo_etl_utils/airnow_utils.py
  src/airflow/airqo_etl_utils/daily_data_utils.py
  src/airflow/airqo_etl_utils/data_warehouse_utils.py
  src/airflow/airqo_etl_utils/forecast_data_utils.py
  src/airflow/airqo_etl_utils/kcca_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/data_warehouse.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/main.py
Labels: ready for review

#1566 [HOTFIX] Fixing streaming of historical data
  src/airflow/airqo_etl_utils/date.py
Labels: ready for review

#1568 Hotfixes for auth service
  src/auth-service/models/Network.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#1569 move to production
  src/airflow/airqo_etl_utils/date.py
  src/auth-service/models/Network.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#1535 searching for nearest predictions using geo coordinates
  src/gp-model/config.py
  src/gp-model/main.py
  src/gp-model/requirements.txt
  src/predict/api/app.py
  src/predict/api/config/constants.py
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
  src/predict/api/requirements.txt
  src/predict/api/routes/api.py
Labels: ready for review

#1571 [HOTFIX] Fixing the start date and end time values for parameters to only cater for Historical tasks
  src/airflow/airqo_etl_utils/date.py
  src/airflow/airqo_etl_utils/utils.py
  src/airflow/dags/airnow.py
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/daily_measurements.py
  src/airflow/dags/kcca_measurements.py
  src/airflow/dags/nasa_measurements.py
  src/airflow/dags/urban_better_measurements.py
  src/airflow/dags/weather_measurements.py
Labels: ready for review

#1570 auth service hotfixes
  src/auth-service/controllers/create-network.js
  src/auth-service/controllers/create-role.js
  src/auth-service/models/Network.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/v1/networks.js
  src/auth-service/routes/v2/networks.js
  src/auth-service/utils/bulk-script.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-network.js
Labels: ready for review, auth-service

#1573 move to production
  src/auth-service/controllers/create-network.js
  src/auth-service/controllers/create-role.js
  src/auth-service/models/Network.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/v1/networks.js
  src/auth-service/routes/v2/networks.js
  src/auth-service/utils/bulk-script.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#1574 resolve the joined date for available users
  src/auth-service/config/constants.js
Labels: auth-service

#1578 move to production
  src/device-registry/routes/v1/devices.js
  src/device-registry/routes/v2/devices.js
Labels: ready for review

#1576 Adding health tips to air quality search API.
  src/predict/api/config/constants.py
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
Labels: ready for review

#1580 fix the joined date for available network users
  src/auth-service/utils/create-network.js
Labels: ready for review

#1581 move to production
  src/auth-service/utils/create-network.js
  src/predict/api/config/constants.py
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
Labels: ready for review

#1585 move to production
  src/auth-service/utils/create-network.js
Labels: ready for review

#1586 refactor assignment of users to networks
  src/auth-service/controllers/create-network.js
  src/auth-service/models/Network.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#1587 move to production
  src/auth-service/controllers/create-network.js
  src/auth-service/models/Network.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#1588 enhancing network creation logic
  src/auth-service/config/constants.js
  src/auth-service/models/Network.js
  src/auth-service/models/User.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#1589 move to production
  src/auth-service/config/constants.js
  src/auth-service/models/Network.js
  src/auth-service/models/User.js
  src/auth-service/utils/create-network.js
Labels: ready for review

#1590 fixing runtime for constants
  src/auth-service/config/constants.js
Labels: ready for review

#1593 Hotfix auth service
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-network.js
  src/auth-service/controllers/create-user.js
  src/auth-service/models/Client.js
  src/auth-service/models/Network.js
  src/auth-service/models/Permission.js
  src/auth-service/models/User.js
  src/auth-service/routes/v1/permissions.js
  src/auth-service/routes/v1/roles.js
  src/auth-service/routes/v1/tokens.js
  src/auth-service/routes/v2/permissions.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-network.js
Labels: ready for review, auth-service

#1318 [NETWORK UPTIME] Approach one
  src/device-monitoring/app.py
  src/device-monitoring/config/constants.py
  src/device-monitoring/controllers/uptime_controller.py
  src/device-monitoring/final_uptime_calc.ipynb
  src/device-monitoring/helpers/http.py
  src/device-monitoring/helpers/request_validators.py
  src/device-monitoring/helpers/uptime.py
  src/device-monitoring/playground.py
  src/device-monitoring/routes.py
Labels: ready for review

#1599 hotfix for assigning users to networks
  src/auth-service/utils/create-network.js
Labels: hotfix, ready for review, auth-service

#1600 user is not allowed to create device on Thingspeak incase they are in testing ENVs
  src/device-registry/utils/create-device.js
Labels: ready for review

#1342 [GP MODEL] integrating kafka
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/gp-model/Chart.yaml
  k8s/gp-model/templates/cronjob.yaml
  k8s/gp-model/templates/deployment.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  src/gp-model/.gitignore
  src/gp-model/Dockerfile
  src/gp-model/config.py
  src/gp-model/data/data.py
  src/gp-model/main.py
  src/gp-model/message-broker.py
  src/gp-model/requirements.txt
Labels: ready for review

#1604 Deployment/argocd updates
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/airflow/values-stage.yaml
  k8s/analytics/api/templates/deployment.yaml
  k8s/analytics/api/values-prod.yaml
  k8s/analytics/api/values-stage.yaml
  k8s/analytics/job/values-stage.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-stage.yaml
  k8s/channel-data/values-stage.yaml
  k8s/data-mgt/values-stage.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/values-stage.yaml
  k8s/exceedance/values-stage-airqo.yaml
  k8s/exceedance/values-stage-kcca.yaml
  k8s/fault-detection/values-stage.yaml
  k8s/gp-model/Chart.yaml
  k8s/gp-model/templates/_helpers.tpl
  k8s/gp-model/templates/cronjob.yaml
  k8s/gp-model/templates/deployment.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/meta-data/values-stage.yaml
  k8s/network-uptime/values-stage.yaml
  k8s/predict/job/values-stage.yaml
  k8s/predict/train-job/values-stage.yaml
  k8s/view/api/values-stage.yaml
  k8s/view/message-broker/values-stage.yaml
Labels: ready for review

#1607 add the v2 versions for the airqloud summary and dashboard endpoints
  src/device-registry/routes/v2/airqlouds.js
Labels: ready for review
