Repository airqo-platform/AirQo-api, pull requests merged in 2023-06, with the labels that each got.

#1610 quick fix to import issue
  src/gp-model/main.py
Labels: ready for review, priority-high

#1612 resolve runtime for fetching user defaults
  src/auth-service/models/Defaults.js
Labels: ready for review, auth-service

#1611 move to production
  src/auth-service/models/Defaults.js
  src/gp-model/main.py
Labels: ready for review

#1609 Adding v2 to meta data APIs
  .github/workflows/deploy-previews.yml
  src/meta-data/Dockerfile
  src/meta-data/api/controllers/extract.py
  src/meta-data/api/routes/api.py
  src/meta-data/app.py
  src/meta-data/config.py
  src/meta-data/docker-compose.yml
  src/meta-data/message-broker.py
Labels: ready for review

#1617 Ft gp model sa
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/gp-model/templates/cronjob.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
Labels: ready for review

#1616 Adding an endpoint to log collocation collection
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
Labels: ready for review

#1614 Adding errors field to collocation results.
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/models.py
Labels: ready for review

#1608 upgrade mongos backup disk size
  infra/terraform/gcp/modules/ComputeDisk/mongos-router-0.tf
  infra/terraform/gcp/modules/ComputeInstance/mongos-router-0.tf
Labels: ready for review

#1621 Disable Device updates in staging and enhance KAFKA logging
  src/device-registry/bin/www
  src/device-registry/utils/create-device.js
Labels: ready for review, device-registry

#1625 hotfixes for device creation
  src/device-registry/models/Device.js
Labels: ready for review, device-registry

#1631 Multiple hotfixes for auth-service
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-user.js
  src/auth-service/controllers/request-access.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/User.js
  src/auth-service/routes/v1/requests.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/requests.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/request-access.js
Labels: ready for review, auth-service

#1632 move to production
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-user.js
  src/auth-service/controllers/request-access.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/User.js
  src/auth-service/routes/v1/requests.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/requests.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/request-access.js
Labels: ready for review, auth-service

#1638 re-introducing #1631
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-user.js
  src/auth-service/controllers/request-access.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/User.js
  src/auth-service/routes/v1/requests.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/requests.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/request-access.js
Labels: ready for review

#1494 Create functionality for deleting Mobile user details
  src/auth-service/config/firebase-admin.js
  src/auth-service/controllers/create-user.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/index.js
Labels: ready for review

#1643 move to production
  src/auth-service/config/firebase-admin.js
  src/auth-service/controllers/create-user.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/index.js
Labels: ready for review

#1567 Hotfixes for Gmail login endpoint
  src/auth-service/app.js
  src/auth-service/bin/www
  src/auth-service/config/constants.js
  src/auth-service/config/dao.js
  src/auth-service/config/middleware.js
  src/auth-service/controllers/create-user.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/AccessToken.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/bulk-script.js
  src/auth-service/utils/control-access.js
Labels: ready for review, auth-service

#1647 move to production
  src/auth-service/app.js
  src/auth-service/bin/www
  src/auth-service/config/constants.js
  src/auth-service/config/dao.js
  src/auth-service/config/middleware.js
  src/auth-service/controllers/create-user.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/AccessToken.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/bulk-script.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#1648 create alias during device creation
  src/device-registry/models/Device.js
Labels: hotfix, device-registry

#1649 move to production
  src/device-registry/models/Device.js
Labels: ready for review

#1650 automatically generate site_codes and device_codes after creations
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
Labels: ready for review

#1651 move to production
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
Labels: ready for review

#1652 Fix cicd auto sync
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/device-uptime/README.md
Labels: ready for review

#1654 fixing User confirmation issues
  src/auth-service/models/Candidate.js
  src/auth-service/utils/request-access.js
Labels: ready for review

#1653 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/device-uptime/values-stage.yaml
  src/auth-service/models/Candidate.js
  src/auth-service/utils/request-access.js
  src/device-uptime/README.md
Labels: ready for review

#1656 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  src/auth-service/models/Candidate.js
  src/auth-service/utils/request-access.js
Labels: ready for review

#1658 migrates all changes from deployment/argocd to staging
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/calibrate/values-stage.yaml
  k8s/channel-data/values-prod.yaml
  k8s/channel-data/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-mgt/values-stage.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/device-uptime/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/exceedance/values-stage-airqo.yaml
  k8s/exceedance/values-stage-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/fault-detection/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/meta-data/values-prod.yaml
  k8s/meta-data/values-stage.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/api/values-stage.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/job/values-stage.yaml
  k8s/predict/train-job/values-prod.yaml
  k8s/view/api/values-prod.yaml
  k8s/view/api/values-stage.yaml
  k8s/view/message-broker/values-prod.yaml
  k8s/view/message-broker/values-stage.yaml
  src/device-uptime/README.md
Labels: ready for review

#1664 Heatmap endpoint updates
  src/predict/api/config/constants.py
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
  src/predict/api/models/__init__.py
  src/predict/api/models/predict.py
Labels: ready for review, predict

#1662 move to production
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/calibrate/values-stage.yaml
  k8s/channel-data/values-prod.yaml
  k8s/channel-data/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-mgt/values-stage.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/device-uptime/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/exceedance/values-stage-airqo.yaml
  k8s/exceedance/values-stage-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/fault-detection/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/meta-data/values-prod.yaml
  k8s/meta-data/values-stage.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/api/values-stage.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/job/values-stage.yaml
  k8s/predict/train-job/values-prod.yaml
  k8s/predict/train-job/values-stage.yaml
  k8s/view/api/values-prod.yaml
  k8s/view/api/values-stage.yaml
  k8s/view/message-broker/values-prod.yaml
  k8s/view/message-broker/values-stage.yaml
  src/device-uptime/README.md
  src/predict/api/config/constants.py
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
  src/predict/api/models/__init__.py
  src/predict/api/models/predict.py
Labels: ready for review

#1627 Add task for restreaming data to the API
  src/airflow/dags/airnow.py
  src/airflow/dags/airqo_measurements.py
Labels: ready for review

#1666 Returning saved data summaries
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/views/data.py
Labels: ready for review

#1668 Uptime APIs
  src/device-monitoring/config/constants.py
  src/device-monitoring/controllers/uptime_controller.py
  src/device-monitoring/helpers/uptime.py
Labels: ready for review

#1671 add more details to the list of assigned users
  src/auth-service/utils/create-network.js
Labels: ready for review

#1672 move to production
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/train-job/values-prod.yaml
  k8s/view/api/values-prod.yaml
  k8s/view/message-broker/values-prod.yaml
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/views/data.py
  src/auth-service/utils/create-network.js
  src/device-monitoring/config/constants.py
  src/device-monitoring/controllers/uptime_controller.py
  src/device-monitoring/helpers/uptime.py
Labels: ready for review

#1674 Heatmap endpoint optimisation
  src/predict/api/config/constants.py
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
  src/predict/api/requirements.txt
Labels: ready for review, predict

#1675 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/train-job/values-prod.yaml
  k8s/view/api/values-prod.yaml
  k8s/view/message-broker/values-prod.yaml
  src/predict/api/config/constants.py
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
  src/predict/api/requirements.txt
Labels: ready for review

#1673 Use Case: Manage a User's Favourite Places
  src/auth-service/app.js
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-favorite.js
  src/auth-service/models/Favorite.js
  src/auth-service/routes/v1/favorites.js
  src/auth-service/routes/v1/index.js
  src/auth-service/routes/v2/favorites.js
  src/auth-service/routes/v2/index.js
  src/auth-service/utils/create-favorite.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review, auth-service

#1692 just correcting the AQI index ranges
  src/device-registry/models/Event.js
Labels: device-registry

#1694 correcting the aqi_color_name ranges
  src/device-registry/models/Event.js
Labels: ready for review

#1695 move to production
  k8s/device-registry/values-prod.yaml
  src/device-registry/models/Event.js
Labels: ready for review

#1698 move to production
  k8s/analytics/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  src/analytics/api/models/events.py
  src/auth-service/README.md
Labels: ready for review

#1700 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  src/device-registry/package.json
Labels: ready for review

#1701 explicitly add the NODE_ENV to the Dockerfile when running in production
  src/auth-service/package.json
Labels: ready for review

#1678 Use Case: Manage “Know Your Air” Lessons
  src/device-registry/app.js
  src/device-registry/config/constants.js
  src/device-registry/config/database.js
  src/device-registry/config/database.old.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Event.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/Measurement.js
  src/device-registry/models/test/ut_site.js
  src/device-registry/routes/v1/index.js
  src/device-registry/routes/v1/kya.js
  src/device-registry/routes/v2/index.js
  src/device-registry/routes/v2/kya.js
  src/device-registry/utils/common.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-monitor.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/multitenancy.js
Labels: ready for review, device-registry

#1685 Configuring external access to kafka via a controller IP
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/kafka/clusters/kafka-cluster.yaml
  k8s/kafka/operator/deployment-script.sh
Labels: ready for review

#1706 Compute historical data summary
  src/analytics/devices_summary.py
Labels: ready for review

#1709 just handling a possible runtime?
  src/device-registry/models/Device.js
  src/device-registry/utils/create-device.js
Labels: ready for review

#1704 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/kafka/clusters/kafka-cluster.yaml
  k8s/kafka/operator/deployment-script.sh
  src/analytics/devices_summary.py
  src/device-registry/app.js
  src/device-registry/config/constants.js
  src/device-registry/config/database.js
  src/device-registry/config/database.old.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/Measurement.js
  src/device-registry/models/test/ut_site.js
  src/device-registry/routes/v1/index.js
  src/device-registry/routes/v1/kya.js
  src/device-registry/routes/v2/index.js
  src/device-registry/routes/v2/kya.js
  src/device-registry/utils/common.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-monitor.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/multitenancy.js
Labels: ready for review, auth-service

#1712 Fix Consolidated data pipeline
  src/airflow/dags/data_warehouse.py
Labels: ready for review

#1713 changing schema configurations for Devices
  src/device-registry/models/Device.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-know-your-air.js
Labels: ready for review

#1707 Data Export scheduling - enhancements.
  src/analytics/api/models/data_export.py
  src/analytics/api/views/data.py
  src/analytics/celery_app.py
Labels: ready for review

#1705 Hourly Intra sensor data
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/models.py
Labels: ready for review

#1715 address index related runtime issues
  src/device-registry/models/Device.js
Labels: ready for review

#1703 Heatmap feedback fixes
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
Labels: ready for review, predict

#1716 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/models.py
  src/device-registry/models/Device.js
Labels: ready for review

#1708 Daily Forecast endpoint updates
  src/predict/api/helpers/utils.py
  src/predict/jobs/forecast/.dockerignore
  src/predict/jobs/forecast/config.py
  src/predict/jobs/forecast/daily_forecasts.py
  src/predict/jobs/forecast/models.py
  src/predict/jobs/forecast/requirements.txt
Labels: ready for review, predict

#1717 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/api/values-stage.yaml
  k8s/predict/job/values-stage.yaml
  k8s/predict/train-job/values-stage.yaml
  src/predict/api/controllers/prediction.py
  src/predict/api/helpers/utils.py
  src/predict/jobs/forecast/.dockerignore
  src/predict/jobs/forecast/config.py
  src/predict/jobs/forecast/daily_forecasts.py
  src/predict/jobs/forecast/models.py
  src/predict/jobs/forecast/requirements.txt
Labels: ready for review

#1718 Hotfix - data export
  src/analytics/celery_app.py
Labels: ready for review

#1719 Forecast Job Hotfix
  src/predict/jobs/forecast/daily_forecasts.py
Labels: ready for review, predict

#1722 Fix query syntax
  src/predict/jobs/forecast/models.py
Labels: ready for review, predict

#1724 only return measurements for deployed devices
  src/device-registry/controllers/create-event.js
  src/device-registry/routes/v1/devices.js
Labels: ready for review, device-registry

#1725 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/api/values-stage.yaml
  k8s/predict/job/values-stage.yaml
  k8s/predict/train-job/values-stage.yaml
  src/device-registry/controllers/create-event.js
  src/device-registry/routes/v1/devices.js
Labels: ready for review

#1730 just trimming the device name during creation process
  src/device-registry/routes/v1/devices.js
Labels: ready for review

#1731 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/train-job/values-prod.yaml
  src/device-registry/routes/v1/devices.js
Labels: ready for review

#1732 hotfix for retrieving user activity logs
  src/auth-service/utils/create-user.js
  src/auth-service/utils/date.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#1733 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/train-job/values-prod.yaml
  src/auth-service/utils/create-user.js
  src/auth-service/utils/date.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#1734 remove measurements where pm2_5 is null
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1735 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/train-job/values-prod.yaml
  src/device-registry/controllers/create-event.js
Labels: ready for review, device-registry

#1737 quick device-registry fix
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1738 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/train-job/values-prod.yaml
  src/device-registry/controllers/create-event.js
Labels: ready for review

#1745 Collocation results sorting and error messages
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/models.py
Labels: ready for review

#1545 Implementing Email design improvements.
  src/auth-service/config/images/airqoLogo.png
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
  src/firebase/auth/functions/config/emailTemplate.html
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/config/images/Twitter.png
  src/firebase/auth/functions/config/images/airqoLogo.png
  src/firebase/auth/functions/config/images/facebookLogo.png
  src/firebase/auth/functions/config/images/linkedInLogo.png
  src/firebase/auth/functions/config/images/welcomeImage.png
  src/firebase/auth/functions/config/images/youtubeLogo.png
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
  src/firebase/auth/functions/package.json
Labels: ready for review

#1682 BigQuery connectors
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  src/kafka-connectors/bigquery-connector/.env.sample
  src/kafka-connectors/bigquery-connector/Dockerfile
  src/kafka-connectors/bigquery-connector/README.md
  src/kafka-connectors/bigquery-connector/bigquery_api.py
  src/kafka-connectors/bigquery-connector/config.py
  src/kafka-connectors/bigquery-connector/main.py
  src/kafka-connectors/bigquery-connector/message_broker.py
  src/kafka-connectors/bigquery-connector/models.py
  src/kafka-connectors/bigquery-connector/requirements.txt
Labels: ready for review

#1721 K8s predict helmcharts
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/predict/.helmignore
  k8s/predict/Chart.yaml
  k8s/predict/api/Chart.yaml
  k8s/predict/api/templates/tests/test-connection.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/api/values-stage.yaml
  k8s/predict/charts/.gitkeep
  k8s/predict/job/.helmignore
  k8s/predict/job/Chart.yaml
  k8s/predict/job/charts/.gitkeep
  k8s/predict/job/templates/_helpers.tpl
  k8s/predict/job/values-prod.yaml
  k8s/predict/job/values-stage.yaml
  k8s/predict/templates/NOTES.txt
  k8s/predict/templates/_helpers.tpl
  k8s/predict/templates/api.yaml
  k8s/predict/templates/hpa.yaml
  k8s/predict/templates/predict-job.yaml
  k8s/predict/templates/service.yaml
  k8s/predict/templates/tests/test-connection.yaml
  k8s/predict/templates/train-job.yaml
  k8s/predict/train-job/.helmignore
  k8s/predict/train-job/charts/.gitkeep
  k8s/predict/train-job/templates/_helpers.tpl
  k8s/predict/train-job/values-prod.yaml
  k8s/predict/train-job/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
Labels: ready for review

#1747 Improve heatmap endpoint to get all GP predictions
  src/predict/api/helpers/utils.py
Labels: ready for review, predict

#1749 Resolving errors while collocating single devices
  src/device-monitoring/helpers/collocation_utils.py
Labels: ready for review

#1750 Move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  k8s/view/values-prod.yaml
  src/device-monitoring/helpers/collocation_utils.py
Labels: ready for review

#1753 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/middleware/passport.js
Labels: ready for review

#1754 whiteListGoogleAuthEndpoints
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: hotfix, ready for review, devops

#1755 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
Labels: ready for review

#1756 Device Battery APIs
  src/device-monitoring/controllers/check_status.py
  src/device-monitoring/helpers/convert_dates.py
  src/device-monitoring/models.py
  src/device-monitoring/routes.py
Labels: ready for review

#1758 Added handling of 405 errors
  src/device-monitoring/app.py
  src/device-monitoring/controllers/collocation.py
Labels: ready for review

#1759 Fix Email bug in AUTH service
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#1763 QA for Emails
  src/auth-service/controllers/create-user.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/index.js
Labels: ready for review

#1765 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/controllers/create-user.js
  src/auth-service/routes/v1/users.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
  src/firebase/auth/functions/config/emailTemplates.js
  src/firebase/auth/functions/index.js
Labels: ready for review

#1764 3 hotfixes for creating devices
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
Labels: ready for review

#1766 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
Labels: ready for review

#1760 Modifications to the Favorites Endpoint
  src/auth-service/config/constants.js
  src/auth-service/models/Favorite.js
  src/auth-service/routes/v1/favorites.js
  src/auth-service/routes/v2/favorites.js
  src/auth-service/utils/create-favorite.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#1768 pre-save airqloud_codes on creation
  src/device-registry/models/Airqloud.js
Labels: ready for review

#1767 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/config/constants.js
  src/auth-service/models/Favorite.js
  src/auth-service/routes/v1/favorites.js
  src/auth-service/routes/v2/favorites.js
  src/auth-service/utils/create-favorite.js
  src/auth-service/utils/generate-filter.js
  src/device-registry/models/Airqloud.js
Labels: ready for review

#1769 Exporting collocation collection
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
Labels: ready for review

#1770 Move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
Labels: ready for review

#1771 [device-registry] use ENVs for the valid tenant values
  src/device-registry/routes/v1/events.js
  src/device-registry/routes/v2/events.js
Labels: ready for review

#1751 Updated action versions
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  .github/workflows/test-changes.yml
  workflow-trigger
Labels: ready for review

#1772 move to production
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  .github/workflows/test-changes.yml
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-stage.yaml
  k8s/channel-data/values-stage.yaml
  k8s/data-mgt/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/values-stage.yaml
  k8s/exceedance/values-stage-airqo.yaml
  k8s/exceedance/values-stage-kcca.yaml
  k8s/fault-detection/values-stage.yaml
  k8s/gp-model/values-stage.yaml
  k8s/meta-data/values-stage.yaml
  k8s/network-uptime/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  k8s/view/values-prod.yaml
  k8s/view/values-stage.yaml
  src/device-registry/routes/v1/events.js
  src/device-registry/routes/v2/events.js
  workflow-trigger
Labels: ready for review

#1775 Collocation hot fixes
  src/device-monitoring/app.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/helpers/exceptions.py
  src/device-monitoring/models.py
Labels: ready for review

#1777 Move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-monitoring/app.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/collocation_utils.py
  src/device-monitoring/helpers/exceptions.py
  src/device-monitoring/models.py
Labels: ready for review

#1779 Adding sychronization to Favorites endpoints
  src/auth-service/controllers/create-favorite.js
  src/auth-service/routes/v1/favorites.js
  src/auth-service/routes/v2/favorites.js
  src/auth-service/utils/create-favorite.js
Labels: ready for review

#1780 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/controllers/create-favorite.js
  src/auth-service/routes/v1/favorites.js
  src/auth-service/routes/v2/favorites.js
  src/auth-service/utils/create-favorite.js
Labels: ready for review
