Repository airqo-platform/AirQo-api, pull requests merged in 2023-02, with the labels that each got.

#1290 [device-registry] just increasing the JavaScript heap size
  src/device-registry/package.json
Labels: hotfix, ready for review, device-registry

#1291 move to production
  LICENSE
  src/device-registry/package.json
Labels: ready for review

#1292 chore - deployment files
  k8s/airflow/airflow-app.yaml
  k8s/airflow/stage-airflow-app.yaml
Labels: ready for review

#1298 few hotfixes for the create-device use case
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-device.js
  src/device-registry/models/Device.js
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/create-device.js
Labels: hotfix, ready for review, device-registry

#1299 move to production
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-device.js
  src/device-registry/models/Device.js
  src/device-registry/routes/api-v1.js
  src/device-registry/utils/create-device.js
Labels: ready for review

#1300 fixing a runtime issue for candidate confirmation
  src/auth-service/utils/request-access.js
Labels: ready for review, auth-service

#1301 move to production
  src/auth-service/utils/request-access.js
Labels: ready for review

#1279 Cronjob pod scheduleing updates
  k8s/analytics/job/templates/cronjob.yaml
  k8s/channel-data/templates/cronjob.yaml
  k8s/data-mgt/templates/deployment.yaml
  k8s/exceedance/templates/cronjob.yaml
  k8s/gp-model/templates/cronjob.yaml
  k8s/nodes/prod-compute.json
  k8s/nodes/prod-high-memory.json
  k8s/nodes/stage-compute.json
  k8s/nodes/stage-high-memory.json
  k8s/predict/job/templates/cronjob.yaml
  k8s/predict/train-job/templates/cronjob.yaml
Labels: enhancement, ready for review, devops

#1304 adding the country field to the Candidates schema
  src/auth-service/controllers/create-default.js
  src/auth-service/controllers/create-user.js
  src/auth-service/controllers/request-access.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/User.js
  src/auth-service/routes/v1/requests.js
  src/auth-service/utils/request-access.js
Labels: ready for review

#1294 device registry refactoring and enhancements
  src/device-registry/.gitignore
  src/device-registry/app.js
  src/device-registry/config/cloudinary.js
  src/device-registry/config/database.js
  src/device-registry/config/log4js.js
  src/device-registry/config/redis.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Location.js
  src/device-registry/models/Measurement.js
  src/device-registry/models/Photo.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/UniqueIdentifierCounter.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/api-v1.js
  src/device-registry/routes/api-v2.js
  src/device-registry/routes/index.js
  src/device-registry/routes/test/.gitkeep
  src/device-registry/routes/v1/activities.js
  src/device-registry/routes/v1/airqlouds.js
  src/device-registry/routes/v1/devices.js
  src/device-registry/routes/v1/events.js
  src/device-registry/routes/v1/index.js
  src/device-registry/routes/v1/locations.js
  src/device-registry/routes/v1/photos.js
  src/device-registry/routes/v1/sensors.js
  src/device-registry/routes/v1/sites.js
  src/device-registry/routes/v2/activities.js
  src/device-registry/routes/v2/airqlouds.js
  src/device-registry/routes/v2/devices.js
  src/device-registry/routes/v2/events.js
  src/device-registry/routes/v2/index.js
  src/device-registry/routes/v2/locations.js
  src/device-registry/routes/v2/photos.js
  src/device-registry/routes/v2/sensors.js
  src/device-registry/routes/v2/sites.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-monitor.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/date.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/log.js
  src/device-registry/utils/multitenancy.js
Labels: enhancement, ready for review, refactoring, device-registry

#1305 fixing runtime for gretting sites
  src/device-registry/app.js
  src/device-registry/routes/v1/index.js
  src/device-registry/routes/v2/index.js
Labels: ready for review

#1306 fix country issue when creating a candidate
  src/auth-service/controllers/request-access.js
Labels: ready for review

#1307 [Hotfix] device uptime - Added checks for device number and name
  src/device-uptime/device_uptime.py
Labels: ready for review

#1308 new endpoint for fetching airqlouds without locations
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/models/Airqloud.js
  src/device-registry/routes/v1/airqlouds.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1309 [Analytics hotfix] - mean charts API
  src/analytics/api/views/dashboard.py
Labels: ready for review

#1311 Setting AirQo as default tenant value for analytics endpoint
  src/analytics/api/views/dashboard.py
Labels: ready for review

#1297 Ft update airflow cicd
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/airflow/.helmignore
  k8s/airflow/Chart.yaml
  k8s/airflow/airflow-app.yaml
  k8s/airflow/charts/.gitkeep
  k8s/airflow/stage-airflow-app.yaml
  k8s/airflow/templates/NOTES.txt
  k8s/airflow/templates/_helpers.tpl
  k8s/airflow/templates/deployment.yaml
  k8s/airflow/templates/hpa.yaml
  k8s/airflow/templates/service.yaml
  k8s/airflow/templates/tests/test-connection.yaml
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
Labels: enhancement, ready for review, devops

#1310 refactoring the error responses and hotfixing create photos use case
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Location.js
  src/device-registry/models/Photo.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-monitor.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/errors.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry

#1317 prevent the commit of any .json files
  src/predict/.gitignore
Labels: ready for review, predict

#1320 resolving runtime errors for the create photo usecase
  src/device-registry/models/Photo.js
  src/device-registry/routes/v1/photos.js
  src/device-registry/utils/create-photo.js
Labels: ready for review

#1321 just hard coding the limit value
  src/device-registry/app.js
  src/device-registry/models/Photo.js
Labels: ready for review

#1324 address get events hotfix
  src/device-registry/bin/www
  src/device-registry/utils/create-event.js
Labels: ready for review, device-registry

#1325 move to production
  src/device-registry/bin/www
  src/device-registry/utils/create-event.js
Labels: ready for review

#1328 enhance input validations during he device creation process
  src/device-registry/routes/v1/devices.js
Labels: ready for review, device-registry

#1331 move to production
  src/device-registry/routes/v1/devices.js
Labels: ready for review

#1316 fix bugs and enhance the Activity creation process
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/routes/v1/activities.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry

#1332 move to production
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/routes/v1/activities.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1323 enhancements to the device photo creation and deletion processes
  src/device-registry/models/Photo.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/generate-filter.js
Labels: enhancement, ready for review, device-registry

#1336 move to production
  src/device-registry/models/Photo.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/generate-filter.js
Labels: enhancement, ready for review, device-registry

#1326 Remove user data from lookup endpoint results
  src/auth-service/utils/create-user.js
Labels: ready for review

#1337 move to production
  src/auth-service/utils/create-user.js
Labels: ready for review

#1338 Few enhancements to the create-photo use-case
  src/device-registry/controllers/create-photo.js
  src/device-registry/models/Photo.js
  src/device-registry/utils/create-photo.js
Labels: ready for review, device-registry

#1339 move to production
  src/device-registry/controllers/create-photo.js
  src/device-registry/models/Photo.js
  src/device-registry/utils/create-photo.js
Labels: ready for review

#1340 Updating analytics Docker image
  src/analytics/Dockerfile
Labels: ready for review

#1341 data-export - adding tenant when user exports by device
  src/analytics/api/models/events.py
  src/analytics/api/utils/pollutants/pm_25.py
Labels: ready for review

#1344 hotfix for deleting photo
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1345 move to production
  src/analytics/Dockerfile
  src/analytics/api/models/events.py
  src/analytics/api/utils/pollutants/pm_25.py
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1346 move to production
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-network.js
  src/auth-service/models/Network.js
  src/auth-service/routes/v1/networks.js
  src/auth-service/utils/create-network.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#1329 Create DAG for extracting Raw data
  src/airflow/dags/airqo_measurements.py
  src/airflow/dags/task_docs.py
Labels: ready for review

#1270 Collocation APIs
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  k8s/device-monitor/prod-device-monitor-api.yaml
  k8s/device-monitor/stage-device-monitor-api.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  src/device-monitoring/app.py
  src/device-monitoring/config/constants.py
  src/device-monitoring/controllers/check_status.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/convert_dates.py
  src/device-monitoring/helpers/pre_request.py
  src/device-monitoring/requirements.txt
  src/device-monitoring/routes.py
Labels: ready for review

#1349 QA works for Kafka message consumption in device registry
  src/device-registry/app.js
  src/device-registry/bin/www
  src/device-registry/utils/create-event.js
  src/device-registry/utils/errors.js
Labels: ready for review, device-registry

#1351 [MOBILE APP] latest app version API
  src/view/pom.xml
  src/view/src/main/java/airqo/controllers/AppController.java
  src/view/src/main/java/airqo/models/StoreVersion.java
  src/view/src/main/java/airqo/services/AppService.java
  src/view/src/main/resources/application.properties
Labels: ready for review

#1276 Ft grafana staging access
  k8s/grafana/datasources.yaml
  k8s/grafana/grafana.ini
  k8s/nginx/staging/global-config.yaml
  k8s/nginx/staging/virtual-server.yaml
Labels: ready for review, feature-request, devops

#1353 Revert "remove line break"
  src/device-monitoring/routes.py
Labels: hotfix, ready for review

#1333 Ft train premptive node
  infra/ansible/playbooks/k8s/k8s-hosts-prod
  infra/ansible/playbooks/k8s/k8s-hosts-stage
  infra/ansible/playbooks/k8s/preemptive-worker.yml
  infra/ansible/playbooks/k8s/preemptives.yml
  infra/ansible/playbooks/k8s/templates/join_k8s_cluster.sh.j2
  infra/ansible/playbooks/k8s/templates/remove_preemptive_node.sh.j2
  infra/ansible/playbooks/k8s/templates/remove_preemptives.sh.j2
  infra/terraform/gcp/modules/ComputeDisk/airqo-k8s-worker-4.tf
  infra/terraform/gcp/modules/ComputeInstance/airqo-k8s-worker-4.tf
  infra/terraform/gcp/modules/ComputeResourcePolicy/hourly-k8s-runners.tf
  infra/terraform/gcp/modules/ComputeResourcePolicy/monthly-k8s-runners.tf
  k8s/nodes/airqo-k8s-worker-0.json
  k8s/nodes/airqo-k8s-worker-1.json
  k8s/nodes/airqo-k8s-worker-2.json
  k8s/nodes/airqo-k8s-worker-3.json
  k8s/nodes/airqo-k8s-worker-4.json
  k8s/nodes/airqo-stage-k8s-worker-0.json
  k8s/nodes/airqo-stage-k8s-worker-1.json
  k8s/nodes/airqo-stage-k8s-worker-2.json
  k8s/nodes/airqo-stage-k8s-worker-3.json
  k8s/nodes/airqo-stage-k8s-worker-4.json
  k8s/nodes/prod-general-purpose.json
  k8s/nodes/prod-gpu.json
  k8s/nodes/stage-general-purpose.json
  k8s/nodes/stage-gpu.json
  k8s/predict/train-job/templates/cronjob.yaml
  k8s/predict/train-job/values-prod.yaml
  k8s/predict/train-job/values-stage.yaml
Labels: ready for review, devops

#1356 increase device monitoring limits
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
Labels: hotfix, ready for review

#1314 Fix clean up ci pipeline
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/analytics/prod-analytics-api.yaml
  k8s/analytics/stage-analytics-api.yaml
  k8s/auth-service/prod-auth-api.yaml
  k8s/auth-service/stage-auth-api.yaml
  k8s/auth-service/values-dev.yaml
  k8s/calibrate/prod-calibrate-api.yaml
  k8s/calibrate/stage-calibrate-api.yaml
  k8s/channel-data/prod-airqo-update-channel-data-job.yaml
  k8s/channel-data/stage-airqo-update-channel-data-job.yaml
  k8s/data-mgt/prod-data-mgt-api.yaml
  k8s/data-mgt/stage-data-mgt-api.yaml
  k8s/data-mgt/values-dev.yaml
  k8s/device-monitor/prod-device-monitor-api.yaml
  k8s/device-monitor/stage-device-monitor-api.yaml
  k8s/device-monitor/values-dev.yaml
  k8s/device-registry/prod-device-registry-api.yaml
  k8s/device-registry/stage-device-registry-api.yaml
  k8s/device-registry/values-dev.yaml
  k8s/device-status/prod-airqo-device-status-job.yaml
  k8s/device-status/stage-airqo-device-status-job.yaml
  k8s/device-uptime/prod-airqo-device-uptime-job.yaml
  k8s/device-uptime/stage-airqo-device-uptime-job.yaml
  k8s/events-monitor/prod-events-notifs-cronjob.yaml
  k8s/events-monitor/stage-events-notifs-cronjob.yaml
  k8s/exceedance/prod-airqo-exceedance-job.yaml
  k8s/exceedance/prod-kcca-exceedance-job.yaml
  k8s/exceedance/stage-airqo-exceedance-job.yaml
  k8s/exceedance/stage-kcca-exceedance-job.yaml
  k8s/fault-detection/prod-fault-detection-api.yaml
  k8s/fault-detection/stage-fault-detection-api.yaml
  k8s/gp-model/prod-airqo-gp-model-job.yaml
  k8s/gp-model/stage-airqo-gp-model-job.yaml
  k8s/locate/prod-locate-api.yaml
  k8s/locate/stage-locate-api.yaml
  k8s/locate/values-dev.yaml
  k8s/meta-data/prod-meta-data-api.yaml
  k8s/meta-data/stage-meta-data-api.yaml
  k8s/network-uptime/prod-airqo-network-uptime-api.yaml
  k8s/network-uptime/stage-airqo-network-uptime-api.yaml
  k8s/predict/prod-airqo-predict-job.yaml
  k8s/predict/prod-airqo-train-job.yaml
  k8s/predict/prod-prediction-api.yaml
  k8s/predict/stage-airqo-predict-job.yaml
  k8s/predict/stage-airqo-train-job.yaml
  k8s/predict/stage-prediction-api.yaml
  k8s/predict/values-dev.yaml
  k8s/redis/prod-redis-server.yaml
  k8s/redis/stage-redis-server.yaml
  k8s/view/prod-view-api.yaml
  k8s/view/prod-view-message-broker.yaml
  k8s/view/stage-view-api.yaml
  k8s/view/stage-view-message-broker.yaml
Labels: enhancement, hotfix, ready for review

#1358 Adding error handling and logging to kafka messages
  src/device-registry/bin/www
Labels: ready for review

#1357 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/analytics/prod-analytics-api.yaml
  k8s/analytics/stage-analytics-api.yaml
  k8s/auth-service/prod-auth-api.yaml
  k8s/auth-service/stage-auth-api.yaml
  k8s/auth-service/values-dev.yaml
  k8s/calibrate/prod-calibrate-api.yaml
  k8s/calibrate/stage-calibrate-api.yaml
  k8s/channel-data/prod-airqo-update-channel-data-job.yaml
  k8s/channel-data/stage-airqo-update-channel-data-job.yaml
  k8s/data-mgt/prod-data-mgt-api.yaml
  k8s/data-mgt/stage-data-mgt-api.yaml
  k8s/data-mgt/values-dev.yaml
  k8s/device-monitor/prod-device-monitor-api.yaml
  k8s/device-monitor/stage-device-monitor-api.yaml
  k8s/device-monitor/values-dev.yaml
  k8s/device-registry/prod-device-registry-api.yaml
  k8s/device-registry/stage-device-registry-api.yaml
  k8s/device-registry/values-dev.yaml
  k8s/device-status/prod-airqo-device-status-job.yaml
  k8s/device-status/stage-airqo-device-status-job.yaml
  k8s/device-uptime/prod-airqo-device-uptime-job.yaml
  k8s/device-uptime/stage-airqo-device-uptime-job.yaml
  k8s/events-monitor/prod-events-notifs-cronjob.yaml
  k8s/events-monitor/stage-events-notifs-cronjob.yaml
  k8s/exceedance/prod-airqo-exceedance-job.yaml
  k8s/exceedance/prod-kcca-exceedance-job.yaml
  k8s/exceedance/stage-airqo-exceedance-job.yaml
  k8s/exceedance/stage-kcca-exceedance-job.yaml
  k8s/fault-detection/prod-fault-detection-api.yaml
  k8s/fault-detection/stage-fault-detection-api.yaml
  k8s/gp-model/prod-airqo-gp-model-job.yaml
  k8s/gp-model/stage-airqo-gp-model-job.yaml
  k8s/locate/prod-locate-api.yaml
  k8s/locate/stage-locate-api.yaml
  k8s/locate/values-dev.yaml
  k8s/meta-data/prod-meta-data-api.yaml
  k8s/meta-data/stage-meta-data-api.yaml
  k8s/network-uptime/prod-airqo-network-uptime-api.yaml
  k8s/network-uptime/stage-airqo-network-uptime-api.yaml
  k8s/predict/prod-airqo-predict-job.yaml
  k8s/predict/prod-airqo-train-job.yaml
  k8s/predict/prod-prediction-api.yaml
  k8s/predict/stage-airqo-predict-job.yaml
  k8s/predict/stage-airqo-train-job.yaml
  k8s/predict/stage-prediction-api.yaml
  k8s/predict/values-dev.yaml
  k8s/redis/prod-redis-server.yaml
  k8s/redis/stage-redis-server.yaml
  k8s/view/prod-view-api.yaml
  k8s/view/prod-view-message-broker.yaml
  k8s/view/stage-view-api.yaml
  k8s/view/stage-view-message-broker.yaml
  src/airflow/airqo_etl_utils/message_broker_utils.py
  src/airflow/dags/airnow_bam_data.py
  src/device-monitoring/helpers/collocation.py
  src/device-registry/routes/v1/devices.js
Labels: ready for review
