Repository airqo-platform/AirQo-api, pull requests merged in 2023-03, with the labels that each got.

#1367 Hotfix - device status endpoint
  src/device-monitoring/Dockerfile
  src/device-monitoring/controllers/check_status.py
Labels: ready for review

#1330 only pull images when they are not present locally
  k8s/airflow/airflow-app.yaml
  k8s/airflow/templates/deployment.yaml
  k8s/analytics/api/templates/deployment.yaml
  k8s/argo-cd/argocd-server-deployment.yaml
  k8s/auth-service/templates/deployment.yaml
  k8s/calibrate/templates/deployment.yaml
  k8s/data-mgt/templates/deployment.yaml
  k8s/device-monitor/templates/deployment.yaml
  k8s/device-registry/templates/deployment.yaml
  k8s/fault-detection/templates/deployment.yaml
  k8s/locate/templates/deployment.yaml
  k8s/meta-data/templates/deployment.yaml
  k8s/network-uptime/templates/deployment.yaml
  k8s/notification-service/prod-notification-api.yaml
  k8s/notification-service/stage-notification-api.yaml
  k8s/predict/api/templates/deployment.yaml
  k8s/redis/templates/deployment.yaml
  k8s/schema-registry/prod-schema-registry.yaml
  k8s/schema-registry/stage-schema-registry.yaml
  k8s/schema-registry/templates/deployment.yaml
  k8s/streams/prod-airqo-raw-measurements-stream.yaml
  k8s/streams/prod-airqo-tahmo-values-stream.yaml
  k8s/streams/prod-kcca-raw-measurements-stream.yaml
  k8s/streams/stage-airqo-raw-measurements-stream.yaml
  k8s/streams/stage-airqo-tahmo-values-stream.yaml
  k8s/streams/stage-kcca-raw-measurements-stream.yaml
  k8s/view/api/templates/deployment.yaml
  k8s/view/message-broker/templates/deployment.yaml
Labels: hotfix, ready for review

#1359 Ft train job clean
  k8s/predict/train-job/templates/cronjob.yaml
  k8s/predict/train-job/values-prod.yaml
  k8s/predict/train-job/values-stage.yaml
Labels: ready for review

#1350 just refactoring the logic for QR code creation
  src/device-registry/controllers/create-device.js
  src/device-registry/utils/create-device.js
Labels: ready for review, device-registry

#1369 changes to the response format and content to verify access token
  src/auth-service/controllers/create-token.js
  src/auth-service/models/AccessToken.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#1368 Ft new gateway auth
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: enhancement, ready for review, devops, auth-service

#1373 QA for integrating device registry with KAFKA
  src/device-registry/.gitignore
  src/device-registry/bin/www
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Event.js
  src/device-registry/routes/v2/events.js
  src/device-registry/scripts/bulk-create.js
  src/device-registry/scripts/bulk-delete.js
  src/device-registry/scripts/bulk-update.js
  src/device-registry/utils/bulk-script.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-monitor.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1374 QA for KAFKA and device registry >> adding more loggers
  src/device-registry/bin/www
Labels: ready for review

#1375 stringify kafka value message
  src/device-registry/bin/www
Labels: ready for review

#1376 repair bad JSON strings from KAFKA
  src/device-registry/bin/www
  src/device-registry/package-lock.json
  src/device-registry/package.json
Labels: ready for review

#1377 more details to input validation errors
  src/device-registry/bin/www
Labels: ready for review

#1378 cleaning the measurements before input validation checks
  src/device-registry/bin/www
Labels: ready for review

#1379 fixing a runtime error
  src/device-registry/bin/www
Labels: ready for review

#1380 allow unknowns and also remove all NaNs
  src/device-registry/bin/www
Labels: ready for review

#1381 temporarily disable enrichment operation
  src/device-registry/utils/create-event.js
Labels: ready for review

#1383 small change just to trigger new messsage broker secrets
  src/device-registry/bin/www
Labels: ready for review

#1384 trigger change of cloud code secrets
  src/device-registry/bin/www
Labels: ready for review

#1385 more configs for events sent from KAFKA
  src/device-registry/config/constants.js
Labels: ready for review

#1366 move to production
  k8s/airflow/airflow-app.yaml
  k8s/airflow/templates/deployment.yaml
  k8s/analytics/api/templates/deployment.yaml
  k8s/argo-cd/argocd-server-deployment.yaml
  k8s/auth-service/templates/deployment.yaml
  k8s/calibrate/templates/deployment.yaml
  k8s/data-mgt/templates/deployment.yaml
  k8s/device-monitor/templates/deployment.yaml
  k8s/device-registry/templates/deployment.yaml
  k8s/fault-detection/templates/deployment.yaml
  k8s/locate/templates/deployment.yaml
  k8s/meta-data/templates/deployment.yaml
  k8s/network-uptime/templates/deployment.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/notification-service/prod-notification-api.yaml
  k8s/notification-service/stage-notification-api.yaml
  k8s/predict/api/templates/deployment.yaml
  k8s/predict/train-job/templates/cronjob.yaml
  k8s/predict/train-job/values-prod.yaml
  k8s/predict/train-job/values-stage.yaml
  k8s/redis/templates/deployment.yaml
  k8s/schema-registry/prod-schema-registry.yaml
  k8s/schema-registry/stage-schema-registry.yaml
  k8s/schema-registry/templates/deployment.yaml
  k8s/streams/prod-airqo-raw-measurements-stream.yaml
  k8s/streams/prod-airqo-tahmo-values-stream.yaml
  k8s/streams/prod-kcca-raw-measurements-stream.yaml
  k8s/streams/stage-airqo-raw-measurements-stream.yaml
  k8s/streams/stage-airqo-tahmo-values-stream.yaml
  k8s/streams/stage-kcca-raw-measurements-stream.yaml
  k8s/view/api/templates/deployment.yaml
  k8s/view/message-broker/templates/deployment.yaml
  src/auth-service/controllers/create-token.js
  src/auth-service/models/AccessToken.js
  src/auth-service/utils/control-access.js
  src/device-monitoring/Dockerfile
  src/device-monitoring/controllers/check_status.py
  src/device-registry/.gitignore
  src/device-registry/bin/www
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Event.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/routes/v2/events.js
  src/device-registry/scripts/bulk-create.js
  src/device-registry/scripts/bulk-delete.js
  src/device-registry/scripts/bulk-update.js
  src/device-registry/utils/bulk-script.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-monitor.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1386 Removing repetitive function to fix duplicate-key errors
  src/airflow/dags/airqo_measurements.py
Labels: ready for review

#1387 Revert "Removing repetitive function to fix duplicate-key errors"
  src/airflow/dags/airqo_measurements.py
Labels: ready for review

#1390 Hotfix - data pipeline
  src/airflow/airqo_etl_utils/weather_data_utils.py
Labels: ready for review

#1372 Collocation endpoints
  src/device-monitoring/Dockerfile
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/utils.py
  src/device-monitoring/requirements.txt
  src/device-monitoring/routes.py
Labels: ready for review

#1203 deployment/argocd updates
  k8s/airflow/Chart.yaml
  k8s/airflow/templates/hpa.yaml
  k8s/airflow/templates/tests/test-connection.yaml
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/api/values-prod.yaml
  k8s/analytics/api/values-stage.yaml
  k8s/analytics/job/values-prod.yaml
  k8s/analytics/job/values-stage.yaml
  k8s/auth-service/templates/deployment.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/calibrate/values-stage.yaml
  k8s/channel-data/values-prod.yaml
  k8s/channel-data/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-mgt/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/device-uptime/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/exceedance/values-stage-airqo.yaml
  k8s/exceedance/values-stage-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/fault-detection/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/locate/values-prod.yaml
  k8s/locate/values-stage.yaml
  k8s/meta-data/values-prod.yaml
  k8s/meta-data/values-stage.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/network-uptime/values-stage.yaml
  k8s/predict/api/templates/service.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/api/values-stage.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/job/values-stage.yaml
  k8s/predict/train-job/values-prod.yaml
  k8s/predict/train-job/values-stage.yaml
  k8s/view/api/templates/deployment.yaml
  k8s/view/api/values-prod.yaml
  k8s/view/api/values-stage.yaml
  k8s/view/message-broker/values-prod.yaml
  k8s/view/message-broker/values-stage.yaml
Labels: chore, ready for review, devops, priority-high

#1392 MOVE TO PRODUCTION
  k8s/airflow/Chart.yaml
  k8s/airflow/templates/hpa.yaml
  k8s/airflow/templates/tests/test-connection.yaml
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/api/values-prod.yaml
  k8s/analytics/api/values-stage.yaml
  k8s/analytics/job/values-prod.yaml
  k8s/analytics/job/values-stage.yaml
  k8s/auth-service/templates/deployment.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/calibrate/values-stage.yaml
  k8s/channel-data/values-prod.yaml
  k8s/channel-data/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-mgt/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/device-uptime/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/exceedance/values-stage-airqo.yaml
  k8s/exceedance/values-stage-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/fault-detection/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/locate/values-prod.yaml
  k8s/locate/values-stage.yaml
  k8s/meta-data/values-prod.yaml
  k8s/meta-data/values-stage.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/network-uptime/values-stage.yaml
  k8s/predict/api/templates/service.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/api/values-stage.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/job/values-stage.yaml
  k8s/predict/train-job/values-prod.yaml
  k8s/predict/train-job/values-stage.yaml
  k8s/view/api/templates/deployment.yaml
  k8s/view/api/values-prod.yaml
  k8s/view/api/values-stage.yaml
  k8s/view/message-broker/values-prod.yaml
  k8s/view/message-broker/values-stage.yaml
  src/device-monitoring/Dockerfile
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/utils.py
  src/device-monitoring/requirements.txt
  src/device-monitoring/routes.py
Labels: ready for review

#1393 Deployment/argocd
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/api/values-prod.yaml
  k8s/analytics/api/values-stage.yaml
  k8s/analytics/job/values-prod.yaml
  k8s/analytics/job/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/calibrate/values-stage.yaml
  k8s/channel-data/values-prod.yaml
  k8s/channel-data/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-mgt/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/device-uptime/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/exceedance/values-stage-airqo.yaml
  k8s/exceedance/values-stage-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/fault-detection/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/locate/values-prod.yaml
  k8s/locate/values-stage.yaml
  k8s/meta-data/values-prod.yaml
  k8s/meta-data/values-stage.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/network-uptime/values-stage.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/api/values-stage.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/job/values-stage.yaml
  k8s/predict/train-job/values-prod.yaml
  k8s/predict/train-job/values-stage.yaml
  k8s/view/api/values-prod.yaml
  k8s/view/api/values-stage.yaml
  k8s/view/message-broker/values-prod.yaml
  k8s/view/message-broker/values-stage.yaml
Labels: hotfix, ready for review

#1397 Exporting data for BAM devices
  src/analytics/api/models/events.py
  src/analytics/config.py
Labels: ready for review

#1269 [mobile-app] send welcome messages
  src/auth-service/Dockerfile
  src/auth-service/app.js
  src/auth-service/bin/www
  src/auth-service/config/constants.js
  src/auth-service/config/firebase-admin.js
  src/auth-service/config/log4js.js
  src/auth-service/controllers/request-access.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/errors.js
  src/auth-service/utils/mailer.js
  src/firebase/auth/.firebaserc
  src/firebase/auth/firebase.json
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package.json
  src/firebase/auth/package.json
Labels: ready for review, auth-service, mobile-app

#1370 Airqloud calibrated data summary
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/views/__init__.py
  src/analytics/api/views/dashboard.py
  src/analytics/api/views/data.py
  src/analytics/api/views/map.py
Labels: ready for review

#1404 Collocation scheduling
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/device-monitor/Chart.yaml
  k8s/device-monitor/charts/.gitkeep
  k8s/device-monitor/charts/airqo-device-monitor-api-1.0.0.tgz
  k8s/device-monitor/templates/deployment.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  src/device-monitoring/.dockerignore
  src/device-monitoring/.gitignore
  src/device-monitoring/Dockerfile
  src/device-monitoring/README.md
  src/device-monitoring/app.py
  src/device-monitoring/config/constants.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/helpers/convert_dates.py
  src/device-monitoring/requirements.txt
  src/device-monitoring/routes.py
Labels: ready for review

#1403 create dynamic health tips
  k8s/kafka/topics/kafka-topics.yaml
  src/device-registry/app.js
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/models/Event.js
  src/device-registry/models/HealthTips.js
  src/device-registry/routes/v1/index.js
  src/device-registry/routes/v1/tips.js
  src/device-registry/routes/v2/index.js
  src/device-registry/routes/v2/tips.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry

#1400 Hotfixes for the auth-service (forgot password feature)
  src/auth-service/controllers/create-user.js
  src/auth-service/models/User.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-inquiry.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/request-access.js
Labels: ready for review, auth-service

#1410 move to production
  k8s/kafka/topics/kafka-topics.yaml
  src/auth-service/controllers/create-user.js
  src/auth-service/models/User.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-inquiry.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/generate-filter.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/request-access.js
  src/device-registry/app.js
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/models/Event.js
  src/device-registry/models/HealthTips.js
  src/device-registry/routes/v1/index.js
  src/device-registry/routes/v1/tips.js
  src/device-registry/routes/v2/index.js
  src/device-registry/routes/v2/tips.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1399 device-registry hotfixes and metadata grooming
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Location.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/UniqueIdentifierCounter.js
  src/device-registry/routes/v1/airqlouds.js
  src/device-registry/routes/v1/devices.js
  src/device-registry/routes/v1/events.js
  src/device-registry/routes/v1/sites.js
  src/device-registry/utils/create-site.js
Labels: ready for review, device-registry

#1412 return running/active devices ONLY
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Event.js
  src/device-registry/routes/v1/events.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry

#1413 move to production
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Location.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/UniqueIdentifierCounter.js
  src/device-registry/routes/v1/airqlouds.js
  src/device-registry/routes/v1/devices.js
  src/device-registry/routes/v1/events.js
  src/device-registry/routes/v1/sites.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1247 Query for locations with good air quality + etc
  src/device-registry/.gitignore
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Event.js
  src/device-registry/models/Photo.js
  src/device-registry/routes/v1/events.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review, device-registry

#1414 move to production
  src/device-registry/.gitignore
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Event.js
  src/device-registry/models/Photo.js
  src/device-registry/routes/v1/events.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#1415 MOB-78 Send Welcome Messages Alternative
  src/firebase/auth/config/emailTemplates.js
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
  src/firebase/auth/functions/package.json
Labels: ready for review

#1416 move to production
  src/firebase/auth/config/emailTemplates.js
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
  src/firebase/auth/functions/package.json
Labels: ready for review

#1421 Adding ImageUrl field to health-tips
  src/device-registry/models/HealthTips.js
  src/device-registry/routes/v1/tips.js
  src/device-registry/routes/v2/tips.js
Labels: ready for review

#1422 reorder auth statements to fix '/' access bug
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
Labels: hotfix, ready for review

#1419 move to production
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/api/values-prod.yaml
  k8s/analytics/api/values-stage.yaml
  k8s/analytics/job/values-prod.yaml
  k8s/analytics/job/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/channel-data/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-monitor/templates/deployment.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/fault-detection/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/meta-data/values-prod.yaml
  k8s/meta-data/values-stage.yaml
  k8s/network-uptime/values-prod.yaml
  k8s/nginx/production/global-config.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/api/values-prod.yaml
  k8s/predict/job/values-prod.yaml
  k8s/predict/train-job/values-prod.yaml
  k8s/view/api/values-prod.yaml
  src/device-registry/models/HealthTips.js
  src/device-registry/routes/v1/tips.js
  src/device-registry/routes/v2/tips.js
Labels: ready for review

#1423 [Collocation] Data completeness results
  src/device-monitoring/config/constants.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/routes.py
Labels: ready for review

#1420 [HEATMAP] Refactored: Data and Data preprocessing
  src/gp-model/config.py
  src/gp-model/data/__init__.py
  src/gp-model/data/data.py
  src/gp-model/data/preprocess.py
  src/gp-model/main.py
Labels: enhancement, work in progress, hotfix

#1427 Enable logging on staging
  src/device-registry/utils/log.js
Labels: ready for review

#1426 Hot-Fix on aqi category for health tips
  src/device-registry/models/HealthTips.js
Labels: ready for review

#1428 move to production
  src/device-monitoring/config/constants.py
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/routes.py
  src/device-registry/models/HealthTips.js
  src/device-registry/utils/log.js
  src/gp-model/config.py
  src/gp-model/data/__init__.py
  src/gp-model/data/data.py
  src/gp-model/data/preprocess.py
  src/gp-model/main.py
Labels: ready for review

#1424 Collocation - Data formatting
  k8s/device-monitor/templates/deployment.yaml
  src/device-monitoring/Dockerfile
  src/device-monitoring/controllers/collocation.py
  src/device-monitoring/helpers/collocation.py
  src/device-monitoring/routes.py
Labels: ready for review

#1302 allows users to sign in using their Google account
  src/auth-service/config/constants.js
  src/auth-service/controllers/create-user.js
  src/auth-service/middleware/auth.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/User.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/v1/users.js
Labels: enhancement, ready for review, auth-service

#1391 Log user activity in the Auth Service
  src/auth-service/app.js
  src/auth-service/bin/www
  src/auth-service/config/dbConnection.js
  src/auth-service/config/log4js.js
  src/auth-service/controllers/create-default.js
  src/auth-service/controllers/create-inquiry.js
  src/auth-service/controllers/create-user.js
  src/auth-service/middleware/can-access.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/Group.js
  src/auth-service/models/Inquiry.js
  src/auth-service/models/Network.js
  src/auth-service/models/User.js
  src/auth-service/models/log.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/routes/v1/inquiries.js
  src/auth-service/routes/v1/users.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-default.js
  src/auth-service/utils/create-inquiry.js
  src/auth-service/utils/create-network.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/log.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/multitenancy.js
  src/auth-service/utils/request-access.js
  src/auth-service/utils/test/ut_request.js
Labels: ready for review, auth-service

#1432 new endpoint for getting the latest measurements for external usage
  src/device-registry/config/constants.js
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Event.js
  src/device-registry/routes/v1/events.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/log.js
Labels: ready for review

#1434 move to production
  src/auth-service/package-lock.json
Labels: ready for review

#1437 Fix status badges
  README.md
Labels: documentation, enhancement, hotfix, ready for review

#1438 move to production
  README.md
Labels: ready for review

#1439 disable Slack logging for duplicate errors
  src/device-registry/utils/create-event.js
Labels: ready for review

#1440 move to production
  src/device-registry/utils/create-event.js
Labels: ready for review
