Repository airqo-platform/AirQo-api, pull requests merged in 2024-03, with the labels that each got.

#3047 Mobile App Push Notifications
  src/firebase/auth/firebase.json
  src/firebase/auth/functions/.gcloudignore
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package.json
  src/firebase/auth/functions/utils/utils.js
  src/firebase/auth/package-lock.json
  src/workflows/airqo_etl_utils/airqo_api.py
  src/workflows/airqo_etl_utils/app_notification_utils.py
  src/workflows/airqo_etl_utils/config.py
  src/workflows/dags/app_notifications.py
Labels: ready for review, mobile-app

#3065 spatial files realigned
  src/spatial/.dockerignore
  src/spatial/.gitignore
  src/spatial/Dockerfile
  src/spatial/README.md
  src/spatial/app.py
  src/spatial/configure.py
  src/spatial/controllers/controllers.py
  src/spatial/job/local_moran/controllers/controller.py
  src/spatial/job/local_moran/main.py
  src/spatial/models/getis_model.py
  src/spatial/models/localmoran_model.py
  src/spatial/requirements.txt
  src/spatial/views/getis_confidence_services.py
  src/spatial/views/getis_services.py
  src/spatial/views/localmoran_services.py
Labels: ready for review, priority-high

#3045 improve security and speed
  src/analytics/api/models/base/data_processing.py
  src/analytics/api/models/base/diurnal_data_processing.py
  src/analytics/api/utils/pollutants/report.py
  src/analytics/config.py
  src/analytics/manage.py
Labels: data-engineering, ready for review, priority-high

#3066 Minor Fixes: Uptime and Workflows
  src/device-uptime/utils/device_hourly_records.py
  src/workflows/dags/app_notifications.py
Labels: ready for review

#3064 Fix bug of missing forecasts in mobile app
  src/gp-model/main.py
  src/predict/api/helpers.py
  src/predict/api/prediction.py
  src/workflows/dags/ml_training_jobs.py
Labels: work in progress, ready for review

#3067 change base URL for forgot password link -- in new Analytics
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
  src/auth-service/utils/test/ut_email.msgs.js
Labels: ready for review

#3069 fix forgort password link for new Analytics
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#3070 enhancing client activation
  src/auth-service/config/global/db-projections.js
  src/auth-service/controllers/create-client.js
  src/auth-service/models/Client.js
  src/auth-service/routes/v2/clients.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3071 Minor PR to trigger secrets update
  src/gp-model/config.py
  src/gp-model/data/data.py
  src/gp-model/data/preprocess.py
  src/gp-model/helpers/get_data.py
  src/gp-model/main.py
  src/gp-model/tests/test_preprocess.py
  src/predict/api/prediction.py
  src/workflows/airqo_etl_utils/airqo_api.py
  src/workflows/airqo_etl_utils/app_notification_utils.py
  src/workflows/airqo_etl_utils/config.py
  src/workflows/dags/app_notifications.py
Labels: ready for review

#3072 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/gp-model/config.py
  src/gp-model/data/data.py
  src/gp-model/data/preprocess.py
  src/gp-model/helpers/get_data.py
  src/gp-model/main.py
  src/gp-model/tests/test_preprocess.py
  src/predict/api/prediction.py
  src/workflows/airqo_etl_utils/airqo_api.py
  src/workflows/airqo_etl_utils/app_notification_utils.py
  src/workflows/airqo_etl_utils/config.py
  src/workflows/dags/app_notifications.py
Labels: ready for review

#3073 reduce user details in client details
  src/auth-service/config/global/db-projections.js
Labels: ready for review

#3075 adjustments to email sent and API response when deactivating clients
  src/auth-service/controllers/create-client.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3076 Enhanced Filtering Capabilities for Private Sites and Devices
  src/device-registry/routes/v2/cohorts.js
  src/device-registry/routes/v2/grids.js
  src/device-registry/utils/create-cohort.js
  src/device-registry/utils/create-grid.js
  src/device-registry/utils/errors.js
Labels: ready for review

#3078 enriching the log statement for inactive client
  src/auth-service/utils/control-access.js
Labels: ready for review

#3077 Minor Fixes Push Notifications
  src/workflows/airqo_etl_utils/app_notification_utils.py
  src/workflows/dags/app_notifications.py
Labels: ready for review

#3079 enriching the log statement for inactive token
  src/auth-service/utils/control-access.js
Labels: ready for review

#3080 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#3082 Update README.md of entire API repo
  README.md
Labels: ready for review

#3084 Analytics fix
  src/analytics/api/utils/data_formatters.py
  src/analytics/config.py
Labels: ready for review

#3083 move to production
  README.md
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/analytics/api/utils/data_formatters.py
  src/analytics/config.py
Labels: ready for review

#3086 Adding CORS in spatial
  src/spatial/app.py
Labels: ready for review

#3088 Batch users when sending app_notifications
  src/workflows/dags/app_notifications.py
Labels: ready for review

#3081 MODIS Aerosol_optical_depth
  src/meta-data/api/controllers/extract.py
  src/meta-data/api/models/extract.py
  src/meta-data/api/routes/api.py
Labels: ready for review, priority-medium

#3091 always return data for recent events endpoint
  src/device-registry/controllers/create-event.js
  src/device-registry/models/Reading.js
  src/device-registry/routes/v2/readings.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3093 resolve runtime error on new readings endpoint
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3095 expanding the search range for recent readings
  src/device-registry/models/Reading.js
Labels: ready for review

#3096 Nan to null
  src/analytics/api/models/base/data_processing.py
  src/analytics/api/models/base/diurnal_data_processing.py
Labels: ready for review, priority-high

#3097 resolving runtime around emailing reports
  src/auth-service/utils/mailer.js
Labels: ready for review

#3098 fixing the filter for readings
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3099 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3094 Spatial k8s and ci/cd
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/nginx/production/analytics-vs.yaml
  k8s/nginx/production/api-vs.yaml
  k8s/nginx/production/platform-vs.yaml
  k8s/nginx/staging/analytics-vs.yaml
  k8s/nginx/staging/api-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
  k8s/spatial/.helmignore
  k8s/spatial/Chart.yaml
  k8s/spatial/templates/NOTES.txt
  k8s/spatial/templates/_helpers.tpl
  k8s/spatial/templates/deployment.yaml
  k8s/spatial/templates/hpa.yaml
  k8s/spatial/templates/service.yaml
  k8s/spatial/templates/tests/test-connection.yaml
  k8s/spatial/values-prod.yaml
  k8s/spatial/values-stage.yaml
  src/spatial/Dockerfile
Labels: ready for review

#3105 Trigger Backend Apps
  src/calibrate/readme.md
  src/data-mgt/README.md
  src/data-proxy/README.md
  src/device-status/README.md
  src/exceedances/README.md
  src/gp-model/README.md
  src/incentives/README.md
  src/locate/README.md
  src/meta-data/README.md
  src/predict/README.md
  src/view/README.md
Labels: ready for review

#3107 for recent readings, changing defaults to 3 days back
  src/device-registry/models/Reading.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3106 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-stage.yaml
  k8s/data-proxy/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/exceedance/values-stage-airqo.yaml
  k8s/exceedance/values-stage-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  k8s/locate/values-prod.yaml
  k8s/locate/values-stage.yaml
  k8s/meta-data/values-prod.yaml
  k8s/meta-data/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  k8s/view/values-prod.yaml
  k8s/view/values-stage.yaml
  k8s/workflows/values-prod.yaml
  src/calibrate/readme.md
  src/data-mgt/README.md
  src/data-proxy/README.md
  src/device-registry/models/Reading.js
  src/device-registry/utils/generate-filter.js
  src/device-status/README.md
  src/exceedances/README.md
  src/gp-model/README.md
  src/incentives/README.md
  src/locate/README.md
  src/meta-data/README.md
  src/predict/README.md
  src/view/README.md
Labels: ready for review

#3108 enhancing the general welcome email
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#3110 Update Push notification messages for the different categories
  src/workflows/airqo_etl_utils/app_notification_utils.py
  src/workflows/dags/app_notifications.py
Labels: ready for review

#3109 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/calibrate/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/data-proxy/values-stage.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-status/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/exceedance/values-stage-airqo.yaml
  k8s/exceedance/values-stage-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  k8s/locate/values-prod.yaml
  k8s/locate/values-stage.yaml
  k8s/meta-data/values-prod.yaml
  k8s/meta-data/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  k8s/view/values-prod.yaml
  k8s/view/values-stage.yaml
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.msgs.js
  src/workflows/airqo_etl_utils/app_notification_utils.py
  src/workflows/dags/app_notifications.py
Labels: ready for review

#3112 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/nginx/production/platform-vs.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
Labels: ready for review

#3113 Minor name modifications to Push notifs
  src/workflows/airqo_etl_utils/app_notification_utils.py
Labels: ready for review

#3114 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/airqo_etl_utils/app_notification_utils.py
Labels: ready for review

#3085 Fault detection udpates
  src/predict/api/helpers.py
  src/predict/api/prediction.py
  src/workflows/Dockerfile
  src/workflows/airqo_etl_utils/airqo_utils.py
  src/workflows/airqo_etl_utils/app_notification_utils.py
  src/workflows/airqo_etl_utils/bigquery_api.py
  src/workflows/airqo_etl_utils/ml_utils.py
  src/workflows/airqo_etl_utils/setup.py
  src/workflows/airqo_etl_utils/tests/test_ml_utils.py
  src/workflows/dags/app_notifications.py
  src/workflows/dags/fault_detection_job.py
  src/workflows/dags/ml_prediction_jobs.py
  src/workflows/dags/ml_training_jobs.py
  src/workflows/requirements.txt
  src/workflows/workflows-requirements.txt
Labels: ready for review

#3116 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/predict/api/helpers.py
  src/predict/api/prediction.py
  src/workflows/Dockerfile
  src/workflows/airqo_etl_utils/airqo_utils.py
  src/workflows/airqo_etl_utils/app_notification_utils.py
  src/workflows/airqo_etl_utils/bigquery_api.py
  src/workflows/airqo_etl_utils/ml_utils.py
  src/workflows/airqo_etl_utils/setup.py
  src/workflows/airqo_etl_utils/tests/test_ml_utils.py
  src/workflows/dags/app_notifications.py
  src/workflows/dags/fault_detection_job.py
  src/workflows/dags/ml_prediction_jobs.py
  src/workflows/dags/ml_training_jobs.py
  src/workflows/requirements.txt
  src/workflows/workflows-requirements.txt
Labels: ready for review

#3118 Update README.md of device registry
  src/device-registry/README.md
Labels: ready for review

#3119 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/README.md
Labels: ready for review
