Repository airqo-platform/AirQo-api, pull requests merged in 2024-02, with the labels that each got.

#3001 endpoints for managing the notification settings of users
  src/auth-service/controllers/create-user.js
  src/auth-service/models/Subscription.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3004 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/controllers/create-user.js
  src/auth-service/models/Subscription.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3005 Only send to subscribed BCC emails
  src/auth-service/utils/mailer.js
Labels: ready for review

#3006 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/mailer.js
Labels: ready for review

#3007 setup new endpoint for all forecasts
  src/predict/api/.gitignore
  src/predict/api/app.py
  src/predict/api/config.py
  src/predict/api/helpers.py
  src/predict/api/logging_config.json
  src/predict/api/prediction.py
  src/predict/api/routes.py
Labels: ready for review, predict

#3010 move to production
  k8s/auth-service/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  k8s/workflows/values-prod.yaml
  src/predict/api/.gitignore
  src/predict/api/app.py
  src/predict/api/config.py
  src/predict/api/helpers.py
  src/predict/api/logging_config.json
  src/predict/api/prediction.py
  src/predict/api/routes.py
Labels: ready for review

#3011 fix issues with forgot password feature
  src/auth-service/utils/create-user.js
Labels: ready for review

#3012 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/create-user.js
Labels: ready for review

#3016 remove 176 from blacklisted prefixes
  src/auth-service/utils/control-access.js
Labels: ready for review

#3017 move to production
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#3019 Returning error messages in device monitoring
  src/device-monitoring/app.py
Labels: ready for review

#3025 [View microservice] Update README.md
  src/view/README.md
Labels: ready for review

#3022 [device monitoring] Update README.md
  src/device-monitoring/README.md
Labels: ready for review

#3024 [Device Status] Update README.md
  src/device-status/README.md
Labels: ready for review

#3018 move to production
  k8s/auth-service/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-stage.yaml
  k8s/workflows/values-prod.yaml
  src/device-monitoring/README.md
  src/device-monitoring/app.py
  src/device-status/README.md
  src/view/README.md
Labels: ready for review

#3003 auto reporting
  src/analytics/.gitignore
  src/analytics/api/models/base/data_processing.py
  src/analytics/api/utils/pollutants/report.py
  src/analytics/config.py
  src/analytics/manage.py
  src/analytics/requirements.txt
Labels: ready for review, priority-high

#3014 Upgrading and Personalising Mobile App Email and Push Notifications
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
  src/firebase/auth/functions/package.json
  src/firebase/auth/functions/utils/firebaseConfig.js
  src/firebase/auth/functions/utils/utils.js
  src/firebase/auth/package.json
Labels: ready for review

#3027 fix runtime error on user deletion
  src/auth-service/utils/create-user.js
Labels: ready for review

#3028 hotfixing user creation
  src/auth-service/utils/create-user.js
Labels: ready for review

#3031 En assistance inquiries
  src/auth-service/config/global/envs.js
  src/auth-service/routes/v2/inquiries.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3034 Minor fixes: Mobile App
  src/auth-service/utils/create-user.js
  src/firebase/auth/functions/index.js
Labels: ready for review

#3030 Move reporting
  src/analytics/api/models/base/data_processing.py
  src/analytics/api/utils/pollutants/report.py
  src/analytics/jobs/reports/config.py
  src/analytics/manage.py
Labels: ready for review

#3026 move to production
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/analytics/.gitignore
  src/analytics/config.py
  src/analytics/jobs/reports/config.py
  src/analytics/manage.py
  src/analytics/requirements.txt
  src/auth-service/config/global/envs.js
  src/auth-service/routes/v2/inquiries.js
  src/auth-service/utils/create-user.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
  src/firebase/auth/functions/package.json
  src/firebase/auth/functions/utils/firebaseConfig.js
  src/firebase/auth/functions/utils/utils.js
  src/firebase/auth/package.json
Labels: ready for review

#3037 new endpoint to activate or deactivate client
  src/auth-service/config/global/db-projections.js
  src/auth-service/controllers/create-client.js
  src/auth-service/models/Client.js
  src/auth-service/routes/v2/clients.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#3039 Fix `Resource not found` error causing `mlflow` to not render on airqo domain
  k8s/mlflow/templates/deployment.yaml
Labels: ready for review, k8s

#3040 updating developer email content
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#3041 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#3042 Increasing resources for Redis
  k8s/redis/templates/deployment.yaml
  k8s/redis/values-stage.yaml
Labels: ready for review

#3043 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/redis/templates/deployment.yaml
  k8s/redis/values-stage.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
Labels: ready for review

#3036 reporting API
  src/analytics/api/docs/report/generate_grid_report_post.yml
  src/analytics/api/models/base/data_processing.py
  src/analytics/api/utils/pollutants/report.py
  src/analytics/api/views/report.py
  src/analytics/config.py
  src/analytics/manage.py
  src/analytics/requirements.txt
Labels: data-engineering, priority-high

#3049 block 142
  src/auth-service/utils/control-access.js
Labels: ready for review

#3051 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#3052 [Recent Measurements Hotfix] checking params when generating cache ID
  src/device-registry/utils/create-event.js
Labels: hotfix, ready for review

#3053 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/utils/create-event.js
Labels: ready for review

#3054 adding 35 to the blocked prefixes
  src/auth-service/utils/control-access.js
Labels: ready for review

#3055 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#3056 undo the 35 block
  src/auth-service/utils/control-access.js
Labels: ready for review

#3057 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#3060 comment out bigquery
  src/predict/jobs/predict_places_air_quality/main.py
Labels: ready for review, priority-high

#3059 Fixing Device Uptime
  src/device-uptime/config.py
  src/device-uptime/utils/device_hourly_records.py
Labels: ready for review

#3048 Add flitering of private devices & sites
  src/analytics/.gitignore
  src/analytics/api/models/base/data_processing.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/utils/pollutants/report.py
  src/analytics/api/views/dashboard.py
  src/analytics/api/views/data.py
  src/analytics/api/views/report.py
  src/analytics/config.py
  src/analytics/jobs/reports/config.py
  src/analytics/main.py
  src/analytics/manage.py
Labels: ready for review

#3046 Spatial local moran
  src/spatial/controllers/note.txt
  src/spatial/controllers/tests/note.txt
  src/spatial/helpers/note.txt
  src/spatial/helpers/tests/note.txt
  src/spatial/job/local_moran/.gitignore
  src/spatial/job/local_moran/README.md
  src/spatial/job/local_moran/app.py
  src/spatial/job/local_moran/configure.py
  src/spatial/job/local_moran/controllers/controller.py
  src/spatial/job/local_moran/main.py
  src/spatial/job/local_moran/models/model.py
  src/spatial/job/local_moran/requirements.txt
  src/spatial/job/local_moran/services/localmoran_services.py
  src/spatial/models/note.txt
  src/spatial/models/tests/note.txt
  src/spatial/note.txt
  src/spatial/routes/note.txt
  src/spatial/routes/tests/note.txt
Labels: data-engineering, ready for review, priority-high
