Repository airqo-platform/AirQo-api, pull requests merged in 2024-07, with the labels that each got.

#3248 just triggering new ENVs for BCC emails
  src/auth-service/README.md
Labels: ready for review

#3249 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/README.md
Labels: ready for review

#3237 Fix missing Latitude and Longitude meta-data in extract_raw_data()
  src/workflows/airqo_etl_utils/airqo_api.py
  src/workflows/airqo_etl_utils/airqo_utils.py
Labels: data-engineering, ready for review

#3236 Fix aggregate_data method to work with pandas 2.X.X
  src/workflows/airqo_etl_utils/weather_data_utils.py
Labels: data-engineering, ready for review

#3251 just resolving a runtime for expired tokens email notifications
  src/auth-service/utils/control-access.js
Labels: ready for review

#3250 move to production
  gx/.gitignore
  gx/README.md
  gx/checkpoints/.gitkeep
  gx/dev-requirements.txt
  gx/expectations/.ge_store_backend_id
  gx/expectations/air_quality_completeness.json
  gx/expectations/air_quality_consistency_across_sensors.json
  gx/expectations/air_quality_data_quality.json
  gx/expectations/air_quality_referential_integrity.json
  gx/expectations/air_quality_schema_validation.json
  gx/expectations/air_quality_statistical_anomalies.json
  gx/expectations/air_quality_temporal_consistency.json
  gx/expectations/air_quality_uniqueness_integrity.json
  gx/great_expectations.yml
  gx/plugins/custom_data_docs/styles/data_docs_custom_styles.css
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/utils/control-access.js
  src/workflows/airqo_etl_utils/airqo_api.py
  src/workflows/airqo_etl_utils/airqo_utils.py
  src/workflows/airqo_etl_utils/weather_data_utils.py
Labels: ready for review

#3252 adding the token name in the email alert
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3253 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3256 platform domain redirect to analytics domain
  k8s/nginx/production/platform-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
Labels: ready for review

#3257 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/nginx/production/platform-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
Labels: ready for review

#3258 predict by parish
  src/predict/jobs/predict_places_air_quality/main.py
  src/predict/jobs/predict_places_air_quality/utils.py
Labels: ready for review, priority-high

#3259 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/predict/jobs/predict_places_air_quality/main.py
  src/predict/jobs/predict_places_air_quality/utils.py
Labels: ready for review

#3260 just triggering a change of ENVS in the predict places job
  src/predict/jobs/predict_places_air_quality/README.md
Labels: ready for review

#3261 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  k8s/workflows/values-prod.yaml
  src/predict/jobs/predict_places_air_quality/README.md
Labels: ready for review

#3262 Feature/Integrate Great Expectations into Airflow DAGs
  gx/README.md
  gx/__init__.py
  gx/expectations/air_quality_range_validation.json
  src/workflows/Dockerfile
  src/workflows/dags/airqo_measurements.py
Labels: data-engineering, ready for review, data-mgt

#3267 For optimisation, reducing default limit from 1000 to 100
  src/auth-service/models/User.js
  src/auth-service/routes/v2/candidates.js
  src/auth-service/routes/v2/checklist.js
  src/auth-service/routes/v2/clients.js
  src/auth-service/routes/v2/defaults.js
  src/auth-service/routes/v2/departments.js
  src/auth-service/routes/v2/favorites.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/routes/v2/inquiries.js
  src/auth-service/routes/v2/locationHistory.js
  src/auth-service/routes/v2/networks-old.js
  src/auth-service/routes/v2/networks.js
  src/auth-service/routes/v2/permissions.js
  src/auth-service/routes/v2/preferences.js
  src/auth-service/routes/v2/requests.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/routes/v2/scopes.js
  src/auth-service/routes/v2/searchHistory.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/routes/v2/types.js
  src/auth-service/routes/v2/users.js
Labels: ready for review

#3265 move to production
  gx/README.md
  gx/__init__.py
  gx/expectations/air_quality_range_validation.json
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/models/User.js
  src/auth-service/routes/v2/candidates.js
  src/auth-service/routes/v2/checklist.js
  src/auth-service/routes/v2/clients.js
  src/auth-service/routes/v2/defaults.js
  src/auth-service/routes/v2/departments.js
  src/auth-service/routes/v2/favorites.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/routes/v2/inquiries.js
  src/auth-service/routes/v2/locationHistory.js
  src/auth-service/routes/v2/networks-old.js
  src/auth-service/routes/v2/networks.js
  src/auth-service/routes/v2/permissions.js
  src/auth-service/routes/v2/preferences.js
  src/auth-service/routes/v2/requests.js
  src/auth-service/routes/v2/roles.js
  src/auth-service/routes/v2/scopes.js
  src/auth-service/routes/v2/searchHistory.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/routes/v2/types.js
  src/auth-service/routes/v2/users.js
  src/workflows/Dockerfile
  src/workflows/dags/airqo_measurements.py
Labels: ready for review

#3269 move to production
  .pre-commit-config.yaml
  gx/dev-requirements.txt
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/airqo_etl_utils/airqo_api.py
  src/workflows/airqo_etl_utils/airqo_utils.py
  src/workflows/airqo_etl_utils/setup.py
  src/workflows/dev-requirements.txt
Labels: ready for review

#3270 just sorting our secrets issues
  src/workflows/README.md
Labels: work in progress

#3271 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/README.md
Labels: ready for review

#3272 Hotfix/invalid great expectations args
  gx/README.md
  gx/great_expectations.yml
  src/workflows/dags/airqo_measurements.py
Labels: bug, hotfix, priority-high

#3274 patch-broken-dag-airqo-measurements
  src/workflows/dags/airqo_measurements.py
Labels: bug, hotfix, priority-high

#3276 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/dags/airqo_measurements.py
Labels: ready for review

#3275 Correct the current year in outgoing Emails
  src/auth-service/config/global/email-templates.js
  src/firebase/auth/functions/config/emailTemplates.js
  src/workflows/airqo_etl_utils/email_templates.py
Labels: hotfix, ready for review

#3277 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/config/global/email-templates.js
  src/firebase/auth/functions/config/emailTemplates.js
  src/workflows/airqo_etl_utils/email_templates.py
Labels: ready for review

#3281 addressing missing token description in expire token notifications
  src/auth-service/utils/control-access.js
Labels: ready for review

#3282 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#3286 Correct Port for Reports Service
  k8s/nginx/production/platform-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
Labels: ready for review

#3288 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/nginx/production/platform-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
  src/workflows/airqo_etl_utils/airqo_utils.py
Labels: ready for review

#3290 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/airqo_etl_utils/airqo_utils.py
Labels: ready for review

#3264 Change subscribe clause for compulsory emails
  src/auth-service/config/global/email-templates.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/email.templates.js
Labels: ready for review

#3284 Type Error Fix & Unit test for AirQo-Historical-Hourly-Measurements (extract_aggregated_raw_data)
  src/workflows/airqo_etl_utils/airqo_utils.py
  src/workflows/airqo_etl_utils/tests/test_airqo_utils.py
Labels: data-engineering, ready for review

#3293 just adding firstName and lastName to the use stats
  src/auth-service/models/User.js
Labels: ready for review

#3294 just to trigger deployment of workflows
  src/workflows/README.md
Labels: ready for review

#3295 move to production
  k8s/analytics/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  src/workflows/README.md
Labels: ready for review

#3296 just retriggering auth-service
  src/auth-service/README.md
Labels: ready for review

#3297 move to production
  k8s/analytics/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/README.md
Labels: ready for review

#3298 AirQo-Historical-Hourly-Measurements Unit Tests
  src/workflows/airqo_etl_utils/tests/test_airqo_utils.py
Labels: ready for review

#3300 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/airqo_etl_utils/tests/test_airqo_utils.py
Labels: ready for review

#3304 updating AQI breakpoints due to recent EPA updates
  src/device-registry/README.md
  src/device-registry/models/Event.js
Labels: ready for review

#3305 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/README.md
  src/device-registry/models/Event.js
Labels: ready for review

#3308 Increase Resources for Workflows to fix Sigkill for some DAGs
  k8s/workflows/values-prod.yaml
Labels: ready for review

#3306 move to production
  gx/.gitignore
  gx/README.md
  gx/__init__.py
  gx/checkpoints/.gitkeep
  gx/dev-requirements.txt
  gx/expectations/.ge_store_backend_id
  gx/expectations/air_quality_completeness.json
  gx/expectations/air_quality_consistency_across_sensors.json
  gx/expectations/air_quality_data_quality.json
  gx/expectations/air_quality_range_validation.json
  gx/expectations/air_quality_referential_integrity.json
  gx/expectations/air_quality_schema_validation.json
  gx/expectations/air_quality_statistical_anomalies.json
  gx/expectations/air_quality_temporal_consistency.json
  gx/expectations/air_quality_uniqueness_integrity.json
  gx/great_expectations.yml
  gx/plugins/custom_data_docs/styles/data_docs_custom_styles.css
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/workflows/airqo_etl_utils/airqo_gx_metrics.py
  src/workflows/airqo_etl_utils/airqo_gx_utils.py
  src/workflows/airqo_etl_utils/setup.py
  src/workflows/dev-requirements.txt
Labels: ready for review
