Repository airqo-platform/AirQo-api, pull requests merged in 2024-06, with the labels that each got.

#3211 hotfixing the email for incomplete profiles
  src/auth-service/config/global/email-templates.js
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#3212 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/config/global/email-templates.js
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#3213 resolve the runtime for case where name is udefined during emails
  src/auth-service/config/global/email-templates.js
Labels: ready for review

#3214 move to production
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/config/global/email-templates.js
Labels: ready for review

#3215 Fix DAG configuration for 'AirQo-Historical-Bam-Measurements'
  src/workflows/dags/airqo_bam_measurements.py
Labels: data-engineering

#3217 Update Workflows ReadMe.
  src/workflows/README.md
Labels: ready for review

#3218 sends an email alert to User whenever they try to register using already existing email
  src/auth-service/models/User.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3216 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/models/User.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
  src/workflows/README.md
  src/workflows/dags/airqo_bam_measurements.py
Labels: ready for review

#3220 Fix Skipping of Email-notifs Dag runs.
  src/workflows/dags/app_notifications.py
Labels: ready for review

#3219 Updated DAG definitions with correct parameters and schedule intervals
  src/workflows/dags/airnow.py
Labels: data-engineering, ready for review

#3221 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/dags/airnow.py
  src/workflows/dags/app_notifications.py
Labels: ready for review

#3222 Only notify on deployment and recall activities
  src/auth-service/middleware/passport.js
Labels: ready for review

#3223 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/middleware/passport.js
Labels: ready for review

#3225 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-stage.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/spatial/views/derived_pm2_5.py
  src/spatial/views/localmoran_services.py
Labels: ready for review

#3226 Setup device weather data downloads
  src/analytics/api/models/base/data_processing.py
  src/analytics/api/models/base/diurnal_data_processing.py
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/utils/pollutants/pm_25.py
  src/analytics/api/utils/pollutants/report.py
  src/analytics/api/views/data.py
  src/analytics/config.py
  src/analytics/manage.py
Labels: ready for review

#3228 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/analytics/api/models/base/data_processing.py
  src/analytics/api/models/base/diurnal_data_processing.py
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/utils/pollutants/pm_25.py
  src/analytics/api/utils/pollutants/report.py
  src/analytics/api/views/data.py
  src/analytics/config.py
  src/analytics/manage.py
Labels: ready for review

#3229 Update datetime usage: change datetime.utcnow() to datetime.now(timez…
  src/workflows/airqo_etl_utils/commons.py
  src/workflows/airqo_etl_utils/date.py
  src/workflows/airqo_etl_utils/utils.py
  src/workflows/airqo_etl_utils/weather_data_utils.py
  src/workflows/airqo_etl_utils/workflows_custom_utils.py
  src/workflows/dags/airnow.py
  src/workflows/dags/airqo_bam_measurements.py
  src/workflows/dags/app_notifications.py
  src/workflows/dags/daily_measurements.py
  src/workflows/dags/data_summary.py
  src/workflows/dags/kcca_measurements.py
  src/workflows/dags/ml_prediction_jobs.py
  src/workflows/dags/urban_better_measurements.py
  src/workflows/dags/weather_measurements.py
Labels: python, ready for review

#3233 Enhanced Data Acquisition Speed Through Parallel Computing
  src/spatial/models/pull_satellite_model.py
  src/spatial/views/derived_pm2_5.py
Labels: ready for review, priority-medium

#3235 Add Pidgin translations For KYA lessons, healthtips and Quiz
  src/device-registry/utils/translate.js
Labels: ready for review

#3232 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-stage.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/device-registry/utils/translate.js
  src/spatial/models/pull_satellite_model.py
  src/spatial/views/derived_pm2_5.py
  src/workflows/airqo_etl_utils/airqo_api.py
  src/workflows/airqo_etl_utils/bigquery_api.py
  src/workflows/airqo_etl_utils/commons.py
  src/workflows/airqo_etl_utils/date.py
  src/workflows/airqo_etl_utils/utils.py
  src/workflows/airqo_etl_utils/weather_data_utils.py
  src/workflows/airqo_etl_utils/workflows_custom_utils.py
  src/workflows/dags/airnow.py
  src/workflows/dags/airqo_bam_measurements.py
  src/workflows/dags/airqo_measurements.py
  src/workflows/dags/app_notifications.py
  src/workflows/dags/daily_measurements.py
  src/workflows/dags/data_summary.py
  src/workflows/dags/kcca_measurements.py
  src/workflows/dags/ml_prediction_jobs.py
  src/workflows/dags/urban_better_measurements.py
  src/workflows/dags/weather_measurements.py
Labels: ready for review

#3238 Hotfix for failing data export
  src/analytics/api/models/events.py
Labels: ready for review

#3239 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/analytics/api/models/events.py
Labels: ready for review

#3240 Remove random locations from notifications
  src/workflows/airqo_etl_utils/app_notification_utils.py
Labels: ready for review

#3241 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/airqo_etl_utils/app_notification_utils.py
Labels: ready for review

#3244 Enhancements for expired and expiring tokens
  src/auth-service/bin/token-expiration-job.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3245 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/bin/token-expiration-job.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3243 Update Consolidated-Data-ETL DAG Schedule to Run Twice Daily
  src/workflows/dags/data_warehouse.py
Labels: data-engineering, ready for review

#3247 just a minor correction to the logging statement for expired tokens
  src/auth-service/utils/control-access.js
Labels: ready for review

#3246 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/utils/control-access.js
  src/workflows/dags/data_warehouse.py
Labels: ready for review
