Repository airqo-platform/AirQo-api, pull requests merged in 2024-05, with the labels that each got.

#3164 Analytics Top Cards: Extend the default search filter to 7 days
  src/device-registry/models/Reading.js
Labels: ready for review

#3165 move to production
  k8s/analytics/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/gp-model/values-stage.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/meta-data/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-stage.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/models/Reading.js
Labels: ready for review

#3166 remove the one hour expiry on JWTs
  src/auth-service/models/User.js
Labels: ready for review

#3167 move to production
  k8s/analytics/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/models/User.js
Labels: ready for review

#3169 trigger microservices
  src/auth-service/README.md
  src/device-registry/README.md
Labels: ready for review

#3170 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/README.md
  src/device-registry/README.md
Labels: ready for review

#3171 reduce the input validation precision to 1 dec place
  src/device-registry/routes/v2/sites.js
Labels: ready for review

#3172 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/routes/v2/sites.js
Labels: ready for review

#3157 Update data calibration to use airqloud specific models
  src/calibrate/.gitignore
  src/calibrate/Jenkinsfile
  src/calibrate/app.py
  src/calibrate/bin/start.sh
  src/calibrate/calibrate.py
  src/calibrate/cicd-build-trigger
  src/calibrate/controllers/__init__.py
  src/calibrate/controllers/calibrate.py
  src/calibrate/helpers/.gitkeep
  src/calibrate/jobs/.gitkeep
  src/calibrate/jobs/regression.py
  src/calibrate/jobs/train_calibrate_tool.py
  src/calibrate/models/.gitkeep
  src/calibrate/models/calibrate_tool.py
  src/calibrate/models/regression.py
  src/calibrate/models/train_calibrate_tool.py
  src/calibrate/readme.md
  src/calibrate/routes.py
  src/calibrate/routes/api.py
  src/workflows/Dockerfile
  src/workflows/README.md
  src/workflows/airqo_etl_utils/airqo_api.py
  src/workflows/airqo_etl_utils/airqo_utils.py
  src/workflows/airqo_etl_utils/app_notification_utils.py
  src/workflows/airqo_etl_utils/calibration_utils.py
  src/workflows/airqo_etl_utils/config.py
  src/workflows/airqo_etl_utils/constants.py
  src/workflows/airqo_etl_utils/email_templates.py
  src/workflows/airqo_etl_utils/forecast_data_utils.py
  src/workflows/airqo_etl_utils/setup.py
  src/workflows/airqo_etl_utils/utils.py
  src/workflows/dags/airqo_measurements.py
  src/workflows/dags/airqo_mobile_measurements.py
  src/workflows/dags/app_notifications.py
  src/workflows/dags/dag_docs.py
  src/workflows/dags/task_docs.py
  src/workflows/dev-requirements.txt
  src/workflows/docker-compose.yaml
  src/workflows/main.py
  src/workflows/run-workflows-only.sh
  src/workflows/schedule-dag.py
  workflow-trigger
Labels: ready for review

#3174 Trigger CI/CD
  src/workflows/dags/airqo_mobile_measurements.py
Labels: ready for review

#3176 HOTFIX - fixes issue of missing data for some devices
  src/workflows/airqo_etl_utils/airqo_utils.py
  src/workflows/airqo_etl_utils/message_broker_utils.py
Labels: ready for review

#3175 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/kafka/BigQuery-connectors/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/workflows/airqo_etl_utils/airqo_utils.py
  src/workflows/airqo_etl_utils/message_broker_utils.py
  src/workflows/dags/airqo_mobile_measurements.py
Labels: ready for review

#3177 Remove null rows before model predictions
  src/workflows/airqo_etl_utils/airqo_utils.py
Labels: ready for review

#3178 move to production
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/workflows/airqo_etl_utils/airqo_utils.py
Labels: ready for review

#3179 Replace infinite values with 0
  src/workflows/airqo_etl_utils/airqo_utils.py
Labels: ready for review

#3180 move to production
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/workflows/airqo_etl_utils/airqo_utils.py
Labels: ready for review

#3181 just temporarily disabling delete of preferences
  src/auth-service/utils/create-preference.js
Labels: ready for review

#3182 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/utils/create-preference.js
Labels: ready for review

#3183 only returned nearest AirQo sites which are active
  src/device-registry/models/Site.js
  src/device-registry/utils/create-site.js
Labels: ready for review

#3184 move to production
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/models/Site.js
  src/device-registry/utils/create-site.js
Labels: ready for review

#3185 hotfix for saving preferences
  src/auth-service/utils/create-preference.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#3186 move to production
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-monitor/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/utils/create-preference.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#3188 email alerts for expiring tokens
  src/auth-service/bin/server.js
  src/auth-service/bin/token-expiration-job.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: hotfix, ready for review

#3192 Hotfix token expiration - handling potential timezone errors
  src/auth-service/bin/token-expiration-job.js
Labels: ready for review

#3189 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/bin/server.js
  src/auth-service/bin/token-expiration-job.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3144 Implement Monthly Reminder for Users with Unknown First Name
  src/auth-service/bin/incomplete-profile-job.js
  src/auth-service/bin/server.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3193 move to production
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/bin/incomplete-profile-job.js
  src/auth-service/bin/server.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3194 remove bcc from update profile emails
  src/auth-service/utils/mailer.js
Labels: ready for review

#3195 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/utils/mailer.js
Labels: ready for review

#3196 introducing conditional JWT authentication
  src/auth-service/middleware/passport.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/utils/create-group.js
Labels: ready for review

#3197 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/middleware/passport.js
  src/auth-service/routes/v2/groups.js
  src/auth-service/utils/create-group.js
Labels: ready for review

#3190 sateliteAOD
  src/spatial/configure.py
  src/spatial/controllers/controllers.py
  src/spatial/models/pull_satellite_model.py
  src/spatial/requirements.txt
  src/spatial/views/derived_pm2_5.py
Labels: ready for review, priority-medium

#3199 move to production
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/spatial/configure.py
  src/spatial/controllers/controllers.py
  src/spatial/models/pull_satellite_model.py
  src/spatial/requirements.txt
  src/spatial/views/derived_pm2_5.py
Labels: ready for review

#3200 change email greeting depending on name availability
  src/auth-service/config/global/email-templates.js
Labels: ready for review

#3203 derived pm25
  src/spatial/controllers/controllers.py
  src/spatial/views/derived_pm2_5.py
Labels: ready for review, priority-high

#3205 fix runtime when sending emails with undefined name
  src/auth-service/config/global/email-templates.js
Labels: ready for review

#3206 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-stage.yaml
  k8s/view/values-prod.yaml
  src/auth-service/config/global/email-templates.js
Labels: ready for review

#3207 addressing runtime errors around emailing for 2 jobs
  src/auth-service/bin/incomplete-profile-job.js
  src/auth-service/bin/token-expiration-job.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3208 move to production
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/bin/incomplete-profile-job.js
  src/auth-service/bin/token-expiration-job.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#3209 temporarily remove bcc emails from compromised tokens
  src/auth-service/utils/mailer.js
Labels: ready for review

#3210 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/utils/mailer.js
Labels: ready for review
