Repository airqo-platform/AirQo-api, pull requests merged in 2024-11, with the labels that each got.

#3797 remove unnecessary log
  src/auth-service/models/Maintenance.js
Labels: ready for review

#3798 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/models/Maintenance.js
Labels: ready for review

#3799 creating a custom 404 error page
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#3801 resolving the unknown escape sequence
  k8s/nginx/staging/global-config.yaml
Labels: ready for review

#3802 Removed the .customSanitizer() blocks that were forcing 5 decimal places
  src/device-registry/routes/v2/sites.js
  src/device-registry/utils/create-site.js
Labels: ready for review

#3803 Modify Kafka yaml configurations
  k8s/kafka/clusters/kafka-cluster.yaml
Labels: ready for review

#3800 move to production
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/kafka/clusters/kafka-cluster.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/nginx/staging/global-config.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/routes/v2/sites.js
  src/device-registry/utils/create-site.js
Labels: ready for review

#3810 fix the update endpoint for device maintenance
  src/auth-service/utils/create-maintenance.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#3809 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/kafka/clusters/kafka-cluster-prod.yaml
  k8s/kafka/clusters/kafka-cluster-stage.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/create-maintenance.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#3811 removing the name as one of Site identifiers
  src/device-registry/models/Site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3812 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/models/Site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3813 just retriggering device-registry
  src/device-registry/README.md
Labels: ready for review

#3807 add code to save model predictions to BigQuery
  src/spatial/configure.py
  src/spatial/views/derived_pm2_5.py
  src/spatial/views/satellite_predictions.py
Labels: ready for review

#3815 retrigger 3 microservices
  src/auth-service/README.md
  src/device-registry/README.md
  src/spatial/README.md
Labels: ready for review

#3814 move to production
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/spatial/values-stage.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/README.md
  src/spatial/README.md
  src/spatial/configure.py
  src/spatial/views/derived_pm2_5.py
  src/spatial/views/satellite_predictions.py
Labels: ready for review

#3818 move to production
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/meta-data/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/spatial/values-stage.yaml
  k8s/view/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/utils/http.py
  src/analytics/api/utils/request_validators.py
  src/analytics/api/views/dashboard.py
  src/analytics/api/views/data.py
  src/analytics/api/views/report.py
  src/analytics/requirements.txt
Labels: ready for review

#3822 feat: Add duplicate site fields detection job with comprehensive test coverage
  src/device-registry/bin/jobs/check-duplicate-site-fields-job.js
  src/device-registry/bin/jobs/test/ut_check-duplicate-site-fields-job.js
  src/device-registry/bin/server.js
Labels: ready for review

#3823 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-registry/bin/jobs/check-duplicate-site-fields-job.js
  src/device-registry/bin/jobs/test/ut_check-duplicate-site-fields-job.js
  src/device-registry/bin/server.js
Labels: ready for review

#3826 opmise db query during duplicate detection
  src/device-registry/bin/jobs/check-duplicate-site-fields-job.js
Labels: ready for review

#3827 move to production
  k8s/analytics/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-registry/bin/jobs/check-duplicate-site-fields-job.js
Labels: ready for review

#3829 Refactor Duplicate Site Fields Checker: Improve Efficiency
  src/device-registry/bin/jobs/check-duplicate-site-fields-job.js
  src/device-registry/bin/jobs/test/ut_check-duplicate-site-fields-job.js
Labels: ready for review

#3830 move to production
  k8s/analytics/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-registry/bin/jobs/check-duplicate-site-fields-job.js
  src/device-registry/bin/jobs/test/ut_check-duplicate-site-fields-job.js
Labels: ready for review

#3832 fix: resolve KafkaJS subscription error
  src/auth-service/bin/jobs/kafka-consumer.js
Labels: ready for review

#3834 just updating the unit testing file for Kafka Consumer
  src/auth-service/bin/jobs/test/ut_kafka-consumer.js
Labels: ready for review

#3833 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/view/values-prod.yaml
  src/auth-service/bin/jobs/kafka-consumer.js
  src/auth-service/bin/jobs/test/ut_kafka-consumer.js
Labels: ready for review

#3835 in device registry, Fixed the Kafka subscription issue
  src/device-registry/bin/jobs/kafka-consumer.js
  src/device-registry/bin/jobs/test/ut_kafka-consumer.js
Labels: ready for review

#3836 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-registry/bin/jobs/kafka-consumer.js
  src/device-registry/bin/jobs/test/ut_kafka-consumer.js
Labels: ready for review

#3838 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/view/values-prod.yaml
  src/device-registry/routes/v2/readings.js
Labels: ready for review

#3839 Update values-stage.yaml
  k8s/device-registry/values-stage.yaml
Labels: ready for review

#3840 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
Labels: ready for review

#3841 Update README.md for device-registry
  src/device-registry/README.md
Labels: ready for review

#3842 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/README.md
Labels: ready for review

#3843 just modifying the breakpoints for all the index endpoints
  src/device-registry/config/global/mappings.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3844 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/config/global/mappings.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3848 hotfxes around the approximate GPS value endpoints
  src/device-registry/controllers/create-site.js
  src/device-registry/routes/v2/sites.js
Labels: ready for review

#3849 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/controllers/create-site.js
  src/device-registry/routes/v2/sites.js
Labels: ready for review

#3850 more checks to prevent modification of GPS coordinates
  src/device-registry/models/Site.js
Labels: ready for review

#3851 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/models/Site.js
Labels: ready for review

#3852 refactor token routes definitions
  src/auth-service/package.json
  src/auth-service/routes/v2/test/ut_tokens.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/routes/v2/tokens.old.js
  src/auth-service/validators/test/ut_token.validators.js
  src/auth-service/validators/token.validators.js
Labels: ready for review

#3854 centralising the AQI categorisation logic
  src/device-registry/models/Event.js
  src/device-registry/models/Reading.js
Labels: ready for review

#3856 removing the required restriction
  src/device-registry/models/Reading.js
Labels: ready for review

#3855 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/models/Event.js
  src/device-registry/models/Reading.js
Labels: ready for review

#3862 move to production
  .github/workflows/deploy-previews.yml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/calibrate/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/website/Dockerfile
  src/website/README.md
Labels: ready for review

#3866 Trigger static files
  src/website/README.md
Labels: ready for review

#3868 just small refactoring for device registry
  src/device-registry/config/global/db-projections.js
  src/device-registry/models/Device.js
  src/device-registry/routes/v2/grids.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-grid.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3872 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/analytics/api/views/dashboard.py
Labels: ready for review

#3870 just add authRequired field to Devices
  src/device-registry/config/global/db-projections.js
  src/device-registry/models/Device.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3873 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/config/global/db-projections.js
  src/device-registry/models/Device.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3874 just modifying the device identifier
  src/device-registry/config/global/db-projections.js
  src/device-registry/models/Device.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3875 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/config/global/db-projections.js
  src/device-registry/models/Device.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3876 just adding serial numbers to the device_codes at creation
  src/device-registry/models/Device.js
Labels: ready for review

#3877 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/models/Device.js
Labels: ready for review

#3879 Enhance device filter to support boolean query parameters
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3880 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3882 just fixing a runtime around DB insertions
  src/device-registry/models/AdminLevel.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Grid.js
  src/device-registry/models/HealthTips.js
  src/device-registry/models/Host.js
  src/device-registry/models/KnowYourAirAnswer.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirQuestion.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/KnowYourAirUserQuizProgress.js
  src/device-registry/models/Location.js
  src/device-registry/models/Network.js
  src/device-registry/models/Photo.js
  src/device-registry/models/Reading.js
  src/device-registry/models/Signal.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/UniqueIdentifierCounter.js
  src/device-registry/utils/create-activity.js
Labels: ready for review

#3883 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/models/AdminLevel.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Grid.js
  src/device-registry/models/HealthTips.js
  src/device-registry/models/Host.js
  src/device-registry/models/KnowYourAirAnswer.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirQuestion.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/KnowYourAirUserQuizProgress.js
  src/device-registry/models/Location.js
  src/device-registry/models/Network.js
  src/device-registry/models/Photo.js
  src/device-registry/models/Reading.js
  src/device-registry/models/Signal.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/UniqueIdentifierCounter.js
  src/device-registry/utils/create-activity.js
Labels: ready for review

#3884 Include site category data in Readings schema
  src/device-registry/models/Reading.js
  src/device-registry/utils/scripts/api-response-transformer.js
  src/device-registry/utils/scripts/bulk-script.js
Labels: ready for review

#3885 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/models/Reading.js
  src/device-registry/utils/scripts/api-response-transformer.js
  src/device-registry/utils/scripts/bulk-script.js
Labels: ready for review

#3886 add averages data to the readings output
  src/device-registry/bin/jobs/v2.1-store-readings-job.js
  src/device-registry/bin/jobs/v3.1-store-readings-job.js
  src/device-registry/bin/server.js
  src/device-registry/models/Reading.js
Labels: ready for review

#3887 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/bin/jobs/v2.1-store-readings-job.js
  src/device-registry/bin/jobs/v3.1-store-readings-job.js
  src/device-registry/bin/server.js
  src/device-registry/models/Reading.js
Labels: ready for review

#3889 just randomly retriggering device registry
  src/device-registry/README.md
Labels: ready for review

#3890 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/locate/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/README.md
Labels: ready for review

#3891 switching back to the old job
  src/device-registry/bin/server.js
Labels: ready for review

#3892 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/bin/server.js
Labels: ready for review

#3893 just more optimisations to the readings job - v2.1
  src/device-registry/bin/jobs/v2.1-store-readings-job.js
  src/device-registry/bin/server.js
  src/device-registry/models/Event.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
Labels: ready for review

#3896 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/bin/jobs/v2.1-store-readings-job.js
  src/device-registry/bin/server.js
  src/device-registry/models/Event.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
Labels: ready for review

#3899 fixing datetime issues for the averages
  src/device-registry/models/Event.js
Labels: ready for review

#3901 just adding logging in staging
  src/device-registry/models/Event.js
Labels: ready for review

#3902 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/models/Event.js
Labels: ready for review

#3903 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  src/website/apps/FAQ/admin.py
  src/website/apps/FAQ/models.py
  src/website/apps/FAQ/urls.py
  src/website/apps/FAQ/views.py
  src/website/apps/externalTeam/migrations/0002_alter_externalteammember_picture.py
  src/website/apps/externalTeam/migrations/0003_alter_externalteammember_picture.py
  src/website/apps/externalTeam/migrations/0004_alter_externalteammember_picture.py
  src/website/apps/externalTeam/migrations/0005_alter_externalteammember_picture.py
  src/website/apps/externalTeam/migrations/0006_alter_externalteammember_picture.py
  src/website/apps/externalTeam/migrations/0007_alter_externalteammember_picture.py
  src/website/apps/externalTeam/migrations/0008_alter_externalteammember_picture.py
  src/website/apps/externalteams/__init__.py
  src/website/apps/externalteams/admin.py
  src/website/apps/externalteams/apps.py
  src/website/apps/externalteams/migrations/0001_initial.py
  src/website/apps/externalteams/migrations/__init__.py
  src/website/apps/externalteams/models.py
  src/website/apps/externalteams/serializers.py
  src/website/apps/externalteams/tests.py
  src/website/apps/externalteams/urls.py
  src/website/apps/externalteams/views.py
  src/website/apps/faqs/__init__.py
  src/website/apps/faqs/admin.py
  src/website/apps/faqs/apps.py
  src/website/apps/faqs/migrations/0001_initial.py
  src/website/apps/faqs/migrations/__init__.py
  src/website/apps/faqs/models.py
  src/website/apps/faqs/serializers.py
  src/website/apps/faqs/tests.py
  src/website/apps/faqs/urls.py
  src/website/apps/faqs/views.py
  src/website/core/settings.py
  src/website/core/urls.py
  src/website/core/views.py
  src/website/static/admin/css/main.css
  src/website/static/admin/images/airqo-dashboard.png
  src/website/static/admin/images/favicon.ico
  src/website/templates/404.html
  src/website/templates/500.html
  src/website/templates/index.html
Labels: ready for review

#3904 website-backend: admin portal fix
  src/website/static/admin/images/airqo-dashboard.png
  src/website/templates/admin/base_site.html
  src/website/templates/index.html
Labels: ready for review

#3906 website-backend: update static files url
  src/website/core/settings.py
Labels: ready for review

#3907 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/website/values-stage.yaml
  src/website/core/settings.py
Labels: ready for review

#3908 website-backend: Authenticaton added for staff and non AirQo members (API docs)
  src/website/core/settings.py
  src/website/core/urls.py
Labels: ready for review

#3909 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/website/values-stage.yaml
  src/website/core/settings.py
  src/website/core/urls.py
Labels: ready for review

#3910 website-backend: CSRF ISSUE
  src/website/core/settings.py
Labels: ready for review

#3911 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/website/values-stage.yaml
  src/website/core/settings.py
Labels: ready for review

#3912 enhancements to the User schema to prevent accidental updates
  src/auth-service/models/User.js
Labels: ready for review

#3913 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/website/values-stage.yaml
  src/auth-service/models/User.js
Labels: ready for review

#3914 Just refactoring Site model
  src/device-registry/models/Site.js
  src/device-registry/utils/scripts/api-response-transformer.js
Labels: ready for review

#3915 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  src/device-registry/models/Site.js
  src/device-registry/utils/scripts/api-response-transformer.js
Labels: ready for review

#3916 just storing user old
  src/auth-service/models/UserOld.js
Labels: ready for review

#3918 just reverting user model changes
  src/auth-service/models/User.js
  src/auth-service/models/UserNew.js
Labels: ready for review

#3919 enhance the US schema
  src/auth-service/models/AccessRequest.js
  src/auth-service/models/AccessToken.js
  src/auth-service/models/BlacklistedIP.js
  src/auth-service/models/BlacklistedIPPrefix.js
  src/auth-service/models/BlacklistedIPRange.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/Checklist.js
  src/auth-service/models/Client.js
  src/auth-service/models/Defaults.js
  src/auth-service/models/Department.js
  src/auth-service/models/Favorite.js
  src/auth-service/models/Group.js
  src/auth-service/models/IPPrefix.js
  src/auth-service/models/Inquiry.js
  src/auth-service/models/LocationHistory.js
  src/auth-service/models/Maintenance.js
  src/auth-service/models/Network.js
  src/auth-service/models/Permission.js
  src/auth-service/models/Preference.js
  src/auth-service/models/Role.js
  src/auth-service/models/Scope.js
  src/auth-service/models/SearchHistory.js
  src/auth-service/models/SelectedSite.js
  src/auth-service/models/Subscription.js
  src/auth-service/models/UnknownIP.js
  src/auth-service/models/User.js
  src/auth-service/models/UserOld.js
  src/auth-service/models/VerifyToken.js
  src/auth-service/models/WhitelistedIP.js
  src/auth-service/models/log.js
Labels: ready for review

#3920 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/models/AccessRequest.js
  src/auth-service/models/AccessToken.js
  src/auth-service/models/BlacklistedIP.js
  src/auth-service/models/BlacklistedIPPrefix.js
  src/auth-service/models/BlacklistedIPRange.js
  src/auth-service/models/Candidate.js
  src/auth-service/models/Checklist.js
  src/auth-service/models/Client.js
  src/auth-service/models/Defaults.js
  src/auth-service/models/Department.js
  src/auth-service/models/Favorite.js
  src/auth-service/models/Group.js
  src/auth-service/models/IPPrefix.js
  src/auth-service/models/Inquiry.js
  src/auth-service/models/LocationHistory.js
  src/auth-service/models/Maintenance.js
  src/auth-service/models/Network.js
  src/auth-service/models/Permission.js
  src/auth-service/models/Preference.js
  src/auth-service/models/Role.js
  src/auth-service/models/Scope.js
  src/auth-service/models/SearchHistory.js
  src/auth-service/models/SelectedSite.js
  src/auth-service/models/Subscription.js
  src/auth-service/models/UnknownIP.js
  src/auth-service/models/User.js
  src/auth-service/models/UserOld.js
  src/auth-service/models/VerifyToken.js
  src/auth-service/models/WhitelistedIP.js
  src/auth-service/models/log.js
Labels: ready for review

#3923 creating a unified pre-hook for User model
  src/auth-service/models/User.js
Labels: ready for review

#3924 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  src/auth-service/models/User.js
Labels: ready for review

#3922 website-backend: update models file
  src/website/apps/africancities/migrations/0009_africancountry_created_africancountry_is_deleted_and_more.py
  src/website/apps/africancities/migrations/0010_africancountry_created_africancountry_is_deleted_and_more.py
  src/website/apps/board/migrations/0005_boardmember_created_boardmember_is_deleted_and_more.py
  src/website/apps/board/migrations/0006_boardmember_created_boardmember_is_deleted_and_more.py
  src/website/apps/career/migrations/0002_bulletdescription_created_and_more.py
  src/website/apps/career/migrations/0003_bulletdescription_created_and_more.py
  src/website/apps/cleanair/migrations/0013_cleanairresource_created_cleanairresource_is_deleted_and_more.py
  src/website/apps/cleanair/migrations/0014_add_basemodel_fields.py
  src/website/apps/cleanair/migrations/0015_add_missing_fields.py
  src/website/apps/cleanair/migrations/0016_alter_cleanairresource_created_and_more.py
  src/website/apps/event/migrations/0009_event_created_event_is_deleted_event_modified_and_more.py
  src/website/apps/event/migrations/0010_event_created_event_is_deleted_event_modified_and_more.py
  src/website/apps/externalteams/migrations/0002_externalteammember_created_and_more.py
  src/website/apps/externalteams/migrations/0003_add_basemodel_fields.py
  src/website/apps/externalteams/migrations/0004_add_missing_fields.py
  src/website/apps/highlights/admin.py
  src/website/apps/highlights/migrations/0009_highlight_created_highlight_is_deleted_and_more.py
  src/website/apps/highlights/migrations/0010_highlight_created_highlight_is_deleted_and_more.py
  src/website/apps/impact/migrations/0002_impactnumber_created_impactnumber_is_deleted_and_more.py
  src/website/apps/impact/migrations/0003_impactnumber_created_impactnumber_is_deleted_and_more.py
  src/website/apps/partners/migrations/0005_partner_created_partner_is_deleted_partner_modified_and_more.py
  src/website/apps/partners/migrations/0006_partner_created_partner_is_deleted_partner_modified_and_more.py
  src/website/apps/press/migrations/0009_press_created_press_is_deleted_press_modified_and_more.py
  src/website/apps/press/migrations/0010_press_created_press_is_deleted_press_modified.py
  src/website/apps/publications/migrations/0009_publication_created_publication_is_deleted_and_more.py
  src/website/apps/publications/migrations/0010_publication_created_publication_is_deleted_and_more.py
  src/website/apps/team/migrations/0005_member_created_member_is_deleted_member_modified_and_more.py
  src/website/apps/team/migrations/0006_member_created_member_is_deleted_member_modified_and_more.py
  src/website/core/settings.py
  src/website/utils/fields.py
  src/website/utils/models.py
Labels: ready for review

#3929 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/website/values-stage.yaml
  src/analytics/api/models/events.py
Labels: ready for review

#3928 website-backend: model updates
  src/website/apps/africancities/migrations/0011_africancountry_created_africancountry_is_deleted_and_more.py
  src/website/apps/africancities/migrations/0012_alter_africancountry_country_flag_alter_image_image.py
  src/website/apps/africancities/migrations/0013_alter_africancountry_country_flag_alter_image_image.py
  src/website/apps/board/migrations/0007_boardmember_created_boardmember_is_deleted_and_more.py
  src/website/apps/board/migrations/0008_alter_boardmember_picture.py
  src/website/apps/board/migrations/0009_alter_boardmember_picture.py
  src/website/apps/career/migrations/0004_bulletdescription_created_and_more.py
  src/website/apps/cleanair/migrations/0017_alter_cleanairresource_resource_file_and_more.py
  src/website/apps/cleanair/migrations/0018_alter_cleanairresource_resource_file_and_more.py
  src/website/apps/event/migrations/0011_event_created_event_is_deleted_event_modified_and_more.py
  src/website/apps/event/migrations/0012_alter_event_background_image_alter_event_event_image_and_more.py
  src/website/apps/event/migrations/0013_alter_event_background_image_alter_event_event_image_and_more.py
  src/website/apps/externalteams/migrations/0005_alter_externalteammember_picture.py
  src/website/apps/externalteams/migrations/0006_alter_externalteammember_picture.py
  src/website/apps/highlights/migrations/0011_highlight_created_highlight_is_deleted_and_more.py
  src/website/apps/highlights/migrations/0012_alter_highlight_image.py
  src/website/apps/highlights/migrations/0013_alter_highlight_image.py
  src/website/apps/impact/migrations/0004_impactnumber_created_impactnumber_is_deleted_and_more.py
  src/website/apps/partners/migrations/0007_partner_created_partner_is_deleted_partner_modified_and_more.py
  src/website/apps/partners/migrations/0008_alter_partner_partner_image_and_more.py
  src/website/apps/partners/migrations/0009_alter_partner_partner_image_and_more.py
  src/website/apps/press/migrations/0011_press_created_press_is_deleted_press_modified.py
  src/website/apps/press/migrations/0012_alter_press_publisher_logo.py
  src/website/apps/press/migrations/0013_alter_press_publisher_logo.py
  src/website/apps/publications/migrations/0011_publication_created_publication_is_deleted_and_more.py
  src/website/apps/publications/migrations/0012_alter_publication_resource_file.py
  src/website/apps/publications/migrations/0013_alter_publication_resource_file.py
  src/website/apps/team/migrations/0007_member_created_member_is_deleted_member_modified_and_more.py
  src/website/apps/team/migrations/0008_alter_member_picture.py
  src/website/apps/team/migrations/0009_alter_member_picture.py
  src/website/assets/events/images/checkme.jpg
  src/website/assets/events/images/checkme_ce3jnHI.jpg
  src/website/assets/events/images/testimage.jpg
  src/website/core/settings.py
  src/website/utils/fields.py
Labels: ready for review

#3925 Added website backend workflow and virtualServerRoute
  .github/workflows/deploy-apis-to-production.yml
  k8s/nginx/production/platform-vs.yaml
  src/website/README.md
Labels: ready for review

#3930 move to production
  .github/workflows/deploy-apis-to-production.yml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/nginx/production/platform-vs.yaml
  k8s/predict/values-prod.yaml
  k8s/website/values-stage.yaml
  src/website/README.md
  src/website/apps/africancities/migrations/0011_africancountry_created_africancountry_is_deleted_and_more.py
  src/website/apps/africancities/migrations/0012_alter_africancountry_country_flag_alter_image_image.py
  src/website/apps/africancities/migrations/0013_alter_africancountry_country_flag_alter_image_image.py
  src/website/apps/board/migrations/0007_boardmember_created_boardmember_is_deleted_and_more.py
  src/website/apps/board/migrations/0008_alter_boardmember_picture.py
  src/website/apps/board/migrations/0009_alter_boardmember_picture.py
  src/website/apps/career/migrations/0004_bulletdescription_created_and_more.py
  src/website/apps/cleanair/migrations/0017_alter_cleanairresource_resource_file_and_more.py
  src/website/apps/cleanair/migrations/0018_alter_cleanairresource_resource_file_and_more.py
  src/website/apps/event/migrations/0011_event_created_event_is_deleted_event_modified_and_more.py
  src/website/apps/event/migrations/0012_alter_event_background_image_alter_event_event_image_and_more.py
  src/website/apps/event/migrations/0013_alter_event_background_image_alter_event_event_image_and_more.py
  src/website/apps/externalteams/migrations/0005_alter_externalteammember_picture.py
  src/website/apps/externalteams/migrations/0006_alter_externalteammember_picture.py
  src/website/apps/highlights/migrations/0011_highlight_created_highlight_is_deleted_and_more.py
  src/website/apps/highlights/migrations/0012_alter_highlight_image.py
  src/website/apps/highlights/migrations/0013_alter_highlight_image.py
  src/website/apps/impact/migrations/0004_impactnumber_created_impactnumber_is_deleted_and_more.py
  src/website/apps/partners/migrations/0007_partner_created_partner_is_deleted_partner_modified_and_more.py
  src/website/apps/partners/migrations/0008_alter_partner_partner_image_and_more.py
  src/website/apps/partners/migrations/0009_alter_partner_partner_image_and_more.py
  src/website/apps/press/migrations/0011_press_created_press_is_deleted_press_modified.py
  src/website/apps/press/migrations/0012_alter_press_publisher_logo.py
  src/website/apps/press/migrations/0013_alter_press_publisher_logo.py
  src/website/apps/publications/migrations/0011_publication_created_publication_is_deleted_and_more.py
  src/website/apps/publications/migrations/0012_alter_publication_resource_file.py
  src/website/apps/publications/migrations/0013_alter_publication_resource_file.py
  src/website/apps/team/migrations/0007_member_created_member_is_deleted_member_modified_and_more.py
  src/website/apps/team/migrations/0008_alter_member_picture.py
  src/website/apps/team/migrations/0009_alter_member_picture.py
  src/website/assets/events/images/checkme.jpg
  src/website/assets/events/images/checkme_ce3jnHI.jpg
  src/website/assets/events/images/testimage.jpg
  src/website/core/settings.py
  src/website/utils/fields.py
Labels: ready for review

#3934 ensure that existing networks are NOT deleted
  src/auth-service/models/User.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#3933 move to production
  k8s/analytics/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/website/values-stage.yaml
  src/auth-service/models/User.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#3846 auto reporting
  src/spatial/configure.py
  src/spatial/controllers/controllers.py
  src/spatial/models/report_datafetcher.py
  src/spatial/requirements.txt
  src/spatial/views/report_view.py
Labels: work in progress, ready for review

#3935 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/website/values-prod.yaml
  src/spatial/configure.py
  src/spatial/controllers/controllers.py
  src/spatial/models/report_datafetcher.py
  src/spatial/requirements.txt
  src/spatial/views/report_view.py
Labels: ready for review

#3938 ensuring that we only keep the latest role for each network
  src/auth-service/models/User.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#3939 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/spatial/values-stage.yaml
  k8s/website/values-prod.yaml
  src/auth-service/models/User.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#3937 Report with AI +prompts
  src/spatial/models/report_datafetcher.py
  src/spatial/requirements.txt
Labels: hotfix, ready for review

#3940 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  src/spatial/models/report_datafetcher.py
  src/spatial/requirements.txt
Labels: ready for review

#3941 handling cases where this.getQuery might not be available
  src/auth-service/models/User.js
Labels: ready for review

#3942 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/spatial/values-stage.yaml
  k8s/website/values-prod.yaml
  src/auth-service/models/User.js
Labels: ready for review

#3943 just a small hotfix for device updates
  src/device-registry/models/Device.js
Labels: ready for review

#3944 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  src/device-registry/models/Device.js
Labels: ready for review

#3946 Adding site creation among activities to log and store for future reference
  src/device-registry/models/Activity.js
  src/device-registry/models/test/ut_activity.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3947 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  src/device-registry/models/Activity.js
  src/device-registry/models/test/ut_activity.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#3948 report
  src/spatial/models/report_datafetcher.py
Labels: hotfix, ready for review

#3949 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  src/spatial/models/report_datafetcher.py
Labels: ready for review
