Repository airqo-platform/AirQo-api, pull requests merged in 2024-01, with the labels that each got.

#2683 access control for measurements across micros
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/routes/v2/cohorts.js
  src/device-registry/routes/v2/grids.js
  src/device-registry/utils/create-cohort.js
  src/device-registry/utils/create-grid.js
Labels: ready for review

#2713 updating the micros base URL and error handling hotfix
  src/data-proxy/bin/server.js
Labels: ready for review

#2716 Update README.md
  src/device-registry/README.md
Labels: ready for review

#2301 Setup Mlflow on Kubernetes
  k8s/mlflow/.helmignore
  k8s/mlflow/Chart.yaml
  k8s/mlflow/README.md
  k8s/mlflow/files/dbchecker.sh
  k8s/mlflow/mlflow-pv.yaml
  k8s/mlflow/mlflow-pvc.yaml
  k8s/mlflow/templates/NOTES.txt
  k8s/mlflow/templates/_helpers.tpl
  k8s/mlflow/templates/deployment.yaml
  k8s/mlflow/templates/service.yaml
  k8s/mlflow/values.yaml
  k8s/nginx/staging/platform-vs.yaml
Labels: ready for review, k8s

#2718 Update README.md
  src/device-registry/README.md
Labels: ready for review

#2719 optimising the blacklisting logic
  src/auth-service/utils/control-access.js
Labels: ready for review

#2720 [Analytics] Update README.md
  src/analytics/README.md
Labels: ready for review

#2721 [device status] Update README.md
  src/device-status/README.md
Labels: ready for review

#2722 [device uptime] Update README.md
  src/device-uptime/README.md
Labels: ready for review

#2723 [exceedances] Update README.md
  src/exceedances/README.md
Labels: ready for review

#2724 Update Node version Firebase Functions
  src/firebase/auth/functions/index.js
  src/firebase/auth/functions/package-lock.json
  src/firebase/auth/functions/package.json
  src/firebase/backup/functions/package-lock.json
  src/firebase/backup/functions/package.json
Labels: ready for review

#2725 [incentives] Update README.md
  src/incentives/README.md
Labels: ready for review

#2726 edge case of missing nvalues
  src/device-registry/config/global/envs.js
  src/device-registry/models/Event.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2727 error handling enhancements
  src/auth-service/utils/control-access.js
  src/auth-service/utils/stringify.js
Labels: ready for review

#2728 enhancements to error handling
  src/incentives/utils/create-host.js
  src/incentives/utils/create-sim.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/stringify.js
Labels: ready for review

#2729 hotfix for nvalues
  src/device-registry/models/Event.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2730 [incentives] fixing runtime errors for transaction util
  src/incentives/utils/create-transaction.js
Labels: ready for review

#2731 hotfixing issue for NAN of NVALUES
  src/device-registry/config/global/mappings.js
Labels: ready for review

#2733 [data MGT node] Update README.md
  src/data-mgt/node/README.md
Labels: ready for review

#2732 Disable Kafka Error logging
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review

#2734 Easily retrieve user analytics related to behavioral and Feature interactions
  src/auth-service/controllers/create-user.js
  src/auth-service/routes/v2/users.js
  src/auth-service/utils/create-user.js
Labels: ready for review

#2736 adding emojis to measurements SLACK notifications
  src/device-registry/models/Event.js
Labels: ready for review

#2735 send email notifications every after site activity (deploy,recall,maintain)
  src/auth-service/middleware/passport.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review, auth-service

#2737 Manual script for generating downtime report
  src/device-registry/.gitignore
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/utils/scripts/bulk-script.js
  src/device-registry/utils/scripts/downtime-report.js
Labels: ready for review

#2739 hotfix for VersionError in mongoose
  src/auth-service/utils/control-access.js
Labels: ready for review

#2740 hotfix for tenant
  src/auth-service/utils/mailer.js
Labels: ready for review

#2738 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/utils/control-access.js
  src/auth-service/utils/mailer.js
  src/device-registry/.gitignore
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/utils/scripts/bulk-script.js
  src/device-registry/utils/scripts/downtime-report.js
Labels: ready for review

#2741 candidate confirmation hotfix
  src/auth-service/utils/create-candidate.js
Labels: ready for review

#2742 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-mgt/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/utils/create-candidate.js
Labels: ready for review

#2745 hotfix some issues with blacklisting
  src/auth-service/utils/control-access.js
Labels: ready for review

#2746 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#2747 enhancing the logger statemenets
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/AdminLevel.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Grid.js
  src/device-registry/models/HealthTips.js
  src/device-registry/models/Host.js
  src/device-registry/models/KnowYourAirAnswer.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirQuestion.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/KnowYourAirUserQuizProgress.js
  src/device-registry/models/Location.js
  src/device-registry/models/Network.js
  src/device-registry/models/Photo.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/UniqueIdentifierCounter.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-cohort.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-grid.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/date.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/translate.js
Labels: ready for review

#2748 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/AdminLevel.js
  src/device-registry/models/Airqloud.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Grid.js
  src/device-registry/models/HealthTips.js
  src/device-registry/models/Host.js
  src/device-registry/models/KnowYourAirAnswer.js
  src/device-registry/models/KnowYourAirLesson.js
  src/device-registry/models/KnowYourAirQuestion.js
  src/device-registry/models/KnowYourAirQuiz.js
  src/device-registry/models/KnowYourAirTask.js
  src/device-registry/models/KnowYourAirUserLessonProgress.js
  src/device-registry/models/KnowYourAirUserQuizProgress.js
  src/device-registry/models/Location.js
  src/device-registry/models/Network.js
  src/device-registry/models/Photo.js
  src/device-registry/models/Site.js
  src/device-registry/models/SiteActivity.js
  src/device-registry/models/UniqueIdentifierCounter.js
  src/device-registry/utils/create-activity.js
  src/device-registry/utils/create-airqloud.js
  src/device-registry/utils/create-cohort.js
  src/device-registry/utils/create-device.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/create-grid.js
  src/device-registry/utils/create-health-tips.js
  src/device-registry/utils/create-know-your-air.js
  src/device-registry/utils/create-location.js
  src/device-registry/utils/create-photo.js
  src/device-registry/utils/create-site.js
  src/device-registry/utils/date.js
  src/device-registry/utils/distance.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/translate.js
Labels: ready for review

#2749 more fixes at controller level
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/utils/create-site.js
Labels: ready for review, device-registry

#2751 fixing the runtimes for error handling
  src/incentives/controllers/create-host.js
  src/incentives/controllers/create-network.js
  src/incentives/controllers/create-sim.js
  src/incentives/controllers/create-transaction.js
  src/incentives/models/Host.js
  src/incentives/models/Network.js
  src/incentives/models/Sim.js
  src/incentives/models/transaction.js
  src/incentives/utils/create-host.js
  src/incentives/utils/create-network.js
  src/incentives/utils/create-sim.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/generate-filter.js
Labels: ready for review, incentives

#2750 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/utils/create-site.js
  src/incentives/controllers/create-host.js
  src/incentives/controllers/create-network.js
  src/incentives/controllers/create-sim.js
  src/incentives/controllers/create-transaction.js
  src/incentives/models/Host.js
  src/incentives/models/Network.js
  src/incentives/models/Sim.js
  src/incentives/models/transaction.js
  src/incentives/utils/create-host.js
  src/incentives/utils/create-network.js
  src/incentives/utils/create-sim.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/generate-filter.js
Labels: ready for review

#2752 Change schedule for open Weather data to hourly
  src/airflow/dags/weather_measurements.py
Labels: ready for review

#2753 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/incentives/values-stage.yaml
  src/airflow/dags/weather_measurements.py
Labels: ready for review

#2754 Set up data proxy
  .github/workflows/data-proxy-test.yml
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/data-proxy/.helmignore
  k8s/data-proxy/Chart.yaml
  k8s/data-proxy/charts/.gitkeep
  k8s/data-proxy/templates/NOTES.txt
  k8s/data-proxy/templates/_helpers.tpl
  k8s/data-proxy/templates/deployment.yaml
  k8s/data-proxy/templates/hpa.yaml
  k8s/data-proxy/templates/service.yaml
  k8s/data-proxy/templates/tests/test-connection.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/data-proxy/values-stage.yaml
  k8s/nginx/production/analytics-vs.yaml
  k8s/nginx/production/api-vs.yaml
  k8s/nginx/production/platform-vs.yaml
  k8s/nginx/staging/analytics-vs.yaml
  k8s/nginx/staging/api-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
Labels: ready for review

#2757 more hotfixes for runtimes in controllers
  src/auth-service/config/global/envs.js
  src/auth-service/controllers/create-token.js
  src/auth-service/controllers/create-user.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/AccessToken.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review, auth-service

#2756 Temporarily disable kafka in workflows
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
Labels: ready for review

#2755 move to production
  .github/workflows/data-proxy-test.yml
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  .github/workflows/deploy-previews.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/airflow/values-prod.yaml
  k8s/airflow/values-stage.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/.helmignore
  k8s/data-proxy/Chart.yaml
  k8s/data-proxy/charts/.gitkeep
  k8s/data-proxy/templates/NOTES.txt
  k8s/data-proxy/templates/_helpers.tpl
  k8s/data-proxy/templates/deployment.yaml
  k8s/data-proxy/templates/hpa.yaml
  k8s/data-proxy/templates/service.yaml
  k8s/data-proxy/templates/tests/test-connection.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/data-proxy/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/nginx/production/analytics-vs.yaml
  k8s/nginx/production/api-vs.yaml
  k8s/nginx/production/platform-vs.yaml
  k8s/nginx/staging/analytics-vs.yaml
  k8s/nginx/staging/api-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
  src/airflow/dags/airqo_bam_measurements.py
  src/airflow/dags/airqo_measurements.py
  src/auth-service/config/global/envs.js
  src/auth-service/controllers/create-token.js
  src/auth-service/controllers/create-user.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/AccessToken.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#2758 fixing the emails for device management
  src/auth-service/utils/email.msgs.js
Labels: ready for review, auth-service

#2760 more hotfixes for maintenance emails
  src/auth-service/controllers/create-token.js
  src/auth-service/controllers/create-user.js
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#2759 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/controllers/create-token.js
  src/auth-service/controllers/create-user.js
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#2762 optimise refresh grid function
  src/device-registry/controllers/create-grid.js
  src/device-registry/utils/create-grid.js
Labels: ready for review

#2763 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/data-proxy/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/device-registry/controllers/create-grid.js
  src/device-registry/utils/create-grid.js
Labels: ready for review

#2764 Enhancement for access control
  src/auth-service/controllers/create-candidate.js
  src/auth-service/controllers/create-checklist.js
  src/auth-service/controllers/create-client.js
  src/auth-service/controllers/create-default.js
  src/auth-service/controllers/create-department.js
  src/auth-service/controllers/create-favorite.js
  src/auth-service/controllers/create-group.js
  src/auth-service/controllers/create-inquiry.js
  src/auth-service/controllers/create-location-history.js
  src/auth-service/controllers/create-network.js
  src/auth-service/controllers/create-permission.js
  src/auth-service/controllers/create-preference.js
  src/auth-service/controllers/create-request.js
  src/auth-service/controllers/create-role.js
  src/auth-service/controllers/create-scope.js
  src/auth-service/controllers/create-search-history.js
  src/auth-service/controllers/create-token.js
  src/auth-service/controllers/create-user-type.js
  src/auth-service/controllers/create-user.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-user.js
Labels: ready for review

#2766 handling REQ HEADER already sent runtime errors
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
Labels: ready for review, device-registry

#2767 logging exceptions for known IPs
  src/auth-service/utils/control-access.js
Labels: ready for review, auth-service

#2765 move to production
  k8s/airflow/values-prod.yaml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-status/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/controllers/create-candidate.js
  src/auth-service/controllers/create-checklist.js
  src/auth-service/controllers/create-client.js
  src/auth-service/controllers/create-default.js
  src/auth-service/controllers/create-department.js
  src/auth-service/controllers/create-favorite.js
  src/auth-service/controllers/create-group.js
  src/auth-service/controllers/create-inquiry.js
  src/auth-service/controllers/create-location-history.js
  src/auth-service/controllers/create-network.js
  src/auth-service/controllers/create-permission.js
  src/auth-service/controllers/create-preference.js
  src/auth-service/controllers/create-request.js
  src/auth-service/controllers/create-role.js
  src/auth-service/controllers/create-scope.js
  src/auth-service/controllers/create-search-history.js
  src/auth-service/controllers/create-token.js
  src/auth-service/controllers/create-user-type.js
  src/auth-service/controllers/create-user.js
  src/auth-service/routes/v2/tokens.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/create-user.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
Labels: ready for review

#2769 Updates additional scripts to use new workflows naming
  k8s/nginx/production/platform-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
  k8s/workflows/templates/NOTES.txt
  k8s/workflows/templates/_helpers.tpl
  k8s/workflows/templates/deployment.yaml
  k8s/workflows/templates/hpa.yaml
  k8s/workflows/templates/service.yaml
  k8s/workflows/templates/tests/test-connection.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/workflows-app.yaml
  src/workflows/Dockerfile
  src/workflows/dags/airqo_automated_tweets.py
  src/workflows/xcom-setup.sh
Labels: ready for review

#2770 new scripts for creating array of strings with various inputs
  src/auth-service/.gitignore
  src/auth-service/utils/scripts/csv-splitter.js
  src/auth-service/utils/scripts/json-splitter.js
  src/auth-service/utils/scripts/space-splitter.js
Labels: ready for review

#2771 Restore previous namespace
  k8s/nginx/production/platform-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  k8s/workflows/workflows-app.yaml
Labels: ready for review

#2772 adding more optimisations for access control checks
  src/auth-service/utils/control-access.js
Labels: ready for review

#2773 refactoring the controllers for incentives
  src/incentives/controllers/create-host.js
  src/incentives/controllers/create-network.js
  src/incentives/controllers/create-sim.js
  src/incentives/controllers/create-transaction.js
Labels: ready for review

#2774 more hotfixes for controllers
  src/incentives/controllers/create-host.js
  src/incentives/controllers/create-network.js
  src/incentives/controllers/create-sim.js
  src/incentives/controllers/create-transaction.js
  src/incentives/utils/create-host.js
  src/incentives/utils/create-network.js
  src/incentives/utils/create-sim.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/generate-filter.js
Labels: ready for review

#2775 default to testing environment
  src/incentives/controllers/create-host.js
  src/incentives/controllers/create-network.js
  src/incentives/controllers/create-sim.js
  src/incentives/controllers/create-transaction.js
  src/incentives/models/Host.js
  src/incentives/models/Network.js
  src/incentives/models/Sim.js
  src/incentives/models/transaction.js
  src/incentives/utils/create-host.js
  src/incentives/utils/create-network.js
  src/incentives/utils/create-sim.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/errors.js
  src/incentives/utils/generate-filter.js
Labels: ready for review

#2776 hotfix for auth service controllers
  src/auth-service/controllers/create-candidate.js
  src/auth-service/controllers/create-token.js
  src/auth-service/controllers/create-user.js
Labels: ready for review

#2778 fix issues in auth
  src/auth-service/utils/control-access.js
Labels: ready for review

#2779 more optimisations to the verification logic
  src/auth-service/utils/control-access.js
Labels: ready for review

#2777 hotfix for device registry controllers
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
Labels: ready for review

#2780 optimising verification checks
  src/auth-service/config/global/db-projections.js
  src/auth-service/models/UnknownIP.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2781 default environment for auth service
  src/auth-service/config/constants.js
Labels: ready for review

#2782 default environment for incentives
  src/incentives/config/constants.js
  src/incentives/controllers/create-host.js
  src/incentives/controllers/create-network.js
  src/incentives/controllers/create-sim.js
  src/incentives/controllers/create-transaction.js
  src/incentives/models/Host.js
  src/incentives/models/Network.js
  src/incentives/models/Sim.js
  src/incentives/models/transaction.js
  src/incentives/utils/create-host.js
  src/incentives/utils/create-network.js
  src/incentives/utils/create-sim.js
  src/incentives/utils/create-transaction.js
  src/incentives/utils/errors.js
  src/incentives/utils/generate-filter.js
Labels: ready for review

#2783 default environment for device-registry
  src/device-registry/config/constants.js
Labels: ready for review

#2784 Workflows code fixes
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  k8s/workflows/workflows-app.yaml
  src/workflows/Dockerfile
  src/workflows/airflow_xcom/__init__.py
  src/workflows/airflow_xcom/gcs_xcom_backend.py
  src/workflows/docker-compose.yaml
Labels: ready for review

#2785 Update airflow Dockerfile
  src/workflows/Dockerfile
Labels: ready for review

#2786 Introducing Command Query Responsibility Segregation (CQRS)
  src/device-registry/bin/fetch-and-store-readings.js
  src/device-registry/bin/server.js
  src/device-registry/controllers/create-activity.js
  src/device-registry/controllers/create-airqloud.js
  src/device-registry/controllers/create-cohort.js
  src/device-registry/controllers/create-device.js
  src/device-registry/controllers/create-event.js
  src/device-registry/controllers/create-grid.js
  src/device-registry/controllers/create-health-tips.js
  src/device-registry/controllers/create-know-your-air.js
  src/device-registry/controllers/create-location.js
  src/device-registry/controllers/create-photo.js
  src/device-registry/controllers/create-site.js
  src/device-registry/models/Event.js
  src/device-registry/models/Grid.js
  src/device-registry/models/Reading.js
  src/device-registry/models/wip_Event.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/utils/create-event.js
  src/device-registry/utils/errors.js
  src/device-registry/utils/generate-filter.js
  src/device-registry/utils/jsonify.js
Labels: ready for review

#2788 documents should be automatically removed from the collection 2 months
  src/device-registry/models/Reading.js
Labels: ready for review

#2789 whitelist client IP and resolve HEADER already sent
  src/auth-service/bin/server.js
  src/auth-service/controllers/create-candidate.js
  src/auth-service/controllers/create-checklist.js
  src/auth-service/controllers/create-client.js
  src/auth-service/controllers/create-default.js
  src/auth-service/controllers/create-department.js
  src/auth-service/controllers/create-favorite.js
  src/auth-service/controllers/create-group.js
  src/auth-service/controllers/create-inquiry.js
  src/auth-service/controllers/create-location-history.js
  src/auth-service/controllers/create-network.js
  src/auth-service/controllers/create-permission.js
  src/auth-service/controllers/create-preference.js
  src/auth-service/controllers/create-request.js
  src/auth-service/controllers/create-role.js
  src/auth-service/controllers/create-scope.js
  src/auth-service/controllers/create-search-history.js
  src/auth-service/controllers/create-token.js
  src/auth-service/controllers/create-user-type.js
  src/auth-service/controllers/create-user.js
  src/auth-service/models/WhitelistedIP.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/stringify.js
Labels: ready for review

#2790 disable logging errors for data insertion job
  src/device-registry/bin/fetch-and-store-readings.js
  src/device-registry/controllers/create-event.js
  src/device-registry/routes/v2/index.js
  src/device-registry/routes/v2/readings.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/generate-filter.js
Labels: work in progress

#2791 return the latest measurements for the new readings endpoint
  src/device-registry/models/Reading.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2792 ensure new readings endpoint is not allowed on JWT
  src/auth-service/.gitignore
  src/auth-service/middleware/passport.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/utils/control-access.js
  src/auth-service/utils/scripts/generate-services.js
  src/auth-service/utils/scripts/yaml-extractor.js
Labels: ready for review

#2793 Fix airqo device dag imports
  src/workflows/dags/airqo_automated_tweets.py
  src/workflows/dags/airqo_bam_measurements.py
  src/workflows/dags/airqo_measurements.py
Labels: ready for review

#2794 Update deploy-apis-to-production.yml to resolve prod airflow issues
  .github/workflows/deploy-apis-to-production.yml
Labels: ready for review

#2795 move to production
  .github/workflows/deploy-apis-to-production.yml
  k8s/analytics/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  k8s/workflows/values-prod.yaml
Labels: ready for review

#2796 temporarily stop disk writes
  src/auth-service/utils/control-access.js
Labels: ready for review

#2797 move to production
  k8s/analytics/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#2800 introducing post processing
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/utils/control-access.js
Labels: ready for review

#2801 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/utils/control-access.js
Labels: ready for review

#2806 finalise the optimisations for token verifications
  src/auth-service/utils/control-access.js
Labels: ready for review

#2807 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#2809 document that is older than 1 month will be automatically deleted
  src/device-registry/models/Reading.js
Labels: ready for review

#2811 limiting the number of concurrent tasks to one
  src/auth-service/utils/control-access.js
Labels: ready for review

#2812 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#2813 temporarily disable post processing
  src/auth-service/utils/control-access.js
Labels: ready for review

#2814 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#2815 only store unknown IPs in post processing
  src/auth-service/utils/control-access.js
Labels: ready for review

#2816 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/utils/control-access.js
Labels: ready for review

#2817 fix the logging
  src/auth-service/utils/control-access.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#2818 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-uptime/values-prod.yaml
  k8s/exceedance/values-prod-airqo.yaml
  k8s/exceedance/values-prod-kcca.yaml
  k8s/gp-model/values-prod.yaml
  k8s/incentives/values-prod.yaml
  src/auth-service/utils/control-access.js
  src/auth-service/utils/generate-filter.js
Labels: ready for review

#2819 have the job run every 30 min of every hour
  src/device-registry/bin/fetch-and-store-readings.js
Labels: ready for review

#2820 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  src/device-registry/bin/fetch-and-store-readings.js
Labels: ready for review

#2821 remove log statement causing runtime
  src/auth-service/utils/control-access.js
Labels: ready for review

#2823 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  src/auth-service/utils/control-access.js
  src/device-registry/bin/server.js
  src/device-registry/controllers/create-event.js
  src/device-registry/routes/v2/readings.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2824 small fixes to the shedule
  src/device-registry/controllers/create-event.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2825 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  src/device-registry/controllers/create-event.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2826 removing unused code
  src/device-registry/bin/fetch-and-store-readings.js
Labels: ready for review

#2828 KAFKA Consuming IPs for blacklisting checks
  src/auth-service/bin/index.js
  src/auth-service/bin/kafka-consumer.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2829 adding emojis to loggers
  src/auth-service/bin/kafka-consumer.js
  src/auth-service/bin/server.js
Labels: ready for review

#2830 KAFKA: insert recent measurements for new Events endpoint in staging
  src/device-registry/bin/index.js
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review

#2831 resolve runtime
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review

#2832 KAFKA: just simple refactoring around blacklisting
  k8s/kafka/topics/kafka-topics.yaml
  src/auth-service/bin/index.js
  src/auth-service/bin/kafka-consumer.js
Labels: ready for review

#2833 updating the emoji for success
  src/auth-service/utils/control-access.js
Labels: ready for review

#2834 disable the success KAFKA messages
  src/auth-service/utils/control-access.js
Labels: ready for review

#2837 add more logs for successfull blacklists
  src/auth-service/bin/kafka-consumer.js
Labels: ready for review

#2838 fix runtime around checking if IP falls in range
  src/auth-service/bin/kafka-consumer.js
Labels: ready for review

#2839 fixing more runtimes
  src/auth-service/bin/kafka-consumer.js
Labels: ready for review

#2840 exclude more fields in the users via view unknown IPs
  src/auth-service/config/global/db-projections.js
Labels: ready for review

#2841 small refactoring for device registry
  src/device-registry/bin/index.js
Labels: ready for review

#2836 Trigger Predict to update db connection string
  src/predict/README.md
Labels: ready for review

#2843 Enable Kafka in production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/kafka/clusters/kafka-cluster.yaml
  src/workflows/dags/airnow.py
  src/workflows/dags/airqo_measurements.py
Labels: ready for review

#2844 enable Kafka to insert measurements in production
  src/device-registry/bin/index.js
Labels: ready for review

#2827 move to production
  .github/workflows/deploy-apis-to-production.yml
  .github/workflows/deploy-apis-to-staging.yml
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/kafka/clusters/kafka-cluster.yaml
  k8s/kafka/topics/kafka-topics.yaml
  k8s/predict/values-stage.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/bin/index.js
  src/auth-service/bin/kafka-consumer.js
  src/auth-service/bin/server.js
  src/auth-service/config/global/db-projections.js
  src/auth-service/utils/control-access.js
  src/device-registry/bin/fetch-and-store-readings.js
  src/device-registry/bin/index.js
  src/device-registry/bin/kafka-consumer.js
  src/predict/README.md
  src/workflows/dags/airnow.py
  src/workflows/dags/airqo_measurements.py
Labels: ready for review

#2845 add more services in logging
  src/auth-service/middleware/passport.js
Labels: ready for review

#2846 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/middleware/passport.js
Labels: ready for review

#2847 additional error handling for fetching and storing readings
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review

#2848 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review

#2849 new static for fetching data during automated insertion
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/models/Event.js
Labels: ready for review

#2850 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/models/Event.js
Labels: ready for review

#2852 only enable measurements insertions through Kafka in staging only
  src/device-registry/bin/index.js
Labels: ready for review

#2851 Re-enable sending measurements to API
  src/workflows/dags/airnow.py
  src/workflows/dags/airqo_measurements.py
Labels: ready for review

#2853 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/index.js
  src/workflows/dags/airnow.py
  src/workflows/dags/airqo_measurements.py
Labels: ready for review

#2854 re-enable last refreshed alerts and logs for the view util....
  src/device-registry/models/Event.js
Labels: ready for review

#2855 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/device-registry/models/Event.js
Labels: ready for review

#2856 logging should happen in production environment only
  src/device-registry/models/Event.js
Labels: ready for review

#2857 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/models/Event.js
Labels: ready for review

#2858 In production, re-enable insertion of data through KAFKA
  src/device-registry/bin/index.js
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2859 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/index.js
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2860 reducing or removing the KAFKA duplicate error logs via Slack
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#2861 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/utils/create-event.js
  src/device-registry/utils/generate-filter.js
Labels: ready for review

#2862 reducing the error logs
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2863 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2865 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/kafka-consumer.js
  src/device-registry/utils/create-event.js
Labels: ready for review

#2867 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/routes/v2/sites.js
Labels: ready for review

#2842 update mlflow port numbers
  k8s/mlflow/templates/service.yaml
  k8s/mlflow/values.yaml
  k8s/nginx/staging/platform-vs.yaml
  src/workflows/dags/airqo_automated_tweets.py
Labels: ready for review

#2869 Refactor the blacklisting operations
  src/auth-service/bin/kafka-consumer.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
Labels: ready for review

#2870 automating compromised token emails
  src/auth-service/config/global/db-projections.js
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
Labels: ready for review

#2868 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/gp-model/values-prod.yaml
  k8s/mlflow/templates/service.yaml
  k8s/mlflow/values.yaml
  k8s/nginx/staging/platform-vs.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/bin/kafka-consumer.js
  src/auth-service/config/global/db-projections.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/utils/control-access.js
  src/auth-service/utils/email.msgs.js
  src/auth-service/utils/mailer.js
  src/workflows/dags/airqo_automated_tweets.py
Labels: ready for review

#2871 input validation for IP address when updating Client
  src/auth-service/routes/v2/clients.js
Labels: ready for review

#2872 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/routes/v2/clients.js
Labels: ready for review

#2873 resolve runtime for creating a client
  src/auth-service/controllers/create-client.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2874 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/controllers/create-client.js
  src/auth-service/utils/control-access.js
Labels: ready for review

#2875 adding the platform emails ENV constant
  src/auth-service/config/global/envs.js
Labels: ready for review

#2876 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/config/global/envs.js
Labels: ready for review

#2877 updating the email content for compromised token
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#2878 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/gp-model/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/utils/email.msgs.js
Labels: ready for review

#2880 introducing new kafka topics
  k8s/kafka/topics/kafka-topics.yaml
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review

#2879 Adjusting Kafka configurations
  k8s/kafka/topics/kafka-topics.yaml
  src/device-registry/bin/kafka-consumer.js
Labels: ready for review
