Repository airqo-platform/AirQo-api, pull requests merged in 2025-08, with the labels that each got.

#5012 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/nginx/production/global-config.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/superset/docker/start_superset.sh
  src/superset/requirements.txt
Labels: ready for review

#5024 Hotfixes for the Device Shipping use case
  src/device-registry/models/Device.js
  src/device-registry/utils/common/generate-filter.js
  src/device-registry/utils/device.util.js
  src/device-registry/utils/site.util.js
  src/device-registry/validators/device.validators.js
Labels: ready for review

#5028 hotfixing for device registry caching system
  src/device-registry/config/redis.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/utils/event.util.js
Labels: ready for review

#5030 removing misleading warning about listing many clients
  src/auth-service/controllers/client.controller.js
  src/auth-service/utils/client.util.js
Labels: ready for review

#5025 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/config/redis.js
  src/auth-service/controllers/client.controller.js
  src/auth-service/middleware/rate-limiter.js
  src/auth-service/utils/client.util.js
  src/auth-service/utils/common/email-deduplication.util.js
  src/auth-service/utils/common/mailer.util.js
  src/auth-service/utils/group.util.js
  src/auth-service/utils/role-permissions.util.js
  src/auth-service/utils/user.util.js
  src/device-registry/config/redis.js
  src/device-registry/models/Device.js
  src/device-registry/package-lock.json
  src/device-registry/package.json
  src/device-registry/utils/common/generate-filter.js
  src/device-registry/utils/device.util.js
  src/device-registry/utils/event.util.js
  src/device-registry/utils/site.util.js
  src/device-registry/validators/device.validators.js
Labels: ready for review

#5031 enhancements to user registration process
  src/auth-service/config/global/db-projections.js
  src/auth-service/models/User.js
  src/auth-service/utils/user.util.js
  src/auth-service/validators/users.validators.js
Labels: ready for review

#5032 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/config/global/db-projections.js
  src/auth-service/models/User.js
  src/auth-service/utils/user.util.js
  src/auth-service/validators/users.validators.js
Labels: ready for review

#5033 fixing runtime errors for rate limiter middleware
  src/auth-service/middleware/rate-limiter.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
Labels: ready for review

#5034 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/middleware/rate-limiter.js
  src/auth-service/package-lock.json
  src/auth-service/package.json
  src/auth-service/utils/common/email-deduplication.util.js
Labels: ready for review

#5002 heatmap-using-airqo
  src/spatial/controllers/controllers.py
  src/spatial/models/heatmapModel.py
  src/spatial/requirements.txt
  src/spatial/views/heatmapViews.py
Labels: ready for review

#5038 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/superset/superset_config.py
Labels: ready for review

#5040 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/superset/superset_config.py
Labels: ready for review

#5042 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/nginx/production/global-config.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
Labels: ready for review

#5050 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/superset/superset_config.py
Labels: ready for review

#5054 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/nginx/production/superset-vs.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/superset/superset_config.py
Labels: ready for review

#5055 fix slug generation responses and auto generation
  src/auth-service/utils/group.util.js
  src/auth-service/utils/organization-request.util.js
Labels: ready for review

#5062 Add device metadata analysis and cleanup endpoints with enhanced deployment validation
  src/device-registry/controllers/device.controller.js
  src/device-registry/models/Device.js
  src/device-registry/routes/v2/devices.routes.js
  src/device-registry/utils/device.util.js
  src/device-registry/validators/activities.validators.js
  src/device-registry/validators/device.validators.js
Labels: ready for review

#5065 updating Grid polygons/shapes with enhanced safety measures and audit capabilities
  src/device-registry/controllers/grid.controller.js
  src/device-registry/models/Grid.js
  src/device-registry/routes/v2/grids.routes.js
  src/device-registry/utils/grid.util.js
  src/device-registry/validators/grids.validators.js
Labels: ready for review

#5066 updating Cohort names with enhanced safety measures and audit capabilities.
  src/device-registry/controllers/cohort.controller.js
  src/device-registry/models/Cohort.js
  src/device-registry/routes/v2/cohorts.routes.js
  src/device-registry/utils/cohort.util.js
  src/device-registry/validators/cohorts.validators.js
Labels: ready for review

#5060 move to production
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/spatial/values-stage.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/analytics/api/models/bigquery_api.py
  src/analytics/api/models/events.py
  src/analytics/api/utils/data_formatters.py
  src/analytics/api/utils/datautils.py
  src/analytics/api/utils/http.py
  src/analytics/api/utils/messages.py
  src/analytics/api/utils/pollutants/pm_25.py
  src/analytics/api/utils/utils.py
  src/analytics/api/views/__init__.py
  src/analytics/api/views/common/__init__.py
  src/analytics/api/views/common/data_ops.py
  src/analytics/api/views/common/responses.py
  src/analytics/api/views/v2/__init__.py
  src/analytics/api/views/v2/dashboard.py
  src/analytics/api/views/v2/data.py
  src/analytics/api/views/v2/report.py
  src/analytics/api/views/v3/__init__.py
  src/analytics/api/views/v3/data.py
  src/analytics/config.py
  src/analytics/constants.py
  src/analytics/main.py
  src/analytics/requirements.txt
  src/analytics/schemas/ReadMe.md
  src/analytics/schemas/datadownload.py
  src/analytics/schemas/files/airqo_mobile_measurements.json
  src/device-registry/controllers/cohort.controller.js
  src/device-registry/controllers/device.controller.js
  src/device-registry/controllers/grid.controller.js
  src/device-registry/models/Cohort.js
  src/device-registry/models/Device.js
  src/device-registry/models/Grid.js
  src/device-registry/routes/v2/cohorts.routes.js
  src/device-registry/routes/v2/devices.routes.js
  src/device-registry/routes/v2/grids.routes.js
  src/device-registry/utils/cohort.util.js
  src/device-registry/utils/device.util.js
  src/device-registry/utils/grid.util.js
  src/device-registry/validators/activities.validators.js
  src/device-registry/validators/cohorts.validators.js
  src/device-registry/validators/device.validators.js
  src/device-registry/validators/grids.validators.js
  src/spatial/configure.py
  src/spatial/models/heatmapModel.py
  src/spatial/utils/__init__.py
  src/spatial/utils/commons.py
  src/workflows/airqo_etl_utils/datautils.py
  src/workflows/dags/meta_data.py
Labels: ready for review

#5077 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/analytics/api/models/bigquery_api.py
  src/analytics/api/utils/datautils.py
  src/analytics/api/views/v2/dashboard.py
  src/analytics/config.py
  src/analytics/schemas/dashboardchartdata.py
Labels: ready for review

#5070 GCP
  src/spatial/models/heatmapModel.py
Labels: ready for review, predict

#5078 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  src/spatial/models/heatmapModel.py
Labels: ready for review

#5086 fix(groups): invited users not added to groups after accepting email invitations
  src/auth-service/utils/request.util.js
Labels: ready for review

#5089 hotfixes for site categorisation and DB projections for sites
  src/device-registry/config/global/db-projections-v1.js
  src/device-registry/utils/scripts/site-categorisation.js
Labels: ready for review

#5085 get location name using nominatim
  src/spatial/configure.py
  src/spatial/models/heatmapModel.py
  src/spatial/models/site_category_model.py
  src/spatial/views/heatmapViews.py
Labels: ready for review

#5087 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/nginx/production/beacon-vs.yaml
  k8s/nginx/staging/beacon-vs.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/spatial/values-stage.yaml
  src/auth-service/models/User.js
  src/auth-service/utils/request.util.js
  src/auth-service/validators/requests.validators.js
  src/device-registry/bin/jobs/daily-activity-summary-job.js
  src/device-registry/bin/server.js
  src/device-registry/config/global/db-projections-v1.js
  src/device-registry/models/ActivityLog.js
  src/device-registry/utils/common/activity-logger.util.js
  src/device-registry/utils/common/index.js
  src/device-registry/utils/event.util.js
  src/device-registry/utils/scripts/site-categorisation.js
  src/spatial/configure.py
  src/spatial/models/heatmapModel.py
  src/spatial/models/site_category_model.py
  src/spatial/views/heatmapViews.py
Labels: ready for review

#5091 initiating revert of all old readings implementation
  src/device-registry/bin/jobs/store-readings-job-beta.js
  src/device-registry/bin/jobs/store-readings-job.beta.js
  src/device-registry/bin/jobs/store-readings-job.js
  src/device-registry/controllers/event.controller.js
  src/device-registry/models/Event.backup.js
  src/device-registry/models/Reading.backup.js
Labels: work in progress

#5092 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/spatial/values-stage.yaml
  src/device-registry/bin/jobs/store-readings-job-beta.js
  src/device-registry/bin/jobs/store-readings-job.beta.js
  src/device-registry/bin/jobs/store-readings-job.js
  src/device-registry/controllers/event.controller.js
  src/device-registry/models/Event.backup.js
  src/device-registry/models/Reading.backup.js
Labels: ready for review

#5093 add logging for event additions
  src/device-registry/utils/event.util.js
Labels: ready for review

#5096 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  src/analytics/api/models/bigquery_api.py
  src/analytics/api/tests/conftest.py
  src/analytics/api/tests/test_v2_data.py
  src/analytics/api/tests/test_v3_data.py
  src/analytics/api/utils/cursor_utils.py
  src/analytics/api/utils/datautils.py
  src/analytics/api/utils/http.py
  src/analytics/api/views/README.md
  src/analytics/api/views/common/data_ops.py
  src/analytics/api/views/common/responses.py
  src/analytics/api/views/v2/data.py
  src/analytics/api/views/v3/data.py
  src/analytics/config.py
  src/analytics/schemas/datadownload.py
  src/workflows/airqo_etl_utils/bigquery_api.py
  src/workflows/airqo_etl_utils/schema/devices.json
  src/workflows/airqo_etl_utils/tests/test_data_sources.py
Labels: ready for review

#5099 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/analytics/schemas/datadownload.py
Labels: ready for review

#5102 adding more exclusions to summary of sites returned
  src/device-registry/bin/jobs/site-categorization-job.js
  src/device-registry/bin/jobs/site-categorization-notification-job.js
  src/device-registry/bin/server.js
  src/device-registry/config/environments/development.js
  src/device-registry/config/environments/production.js
  src/device-registry/config/environments/staging.js
  src/device-registry/config/global/db-projections.js
  src/device-registry/utils/scripts/site-categorisation.js
Labels: ready for review

#5104 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/analytics/api/tests/conftest.py
  src/analytics/api/tests/test_dashboard.py
  src/analytics/api/tests/test_data_formatters.py
  src/analytics/api/views/v2/dashboard.py
  src/device-registry/bin/jobs/site-categorization-job.js
  src/device-registry/bin/jobs/site-categorization-notification-job.js
  src/device-registry/bin/server.js
  src/device-registry/config/environments/development.js
  src/device-registry/config/environments/production.js
  src/device-registry/config/environments/staging.js
  src/device-registry/config/global/db-projections.js
  src/device-registry/utils/scripts/site-categorisation.js
Labels: ready for review

#5107 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/validators/site.validators.js
Labels: ready for review

#5110 removing noisy Slack logs
  src/device-registry/bin/jobs/site-categorization-job.js
Labels: ready for review

#5123 edited nodeports
  k8s/beacon-api/values-prod.yaml
  k8s/beacon-api/values-stage.yaml
Labels: ready for review

#5125 edited service.yaml
  k8s/beacon-api/templates/service.yaml
Labels: ready for review

#5127 staging beacon api vitrual server route
  k8s/nginx/staging/analytics-vs.yaml
  k8s/nginx/staging/api-vs.yaml
  k8s/nginx/staging/beacon-vs.yaml
  k8s/nginx/staging/netmanager-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
  k8s/nginx/staging/vertex-vs.yaml
  src/beacon-api/README.md
Labels: ready for review

#5129 adding the device lookup endpoints documentation
  src/device-registry/routes/v2/docs/ lookup.md
Labels: ready for review

#5133 removing the old markdown file
  src/device-registry/routes/v2/docs/ lookup.md
Labels: ready for review

#5138 Beaconpath rewrite
  k8s/nginx/staging/platform-vs.yaml
  src/beacon-api/README.md
Labels: ready for review

#5146 move to production
  k8s/analytics/values-prod.yaml
  k8s/beacon-api/values-prod.yaml
  k8s/beacon-api/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/jobs/store-readings-job.js
  src/device-registry/bin/jobs/update-online-status-job.js
  src/device-registry/bin/server.js
  src/device-registry/controllers/event.controller.js
  src/device-registry/models/Device.js
  src/device-registry/models/Event.js
  src/device-registry/models/Reading.js
  src/device-registry/models/Site.js
  src/device-registry/utils/common/generate-filter.js
Labels: ready for review

#5148 Backup files for model and util of events
  src/device-registry/models/backups/Event-29-08-2025.js
  src/device-registry/models/backups/Event.backup.js
  src/device-registry/utils/backups/event.util-29-08-2025.js
Labels: ready for review

#5154 move to production
  k8s/analytics/values-prod.yaml
  k8s/beacon-api/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/predict/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/models/LogThrottle.js
Labels: ready for review

#5155 docs: conditional render of recent measurements for privacy reasons
  src/device-registry/docs/DATA_ACCESS_AND_PRIVACY_POLICY.md
Labels: ready for review

#5157 Fix MongoDB geospatial errors by auto-closing unclosed polygon rings
  src/device-registry/models/Grid.js
  src/device-registry/routes/v2/grids.routes.js
  src/device-registry/validators/common/geometry.js
  src/device-registry/validators/common/index.js
  src/device-registry/validators/grids.validators.js
Labels: ready for review
