Repository airqo-platform/AirQo-api, pull requests merged in 2025-09, with the labels that each got.

#5160 Added anchored regex to staging
  k8s/nginx/production/analytics-vs.yaml
  k8s/nginx/production/api-vs.yaml
  k8s/nginx/production/beacon-vs.yaml
  k8s/nginx/production/netmanager-vs.yaml
  k8s/nginx/production/platform-vs.yaml
  k8s/nginx/production/vertex-vs.yaml
  k8s/nginx/staging/analytics-vs.yaml
  k8s/nginx/staging/api-vs.yaml
  k8s/nginx/staging/beacon-vs.yaml
  k8s/nginx/staging/netmanager-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
  k8s/nginx/staging/vertex-vs.yaml
  src/beacon-api/README.md
Labels: ready for review

#5158 move to production
  k8s/analytics/values-prod.yaml
  k8s/beacon-api/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/nginx/production/analytics-vs.yaml
  k8s/nginx/production/api-vs.yaml
  k8s/nginx/production/beacon-vs.yaml
  k8s/nginx/production/netmanager-vs.yaml
  k8s/nginx/production/platform-vs.yaml
  k8s/nginx/production/vertex-vs.yaml
  k8s/nginx/staging/analytics-vs.yaml
  k8s/nginx/staging/api-vs.yaml
  k8s/nginx/staging/beacon-vs.yaml
  k8s/nginx/staging/netmanager-vs.yaml
  k8s/nginx/staging/platform-vs.yaml
  k8s/nginx/staging/vertex-vs.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/beacon-api/README.md
  src/device-registry/models/Grid.js
  src/device-registry/routes/v2/grids.routes.js
  src/device-registry/validators/common/geometry.js
  src/device-registry/validators/common/index.js
  src/device-registry/validators/grids.validators.js
Labels: ready for review

#5164 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/beacon-api/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/predict/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/analytics/api/models/bigquery_api.py
  src/analytics/api/models/dashboard/dashboarddatautils.py
  src/analytics/api/tests/test_dashboard.py
  src/analytics/api/utils/datautils.py
  src/analytics/api/views/v2/dashboard.py
  src/analytics/config.py
Labels: ready for review

#5170 enhance the response details of devices and sites
  src/device-registry/config/global/db-projections.js
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
  src/device-registry/routes/v2/docs/DEVICES_MANAGEMENT_API_DOCUMENTATION.MD
  src/device-registry/routes/v2/docs/DEVICE_ACTIVITIES_API_DOCUMENTATION.md
  src/device-registry/routes/v2/docs/SITES_API_DOCUMENTATION.md
  src/device-registry/utils/device.util.js
  src/device-registry/utils/site.util.js
Labels: ready for review

#5173 move to production
  k8s/analytics/values-prod.yaml
  k8s/beacon-api/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/predict/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/spatial/values-stage.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/global/db-projections.js
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
  src/device-registry/routes/v2/docs/DEVICES_MANAGEMENT_API_DOCUMENTATION.MD
  src/device-registry/routes/v2/docs/DEVICE_ACTIVITIES_API_DOCUMENTATION.md
  src/device-registry/routes/v2/docs/SITES_API_DOCUMENTATION.md
  src/device-registry/utils/device.util.js
  src/device-registry/utils/site.util.js
Labels: ready for review

#5177 remove accidental file
  token-strategies.js
Labels: ready for review

#5182 Website: Adjust API doc URLs and Docker file optimization
  src/website/.dockerignore
  src/website/.gitignore
  src/website/Dockerfile
  src/website/README.md
  src/website/apps/api/v2/serializers/event.py
  src/website/apps/cleanair/migrations/0025_alter_cleanairresource_options_and_more.py
  src/website/core/settings.py
  src/website/core/urls.py
  src/website/docker-compose.yml
  src/website/entrypoint.sh
  src/website/requirements.txt
  src/website/utils/fields.py
  src/website/utils/validators.py
Labels: ready for review

#5197 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/beacon-api/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/controllers/user.controller.js
  src/auth-service/utils/role-permissions.util.js
Labels: ready for review

#5195 feat: implement custom permission class for v2 API enforce authentication for write operations and allow read-only access
  src/website/README.md
  src/website/apps/api/apps.py
  src/website/apps/api/management/__init__.py
  src/website/apps/api/management/commands/__init__.py
  src/website/apps/api/management/commands/generate_all_slugs.py
  src/website/apps/api/v2/filters/team.py
  src/website/apps/api/v2/mixins.py
  src/website/apps/api/v2/permissions.py
  src/website/apps/api/v2/serializers/career.py
  src/website/apps/api/v2/serializers/event.py
  src/website/apps/api/v2/serializers/mixins.py
  src/website/apps/api/v2/serializers/press.py
  src/website/apps/api/v2/serializers/publications.py
  src/website/apps/api/v2/serializers/team.py
  src/website/apps/api/v2/signals.py
  src/website/apps/api/v2/viewsets/career.py
  src/website/apps/api/v2/viewsets/event.py
  src/website/apps/api/v2/viewsets/press.py
  src/website/apps/api/v2/viewsets/publications.py
  src/website/apps/api/v2/viewsets/team.py
  src/website/apps/career/migrations/0003_add_slug_support.py
  src/website/apps/career/models.py
  src/website/apps/career/serializers.py
  src/website/apps/career/views.py
  src/website/apps/event/migrations/0019_add_slug_support.py
  src/website/apps/event/models.py
  src/website/apps/press/migrations/0012_add_slug_support.py
  src/website/apps/press/models.py
  src/website/apps/press/serializers.py
  src/website/apps/press/views.py
  src/website/apps/publications/migrations/0013_add_slug_support.py
  src/website/apps/publications/models.py
  src/website/apps/team/migrations/0008_add_slug_support.py
  src/website/apps/team/models.py
  src/website/apps/team/serializers.py
  src/website/apps/team/views.py
  src/website/core/settings.py
  src/website/core/urls.py
  src/website/test_api_endpoints.py
  src/website/utils/models.py
Labels: ready for review

#5201 Refactor: Centralize RBAC default roles and improve startup initialization
  src/auth-service/bin/server.js
  src/auth-service/config/database.js
  src/auth-service/config/global/permissions.js
  src/auth-service/middleware/check-scope.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/AccessToken.js
  src/auth-service/models/BlacklistedIP.js
  src/auth-service/models/BlacklistedIPPrefix.js
  src/auth-service/models/BlacklistedIPRange.js
  src/auth-service/models/Checklist.js
  src/auth-service/models/Client.js
  src/auth-service/models/Defaults.js
  src/auth-service/models/Favorite.js
  src/auth-service/models/GuestUser.js
  src/auth-service/models/IPPrefix.js
  src/auth-service/models/LocationHistory.js
  src/auth-service/models/Maintenance.js
  src/auth-service/models/NotificationPreference.js
  src/auth-service/models/Permission.js
  src/auth-service/models/Preference.js
  src/auth-service/models/Role.js
  src/auth-service/models/Scope.js
  src/auth-service/models/SearchHistory.js
  src/auth-service/models/SelectedSite.js
  src/auth-service/models/Subscription.js
  src/auth-service/models/Survey.js
  src/auth-service/models/SurveyResponse.js
  src/auth-service/models/UnknownIP.js
  src/auth-service/models/User.js
  src/auth-service/models/VerifyToken.js
  src/auth-service/models/WhitelistedIP.js
  src/auth-service/models/log.js
  src/auth-service/utils/admin.util.js
  src/auth-service/utils/candidate.util.js
  src/auth-service/utils/client.util.js
  src/auth-service/utils/common/generate-filter.util.js
  src/auth-service/utils/group.util.js
  src/auth-service/utils/network.util.js
  src/auth-service/utils/request.util.js
  src/auth-service/utils/role-permissions.util.js
  src/auth-service/utils/scripts/bulk-script.js
  src/auth-service/utils/scripts/update-network-roles.js
  src/auth-service/utils/survey.util.js
  src/auth-service/utils/token.util.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5202 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/beacon-api/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/bin/server.js
  src/auth-service/config/database.js
  src/auth-service/config/global/permissions.js
  src/auth-service/config/global/token-strategies.js
  src/auth-service/config/tokenStrategyConfig.js
  src/auth-service/middleware/check-scope.js
  src/auth-service/middleware/passport.js
  src/auth-service/models/AccessToken.js
  src/auth-service/models/BlacklistedIP.js
  src/auth-service/models/BlacklistedIPPrefix.js
  src/auth-service/models/BlacklistedIPRange.js
  src/auth-service/models/Checklist.js
  src/auth-service/models/Client.js
  src/auth-service/models/Defaults.js
  src/auth-service/models/Favorite.js
  src/auth-service/models/GuestUser.js
  src/auth-service/models/IPPrefix.js
  src/auth-service/models/LocationHistory.js
  src/auth-service/models/Maintenance.js
  src/auth-service/models/NotificationPreference.js
  src/auth-service/models/Permission.js
  src/auth-service/models/Preference.js
  src/auth-service/models/Role.js
  src/auth-service/models/Scope.js
  src/auth-service/models/SearchHistory.js
  src/auth-service/models/SelectedSite.js
  src/auth-service/models/Subscription.js
  src/auth-service/models/Survey.js
  src/auth-service/models/SurveyResponse.js
  src/auth-service/models/UnknownIP.js
  src/auth-service/models/User.js
  src/auth-service/models/VerifyToken.js
  src/auth-service/models/WhitelistedIP.js
  src/auth-service/models/log.js
  src/auth-service/services/atf.service.js
  src/auth-service/utils/admin.util.js
  src/auth-service/utils/candidate.util.js
  src/auth-service/utils/client.util.js
  src/auth-service/utils/common/generate-filter.util.js
  src/auth-service/utils/group.util.js
  src/auth-service/utils/network.util.js
  src/auth-service/utils/request.util.js
  src/auth-service/utils/role-permissions.util.js
  src/auth-service/utils/scripts/bulk-script.js
  src/auth-service/utils/scripts/update-network-roles.js
  src/auth-service/utils/survey.util.js
  src/auth-service/utils/token.util.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5205 move to production
  k8s/analytics/values-prod.yaml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/beacon-api/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/bin/jobs/token-strategy-migration-job.js
  src/auth-service/bin/server.js
  src/auth-service/controllers/user.controller.js
  src/auth-service/models/User.js
  src/auth-service/models/test/ut_user.model.js
  src/auth-service/utils/role-permissions.util.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5209 Fix syncFavorites deletion failures and improve error handling
  src/auth-service/utils/favorite.util.js
Labels: ready for review

#5234 Chore: Centralize deprecated role names into a constant
  src/auth-service/bin/jobs/token-strategy-migration-job.js
  src/auth-service/config/global/permissions.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5238 Fix: Ensure user interests and profile data are returned in API
  src/auth-service/config/global/db-projections.js
  src/auth-service/models/User.js
  src/auth-service/utils/user.util.js
  src/auth-service/validators/users.validators.js
Labels: ready for review

#5241 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/config/global/permissions.js
  src/auth-service/controllers/user.controller.js
  src/auth-service/docs/SLIDING_SESSION_TOKEN_REFRESH_GUIDE.md
  src/auth-service/middleware/passport.js
  src/auth-service/models/User.js
  src/auth-service/services/atf.service.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5242 prevent unconditional flips verified for users
  src/auth-service/middleware/passport.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5243 move to production
  k8s/auth-service/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/middleware/passport.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5246 Fix: Prevent role assignment failure due to duplicate roles
  src/auth-service/utils/role-permissions.util.js
Labels: ready for review

#5248 Fix: Resolve multiple authentication and role management errors
  src/auth-service/controllers/user.controller.js
  src/auth-service/middleware/passport.js
  src/auth-service/utils/role-permissions.util.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5247 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/controllers/user.controller.js
  src/auth-service/middleware/passport.js
  src/auth-service/utils/role-permissions.util.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5250 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/airqo_etl_utils/constants.py
  src/workflows/airqo_etl_utils/datautils.py
  src/workflows/airqo_etl_utils/meta_data_utils.py
  src/workflows/airqo_etl_utils/schema/device_computed_metadata.json
  src/workflows/airqo_etl_utils/schema/site_computed_metadata.json
  src/workflows/dags/meta_data.py
Labels: ready for review

#5251 Optimize Device and Site Endpoints with Pre-computed Activity Caching
  src/device-registry/bin/jobs/precompute-activities-job.js
  src/device-registry/bin/server.js
  src/device-registry/config/environments/development.js
  src/device-registry/config/environments/production.js
  src/device-registry/config/environments/staging.js
  src/device-registry/models/Activity.js
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
  src/device-registry/utils/device.util.js
  src/device-registry/utils/site.util.js
Labels: ready for review

#5252 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/device-registry/bin/jobs/precompute-activities-job.js
  src/device-registry/bin/server.js
  src/device-registry/config/environments/development.js
  src/device-registry/config/environments/production.js
  src/device-registry/config/environments/staging.js
  src/device-registry/models/Activity.js
  src/device-registry/models/Device.js
  src/device-registry/models/Site.js
  src/device-registry/utils/device.util.js
  src/device-registry/utils/site.util.js
Labels: ready for review

#5253 Fix(auth): Correct token refresh logic to prevent header errors and new endpoint to get enhanced user profile by ID
  src/auth-service/controllers/user.controller.js
  src/auth-service/middleware/passport.js
  src/auth-service/routes/v2/users.routes.js
  src/auth-service/utils/user.util.js
  src/auth-service/validators/users.validators.js
Labels: ready for review

#5255 feat(auth): Centralize and improve token expiration configuration
  src/auth-service/config/global/permissions.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5256 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/config/global/permissions.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5257 fix(auth): Add missing permissions and resolve related type errors
  src/auth-service/config/global/permissions.js
  src/auth-service/utils/group.util.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5259 fix(auth): Correct admin permissions and resolve critical auth bugs
  src/auth-service/config/global/permissions.js
  src/auth-service/migrations/rbac-migration.util.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5263 fix(auth): Cache blacklisted IP ranges in Kafka consumer
  src/auth-service/bin/jobs/kafka-consumer.js
Labels: ready for review

#5265 fix(jobs): Reduce notification noise from online status job
  src/device-registry/bin/jobs/update-online-status-job.js
Labels: ready for review

#5269 fix for password reset to send UI friendly message
  src/auth-service/models/User.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5271 Refactor: Improve password reset validation and apply DRY
  src/auth-service/config/global/regex-patterns.js
  src/auth-service/models/User.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5270 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/config/global/regex-patterns.js
  src/auth-service/models/User.js
  src/auth-service/utils/user.util.js
  src/workflows/airqo_etl_utils/airqo_data_drift_compute.py
  src/workflows/airqo_etl_utils/airqo_utils.py
  src/workflows/airqo_etl_utils/bigquery_api.py
  src/workflows/airqo_etl_utils/config.py
  src/workflows/airqo_etl_utils/data_validator.py
  src/workflows/airqo_etl_utils/datautils.py
  src/workflows/airqo_etl_utils/meta_data_utils.py
  src/workflows/airqo_etl_utils/schema/device_computed_metadata.json
  src/workflows/airqo_etl_utils/schema/measurements_baseline.json
  src/workflows/airqo_etl_utils/schema/site_computed_metadata.json
  src/workflows/airqo_etl_utils/setup.py
  src/workflows/airqo_etl_utils/tests/test_airqo_data_drift_compute.py
  src/workflows/airqo_etl_utils/tests/test_datautils.py
  src/workflows/airqo_etl_utils/tests/test_meta_data_utils.py
  src/workflows/airqo_etl_utils/tests/test_ml_utils.py
  src/workflows/dags/meta_data.py
Labels: ready for review

#5275 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/README.md
Labels: ready for review

#5278 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/README.md
Labels: ready for review

#5287 Fix: Resolve DB buffering timeout in migration script
  src/device-registry/config/database.js
  src/device-registry/migrations/network-status-indexes.js
Labels: ready for review

#5289 Refactor(RBAC): Standardize role names and add backward-compatible migration
  src/auth-service/config/database.js
  src/auth-service/config/global/permissions.js
  src/auth-service/docs/ROLE_BASED_ACCESS_CONTROL.md
  src/auth-service/middleware/adminAccess.js
  src/auth-service/middleware/groupNetworkAuth.js
  src/auth-service/middleware/passport.js
  src/auth-service/migrations/rbac-migration.util.js
  src/auth-service/migrations/rename-legacy-roles.js
  src/auth-service/models/MigrationTracker.js
  src/auth-service/routes/v2/groups.routes.js
  src/auth-service/routes/v2/networks.routes.js
  src/auth-service/routes/v2/users.routes.js
  src/auth-service/utils/group.util.js
  src/auth-service/utils/network.util.js
  src/auth-service/utils/user.util.js
Labels: ready for review

#5286 increase cache to 60minutes
  src/spatial/views/heatmapViews.py
Labels: ready for review, priority-medium

#5290 move to production
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-stage.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/config/database.js
  src/auth-service/config/global/permissions.js
  src/auth-service/docs/ROLE_BASED_ACCESS_CONTROL.md
  src/auth-service/middleware/adminAccess.js
  src/auth-service/middleware/groupNetworkAuth.js
  src/auth-service/middleware/passport.js
  src/auth-service/migrations/rbac-migration.util.js
  src/auth-service/migrations/rename-legacy-roles.js
  src/auth-service/models/MigrationTracker.js
  src/auth-service/routes/v2/groups.routes.js
  src/auth-service/routes/v2/networks.routes.js
  src/auth-service/routes/v2/users.routes.js
  src/auth-service/utils/group.util.js
  src/auth-service/utils/network.util.js
  src/auth-service/utils/user.util.js
  src/spatial/views/heatmapViews.py
Labels: ready for review

#5296 Optimize: Add robust pagination to all list endpoints
  src/device-registry/controllers/activity.controller.js
  src/device-registry/controllers/cohort.controller.js
  src/device-registry/controllers/device.controller.js
  src/device-registry/controllers/grid.controller.js
  src/device-registry/controllers/health-tips.controller.js
  src/device-registry/controllers/site.controller.js
  src/device-registry/models/Site.js
  src/device-registry/utils/activity.util.js
  src/device-registry/utils/cohort.util.js
  src/device-registry/utils/device.util.js
  src/device-registry/utils/grid.util.js
  src/device-registry/utils/health-tips.util.js
  src/device-registry/utils/site.util.js
  src/device-registry/validators/common/pagination.validators.js
Labels: ready for review

#5294 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/jobs/update-online-status-job.js
  src/device-registry/controllers/activity.controller.js
  src/device-registry/controllers/cohort.controller.js
  src/device-registry/controllers/device.controller.js
  src/device-registry/controllers/grid.controller.js
  src/device-registry/controllers/health-tips.controller.js
  src/device-registry/controllers/site.controller.js
  src/device-registry/models/Site.js
  src/device-registry/utils/activity.util.js
  src/device-registry/utils/cohort.util.js
  src/device-registry/utils/device.util.js
  src/device-registry/utils/grid.util.js
  src/device-registry/utils/health-tips.util.js
  src/device-registry/utils/site.util.js
  src/device-registry/validators/common/pagination.validators.js
  src/workflows/airqo_etl_utils/airqo_utils.py
  src/workflows/airqo_etl_utils/commons.py
  src/workflows/airqo_etl_utils/data_warehouse_utils.py
  src/workflows/airqo_etl_utils/datautils.py
  src/workflows/airqo_etl_utils/meta_data_utils.py
  src/workflows/dags/airqo_measurements.py
Labels: ready for review

#5297 trigger device registry
  src/device-registry/README.md
Labels: ready for review

#5298 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/device-registry/README.md
Labels: ready for review

#5302 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/airqo_etl_utils/datautils.py
Labels: ready for review

#5303 user-stats endpoint much more scalable and performant
  src/auth-service/controllers/analytics.controller.js
  src/auth-service/utils/analytics.util.js
Labels: ready for review

#5308 updated all $cond operators to use the array format and corrected the…
  src/device-registry/config/global/db-projections.js
  src/device-registry/controllers/grid.controller.js
Labels: ready for review

#5307 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/global/db-projections.js
  src/device-registry/controllers/airqloud.controller.js
  src/device-registry/controllers/cohort.controller.js
  src/device-registry/controllers/grid.controller.js
  src/device-registry/utils/activity.util.js
  src/device-registry/utils/airqloud.util.js
  src/device-registry/utils/cohort.util.js
  src/device-registry/utils/common/generate-filter.js
  src/device-registry/utils/device.util.js
  src/device-registry/utils/grid.util.js
  src/device-registry/utils/health-tips.util.js
  src/device-registry/utils/site.util.js
Labels: ready for review

#5310 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/controllers/device.controller.js
  src/device-registry/controllers/feed.controller.js
  src/device-registry/routes/v2/devices.routes.js
  src/device-registry/utils/device.util.js
  src/device-registry/utils/feed.util.js
  src/device-registry/validators/device.validators.js
Labels: ready for review

#5311 Website: V2 api query improvements and API documentation updated
  src/website/.gitignore
  src/website/README.md
  src/website/apps/api/v2/filters/cleanair.py
  src/website/apps/api/v2/filters/event.py
  src/website/apps/api/v2/permissions.py
  src/website/apps/api/v2/serializers/africancities.py
  src/website/apps/api/v2/serializers/career.py
  src/website/apps/api/v2/serializers/cleanair.py
  src/website/apps/api/v2/serializers/event.py
  src/website/apps/api/v2/serializers/mixins.py
  src/website/apps/api/v2/serializers/partners.py
  src/website/apps/api/v2/utils.py
  src/website/apps/api/v2/viewsets/africancities.py
  src/website/apps/api/v2/viewsets/board.py
  src/website/apps/api/v2/viewsets/career.py
  src/website/apps/api/v2/viewsets/cleanair.py
  src/website/apps/api/v2/viewsets/event.py
  src/website/apps/api/v2/viewsets/externalteams.py
  src/website/apps/api/v2/viewsets/faqs.py
  src/website/apps/api/v2/viewsets/highlights.py
  src/website/apps/api/v2/viewsets/impact.py
  src/website/apps/api/v2/viewsets/partners.py
  src/website/apps/api/v2/viewsets/press.py
  src/website/apps/api/v2/viewsets/publications.py
  src/website/apps/api/v2/viewsets/team.py
  src/website/apps/event/admin.py
  src/website/apps/event/models.py
  src/website/apps/faqs/admin.py
  src/website/apps/faqs/migrations/0003_alter_faq_options_faq_order.py
  src/website/apps/faqs/models.py
  src/website/apps/highlights/admin.py
  src/website/apps/highlights/models.py
  src/website/apps/partners/migrations/0008_add_slugs_to_partners.py
  src/website/apps/partners/models.py
  src/website/apps/partners/serializers.py
  src/website/assets/events/images/checkme.jpg
  src/website/assets/events/images/testimage.jpg
  src/website/assets/website/uploads/events/files/MARTIN_LEAVE_HANDOVER_REPORT_25th_Feb_-_5th_March_2024.pdf
  src/website/assets/website/uploads/events/images/chuttersnap-aEnH4hJ_Mrs-unsplash.jpg
  src/website/assets/website/uploads/events/images/rachel-coyne-U7HLzMO4SIY-unsplash.jpg
  src/website/assets/website/uploads/events/logos/checkme.jpg
  src/website/assets/website/uploads/events/logos/testimage.jpg
  src/website/core/settings.py
  src/website/core/urls.py
  src/website/entrypoint.sh
  src/website/static/admin/css/event_admin_custom.css
  src/website/static/admin/images/favicon.ico
  src/website/static/admin/images/icon.png
  src/website/templates/index.html
  src/website/test_enhanced_endpoints.py
  src/website/utils/fields.py
Labels: ready for review

#5315 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/website/values-stage.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/jobs/update-online-status-job.js
  src/device-registry/bin/jobs/update-raw-online-status-job.js
  src/device-registry/bin/server.js
  src/device-registry/config/global/db-projections.js
  src/device-registry/models/Device.js
  src/device-registry/utils/common/generate-filter.js
  src/device-registry/utils/feed.util.js
Labels: ready for review

#5318 Fix: Correct uptime accuracy calculation for undeployed devices
  src/device-registry/bin/jobs/update-online-status-job.js
  src/device-registry/bin/jobs/update-raw-online-status-job.js
  src/device-registry/utils/common/index.js
  src/device-registry/utils/common/uptime.util.js
Labels: ready for review

#5319 Fix: Improve graceful shutdown logic for background jobs
  src/device-registry/bin/jobs/check-unassigned-devices-job.js
  src/device-registry/bin/jobs/check-unassigned-sites-job.js
  src/device-registry/bin/jobs/device-status-check-job.js
  src/device-registry/bin/jobs/device-status-hourly-check-job.js
  src/device-registry/bin/jobs/device-uptime-job.js
  src/device-registry/bin/jobs/health-tip-checker-job.js
  src/device-registry/bin/jobs/precompute-activities-job.js
  src/device-registry/bin/jobs/store-readings-job.js
  src/device-registry/bin/jobs/update-duplicate-site-fields-job.js
  src/device-registry/bin/jobs/update-grid-flags-job.js
  src/device-registry/bin/jobs/update-online-status-job.js
  src/device-registry/bin/jobs/update-raw-online-status-job.js
  src/device-registry/models/Grid.js
Labels: ready for review

#5321 Feat: List devices for multiple cohorts
  src/device-registry/controllers/cohort.controller.js
  src/device-registry/routes/v2/cohorts.routes.js
  src/device-registry/utils/cohort.util.js
  src/device-registry/validators/cohorts.validators.js
Labels: ready for review

#5320 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/jobs/check-unassigned-devices-job.js
  src/device-registry/bin/jobs/check-unassigned-sites-job.js
  src/device-registry/bin/jobs/device-status-check-job.js
  src/device-registry/bin/jobs/device-status-hourly-check-job.js
  src/device-registry/bin/jobs/device-uptime-job.js
  src/device-registry/bin/jobs/health-tip-checker-job.js
  src/device-registry/bin/jobs/precompute-activities-job.js
  src/device-registry/bin/jobs/store-readings-job.js
  src/device-registry/bin/jobs/update-duplicate-site-fields-job.js
  src/device-registry/bin/jobs/update-grid-flags-job.js
  src/device-registry/bin/jobs/update-online-status-job.js
  src/device-registry/bin/jobs/update-raw-online-status-job.js
  src/device-registry/controllers/cohort.controller.js
  src/device-registry/models/Grid.js
  src/device-registry/routes/v2/cohorts.routes.js
  src/device-registry/utils/cohort.util.js
  src/device-registry/validators/cohorts.validators.js
Labels: ready for review

#5322 Feat: Enhance Mobile Device Management and API
  src/device-registry/bin/jobs/update-raw-online-status-job.js
  src/device-registry/controllers/device.controller.js
  src/device-registry/models/Device.js
  src/device-registry/routes/v2/devices.routes.js
  src/device-registry/utils/common/generate-filter.js
  src/device-registry/validators/activities.validators.js
  src/device-registry/validators/device.validators.js
Labels: ready for review

#5325 addressing PR feedback for pre-save hook operations
  src/device-registry/models/Device.js
Labels: ready for review

#5328 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/migrations/rename-legacy-roles.js
Labels: ready for review

#5329 Fix: Resolve auth migration errors for tenant and duplicate keys
  src/auth-service/migrations/rename-legacy-roles.js
Labels: ready for review

#5331 temporary disable of perm checks on users/networks endpoint
  src/auth-service/routes/v2/networks.routes.js
Labels: ready for review

#5334 move to production
  .github/workflows/deploy-previews.yml
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
Labels: ready for review

#5335 ensures the migration logic is strictly confined to the airqo tenan
  src/auth-service/migrations/rename-legacy-roles.js
Labels: ready for review

#5336 move to production
  k8s/auth-service/values-prod.yaml
  k8s/auth-service/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/auth-service/migrations/rename-legacy-roles.js
Labels: ready for review

#5338 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/airqo_etl_utils/commons.py
  src/workflows/airqo_etl_utils/datautils.py
  src/workflows/airqo_etl_utils/ml_utils.py
  src/workflows/airqo_etl_utils/utils.py
Labels: ready for review

#5339 just removing noisy log
  src/auth-service/migrations/rename-legacy-roles.js
Labels: ready for review

#5340 move to production
  k8s/auth-service/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/website/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/auth-service/migrations/rename-legacy-roles.js
Labels: ready for review

#5341 Fix: Prevent frequent logouts with sliding window and grace period for JWTs
  src/auth-service/config/global/numericals.js
  src/auth-service/middleware/passport.js
Labels: ready for review

#5367 move to production
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/workflows/airqo_etl_utils/airqo_utils.py
  src/workflows/airqo_etl_utils/datautils.py
  src/workflows/airqo_etl_utils/meta_data_utils.py
  src/workflows/airqo_etl_utils/tests/test_airqo_data_drift_compute.py
  src/workflows/airqo_etl_utils/tests/test_datautils.py
  src/workflows/airqo_etl_utils/tests/test_meta_data_utils.py
  src/workflows/dags/meta_data.py
Labels: ready for review

#5369 move to production
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/workflows/airqo_etl_utils/datautils.py
  src/workflows/airqo_etl_utils/meta_data_utils.py
  src/workflows/airqo_etl_utils/tests/test_meta_data_utils.py
Labels: ready for review

#5371 move to production
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/device-registry/bin/server.js
Labels: ready for review

#5373 move to production
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/server.js
Labels: ready for review

#5375 move to production
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/routes/v2/readings.routes.js
Labels: ready for review

#5377 move to production
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/global/db-projections.js
Labels: ready for review

#5379 move to production
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/global/db-projections.js
Labels: ready for review

#5381 move to production
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/jobs/update-raw-online-status-job.js
Labels: ready for review

#5383 move to production
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/global/db-projections.js
  src/device-registry/utils/device.util.js
  src/device-registry/utils/site.util.js
Labels: ready for review

#5385 move to production
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/global/db-projections.js
Labels: ready for review

#5386 more db project removals
  src/device-registry/config/global/db-projections.js
Labels: ready for review

#5387 move to production
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/global/db-projections.js
Labels: ready for review

#5389 just adding more fields to projections
  src/device-registry/config/global/db-projections.js
Labels: ready for review

#5392 optimisations when handling events in posting, fetching and online status calculations
  src/device-registry/bin/jobs/update-online-status-job.js
  src/device-registry/bin/jobs/update-raw-online-status-job.js
  src/device-registry/bin/server.js
  src/device-registry/models/Event.js
  src/device-registry/utils/event.util.js
Labels: ready for review

#5393 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/bin/jobs/update-online-status-job.js
  src/device-registry/bin/jobs/update-raw-online-status-job.js
  src/device-registry/bin/server.js
  src/device-registry/models/Event.js
  src/device-registry/utils/event.util.js
Labels: ready for review

#5397 move to production
  k8s/analytics/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/redis.js
Labels: ready for review

#5398 redis: alerted to a persistent problem once per hour without overwhelming
  src/device-registry/config/redis.js
Labels: ready for review

#5399 move to production
  k8s/analytics/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/redis.js
Labels: ready for review

#5400 reduce logging redis connection issues to the first 5 mins of every hour
  src/device-registry/config/redis.js
Labels: ready for review

#5401 move to production
  k8s/analytics/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/redis.js
Labels: ready for review

#5408 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/spatial/values-prod.yaml
  k8s/workflows/values-prod.yaml
  k8s/workflows/values-stage.yaml
  src/analytics/api/tests/conftest.py
  src/analytics/api/views/common/data_ops.py
Labels: ready for review

#5411 move to production
  k8s/analytics/values-prod.yaml
  k8s/analytics/values-stage.yaml
  k8s/device-registry/values-prod.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/global/db-projections.js
  src/device-registry/config/redis.js
  src/device-registry/utils/event.util.js
Labels: ready for review

#5412 more API response optimisations
  src/device-registry/config/global/db-projections.js
Labels: ready for review

#5413 move to production
  k8s/analytics/values-prod.yaml
  k8s/device-registry/values-prod.yaml
  k8s/device-registry/values-stage.yaml
  k8s/workflows/values-prod.yaml
  src/device-registry/config/global/db-projections.js
Labels: ready for review

#5409 update heatmapto retrieve more records per request
  src/spatial/models/heatmapModel.py
Labels: ready for review, priority-high
